### ISSUE TITLE
I need all variant full detail by using query.

### ISSUE THREAD

**Issue by ihs-Sharma** [Shopify/mobile-buy-sdk-ios#1003]
@dbart01 
Right now I'm using this query and I need all other details too, but can't find out. please Help!.

                    .variants(first: 10) { $0
                        .edges { $0
                            .node { $0
                                .id()
                                .price()
                                .title()
                                .availableForSale()
                            }
                        }
                    }

I want these details like below.

"id":17331691225177,
"product_id":1808353329241,
"title":"White \/ 2yrs",
"price":"21.00",
"sku":"7627315",
"position":1,
"inventory_policy":"deny",
"compare_at_price":null,
"fulfillment_service":"printful",
"inventory_management":null,
"option1":"White",
"option2":"2yrs",
"option3":null,
"created_at":"2018-11-07T15:59:01-05:00",
"updated_at":"2019-05-31T13:49:56-04:00",
"taxable":true,
"barcode":null,
"grams":68,
"image_id":5220830838873,
"weight":2.4,
"weight_unit":"oz",
"inventory_item_id":17579123933273,
"inventory_quantity":0,
"old_inventory_quantity":0,
"requires_shipping":true,
"admin_graphql_api_id":"gid:\/\/shopify\/ProductVariant\/17331691225177"

**Comment by dbart01** [comment]
Please refer to the [GraphiQL documentation](https://help.shopify.com/en/api/storefront-graphiql) for `ProductVariant` for all available fields.
