### ISSUE TITLE
Clear cart / cancel checkout?

### ISSUE THREAD

**Issue by mnshukla95** [Shopify/mobile-buy-sdk-ios#1005]
We are using an integration that will not use Shopify as a payment gateway. However, it is still possible to have a Shopify checkout in this scenario. Is it possible to clear the cart or cancel a Shopify checkout? I know there is a /clear endpoint, but how is that accessed/used with the mobile buy SDK?

**Comment by parveenBanuS** [comment]
how to remove the cart we added after the sending order???

**Comment by mahendragp** [comment]
I think you need to disassociate checkout from customer.

**Comment by DrTeePot** [comment]
I'm not sure what you mean by an integration that doesn't use Shopify as the payment gateway. 

You can check the `completedAt` field of the checkout to determine when an order has been created (and thus that payment was successful). This will work for any payment that is processed using the checkout web URL or checkout complete methods, regardless of if the payment is processed through Shopify Payments.

Please re-open if this doesn't answer your question.
