### ISSUE TITLE
Shopify Favourite Product Add (How to Add )Like Amazon Wishlist ? 

### ISSUE THREAD

**Issue by nagarajanpn** [Shopify/mobile-buy-sdk-ios#1007]
Hi
Want To add Product into FavList. 
How its possible ? is there any API ? is there

**Comment by mahendragp** [comment]
I am also looking for the same. I didn't found this in Storefront API. 

Could anyone suggest how can I add product into Wishlist? or how to implement the same?

**Comment by dbart01** [comment]
This is not a feature the SDK provides.
