### ISSUE TITLE
v1.2.5 Breaks Apple Pay Checkout

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#101]
In an effort to fix a potential race condition where the shop was not loaded before an Apple Pay checkout started, another bug was introduced that from what I can tell, always prevents Apple Pay checkout from succeeding.

https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/View%20Controllers/BUYViewController.m#L150

Shouldn't the above line be `self.shop == nil`??

**Comment by davidmuzi** [comment]
We are running through regressions tests and will put up a fix ASAP

**Comment by davidmuzi** [comment]
Fixed with https://github.com/Shopify/mobile-buy-sdk-ios/commit/b7248c543f16b41ae4a6121302a40ee7aa0bb5e1
