### ISSUE TITLE
How can one user gift another user with a product ?

### ISSUE THREAD

**Issue by romansorochak** [Shopify/mobile-buy-sdk-ios#1010]
Hello
In my current project I have a flow where one user can gift another user.
User1 (Sender) purchases some product (underwear) as a gift to User2(Receiver).
Then User2(Receiver) should only choose color & size.
(The flow is described on the screenshot attached)
![giftFLOW](https://user-images.githubusercontent.com/7702356/61213996-5b529e80-a70f-11e9-9c81-3d1e7098f7c2.png)

I was considering implementation as follow:
1. When User1(Sender) tries to gif User2(Receiver) with the product(underwear) 
actually User1 buys a gift card (the price of the gift card equals to the price of the product (underwear)
2. We save this gift card on our server.
3. Then User2(Receiver) chooses color & size of the product (underwear).
Then he provides shipping details.
And then completes checkout with the gift card applied. 

questions:
1. Is this flow correct in terms of implementation ?
2. Since gift card is enough to purchase a product (underwear) can user2(Receiver) avoid providing his card details ?
3. Is there a simpler solution to implement this flow ?

Thanks in advance for your help or any consideration about this flow!

**Comment by rebeccajfriedman** [comment]
Hello @romansorochak , [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) for questions around implementing features.
