### ISSUE TITLE
Cannot set up apple-app-site-association file

### ISSUE THREAD

**Issue by GabrielHauber** [Shopify/mobile-buy-sdk-ios#1012]
**Please complete the checklist before filing an issue:**

- [x] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).
- [x] Is this something you can **debug and fix**? Create a pull request and contribute! Bug fixes and documentation fixes are welcome. You can read our [contribution](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/CONTRIBUTING.md) guidelines for more details.

The Shopify Admin interface seems to suggest that it is possible to set up the `apple-app-site-association` file for deep links, via the following interface:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/4985997/62105261-3fd9bd00-b2e5-11e9-8869-dc012857f3d3.png">

However, if I try to set this up according to Apple's instructions, by specifying the AppID with the Team ID prefix, the admin interface gives the following error:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/4985997/62105306-61d33f80-b2e5-11e9-91a5-ca94a260f456.png">

If I specify the app ID without the team ID, it allows it, but shared web credentials don't work as they should in the associated app, as there is no separate place to specify the Team ID as required by Apple.

Apple's documentation is crystal clear on the Team ID requirement:

<img width="781" alt="Screen Shot 2019-07-11 at 2 02 55 pm" src="https://user-images.githubusercontent.com/4985997/62105388-96df9200-b2e5-11e9-96b7-bd35b81ed4f1.png">

Is there some trick that will allow me to specify the Team ID as Apple's documentation specifies?

**Comment by rebeccajfriedman** [comment]
Thanks for flagging this issue!
@jmignac Can you take a look at this?

**Comment by jmignac** [comment]
Hey. This issue is now fixed on our side. Thank you!

**Comment by GabrielHauber** [comment]
Confirmed from my side that this now works, too. Thanks so much!

**Comment by migalv** [comment]
Hello,

I'm trying to set up my apple-app-site-association file for my iOS app but I can't seem to find the path in the Shopify Admin dashboard to edit the apple-app-site-association file. 

Could you please help me out?
