### ISSUE TITLE
CheckoutCompleteWithCreditCardV2

### ISSUE THREAD

**Issue by samir76Git** [Shopify/mobile-buy-sdk-ios#1013]
[Buy.Graph.QueryError.Reason(message: "CheckoutCompleteWithCreditCardV2 access denied", line: nil, column: nil)]

**Comment by rebeccajfriedman** [comment]
As mentioned in the [API checkout guide](https://help.shopify.com/en/api/storefront-api/guides/checkout-guide): to complete the checkout using the checkoutcompletewithtokenizedpaymentv2 mutation you need to have the write_checkouts_payments scope enabled for your app. The scope is enabled by requesting payment processing.

I'm going to close this issue, but feel free to reopen it if the problem persists once you have proper access.

**Comment by ksmks0921** [comment]
When I am gonna complete checkout with CheckoutCompleteWithCreditCardV2 , the response is nil.
Please help me with this.
I have done address update, shipping line update, associate user, get vault id.
