### ISSUE TITLE
Hope to have Objective-C or version that can be used in Objective-C project

### ISSUE THREAD

**Issue by Jshto** [Shopify/mobile-buy-sdk-ios#1016]
Our project is very old. We need this SDK and I am not familiar with swift language. hope to have an object version.thanks

**Comment by dbart01** [comment]
Unfortunately, the Mobile Buy SDK will not be supporting Objective-C directly. However, you can build your own Objective-C binding.

**Comment by Jshto** [comment]
I used cocopods to import this SDK into my OC project. I imported # import "MobileBuySDK-Swift.h", unable to use graph. client and other classes, and it didn't work.
