### ISSUE TITLE
Manual discount amount is not getting

### ISSUE THREAD

**Issue by mahendragp** [Shopify/mobile-buy-sdk-ios#1022]
I've created a discount code from admin panel and the code is "ORDERPERCENTOFF" (by applying this code customer will get 5% OFF on the cart total).

When I apply this code it works as expected and it the amount is get deducted from total and it gives me current total after discount apply.

But when I'm trying to get the deducted amount from checkout(from "discountApplications"), I'm not able to get it from Storefront APIs.

**This is how I'm applying discount coupon**

    let mutation = Storefront.buildMutation { $0
            .checkoutDiscountCodeApplyV2(discountCode: code, checkoutId: GraphQL.ID(rawValue: id)) { $0
                .checkout { $0
                    .id()
                    .subtotalPriceV2 { $0
                        .amount()
                    }
                    .totalPriceV2 { $0
                        .amount()
                    }
                    .totalTaxV2 { $0
                        .amount()
                    }
                    .discountApplications(first: 5) { $0
                        .edges { $0
                            .node { $0
                                .allocationMethod()
                                .value { $0
                                    .onMoneyV2 { $0
                                        .amount()
                                    }
                                }
                            }
                        }
                    }
                    .lineItemsSubtotalPrice { $0
                        .amount()
                    }
                    .lineItems(first: 10) { $0
                        .edges { $0
                            .cursor()
                            .node { $0
                                .title()
                                .id()
                                .quantity()
                                .variant { $0
                                    .availableForSale()
                                    .id()
                                    .product { $0
                                        .images(first: 1) { $0
                                            .edges { $0
                                                .node { $0
                                                    .originalSrc()
                                                }
                                            }
                                        }
                                        .collections(first: 1) { $0
                                            .edges { $0
                                                .node { $0
                                                    .id()
                                                    .title()
                                                }
                                            }
                                        }
                                    }
                                    .priceV2 { $0
                                        .amount()
                                    }
                                    .compareAtPriceV2  { $0
                                        .amount()
                                    }
                                    .selectedOptions { $0
                                        .name()
                                        .value()
                                    }
                                }
                            }
                        }
                    }
                }
                .checkoutUserErrors { $0
                    .field()
                    .message()
                }
            }
        }
 
     let client = Graph.Client(shopDomain: "my Shopify domain", apiKey: "my api key")
    client.mutateGraphWith(mutation) { (response, error) in

            if let id = response?.checkoutDiscountCodeApplyV2?.checkout?.id.rawValue, error == nil {
                print("applyDiscount response: \(response as Any)")

                //here I am getting amount of discount code      
                let amt = response?.checkoutDiscountCodeApplyV2?.checkout?.discountApplications.edges.first?.node.value
          
                handler(id, response?.checkoutDiscountCodeApplyV2?.checkoutUserErrors.first?.message)
                
            } else {
                
                print("applyDiscount error: \(error as Any)")
                handler(nil, "Coupon code can not be applied. Please try again later.")
            }
            
        }.resume()

**How to get discount amount**

 let amt = response?.checkoutDiscountCodeApplyV2?.checkout?.discountApplications.edges.first?.node.value

**From Mobile Buy SDK**

    /// The price value (fixed or percentage) for a discount application. 
    public protocol PricingValue {
    }

It is a empty protocol. So I am not getting how do I get the applied discount coupon amount in checkout.

Any help or suggestions?

**Comment by dbart01** [comment]
`PricingValue` is a GraphQL interface and in this case, can be one of two concrete types: `MoneyV2` or `PricingPercentageValue`. You can get to the concrete type by casting `value` accordingly.

**IMPORTANT**: Since `value` can be one of two concrete types, it's your responsibility to handle both types. If your app is only ever expecting `MoneyV2`, this won't apply to you but has the potential to crash in the future if you start using percentage discounts.

Example of cast:
```swift
let discounts = response?.checkoutDiscountCodeApplyV2?.checkout?.discountApplications.edges.compactMap { $0.node.value as? Storefront.MoneyV2 }

discounts.forEach {
    $0.doSomethingWithMoney()
}
```

**Comment by Komal2905** [comment]
@dbart01 
right now I am getting only MoneyV2 type.
Question is how to read coupon code value which I got from response, so that I can show this is UI

**Comment by darshanwb** [comment]
**Using this graph ql query you have received all cart data with total or subtotal value**

mutation {
  checkoutDiscountCodeApplyV2(checkoutId: "gid://shopify/Checkout/81e5cb6277fc9d3014291e39e56c73?key=070d38051797c886cbe28bbb6f7f433e", discountCode: "AmountOffOrder") {
    checkout {
      id
      webUrl # for testing perpose
      lineItems(first: 250) {
          edges {
            node {
                id
              title
              quantity
              variant {
                title
                price{
                    amount
                }
                image {
                src
              }
              product {
                productType
              }
              selectedOptions {
                name
                value
              }
              }
              discountAllocations {
              allocatedAmount {
                amount
                currencyCode
              }
              discountApplication {
                targetSelection
                targetType
                ... on DiscountCodeApplication {
                  applicable
                  #discountCode {
                   #code
                  #}
                  code
                  value{
                    ... on MoneyV2{
                        amount
                    }
                  }
                }
              }
            }
            } 
          } 
        }
        currencyCode
        lineItemsSubtotalPrice{
            amount
        }
        order{
            currentSubtotalPrice{
                amount
            }
        }
        paymentDue{
            amount
        }
        totalDuties{
            amount
        }
        totalPrice{
            amount
        }
        totalPriceV2{
            amount
        }
        #Get Finally Sub total
        subtotalPriceV2{
            amount
        }
    }
    checkoutUserErrors{
        code
        field
        message
    }
    userErrors {
      field
      message
    }
  }
}

**Comment by darshanwb** [comment]
**Using this graph ql query you have received all cart data with total or subtotal value**

`mutation {
  checkoutDiscountCodeApplyV2(
    checkoutId: "gid://shopify/Checkout/81e5cb6277fc9d3014291e39e56c73?key=070d38051797c886cbe28bbb6f7f433e"
    discountCode: "AmountOffOrder"
  ) {
    checkout {
      id
      webUrl # for testing perpose
      lineItems(first: 250) {
        edges {
          node {
            id
            title
            quantity
            variant {
              title
              price {
                amount
              }
              image {
                src
              }
              product {
                productType
              }
              selectedOptions {
                name
                value
              }
            }
            discountAllocations {
              allocatedAmount {
                amount
                currencyCode
              }
              discountApplication {
                targetSelection
                targetType
                ... on DiscountCodeApplication {
                  applicable
                  #discountCode {
                  #code
                  #}
                  code
                  value {
                    ... on MoneyV2 {
                      amount
                    }
                  }
                }
              }
            }
          }
        }
      }
      currencyCode
      lineItemsSubtotalPrice {
        amount
      }
      order {
        currentSubtotalPrice {
          amount
        }
      }
      paymentDue {
        amount
      }
      totalDuties {
        amount
      }
      totalPrice {
        amount
      }
      totalPriceV2 {
        amount
      }
      #Get Finally Sub total
      subtotalPriceV2 {
        amount
      }
    }
    checkoutUserErrors {
      code
      field
      message
    }
    userErrors {
      field
      message
    }
  }
}
`
