### ISSUE TITLE
Update checkoutWithCreditCard documentation

### ISSUE THREAD

**Issue by RishabhTayal** [Shopify/mobile-buy-sdk-ios#1023]
The current README.md documentation uses V1 of `checkoutCompleteWithCreditCard` mutation. It would be nice to update it to `checkoutCompleteWithCreditCardV2`.

**Comment by rebeccajfriedman** [comment]
Repo is open source! Feel free to make a PR to fix this :)

**Comment by RishabhTayal** [comment]
done
