### ISSUE TITLE
Missing nextActionUrl in Payment object 

### ISSUE THREAD

**Issue by antoinelamy** [Shopify/mobile-buy-sdk-ios#1030]
With 3D secure payments coming across Europe in the following 18 months, the checkout API has changed to include the `nextActionUrl` field in Payment object. I currently don't see this change being reflected in the SDK, would be nice to add it ASAP so that the apps can properly update in time. Would also worth updating the sample code for completing a checkout to include the 3D secure flow.

Reference:
https://help.shopify.com/en/api/guides/3d-secure?utm_source=exacttarget&utm_medium=email&utm_campaign=support&utm_content=support

**Comment by rebeccajfriedman** [comment]
Hi @antoinelamy - this change will only be released in a public version of the Storefront API as part of the `2019-10` release (likely next week). We will propagate this change through to the SDK as soon as it is publicly available in a stable API release.

**Comment by dbart01** [comment]
Shipped in [3.6.1](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.6.1)
