### ISSUE TITLE
Can't checkout. MobileBuySDK.Graph.QueryError error 4

### ISSUE THREAD

**Issue by VasApps** [Shopify/mobile-buy-sdk-ios#1038]
We have a mobile app builder that our merchants use. During the checkout process we create the checkout url and push the user to a webView. Our checkouts have been working since the beginning but suddenly stopped working for many but not all of our merchants.

After logging the error it comes back as following;

"The operation couldn’t be completed. (MobileBuySDK.Graph.QueryError error 4.)"

Some Mobile Buy SDK requests work. For example using the same client I can search for products, collections buy I simply can't create the checkout url, apply discounts, add gift cards, etc. What is going on here? My guess is the storefront token is corrupted.

**Comment by townsendeb** [comment]
Im having this same problem, how did you solve this? @VasApps

**Comment by AdamBCo** [comment]
@VasApps How did you resolve this issue? What was the problem?

**Comment by samsidd** [comment]
have you resolve this error @AdamBCo & @townsendeb

**Comment by GhostCoder7** [comment]
Any solution to this?
