### ISSUE TITLE
File "GraphQL.swift" is absent in the source.

### ISSUE THREAD

**Issue by Alexeichua** [Shopify/mobile-buy-sdk-ios#1039]
Branch "master".
Sample project is in un-buildable state. I din't find any specific description if it's made specially for some reasons. If so, I'm sorry. I've downloaded to get familiar with the SDK, but I can't do anything with this, because the file is just absent.

**Comment by QaiserAbbas** [comment]
I can not find this file as well? How you have created this one?

**Comment by dbart01** [comment]
Please follow the [installation instructions](https://github.com/Shopify/mobile-buy-sdk-ios#installation-). You're missing a submodule.
