### ISSUE TITLE
How to upload a file or image in Mobile Buy Sdk

### ISSUE THREAD

**Issue by Bhargavasrinivas** [Shopify/mobile-buy-sdk-ios#1041]
Hi , 

I am developing an android  application  using Buy SDk ,where  we are supporting for Screen prints and Embroidery work for shirts , so we had given a button to upload file or image so my question is how to send the uploaded file or image to Checkout page . 
  Plz help me out to sort this issue .

**Comment by rebeccajfriedman** [comment]
Hello @Bhargavasrinivas , [please use our forums](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) for questions around implementing features.
