### ISSUE TITLE
Getting different response 

### ISSUE THREAD

**Issue by Komal2905** [Shopify/mobile-buy-sdk-ios#1042]
I need to get product  which are in stock
When I run
 
```graphql
{
  products(first: 10, reverse: false, sortKey: TITLE, query: "inventory_total:0") {
    edges {
      cursor
      node {
        id
        title
      }
    }
  }
}
```

in shopify-graphiql-app  , I get proper result.

but when I use same query in mobile app, the condition in query is getting ignored, and app received all product which have  inventory_total > 0

**Comment by dbart01** [comment]
Could you please provide the query that you've built using the Buy SDK query builder?

**Comment by Komal2905** [comment]
@dbart01 

{shop{name,paymentSettings{currencyCode,countryCode}},products(first:10,reverse:false,sortKey:TITLE,query:"inventory_total:0"){edges{cursor,node{id,title,description,descriptionHtml,vendor,productType,createdAt,updatedAt,tags,images(first:1){edges{node{id,originalSrc,altText}}},variants(first:250){edges{node{price,availableForSale}}},options{id,name,values}}}}}

this is the build query

**Comment by dbart01** [comment]
Please use `available_for_sale:false` instead. As per the `query` parameter documentation:

![Screen Shot 2019-12-12 at 8 20 19 AM](https://user-images.githubusercontent.com/5244861/70715411-3e1efd80-1cb8-11ea-9fbf-877bc2921a03.png)

**Comment by Komal2905** [comment]
@dbart01 Thank you so much :)
I was struggling for 2 days to achieve this
