### ISSUE TITLE
How to get  totalInventory

### ISSUE THREAD

**Issue by Komal2905** [Shopify/mobile-buy-sdk-ios#1045]
I need total inventory of product and I can see in following document that It can get by totalInventory field.
https://help.shopify.com/en/api/graphql-admin-api/reference/object/product?api[version]=2019-10

but can see this value in Storefront.ProductQuery

**Comment by DrTeePot** [comment]
That link is for the [Admin API](https://shopify.dev/docs/admin-api), which is used to extend the merchant experience. These SDK's use the [Storefront API](https://shopify.dev/docs/storefront-api), which is used to build custom storefronts (buying experiences).

[`totalInventory` will be available in the `2020-04` version of the Storefront API](https://shopify.dev/docs/storefront-api/reference/object/product?api[version]=2020-04), and this SDK will be updated shortly after the API is publicly released. Note that you will need the `unauthenticated_read_product_inventory` scope to read product inventory.
