### ISSUE TITLE
How to get cardVaultUrl

### ISSUE THREAD

**Issue by RuchiMakadia** [Shopify/mobile-buy-sdk-ios#1053]
I am currently using 3.7.0 SDK, I am stuck in API cardClient.vault.

I am trying to get token from below code as per mention in the document 

```
 let settings: Storefront.PaymentSettings
        let cardClient: Card.Client = Card.Client()
        
        let task = cardClient.vault(creditCard, to: settings.cardVaultUrl) { (token, error) in
            token
        } 
```
getting error when in code settings.cardVaultUrl 

> Constant 'settings' used before being initialized

I find it to write like 

> Storefront.PaymentSettings()

 something like 

> Card.Client()

but not work please help me Where am I supposed to get that URL from? Thank in advance.

**Comment by dbart01** [comment]
The GraphQL query you're looking for is this:
```graphql
{
  shop {
    paymentSettings {
      cardVaultUrl
    }
  }
}
```

**Comment by RuchiMakadia** [comment]
Thank you
