### ISSUE TITLE
Getting error on Product(media query)

### ISSUE THREAD

**Issue by manoharsinghrawat-cedcoss** [Shopify/mobile-buy-sdk-ios#1060]
MobileBuySDK.Graph.QueryError.invalidQuery(reasons: [MobileBuySDK.Graph.QueryError.Reason(message: "Field \'media\' doesn\'t exist on type \'Product\'", line: nil, column: nil)])

**Comment by osamie** [comment]
Hi @manoharsinghrawat-cedcoss can you confirm what version of the SDK you're seeing this?

**Comment by manoharsinghrawat-cedcoss** [comment]
i am using sdk version 3.7.0

**Comment by osamie** [comment]
@manoharsinghrawat-cedcoss  plz give it a try again with the new patch 3.7.1
Refs
GH: https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.7.1
Cocoa pods: https://cocoapods.org/pods/Mobile-Buy-SDK

I'll leave this Githib issue open for tracking purposes

**Comment by manoharsinghrawat-cedcoss** [comment]
I have uploaded .glb 3D model in media in products as shopify allows only glb extension models to be uploaded, now i want to use usdz file that i am getting from media sources but the image in the usdz model is black and white whereas the image in glb model is colorful. Please check this issue

**Comment by manoharsinghrawat-cedcoss** [comment]
Also in StoreFront.MediaEdge, I am unable to access sourcess in node 
![Screenshot 2020-04-04 at 12 24 26 PM](https://user-images.githubusercontent.com/25762783/78420733-72efff80-766f-11ea-962d-627b7f3bb3c3.png)

**Comment by dbart01** [comment]
The problem is that `MediaEdge.node` exposes an interface not a concrete type. Your node is actually a `Storefront.Media` interface that must be cast to a concrete type before it can be used. If your `Media` instance represent a 3D model, you'll need to do something like this:
```swift
let sources = (model.node as? Storefront.Model3d).sources
```
