### ISSUE TITLE
CreateCheckout mutation / response issue 

### ISSUE THREAD

**Issue by patelgaurav4u** [Shopify/mobile-buy-sdk-ios#1076]
**I am getting**  

```
discountApplication =                                 {
                                    "__typename" = AutomaticDiscountApplication;
                                };

```

**check this mutation for createcheckout** 

`mutation{checkoutCreate(input:{lineItems:[{quantity:1,variantId:"Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMTgyMzg3OTIwOTAzMg=="},{quantity:1,variantId:"Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMTgyMzg3OTU2OTQ4MA=="}],allowPartialAddresses:true}){checkoutUserErrors{field,message},checkout{id,ready,requiresShipping,taxesIncluded,email,order{id,orderNumber,totalPrice},discountApplications(first:250){edges{node{__typename,... on DiscountCodeApplication{applicable,code},... on ManualDiscountApplication{title},... on ScriptDiscountApplication{description}}}},shippingDiscountAllocations{allocatedAmount{amount,currencyCode},discountApplication{__typename,... on DiscountCodeApplication{applicable,code},... on ManualDiscountApplication{title},... on ScriptDiscountApplication{description}}},shippingAddress{firstName,lastName,phone,address1,address2,city,country,countryCodeV2,province,provinceCode,zip},shippingLine{handle,title,price},note,lineItems(first:250){edges{cursor,node{variant{id,price},title,quantity,id,discountAllocations{allocatedAmount{amount,currencyCode},discountApplication{__typename,... on DiscountCodeApplication{applicable,code},... on ManualDiscountApplication{title},... on ScriptDiscountApplication{description}}}}}},webUrl,currencyCode,subtotalPrice,totalTax,totalPrice,paymentDue}}}
`

**Comment by patelgaurav4u** [comment]
@dbart01 please look into this ,
this is facing in live application

**Comment by patelgaurav4u** [comment]
this is api version related issue.

**Comment by osamie** [comment]
Hello @patelgaurav4u 👋 
What is the actual error you are seeing when you call createCheckout? And can you confirm what version of the sdk you're using?

**Comment by patelgaurav4u** [comment]
we got __typename in response even i have't pass in Query

**Comment by dbart01** [comment]
This is not an issue.

**Comment by patelgaurav4u** [comment]
yes , i realize this things , but please update your demo code according the features
