### ISSUE TITLE
Sample not working after changing domain and APIkey

### ISSUE THREAD

**Issue by bharatidudhrejiya** [Shopify/mobile-buy-sdk-ios#1078]

**Comment by osamie** [comment]
@bharatidudhrejiya plz visit https://github.com/Shopify/mobile-buy-sdk-ios-sample to try out the sample app

**Comment by anatoliykant** [comment]
> @bharatidudhrejiya, пожалуйста, посетите [https://github.com/Shopify/mobile-buy-sdk-ios-sample,](https://github.com/Shopify/mobile-buy-sdk-ios-sample) чтобы попробовать пример приложения.

I just checked the application example on the specified link, added a link to my online store (shopDomain) and changed apiKey.
Everything works fine for me.
A very good example application.
Thx, Osamie!

**Comment by osamie** [comment]
@anatoliykant excellent :) 
@bharatidudhrejiya plz visit our [FORUMS](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology) if you run into any further issues. Thanks
