### ISSUE TITLE
Sdk is not syncing immediately with store products information

### ISSUE THREAD

**Issue by manoharsinghrawat-cedcoss** [Shopify/mobile-buy-sdk-ios#1090]
if I make any change in product information in admin and save it and then query product using sdk , I still get the old information of product, even after trying about 10 minutes I am getting the same information till the app is reinstalled

**Comment by dbart01** [comment]
You're hitting the local cache. If you want latest data, you'll need to bypass the cache. Having said that, I only recommend disabling the cache for development as it will have adverse UX side-effects in production.

Have a look at this [issue](https://github.com/Shopify/mobile-buy-sdk-ios/issues/767#issuecomment-335444864) for an example on how to work with cache policies.
