### ISSUE TITLE
Swift Package support for Xcode

### ISSUE THREAD

**Issue by diogot** [Shopify/mobile-buy-sdk-ios#1095]
Hi,

We're migrating our project to use Swift Package Manager Xcode integration to handle our dependencies, is there any plan to support it?

Thanks

**Comment by Codeglee** [comment]
Likewise, we'd appreciate this.

**Comment by dbart01** [comment]
SPM support is now available in [v5.1.0](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/5.1.0)!

**Comment by diogot** [comment]
Awesome, thanks!
