### ISSUE TITLE
Issue in webcheckout

### ISSUE THREAD

**Issue by manoharsinghrawat-cedcoss** [Shopify/mobile-buy-sdk-ios#1096]
With the help of Shopify SDK, we are implementing Web Checkout in the mobile apps. However, there is one issue in the case of logged-in customers. The mobile app is asking the customer to log in again inside the webview which is not appropriate even when the user is already logged in the mobile app .
Please look into it and let us know how this issue can be fixed.

**Comment by vixdug** [comment]
Hi @manoharsinghrawat-cedcoss 

Please see this discussion on the topic here: https://github.com/Shopify/mobile-buy-sdk-ios/issues/841 - Let me know if this does not resolve your issue.

**Comment by manoharsinghrawat-cedcoss** [comment]
Hi, I am getting https://magenative.myshopify.com/22806971/checkouts/01adb751ce5be2cbeff3348118ecebae?key=7e951583b48533d5dba521e75cada133 as weburl from checkoutCustomerAssociateV2 mutation query but again it opens a login page, however it should open a page as logged in user so please tell any solution for this
![Screenshot 2020-07-21 at 4 09 13 PM](https://user-images.githubusercontent.com/25762783/88045690-8bc3e880-cb6c-11ea-9b19-845ece360831.png)

**Comment by vixdug** [comment]
@manoharsinghrawat-cedcoss Are you using `WKWebView`? As stated in the linked issue:  

> Providing the customer access token using the X-Shopify-Customer-Access-Token header in your request to load the web checkout page should resolve the issue.

**Comment by manoharsinghrawat-cedcoss** [comment]
Thanks the above issue is resolved now. But now for customer url in query for orders i.e. https://www.awwalboutique.com/account/orders/a8dd9eef492404e1dab2fe5a20c5b5dd , it is redirecting to login page, can u please help how to authenticate and directly navigate to order details page?

**Comment by vixdug** [comment]
Glad that resolved it. I'm going to close the issue and move this conversation to the community forums as this is no longer a bug report: https://community.shopify.com/c/Storefront-API-SDKs/bd-p/custom-storefronts - Please post your how-to questions there with as much detail as possible for proper engagement.
