### ISSUE TITLE
Get Order name

### ISSUE THREAD

**Issue by mariapush** [Shopify/mobile-buy-sdk-ios#110]
I uses `[self startApplePayCheckout:self.checkout];`
Please tell me how can I get all the data about the successful order? name and date of creation?
Unfortunately I can not test it with a my credit card - this type of purchase is not available in my country and i have to work blindly

**Comment by davidmuzi** [comment]
A completed checkout object contains a `BUYOrder` object which contains the customers name, and the creation date can be obtained from the `BUYCheckout` itself.

**Comment by mariapush** [comment]
@davidmuzi You mean this method?
internal override func checkoutCompleted(checkout: BUYCheckout!, status: BUYStatus)
and this checkout will contain BUYOrder object ?

**Comment by davidmuzi** [comment]
yep

**Comment by mariapush** [comment]
@davidmuzi thank you so much!
