### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler on Xcode 12

### ISSUE THREAD

**Issue by das-palash-appsbee** [Shopify/mobile-buy-sdk-ios#1106]
### Description

Previously I was using Xcode 11.6 to build these frameworks using Carthage. Now I upgraded Xcode to 12 and after building these frameworks when I integrate into my project and tried to run, it shows an error like:

> Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### Steps to Reproduce

1. update your Xcode version to 12.0
2. Build framework using Carthage `carthage update --platform iOS` (version 5.0.0)
3. Add `Buy.framework` and `Pay.framework` into any project
4. Run the project

**Actual Error:** 

`/Users/John/Desktop/Shopify Demo/API/ClientQuery.swift:4:8: Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler: /Users/John/Desktop/Shopify Demo/Shopify Demo/Buy.framework/Modules/Buy.swiftmodule/x86_64-apple-ios-simulator.swiftmodule`

**Workarounds I tried:** 
1. So few workarounds like [this](https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler) where you need to set the **Build Libraries for Distribution** option to **Yes** in your framework's build settings, otherwise the swift compiler doesn't generate the neccessary .swiftinterface files which are the key to future compilers being able to load your old library. But it didn't solve the issue.
2. Next I tried this [Carthage workaround](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) where you need to tweak the **EXCLUDED_ARCHS** statement. But it also failed.

### Versions
    
1. Xcode v 12.0 (12A7209)
2. Carthage v 0.36.0
3. Shopify mobile-buy-sdk-ios  v 5.0.0

**Comment by SocialKitLtd** [comment]
Same issue here

**Comment by SatishMavani** [comment]
Same Issue

**Comment by uncleRX** [comment]
Same Issue

**Comment by mmoloksher** [comment]
same

**Comment by Imanmf** [comment]
same issue

**Comment by anama777** [comment]
Same issue

**Comment by imervich-globant** [comment]
Same issue

**Comment by vixdug** [comment]
Thanks for the feedback. We are looking into this - no more reports needed at this time.

**Comment by dbart01** [comment]
This is now fixed in [v5.1.0](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/5.1.0)! We also recommend to use Swift Package Manager for managing this dependency.

**Comment by DanGDroid** [comment]
try deleting Derived Data and build again

**Comment by newtest-cjt** [comment]
same question

**Comment by Imanmf** [comment]
I had this issue and some issue more. So I decide to migrate to cocoapod.
I am using cocoapod now and I have not any problem.
I suggest you to migrate to cocoa pod guys

**Comment by dbart01** [comment]
Use SPM instead.

**Comment by bunyod0210** [comment]
> try deleting Derived Data and build again

this helped me in Xcode 12 thanks

**Comment by Ganux1** [comment]
Came across this one:
https://github.com/Alamofire/Alamofire/issues/3280

Thought it could be helpful for someone...
