### ISSUE TITLE
facing issue 

### ISSUE THREAD

**Issue by Rakeshwama** [Shopify/mobile-buy-sdk-ios#1109]
error: Build input file cannot be found: '/Users/deepdoshi/Downloads/mobile-buy-sdk-ios-sample-master/mobile-buy-sdk-ios/Dependencies/Swift Gen/support/Sources/GraphQL.swift' (in target 'Buy' from project 'Buy')

**Comment by dbart01** [comment]
Please [follow the instructions](https://github.com/Shopify/mobile-buy-sdk-ios#installation-).

**Comment by Rakeshwama** [comment]
please tell me which step miss because i'm trying multiple times.same error showing to me 
git submodule add git@github.com:Shopify/mobile-buy-sdk-ios.git  showing "Please make sure you have the correct access rights" then I'm using git clone https://github.com/Shopify/mobile-buy-sdk-ios.git
after that same issue please help me .
thanks in advanced.
