### ISSUE TITLE
ApplePay checkout works slowly and inconsistently

### ISSUE THREAD

**Issue by poisonedslo** [Shopify/mobile-buy-sdk-ios#113]
We're facing some issues with ApplePay that we'd like to have resolved.

Issue 1 is that isApplePayAvailable often returns false, when it is available. Checking out the code, I'm not sure how much control you have over this.

Issue 2 is that it usually takes a long time to load ApplePay checkout. We're not doing anything special when starting the checkout process, just calling `startApplePayCheckout:` on BUYViewController.

**Comment by davidmuzi** [comment]
Hey@poisonedsio, 

1. Try putting a breakpoint in the `isApplePayAvailable` method, and check which of the 3 conditions are returning false:
```objective-c
- (BOOL)isApplePayAvailable
{
	// checks if the client is setup to use Apple Pay
	// checks if device hardware is capable of using Apple Pay
	// checks if the device has a payment card setup
	return (self.merchantId.length &&
			[PKPaymentAuthorizationViewController canMakePayments] &&
			[PKPaymentAuthorizationViewController canMakePaymentsUsingNetworks:self.supportedNetworks]);
}
```

2. When Apple Pay is triggered, 2 network calls are made, one to getShop, and another to create/update the checkout.  In your application you can call `getShop` early, and hold onto the `BUYShop` object, and set it on the `BUYViewController` property which will alleviate the need for the implicit call to `getShop` on each call to `startApplePayCheckout`

**Comment by poisonedslo** [comment]
Thanks, that worked!
