### ISSUE TITLE
Value of type '[BUYProduct]' has no member 'variants'

### ISSUE THREAD

**Issue by dzt** [Shopify/mobile-buy-sdk-ios#114]
I encountered a problem where my constant cannot reference the `variants` property from the `BUYProduct` Class. At the beginning of my code I made a variable called products which was an array of products under the BUYProducts class.

Code: https://gist.github.com/dzt/20d843890d73eb071a9a

![image](https://cloud.githubusercontent.com/assets/6421443/13973606/d78fa7da-f07a-11e5-818b-adc910a7ea0b.png)

**Comment by davidmuzi** [comment]
your code provided is trying to access the `variants` property of an array product**s**, instead of the local variable `product` declared on line 72
