### ISSUE TITLE
Access Level Update for AbstractResponse.rawFields property

### ISSUE THREAD

**Issue by mahmutpinarbasi** [Shopify/mobile-buy-sdk-ios#1192]
Hi,

With latest [10.0.0 [2023-01]](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/10.0.0) release, `rawFields` ( previously `fields`) property access level changed to *internal* on `AbstractResponse` class. which is kind a breaking change for entire serialize/deserialize operation on our app. So wondering was it intentional? Is it possible to switch back to `public` access level again? 

You can also see the similar usage on [mobile-buy-sdk-ios-sample](https://github.com/Shopify/mobile-buy-sdk-ios-sample/blob/0565810b86227df0a0211d38490718e1f9f5eb7b/Storefront/GraphQL%2BSerializable.swift)

<img width="1757" alt="Screen Shot 2023-01-31 at 01 04 05" src="https://user-images.githubusercontent.com/10567057/215606695-841e4e64-b670-4cf2-a077-5fd55ff3a6f8.png">

If you guys ok with it; I can create the PR.  what do you think @cocoahero ?

**Comment by mahmutpinarbasi** [comment]
Hi @cocoahero,

My usage is as following;

```swift
extension GraphQL.AbstractResponse: Serializable {
    
    static func deserialize(from representation: SerializedRepresentation) -> Self? {
        return try? self.init(fields: representation)
    }
    
    func serialize() -> SerializedRepresentation {
        return self.fields
    }
}
```

We are using similar infrastructure on our app with buy sdk example app. You can get more details about the usage from here: https://github.com/Shopify/mobile-buy-sdk-ios-sample/blob/0565810b86227df0a0211d38490718e1f9f5eb7b/Storefront/GraphQL%2BSerializable.swift

**Comment by cocoahero** [comment]
Hi @mahmutpinarbasi - please see the above linked PR and let me know if that will solve for your use case.

**Comment by mahmutpinarbasi** [comment]
Hi @cocoahero,

It perfectly solves the issue. Thanks for the quick action.
