### ISSUE TITLE
Add Customer login API

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#126]
Extend the Buy Client with new methods to expose functionality for the customer login API:
- [x] log in to existing account
- [x] log out
- [x] create a new account
- [x] reset password
- [x] fetch orders

@davidmuzi @dbart01

**Comment by bgulanowski** [comment]
Blocked by https://github.com/Shopify/mobile-buy-sdk-ios/issues/123

**Comment by zebarahman** [comment]
Hi, I need to add the Customer API into my app. How do I do it? Do I have to wait for version 2.0 release? When will that be? Thanks.
