### ISSUE TITLE
Improve BUYAccountCredentials API

### ISSUE THREAD

**Issue by dbart01** [Shopify/mobile-buy-sdk-ios#138]
The discoverability of available values is somewhat poor. Would be nice to have a more self-documenting interface to make it easy for developers to know exactly what keys are available to use with `BUYAccountCredentialItem`.

**Comment by zebarahman** [comment]
Hi, I need to add the Customer API into my app. How do I do it? Do I have to wait for version 2.0 release? When will that be? Thanks.
