### ISSUE TITLE
Issue when buying with Apple Pay

### ISSUE THREAD

**Issue by asoviche** [Shopify/mobile-buy-sdk-ios#146]
Hi,

We've done an iPhone App for a Shopify Store (8-9-clothing-co.myshopify.com). Here is the App : https://itunes.apple.com/us/app/8-9/id1094841626?ls=1&mt=8.

It seems users can pay through the App with Apple Pay, receive a confirmation of the payment, but the owner sees no order in his Shopify dashboard.

Is that a behaviour that you could previously observe?

Thanks,
Amaury

**Comment by bgulanowski** [comment]
I'm sorry, but we can't provide troubleshooting advice here. If you find a reproducible bug in the framework, and can provide clear steps to reproduce, please do so. For support and troubleshooting, please use the Shopify forums: https://ecommerce.shopify.com/forums

**Comment by davidmuzi** [comment]
Also, looking at the server logs, and network traffic from the iOS app, it doesn't appear that the Mobile Buy SDK is being used.
