### ISSUE TITLE
Carthage Build Error

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#15]
Building the framework using `carthage update --platform ios` produces an error of:

```
error: cannot parse the debug map for ".../Carthage/Build/iOS/Buy.framework/Buy": The file was not recognized as a valid object file
```

Xcode 7.0.1, Carthage 0.9.2

**Comment by runmad** [comment]
Feel to try out https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/1.2.1 which has a bunch of fixes
