### ISSUE TITLE
Explore cancelling aggregate methods that call multiple URL session tasks

### ISSUE THREAD

**Issue by dbart01** [Shopify/mobile-buy-sdk-ios#158]

**Comment by davidmuzi** [comment]
I think this is a suitable candidate for using NSOperations, which can abstract the NSURLSessionTasks and expose support for cancelling, dependancies, and chaining callbacks.

**Comment by dbart01** [comment]
I think that all `BUYClient` requests should be `NSOperations` 😄

**Comment by davidmuzi** [comment]
Can this be closed?
