### ISSUE TITLE
Add nullability and generics attributes to all public API

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#16]

**Comment by calebd** [comment]
Because Swift.

**Comment by cocoahero** [comment]
WIP branch: https://github.com/hodinkee/mobile-buy-sdk-ios/tree/generics-nullability

**Comment by ollieatkinson** [comment]
:+1:

**Comment by calebd** [comment]
Bumping this issue.

**Comment by bgulanowski** [comment]
Should be solved by version 2.0. Please see develop branch.
