### ISSUE TITLE
Warning in Mobile Buy SDK iOS

### ISSUE THREAD

**Issue by tvjax** [Shopify/mobile-buy-sdk-ios#163]
"'ABRecordRef' is deprecated: first deprecated in iOS 9.0 - use CNContact, CNGroup, or CNContainer" is the warning... 

+ (nullable NSString *)buy_emailFromRecord:(nullable ABRecordRef)record;

How can this be corrected?

**Comment by davidmuzi** [comment]
Im not sure it can.  The SDK supports iOS 8 which requires these methods to exist for Apple Pay to work.

If your application runs on iOS 9+ you can safely remove those deprecated methods.

**Comment by grsteffens** [comment]
Hi @davidmuzi thanks for your reply! What if my project is targeting both 8.0 and 9.0? What do you feel would be the best approach?

**Comment by davidmuzi** [comment]
The SDK uses the correct API for each target.  You shouldn't have to change anything, the warnings can be ignored
