### ISSUE TITLE
Lack of typed collections using generated models in Swift

### ISSUE THREAD

**Issue by dbart01** [Shopify/mobile-buy-sdk-ios#168]
As a result of using Core Data, the model relationships require the use of `NSOrderedSet`, which do not translate to a typed collection in Swift. There is no concept or ordered sets in Swift, therefore making use of `to-many` relationships that use `NSOrderedSet` requires forced-casts. Ideally we want to avoid that.

**Comment by bgulanowski** [comment]
The solution is to provide convenience accessors that use `NSArray`.
