### ISSUE TITLE
Add missing customer API

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#179]
We are missing functionality in the customer API:

- logout
- update

If log out fails because the token doesn't exist, we shouldn't report that as an error. If it succeeds, the `BUYClient` should automatically delete it's copy of the token.

@dbart01 @gabrieloc

**Comment by davidmuzi** [comment]
We should aim for parity with Androids interface:
https://github.com/Shopify/mobile-buy-sdk-android/blob/version-2/MobileBuy/buy/src/main/java/com/shopify/buy/dataprovider/CustomerService.java

**Comment by dbart01** [comment]
Can we open a separate issue for that? There are quite a few differences.

**Comment by bgulanowski** [comment]
The only other missing function appears to be `update`. We should do them together in the same PR, as it's the same scope (missing customer API).

**Comment by gabrieloc** [comment]
Addresses API would need to be added as well.

**Comment by bgulanowski** [comment]
OK, we can make a separate issue for those: https://github.com/Shopify/mobile-buy-sdk-android/blob/version-2/MobileBuy/buy/src/main/java/com/shopify/buy/dataprovider/AddressService.java
