### ISSUE TITLE
Customer auth renewal inconsistent

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#180]
We should standardize all the client APIs to work with whole model objects, not parts. It's not up to developer to keep track of which parts of the API use which parts of models.

Specifically, extending the time of a customer authentication using `-renewCustomerTokenWithID:` should accept a customer argument, not a customer id.

@dbart01 @davidmuzi @gabrieloc

**Comment by davidmuzi** [comment]
The caveat with requiring the entire customer object is that the developer is expected to persist the entire customer object instead of just its ID.

**Comment by bgulanowski** [comment]
You're right. Let's leave it.
