### ISSUE TITLE
Remove all deprecated API

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#186]
Models have methods and properties that are no longer valid. Search for "NS_DEPRECATED_IOS" macro and related ones.

**Comment by dbart01** [comment]
We deprecated `- (void)updateWithRecord:(nullable ABRecordRef)record` but it seems to be used in several places. How do we want to handle this?

**Comment by bgulanowski** [comment]
We should not be using AddressBook anymore. So we have to switch to the Contacts API.

**Comment by davidmuzi** [comment]
Contact framework is not available on iOS 8
