### ISSUE TITLE
No way to maintain cart items between controllers

### ISSUE THREAD

**Issue by grsteffens** [Shopify/mobile-buy-sdk-ios#188]
Am I overlooking something or is there no way to maintain cart items between view controllers? If not, what would be the best way to do so?

**Comment by bgulanowski** [comment]
This sounds like a question about how to use the SDK. We only use Github for reporting and tracking reproducible bugs, not for general help requests.

You can find help on the Shopify API forums here:

https://ecommerce.shopify.com/c/shopify-apis-and-technology
