### ISSUE TITLE
Convert all `identifier` properties to `NSString`

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#196]
Must ensure that all body JSON includes the type expected by Shopify. If API requires a number, file an issue on the API and add a JSON Value Transformer string->number (specified in the attribute's user info dictionary in the model).

**Comment by dbart01** [comment]
@krisorr Mentioned that the JSON seems to contain integer (long) values for identifiers. Do we still want to convert to strings?

**Comment by bgulanowski** [comment]
Deferring.
