### ISSUE TITLE
Audit/fix any client API that modifies args

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#198]
This mostly (or only?) affects Checkout API. Ensure that we are not modifying arguments, but instead, if necessary, copying and modifying the copy.

**Comment by dbart01** [comment]
We've decided to leave the `applyGiftCardCode:` and `removeGiftCard:` API's as is (i.e. allow them to modify the `BUYCheckout` input argument) for the sake of simplicity.
