### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fananta** [Shopify/mobile-buy-sdk-ios#199]
A table of contents for the iOS documentation we should provide for SDK 2.0. (These changes are made in a separate private Shopify repo.)

- **iOS**
    - Overview
        - [x] Getting started
        - [x] Migrating from SDK 1.x
        - [x] Installation
        - [x] Initialization
        - [x] Custom local cache
        - [x] Error handling
    - Storefront Entities
        - [x] Collections
        - [x] Products
    - Checkout
        - [x] Cart
        - [x] Apple Pay (including BUYPaymentButton)
        - [x] Native checkout
        - [x] Web checkout
    - Customer Accounts
        - [x] Creating an account
        - [x] Log in and log out
        - [x] Reset password
        - [x] Activation
        - [ ] Order history
    - Sample Apps
        - [ ] Sample A
        - [ ] Sample B
        - [ ] Sample C
        - [ ] Sample D
    - API Reference

**Comment by fananta** [comment]
close #143, #144 as duplicates.

**Comment by bgulanowski** [comment]
We don't have documentation for the sample apps, but they are themselves documentation. Not going to write any more docs.
