### ISSUE TITLE
Cannot use @import Buy; from Cocoapods

### ISSUE THREAD

**Issue by thkeen** [Shopify/mobile-buy-sdk-ios#21]
If using Cocoapods, I cannot use @import Buy; at all
Error message is: Module 'Buy' not found

Do you guys have any idea?

**Comment by cocoahero** [comment]
@thkeen are you using cocoapods' frameworks?

I believe this is because the podspec does not have a module name configured, therefore it is defaulting to `Mobile_Buy_SDK`. This is fixed in #17.

**Comment by thkeen** [comment]
OK!

**Comment by runmad** [comment]
We're working on fixing Cocoapods, stay tuned. Thanks for the bug report + PR.

**Comment by runmad** [comment]
Feel free to test https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/1.2.1

**Comment by thkeen** [comment]
Thanks!
