### ISSUE TITLE
Cannot remove discount after apply

### ISSUE THREAD

**Issue by Qiki** [Shopify/mobile-buy-sdk-ios#213]
We want add remove discount/promo function in our app. But we didn't find a way to do that.
I tried set `BUYDiscount` to nil and use the `updateCheckout` function in SDK, but it doesn't work. The discount is still there.

Let me know! =)

Thank you so much!

**Comment by EishanVijay** [comment]
Hey! Set the checkout discount using  `discountWithCode` and pass in `nil` to remove the discount from your checkout.

**Comment by Qiki** [comment]
@EishanVijay thank you so much! =)

**Comment by EishanVijay** [comment]
Added `setDiscountCode:(nullable NSString *)code` to `BUYCheckout` so now you just have to pass `nil` as the code and it will remove the discount from the checkout.
