### ISSUE TITLE
Order placed via apple pay is not showing up in shopify order's section.

### ISSUE THREAD

**Issue by Vishal-Singh-Panwar** [Shopify/mobile-buy-sdk-ios#214]
The orders are not appearing in the Shopify Orders section. They appear in customer's Recent Orders section and we have manually mark it as paid to make them appear in orders section. I get the email confirmation however and I also get the order ID.
I made some changes in the BUYClient to make the API calls as described in [this](https://help.shopify.com/api/tutorials/sell-through-the-checkout-api) document. It works fine but I am not sure if this is a reliable change. As the document clearly mentions that:

> 
> Caution
> The Checkout API is only for use with the Sales Channel SDK. It is not possible to use it to create a new checkout for an individual store — for that you can use our JavaScript, iOS, and Android Buy SDKs.

The payment dictionary in the response of 'complete checkout' API is empty if I place an order without modifications and entire amount comes as "payment_due" . But, if I use the web checkout to place an order, then it works just fine. 

Also the changes don't work for Apple Pay. There is nothing specific to Apple Pay in the Checkout API documentation.

Test mode is enabled. I have tried disabling it also but no success. 

Please let me know if I'm missing anything.

**Comment by bgulanowski** [comment]
The `BUYClient` class already uses the Checkout API. What changes did you make, exactly?

We will look into the issue.

**Comment by Vishal-Singh-Panwar** [comment]
The issue got resolved. I disabled the mobile sales channel and enabled it again and everything started working fine. I dint do anything else.  Seems like it was problem with the account setup and not with the  SDK so this issue can be closed. Still wondering why it was happening and why the orders were being placed as unpaid.
