### ISSUE TITLE
BUYClient does not initialize on iPhone 5 and below (iOS 9.3)

### ISSUE THREAD

**Issue by grsteffens** [Shopify/mobile-buy-sdk-ios#217]
I have an issue where the BUYClient is not initializing correctly on iPhone 5 and below. It initializes on all other devices. The following is my code.

```
let shopDomain = "MYDOMAINNAME.myshopify.com"
let apiKey = "APIKEY"
let channelId = "CHANNEL ID"
let client: BUYClient

required init(coder aDecoder:NSCoder) {     
  client = BUYClient(shopDomain: shopDomain, apiKey: apiKey, channelId: channelId)
  super.init(coder: aDecoder)!
}

//Then to call the BUYProductViewController

func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
        
        let cell = collectionView.cellForItemAtIndexPath(indexPath)
        let productViewController: BUYProductViewController = self.productViewController()
        
        productViewController.loadProduct(String(cell!.tag), completion: { (success, error) in
          
            if error == nil {
                productViewController.presentPortraitInViewController(self)
            } else {
                print(error)
            }
            
        })
        
}
    
func productViewController() -> BUYProductViewController {
        
        let theme: BUYTheme = BUYTheme()
        theme.style = .Light
        theme.tintColor = Common.colorWithHexString("#336894", alpha: 1.0)
        theme.showsProductImageBackground = true
        let productViewController = BUYProductViewController.init(client: self.client, theme: theme)
        return productViewController
        
}
```

I only receive the error "Error Domain=shopify Code=3 "Product IDs are not valid. Confirm the product IDs on your shop's admin and also ensure that the visibility is on for the Mobile App channel." I know the item is visible because it loads on other devices (iPhone 5s, iPhone 6, etc). Any help is greatly appreciated.

**Comment by davidmuzi** [comment]
There is no device specific code for network handling.

Can you see how the network requests differ between the device that work and don't?  You should be able to inspect the NSURLSessionDataTasks that are generated in the BUYClient.

**Comment by lengocgiang** [comment]
You should check, function convert type Product IDs .Because iPhone5 is using architect 32bit and 5s/6/6s.. using  architect 64bit . May be it's reason appears error "Product IDs are not valid"

**Comment by bgulanowski** [comment]
If we try to store the product ID in a 32-bit integer, then any products with IDs that are a 64-bit integer will get truncated. But `BUYProduct.productID` is an `NSNumber`. The JSON conversion should only use objects, not an integral type.

Can you verify whether the generated request payload (`NSHTTPReqest.HTTPBody`) contains the correct or an incorrect product ID? (You can read the payload in the LLDB debugger by setting a breakpoint in the `getProduct` method on `BUYClient`, and then type something like:

```swift
po NSString(data: NSHTTPReqest.HTTPBody, encoding: 4)
```

**Comment by bgulanowski** [comment]
Closing due to age. If more information is available, please update and re-open.
