### ISSUE TITLE
Better Checkout Error Handling

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#22]
In our app, we have had several reports from users having issues at checkout. We currently show an `UIAlertView` when an error occurs during the checkout process (from the many delegate methods available) showing the error's description. The most common message is `The operation could not be completed. (shopify error 422)`.

From being able to reproduce the issue locally, I can see that `userInfo` object has some rather raw JSON describing what appears to be an out of stock scenario for one of the products in the cart.

Would it be possible to receive specific `NSError`codes or something so we can better describe the issue at hand to our users?

**Comment by thkeen** [comment]
Experiencing a similar behaviour. SDK says Failed to update checkout, error == nil.

**Comment by runmad** [comment]
What's the status code you're seeing @thkeen?

**Comment by RockyLin** [comment]
code 422 It's hard to get useful information. I have to parse the Error object for precisely error message.
{
    errors =     {
        checkout =         {
            "billing_address" =             {
                phone =                 (
                                        {
                        code = blank;
                        message = "can't be blank";
                        options =                         {
                        };
                    }
                );
            };
            email =             (
            );
            "line_items" =             (
            );
            "payment_gateway" =             (
            );
            "reservation_time" =             (
            );
            "shipping_address" =             {
                phone =                 (
                                        {
                        code = blank;
                        message = "can't be blank";
                        options =                         {
                        };
                    }
                );
            };
            "source_name" =             (
            );
        };
    };
}

**Comment by RockyLin** [comment]
It's hard to get useful information. I have to parse the Error object for precisely error message.
code422{
    errors={
        checkout={
            "billing_address"={
                phone=({
                    code=blank;message="can't be blank";options={
                        
                    };
                });
            };email=();"line_items"=();"payment_gateway"=();"reservation_time"=();"shipping_address"={
                phone=({
                    code=blank;message="can't be blank";options={
                        
                    };
                });
            };"source_name"=();
        };
    };
}

**Comment by RockyLin** [comment]
It's hard to get useful information. I have to parse the Error object for precisely error message.
{
code422
{
    errors={
        checkout={
            "billing_address"={
                phone=({
                    code=blank;message="can't be blank";options={
                        
                    };
                });
            };email=();"line_items"=();"payment_gateway"=();"reservation_time"=();"shipping_address"={
                phone=({
                    code=blank;message="can't be blank";options={
                        
                    };
                });
            };"source_name"=();
        };
    };
}
}

**Comment by poisonedslo** [comment]
Yes, the message is hard to extract and it's often not something you would display to user. It would be very good if user friendly message would be delivered too

**Comment by macromania** [comment]
I really wonder what is the JSON standard followed in this error message?

**Comment by junketjim** [comment]
I agree - I had to write a helper which recursed until we find the code, options and message components of the error.  In order to provide context to the error I had to make a note of the path that I took to get there - for example, ```checkout > creditCard > number``` for invalid card number (or something like that).

**Comment by mihai-moldovan** [comment]
Is there any document which defines all the possible errors?

**Comment by jaysonlane** [comment]
Does anyone have a Shopify error parser they would be willing to open source?

**Comment by biddster** [comment]
Any update on this? A document would be great. Please.

**Comment by davidmuzi** [comment]
While not exhaustive, you can see some of the work going on in our 2.0 integration branch
https://github.com/Shopify/mobile-buy-sdk-ios/blob/integration/sdk-2.0/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Utils/BUYError+BUYAdditions.m

**Comment by jacks205** [comment]
Does anyone know what type of notation the error descriptions are in? I want to try to parse this manually for a project I'm working on.

**Comment by quocble** [comment]
Agreed. The error message sucks!

This is one attempt to extract some errors out 

```+ (NSString*) getCheckoutError: (NSError *) error {
    __block NSString *errorText = @"";
    NSDictionary *checkout = error.userInfo[@"errors"][@"checkout"];
    [checkout enumerateKeysAndObjectsUsingBlock:^(id  _Nonnull key, id  _Nonnull obj, BOOL * _Nonnull stop) {
        if([obj isKindOfClass: [NSArray class]] && [obj count] > 0) {
            errorText = [errorText stringByAppendingFormat:@"%@ %@\n", key,  obj[0][@"message"]];
        } else if([obj isKindOfClass: [NSDictionary class]]){
            [obj enumerateKeysAndObjectsUsingBlock:^(id  _Nonnull key2, id  _Nonnull obj2, BOOL * _Nonnull stop) {
                if([obj2 isKindOfClass: [NSArray class]] && [obj2 count] > 0) {
                    errorText = [errorText stringByAppendingFormat:@"%@ %@ %@\n", key, key2,  obj2[0][@"message"]];
                }
            }];
        }
    }];
    return errorText;
}```

**Comment by jacks205** [comment]
I just noticed they added a new release ([2.0.0](https://github.com/Shopify/mobile-buy-sdk-ios/releases)) and one of their release notes states that they have "Simplified checkout handling". Has anyone seen any updated docs about this or tried it out themselves to see if they improved these error messages?

**Comment by bgulanowski** [comment]
The structure of errors coming back from the endpoints will not be changed. They are designed to match the structure of the data provided in the request.

This file, introduced in 2.0, handles error parsing for some cases:

https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Utils/BUYError+BUYAdditions.m

Please file new issues for specific cases.
