### ISSUE TITLE
Unable to build integration/sdk-2.0 if imported via CocoaPods

### ISSUE THREAD

**Issue by nejcpintar** [Shopify/mobile-buy-sdk-ios#229]
I tried to use the integration branch with CocoaPods 1.0.1 and it doesn't find header files in project. Probably the err is on my side, how can I solve it?

**Comment by bgulanowski** [comment]
Thanks for the report. We will look into it.

**Comment by bgulanowski** [comment]
Fix for this has been posted for review. See PR #247

**Comment by bgulanowski** [comment]
Fixed. Please confirm, thanks.

**Comment by bgulanowski** [comment]
Note that it won't be on the public CocoaPods index until we merge develop into master.
