### ISSUE TITLE
Shopify Script Editor does not apply to Mobile Buy SDK Checkout

### ISSUE THREAD

**Issue by horsejockey** [Shopify/mobile-buy-sdk-ios#231]
The [Shopify Script Editor](https://help.shopify.com/manual/apps/apps-by-shopify/script-editor) allows Shopify Plus users to write a ruby script that is run on the server side to apply discounts and change product properties based on the customers cart.  This script is not being applied to customer checkouts created using the mobile buy sdk.  I created a simple script that should take a product and reduces it by $10.  Works fine on the website store but no discount is applied on the app checkout

```
self.client.createCheckout(checkout) { (checkout, error) in
        if let checkout = checkout {
            print("price should be $10.00")
            print(checkout.totalPrice) // actual price is $20
        }
}
```

This would need to be a server side fix that would run the cart passed in via createCheckout through the script that can be created using the Shopify Script Editor.  This would create a consistent discount/promotion experience for customers wether they are shopping on the web or through the mobile app.

**Comment by bgulanowski** [comment]
This is being explored internally. As you say, it is not an issue with the Buy SDK. We'll update when we have more information. Could be a while.

**Comment by conradbarrett** [comment]
Is there a roadmap for when this will be implemented? Our team is looking for the same functionality.

**Comment by maxlippe** [comment]
@horsejockey I'm having a similar issue right now, did you end up getting it resolved?

**Comment by horsejockey** [comment]
@maxlippe The feature still isn't available.  Please bring it up with whoever you know at Shopify. I talked with my account manager.  I did get a result kind of similar to what I wanted.  We run a special on mobile where if you spend x $ you get a free gift (water bottle or beanie).  I created duplicates of those products and set the price to $0.00 then made them only visible on mobile.  I make sure to not display those products in the app and I manually add them to the cart when they hit the threshold.

**Comment by MikeDeasyBB** [comment]
@bgulanowski has this had any movement?

**Comment by rebeccajfriedman** [comment]
Scripts are now available for private apps: https://developers.shopify.com/changelog/storefront-api-updates-metafields-scripts-and-more
