### ISSUE TITLE
BUYCheckout setting details back to nil causing "can't be blank" error

### ISSUE THREAD

**Issue by jacks205** [Shopify/mobile-buy-sdk-ios#234]
An error for a BUYCheckout detail doesn't show up until you set an invalid property, and resetting that property to nil won't remove that error.

For example,
If you call `updateCheckout` before setting the `billingAddress`, then no error is given. If you set an invalid `billingAddress`, then an error is reported. If you set the `billingAddress` back to nil, then you receive an `can't be blank` error message. 

It's very hard to build a checkout when it needs to be filled in and corrected in order. If I wanted to build my checkout to update when each field is entered (billing address, shipping, contact email, etc), then I get into this deadlock of errors coming back for every detail.

**Comment by mihai-moldovan** [comment]
I ran into the same problem. My workaround is to recreate the checkout from scratch everytime. But it feels more like a hack

**Comment by bgulanowski** [comment]
Which branch is this happening on? Possibly, the `nil` is not being correctly converted to a `null` in the JSON. But can you post a sample of the update request payload (`HTTPBody` on the request object)? Or just update with whether there is a key for `billing_address` with a `null` value in there.
