### ISSUE TITLE
Checkout with already logged in user

### ISSUE THREAD

**Issue by chuongdang** [Shopify/mobile-buy-sdk-ios#241]
I'm testing the SDK 2.0, specially Login and Checkout feature. Currently I managed to login but how can I use that session for webview checkout?

Could someone please help me on this? Thank a lot.

**Comment by davidmuzi** [comment]
If you use the provided PaymentProvider classes, opening a web checkout will automatically authenticate the web session if the user is logged in the app.

https://github.com/Shopify/mobile-buy-sdk-ios/blob/develop/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Payment%20Providers/BUYWebCheckoutPaymentProvider.m#L178

**Comment by lengocgiang** [comment]
@davidmuzi 👍 thansks a bunch!!!

**Comment by vipul4301** [comment]
Hi,
I am facing same issue. I need to create web checkout request with user login. 

Please suggest??
