### ISSUE TITLE
Cannot compile 2.0 using Cocoapods

### ISSUE THREAD

**Issue by davidmuzi** [Shopify/mobile-buy-sdk-ios#242]
> h:35:9: fatal error: 'Buy/BUYAccountCredentials.h' file not found
> #import <Buy/BUYAccountCredentials.h>
>         ^
> 1 error generated.
> /var/folders/n2/2dkpb6ks30vf125hwt6k2p580000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'Buy'
> @import Buy;
>  ~~~~~~~^~~
> 2 errors generated.
> 
> ** BUILD FAILED 

See
[output.txt](https://github.com/Shopify/mobile-buy-sdk-ios/files/328450/output.txt)

**Comment by bgulanowski** [comment]
This is trying to link to the framework header, and to `@import Buy`, which seems incorrect unless CocoaPods is actually using the module (which seems to contradict the static target intention).

For the first problem, need to address search paths build setting to ensure it's looking in the parent folder of the "Buy" headers folder (assuming it exists).

For the second, not sure why CocoaPods is trying to import the module in the first place.

**Comment by nejcpintar** [comment]
Same as #229
