### ISSUE TITLE
BUYClient : getProductsByIds method : Every time getting >> Error Domain=BUYShopifyErrorDomain Code=404 "(null)"

### ISSUE THREAD

**Issue by hitendradeveloper** [Shopify/mobile-buy-sdk-ios#248]
Class :
    BUYClient

Method : 
   - (NSOperation *)getProductsByIds:(NSArray<NSString *> *)productIds completion:      (BUYDataProductsBlock)block;

We are getting error : Error Domain=BUYShopifyErrorDomain Code=404 "(null)" every time when trying to call above method.

sample code:

```
NSString *channelId ="our channelId";
NSString *paymentApiKey = "our paymentApiKey"; 
NSString *shopifyDomain = "our shopifyDomain";

BUYClient *client = [[BUYClient alloc] initWithShopDomain:shopifyDomain apiKey:paymentApiKey appId:channelId];
NSArray *arrProductIDs = @["productID1","productID2"];//this is dynamic inside the code
    [client getProductsByIds:arrProductIDs completion:^(NSArray *fetchedProducts, NSError *error) {
        if (error) {
                 //our logic
        }else{
                //our logic
        }
    }];

```

Instance of BUYClient is working properly with other methods.

**Comment by davidmuzi** [comment]
Our documentation for 2.0 is not live yet which will have a migration section.  You cannot use your `channelId` as the `AppId`, they are different.

Hint, its "8"  :)

**Comment by hitendradeveloper** [comment]
We are using channelId as App Id and it is working for the login signup and other customer releared methods.

**Comment by davidmuzi** [comment]
The customer APIs are not scoped to an app, which is why they continue to work.  The product and collections listings APIs are scoped to an app, which is why they are required.

**Comment by hitendradeveloper** [comment]
@davidmuzi Million Thanks man.! Issue has been resolved, Thanks again for the Hint.
