### ISSUE TITLE
Search product API

### ISSUE THREAD

**Issue by parthjdabhi** [Shopify/mobile-buy-sdk-ios#257]
is there any api for search product by name or category ?

**Comment by davidmuzi** [comment]
Unfortunately not.

**Comment by parthjdabhi** [comment]
what if we have to add search function to app, as its very essential for any any ecommerce app.

**Comment by networld301ios** [comment]
we have to add Search functionality in my app with new SDK. can it possible in new SDk

**Comment by dbart01** [comment]
@networld301ios Please take a look at the [docs for search](https://github.com/Shopify/mobile-buy-sdk-ios#search-).
