### ISSUE TITLE
Lacking of functionality in sdk

### ISSUE THREAD

**Issue by bruno25** [Shopify/mobile-buy-sdk-ios#261]
The version prior 2.0 of the SDK contain catalog and guest checkout methods. In V2.0, we have some customer functionality, but still lot of functionality is missing, wish inhibit any serious complete functionality mobile app development.
As i understand, the ios sdk is a client wrapper that calls into rest api for a shopify app, wish is not available for customization by community. So we're stuck with what this shopify app provide; currently lot of functionality is not provided, for example a search, cart methods...
So how can we add functionality if needed ? Do we need to create our own version of the shopify app, and try to build sdk around it ?
I know i might be mistaken, so please bear with me and forgive me if i am mistaken.

**Comment by davidmuzi** [comment]
Please reserve creating issues for reporting bugs or detailed feature requests.

For more generic discussion on how to use the SDK, please use our [forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology), thanks.
