### ISSUE TITLE
Build sample apps as part of CI

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#262]
We have a few sample apps. Sometimes they get out of date when we make changes to the framework. We should always build all the sample apps to ensure they are up to date.

**Comment by davidmuzi** [comment]
Should we kill the Swift one?  Seems redundant now that we have a customer sample app, which demonstrates Swift usage with the SDK.

**Comment by bgulanowski** [comment]
If there is nothing interesting in there that we can't migrate to one of the other apps, yes.
