### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by galfaroth** [Shopify/mobile-buy-sdk-ios#266]
Hello,
I'm developing app for my client and everytime I try to make any client request I get: NSError shopify 404. Is Shopify API down today?

I'm putting shop's domain, api id and channel id correctly. Trying to use the method: client.getProductsPage. The client is initiated with all parameters correctly but the response inside the block is always 404.

Best,
Piotr

**Comment by davidmuzi** [comment]
Are you using the 2.0 version from the `develop` branch? If so, be careful not to mix up appID and channelID.

**Comment by galfaroth** [comment]
Yes! In API v.2.0 when I put "8" as appId it works!
Why isn't that default? How would I know to put "8" there?

**Comment by davidmuzi** [comment]
You wouldn't 🙂
When the SDK 2.0 is officially launched there will be docs detailing this.
