### ISSUE TITLE
Add method to fetch Products by Collection Handle

### ISSUE THREAD

**Issue by niwinnm** [Shopify/mobile-buy-sdk-ios#270]
It would be useful if we have a method to fetch products which belongs to a specific collection using the collection handle. Right now we only have the method to choose from Collection ID. While integrate deep linking or universal link from Shopify based url, fetchin products based on collection handle/alias will really be needed. 

We need something like this.

```
[client getProductsPage:1 inCollection:collection.collectionHandle completion:^(NSArray<BUYProduct *> *products, NSUInteger page, BOOL reachedEnd, NSError *error) {
  
}];

```

Also the same feature has been added on the server side and has been added as a feature in Shopify Android SDK too. [https://github.com/Shopify/mobile-buy-sdk-android/issues/198](Check here).

**Comment by bgulanowski** [comment]
Fixed by https://github.com/Shopify/mobile-buy-sdk-ios/pull/276

**Comment by bgulanowski** [comment]
If you want to get products in a collection by collection handle, you must do two calls in sequence.

**Comment by JaydeepPatel** [comment]
@niwinnm @bgulanowski  hello Please help me with this==>

http://stackoverflow.com/questions/40589152/get-homepage-category-list-in-api-response-in-shopify

Thank x in Advance

**Comment by davidmuzi** [comment]
@JaydeepPatel please dont post new issues in an existing (and closed) issue, they should be put in a new one.

But, to answer your question the navigation information you are looking for is not accessible via the SDK, that is a property of the Online Store Channel.
