### ISSUE TITLE
How to get appId ?

### ISSUE THREAD

**Issue by parthjdabhi** [Shopify/mobile-buy-sdk-ios#275]
while creating new private application (https://mydomain.myshopify.com/admin/apps/private/new) private application.
and i got following information : 
API key
fb3d12345cab6dd7953fa56aeb979cab
Password
632e12345e87a183f6b75779a8ccea59
Shared secret
b8d412345460bb7f8d196ad4806d7c05
URL format
https://apikey:password@hostname/admin/resource.json
Example URL
https://fb3d612345ab6dd7953fa56aeb979cab:632e12345e87a183f6b75779a8ccea59@mydomain.myshopify.com/admin/orders.json

So i have :
ShopDomain
yourshop.myshopify.com
apiKey
fb3d12345cab6dd7953fa56aeb979cab
**appId : ???**

**which one i use for Appid ?**

**Comment by parthjdabhi** [comment]
@krisorr @bgulanowski @dbart01 @gabriel-letarte @davidmuzi 

**Can any one help me out ?**

**Comment by bgulanowski** [comment]
Currently, the app id is `@"8"`. We'll be updating the docs this morning, and the admin pages immediately after.

**Comment by parthjdabhi** [comment]
Many thanks @bgulanowski

**Comment by tleyden** [comment]
Here are the steps I used to get the v2 SDK to work against the new "Private Apps": https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/using-v2-buy-sdk-ios-with-private-apps-497971
