### ISSUE TITLE
When payment fails, checkout needs to be recreated and products become unavailable

### ISSUE THREAD

**Issue by mihai-moldovan** [Shopify/mobile-buy-sdk-ios#281]
Our application has exactly one item for each product, so whenever someone adds a product to cart that product becomes unavailable.

1. The user adds the product to cart, then goes to checkout.
2. Inputs all the needed info and wrong credit card data.
3. The sdk returns an error about the credit card: 

> Error code 424: {
>     errors =     {
>         checkout =         {
>             "payment_session_id" =             (
>                                 {
>                     code = invalid;
>                     message = "is invalid";
>                     options =                     {
>                     };
>                 }
>             );
>         };
>     };
> }

4. The user updates the credit card data.  Since the sdk does not allow to reuse the same checkout, the checkout object needs to be recreated, but the new checkout will return an error for that specific product since it is no longer available:

> Error code 422: {
>     errors =     {
>         checkout =         {
>             email =             (
>             );
>             "line_items" =             (
>                                 {
>                     quantity =                     (
>                                                 {
>                             code = "not_enough_in_stock";
>                             message = "Not enough items available. Only 0 left.";
>                             options =                             {
>                                 remaining = 0;
>                             };
>                         }
>                     );
>                 }
>             );
>             "reservation_time" =             (
>             );
>             "source_name" =             (
>             );
>         };
>     };
> }

**Comment by bgulanowski** [comment]
> the sdk does not allow to reuse the same checkout

That's not true as far as I know. You can definitely use the same token and try again with a different payment type.

**Comment by mihai-moldovan** [comment]
See this. It was closed as duplicate, but the duplicate gives 404. 
I'll try to isolate the issue in a sample project

**Comment by mihai-moldovan** [comment]
Here is a sample project.  [BuyTest.zip](https://github.com/Shopify/mobile-buy-sdk-ios/files/392070/BuyTest.zip)
Please go in ViewController.swift and input correct data for shop domain, api_key, channel_id and a  product_id. 
If the product has only one item in stock for the first variant, you'll notice the problem.
Please check the console output.

You'll notice that the payment fails from the credit card. Then you can press retry button. It should recreate the checkout starting from the same cart object. You'll notice the error. Also you'll notice that cartToken is nil everytime.

**Comment by davidmuzi** [comment]
I took a look at your sample project.  
1.  The cart token is not the property you should be using to identify the checkout object, you should use `token` on the BUYCheckout object
2.  When a product is added to a checkout, it is reserved until the checkout completes or `reservationTimeLeft` reaches zero.  If you want to release a product from a checkout, set that value to 0, and call update checkout
3.  The sample project uses a test credit card.  Is your shop using Shopify Payments in Test Mode?

**Comment by mihai-moldovan** [comment]
Thanks for the answer.

1. I tried to recreate the checkout with BUYCheckout(cartToken: self.checkout!.token) but it doesn't work. I get cart_token_does_not_exist. Can you please provide a short snipet on how to do it?
2. I tried your solution but I cannot update the checkout anymore since I always get the payment_session invalid error.
3. Yes, I was using it with our test environment so Shopify payments are enabled in test mode. 

Can you please provide links / sample code that shows how to workaround this issue? 

Thank you.

**Comment by davidmuzi** [comment]
My first point was regarding identifying the checkout.  You should use `token` on the checkout object, not `cartToken`.  The constructor you were using before was correct.

Since the payment session fails on update, its `payment_session_id` is still marked dirty, and is attempted to be sent up on subsequent POSTs.  You need to correct this first.  You can either set `checkout.paymentSessionId = nil` and call updateCheckout, or, add a new credit card to the checkout.

If you want to release the quantity, set `paymentSessionId` to nil, and call ``removeProductReservationsFromCheckout`
