### ISSUE TITLE
Newly created store no longer compatible with SDK1

### ISSUE THREAD

**Issue by CharlesW95** [Shopify/mobile-buy-sdk-ios#282]
I just created a new Shopify store and we are no longer provided channelIDs - although the Shopify website and the Markdown on Github already tell us to use the BUYClient initializer with 'appID' as a parameter, this is not available anywhere in code yet - latest builds are 1.2.6 everywhere - what should we do?

**Comment by quocble** [comment]
Yeah. what's with this change? It's not backward compatible.  The new SDK only has the AppID, the old sdk only has ChannelID. I have 200 stores... how can I transition from channelID if the new API is not backward compatible?  I can't make all of them give me the new AppID....

Why is this not handled gracefully through serverAPI regardless how the ID are generated...

**Comment by quocble** [comment]
Yeah, what's the deal?  The new api code is 2.0 which only released a few days ago which does not give ample time to prepare for this transition.

I have 200 stores, with new stores signing up who I can not support with this V2 API until I release the new native app to the appstore ( another week ).

The new V2 API code does not have channelID support. eg. not backward compatible.

The old V1 API should just be forward compatible when it sees this new appID with 1 digit code to avoid breakage.

**Comment by CharlesW95** [comment]
@quocble Is V2 already available? I can't find it anywhere for download

**Comment by quocble** [comment]
https://github.com/Shopify/mobile-buy-sdk-ios/releases  

If you stare really close you see 2.0.0

CocoaPod is not published. I had to point to github

pod 'Mobile-Buy-SDK', :git => 'https://github.com/Shopify/mobile-buy-sdk-ios.git', :tag => '2.0.0'

**Comment by quocble** [comment]
2.0.0 is completely different, no BUYTheme, no BUYViewController. Hundreds of compilation error.

**Comment by CharlesW95** [comment]
@quocble ah, thanks. 

dang, looks like we'll have to wait for a more stable release... I just wish a stable version was ready before they changed the implementation for new stores since in the meantime we won't be able to develop our apps for them...

**Comment by quocble** [comment]
@CharlesW95  Usually a big change from 1.2.6 to 2.0.0 - there would be huge architectural changes that break existing implementation as I fear.  I'm afraid we have to bite the bullet at some point.  Shopify can make this easier by making 1.2.6 forward compatible with the AppID which is all we need.

**Comment by CharlesW95** [comment]
@quocble Yeah literally all I need for my app is another initializer for BUYClient which is compatible with AppID. Oh well. Looks like the only safe way is to stick to 1.2.6, and get on 2 when it becomes stable - the new shops will have to wait.
