### ISSUE TITLE
1.2.X forward compatible with the AppID.

### ISSUE THREAD

**Issue by quocble** [Shopify/mobile-buy-sdk-ios#285]
The change from 1.2.6 to 2.0.0 contains huge architectural changes that break existing implementation.  Half the code is not there like BUYViewController BUYTheme, etc, etc. This would take weeks to change. 

In the meantime, I need to make our existing compatible with new clients that support AppID.  I really suggest Shopify release a forward compatible version with AppID to help with the transition.

**Comment by davidmuzi** [comment]
Version 2 is a major release and thus has several breaking changes from v1.  There are several new features that can be used by upgrading to V2.  The view controllers are no longer part of the SDK, but can be found in the sample apps included.

v1 will continue to work with the API key and Channel ID.

We have no plans to make v1 forward compatible.
