### ISSUE TITLE
Cocoa pods not installing SDK

### ISSUE THREAD

**Issue by asoviche** [Shopify/mobile-buy-sdk-ios#289]
**** 
*update:*

I found that by having #import <Buy/Buy.h>, everything was working, do you have any idea why?
****

Hi,

When using Pods to install the SDK, it is not downloading “Buy.bundle” nor “libMobile-buy-SDK.a” (cf picture). So we cannot use the SDK for the moment :( 

<img width="321" alt="screen shot 2016-08-06 at 16 22 59" src="https://cloud.githubusercontent.com/assets/9138105/17457215/5d46afda-5bf2-11e6-8663-1783fc06aab0.png">

Thanks for the help!

**Comment by pedroprates** [comment]
Found the same problem. Just did a pod search and found that the version of Mobile Buy SDK in cocoa pods is 1.2.6.
<img width="448" alt="screen shot 2016-08-07 at 12 50 46" src="https://cloud.githubusercontent.com/assets/19272574/17463515/b333ea4c-5c9d-11e6-9ac5-44f6dbe9b3d3.png">

**Comment by davidmuzi** [comment]
The pod has since been updated to 2.0.  Please make sure your pod file is up to date.

![1__ruby_and_cocoa_pods_not_installing_sdk_ _issue__289_ _shopify_mobile-buy-sdk-ios](https://cloud.githubusercontent.com/assets/1058176/17480734/4a1eef3e-5d47-11e6-8455-1585417d2d72.png)

**Comment by pedroprates** [comment]
Oops, sorry, my mistake.
