### ISSUE TITLE
adding a product variant to cart

### ISSUE THREAD

**Issue by romeshsahu** [Shopify/mobile-buy-sdk-ios#293]
each product with it's respective variant to be added in cart via method addVariant(BUYProductVariant: ).
I am also implementing the same as: 

buyCart.addVariant(selectedVariant)

//buyCart object is explicitly created. var buyCart = BUYCart().......
but the error is, particular selectedVariant either variant[0] or variant[1] has a cartLineItem property as nil.
And that nil is issuing error: 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableOrderedSet addObject:]: object cannot be nil'

can any one having solution to this. 
Query solution's are appreciated..

**Comment by davidmuzi** [comment]
Sorry, I do not understand the issue.  Have you tried running the Advanced Sample App to see if the issue is reproducible?

variant does not have a `cartLineItem` property.

**Comment by hitendradeveloper** [comment]
Same issue here,

1: BUYCart *cart = [[BUYCart alloc] init];
2: BUYProductVariant *variant = product.variantsArray[0];
3: [cart addVariant:variant];

I can debug and print the values of "variant",
but when line3 executes, it crashes. 

====
2016-08-30 13:43:04.627 Mooncode[13185:135968] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableOrderedSet addObject:]: object cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112971d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000112314deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001128df2f4 -[NSMutableOrderedSet addObject:] + 180
	3   MooncodeTests                       0x0000000120094d52 -[BUYCart addVariant:] + 242

**Comment by bgulanowski** [comment]
`alloc/init` is not supported for creating models. If you are using the standard configuration of the library, you must use `-initWithModelManager:JSONDictionary:`. `modelManager` should be `BUYClient.modelManager`, or from any other model object. In your case, you can use the one on the product, as long as it's not `nil`.

Line 70 of `-addVariant:` invokes `-newCartLineItemWithVariant:`, which in turn creates the new line item using `BUYModelManager.buy_objectWithEntityName:JSONDictionary:`. If there is no model manager, then that method returns `nil`, and you get a crash.

We are considering a simpler design to avoid this problem, but we won't have a chance to work on it for a few months. (In short, we could avoid needing a model manager by making the managed object model, needed for JSON marshalling, a singleton. PRs welcome!)
