### ISSUE TITLE
"Symbol not found" when compiling with xcode 8 beta, running on iOS 9

### ISSUE THREAD

**Issue by billhaley** [Shopify/mobile-buy-sdk-ios#297]
I'm still investigating but thought I'd run this by you and see if it rings any bells.  Trying our app with xcode 8 beta 4, and everything runs fine on iOS 10, both simulator and phone.  Running on iOS 9 immediately crashes, however. 

Console output from a crash on simulator, edited for clarity:

dyld: Symbol not found: _kABPersonAddressCityKey
  Referenced from: /Users/.../Frameworks/Buy.framework/Buy
  Expected in: .../Frameworks/PassKit.framework/PassKit
 in /Users/.../Frameworks/Buy.framework/Buy
(lldb)

**Comment by bgulanowski** [comment]
`ABPersonAddressCityKey` is a symbol in AddressBook.framework. Sounds like your project or your environment is missing a reference to that framework. Are you linking to iOS 10? We haven't really tested that yet. Could be an issue with the beta tools?

**Comment by davidmuzi** [comment]
`dyld: Symbol not found` errors are related to linking, where it can't resolve a symbol.  Ive just confirmed the [Advanced Sample App](https://github.com/Shopify/mobile-buy-sdk-ios/tree/master/Mobile%20Buy%20SDK%20Sample%20Apps/Advanced%20App%20-%20ObjC) runs on iOS 9.3 when compiled with iOS 10.0 SDK on Xcode 8 beta 5.  Albeit, one change was to include the Buy.framework in the Embedded Binaries section of the target.

![mobile_buy_sdk_advanced_sample_xcodeproj](https://cloud.githubusercontent.com/assets/1058176/17898311/4c811146-6925-11e6-845b-9da4121c1f7b.png)

**Comment by billhaley** [comment]
@davidmuzi Thanks for looking into this!  I spent some time with it today, and the only solution that worked was the following: built the 1.2.6 framework and linked that as you've shown above.  I also needed to include both AddressBook and PassKit frameworks as well.

This does mean that using your cocoapod is no longer an option for us, which is unfortunate.  Using the pod and linking AddressBook / PassKit gives us the same error.

**Comment by davidmuzi** [comment]
It looks like this issue is not limit to Cocoapods: https://openradar.appspot.com/28064734

**Comment by davidmuzi** [comment]
Looks like the issue is not limited to our SDK
https://openradar.appspot.com/28064734

Cocoapods may be the source of the issue, as the provided sample apps in the SDK work on iOS 9 when built from Xcode 8

**Comment by mihai-moldovan** [comment]
Hey, I'm using Xcode8 Buy SDK 2.0 with cocoapods. 
After I do pod install I change the PassKit requirement from Required to Optional in the Mobile-Buy-SDK Target configuration. 
Does this work for you? I think there are some needed changes in the cocoapods configuration.
<img width="1416" alt="screen shot 2016-09-26 at 11 02 10" src="https://cloud.githubusercontent.com/assets/1757318/18827006/1ad5faca-83d9-11e6-8bd7-c403b1945ed0.png">

**Comment by wmcbain** [comment]
When can we expect a Xcode 8 update on the Shopify `master` branch?

In other referenced issues you tell people to use the `develop` branch. We've found that to be incompatible with 2.0.0, which is also currently still broken during an archive due to mismatched parameters.

Is there a particular commit that Xcode 8 users should reference? We are at just over two weeks from the release date and even farther out from the GM. Can we get a point release that addresses the issues for Xcode 8?

**Comment by bgulanowski** [comment]
https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/2.0.1

**Comment by wmcbain** [comment]
To be clear the point release posted does not address the problem described in this issue when using cocoapods.

In Podfile:

```
pod 'Mobile-Buy-SDK', :git => 'git@github.com:Shopify/mobile-buy-sdk-ios.git', :tag => '2.0.1'
```

When running the iOS 9.3 simulator:

```
dyld: Symbol not found: _kABPersonAddressCityKey
  Referenced from: /Users/wyattmcbain/Library/Developer/CoreSimulator/Devices/190B514C-5E80-4263-9209-BB73ED86CD91/data/Containers/Bundle/Application/1F608243-BB76-499E-A144-4A9AB77A392E/BevyBar.app/Frameworks/Buy.framework/Buy
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/PassKit.framework/PassKit
 in /Users/wyattmcbain/Library/Developer/CoreSimulator/Devices/190B514C-5E80-4263-9209-BB73ED86CD91/data/Containers/Bundle/Application/1F608243-BB76-499E-A144-4A9AB77A392E/BevyBar.app/Frameworks/Buy.framework/Buy
```

I'm currently using the advice described above to resolve. I have integrated `Buy` with Carthage using submodules and using a personal fork to deal with the linking issues. Would remove reference to Cocoapods integration in the Readme until resolved. 😕

**Comment by bgulanowski** [comment]
We don't have a solution to this problem as of yet. Pull requests welcome.
