### ISSUE TITLE
Carthage Update fails for version 2.0.0

### ISSUE THREAD

**Issue by samphomsopha** [Shopify/mobile-buy-sdk-ios#299]
Running carthage update fails with the following error message below:

*** Building scheme "Buy" in Mobile Buy SDK.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/samphomsopha/Library/Developer/Xcode/DerivedData/Mobile_Buy_SDK-dqlozqzfnsynpbgnhwhaipekmzxz/Build/Intermediates/Mobile\ Buy\ SDK.build/Release-iphoneos/Buy.build/Objects-normal/armv7/BUYClient+Storefront.o Mobile\ Buy\ SDK/Data/BUYClient+Storefront.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/samphomsopha/apps/iOS/zen/Carthage/Checkouts/mobile-buy-sdk-ios/Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m:140:48: error: implicit conversion loses integer precision: 'const NSUInteger' (aka 'const unsigned int') to 'BOOL' (aka 'signed char') [-Werror,-Wconversion]
A shell task (/usr/bin/xcrun xcodebuild -project /Users/samphomsopha/apps/iOS/zen/Carthage/Checkouts/mobile-buy-sdk-ios/Mobile Buy SDK/Mobile Buy SDK.xcodeproj -scheme Buy -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/samphomsopha/Library/Developer/Xcode/DerivedData/Mobile_Buy_SDK-dqlozqzfnsynpbgnhwhaipekmzxz/Build/Intermediates/Mobile\ Buy\ SDK.build/Release-iphoneos/Buy.build/Objects-normal/armv7/BUYClient+Storefront.o Mobile\ Buy\ SDK/Data/BUYClient+Storefront.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by bgulanowski** [comment]
Underlying issue was fixed by https://github.com/Shopify/mobile-buy-sdk-ios/pull/280 but the change hasn't made it into master. In the short term, point to develop branch instead of master.

We can prepare a 2.0.1 build within the week, but if you need a fix in the meantime, cherry pick the commit from the pull request.

 cc @davidmuzi

**Comment by samphomsopha** [comment]
Thanks will give that a try.
