### ISSUE TITLE
Customer token rules

### ISSUE THREAD

**Issue by asoviche** [Shopify/mobile-buy-sdk-ios#300]
Hi,

We’re about to finish the integration of the customer login, and have some questions about the **customerToken** since it contains an expiry date.

- Under what circumstances is the customerToken invalidated?

- If the token is invalidated (or expiry date is expired), can we still access the orders, the checkout, etc? It seems that it’s more the customerID that is used for that.

- What is the best way to test an invalidated token to know what error will be retrieved?

Thanks a lot! :)

**Comment by bgulanowski** [comment]
Please restrict discussion and questions on using the SDK to the Shopify Ecommerce University Forums. Github is for issues (bugs, feature requests) only. Thanks.

https://ecommerce.shopify.com/c/shopify-apis-and-technology

The customer token expires after six weeks.

No, you cannot access private customer data, such as orders, using the API, after that time. What good would an authentication system be if it didn't restrict access? What you do with that data after you download it is your responsibility, but if you saved it locally, you should most definitely delete it.

You can invalidate a token by deleting it using the appropriate API call, `- [BUYClient logoutCustomerCallback:]`. But you could also just set a garbage string value for the `BUYClient.token` without logging in, or just leave it `nil`. It will have the same results (invalid token).

**Comment by asoviche** [comment]
Thank you so much @bgulanowski 👍
