### ISSUE TITLE
Failed to initialize BUYApplePayToken. Invalid or nil paymentToken.

### ISSUE THREAD

**Issue by pavangopal** [Shopify/mobile-buy-sdk-ios#301]
Hi,
I am getting this error "Failed to initialize BUYApplePayToken. Invalid or nil paymentToken." when tried to use apple pay in one of my app.

I am trying to run this app in iPhone 6 simulator.But it is crashing with the same error.
But my web checkout and native checkout seems to work fine .

Here is the screen shot of the shipping and billing address.
![image](https://cloud.githubusercontent.com/assets/13829145/17837034/7359bcac-67c5-11e6-8f47-dd728b1c9130.png)

And also Im using the default credit card given by the simulator for testing .
please guid me with a solution to solve this .

**Comment by davidmuzi** [comment]
Can you provide sample code or the project that demonstrates this issue?

**Comment by bgulanowski** [comment]
A crash issue MUST include the back trace that caused the crash, and any other errors from the logs, as well as explicit steps to reproduce, or we can't do anything to help you.

Apple Pay does not work in the Simulator. It also does not work with fake data, like the address you have in the screen shot. You must make a real purchase from a real shop with a real credit card and real address information, and your shop must not be in test mode.

**Comment by pavangopal** [comment]
Thank you so much for letting me know it doesn't work in simulator . I was using test store and I was using it in simulator.
I got the crash while I was testing the sample objective-c Project from the SDK with my test store credentials. 

Is there anyway to avoid the crash by catching the error prior hand and let the user know about the error.

Steps to reproduce the error:
#define SHOP_DOMAIN @"frontend-dev.myshopify.com"
#define API_KEY @"4016256b9915ea5e5d8b78eb4400b966"
#define APP_ID @"8"

// merchant id :
 NSString * const MerchantId = @"merchant.com.woodswholesalewine.ioschannel";

**Comment by bgulanowski** [comment]
This is a public web page! Don't post your shop credentials here (even for a test shop).

Moreover, any bug in the SDK should work with any shop, so those details are not pertinent to the issue.

That is not the kind of information that we need. We need to see a code sample, and/or the data you entered into the test app and steps you took, AS A USER, to cause the problem. And again, if there is a real crash, you MUST provide the **crash log** and **stack trace**. Thanks.

**Comment by bgulanowski** [comment]
If you are getting an exception, then you must handle it. We can't help you with general iOS programming patterns. Please read up on exception handling on iOS.

If you are getting a normal error, then you should parse it and try to help your user to correct their mistake, but that's specific to your app, and not related to the SDK. If you are having problems with Pay, then you should make sure you read the documentation from Apple. We can't help you with Pay, because we didn't implement it.
