### ISSUE TITLE
Module 'Buy' not found (using CocoaPods)

### ISSUE THREAD

**Issue by julianvogels** [Shopify/mobile-buy-sdk-ios#302]
Hey, 

I just upgraded the Mobile Buy SDK to version 2.0.0 and did all the migration changes. My project won't compile because the framework module isn't found:

`@import Buy;` throws the error _Module 'Buy' not found_

This happens in a newly created blank iOS project as well. I also tried using `#import` but that doesn't change anything.

### Repro steps:

1. Create blank iOS 'Single View' project
2. Run `pod init`
3. Add pod to Podfile.
4. run `pod install`
5. Open workspace
6.  add`@import Buy;` to a view controller
7. Run the project, get the error

Podfile contents:
`# Uncomment this line to define a global platform for your project`
`# platform :ios, '9.0'`

`target 'BuySDKTest' do`
  `# Uncomment this line if you're using Swift or would like to use dynamic frameworks`
`  # use_frameworks!`

`  # Pods for BuySDKTest`
`    pod 'Mobile-Buy-SDK'`

`end`

**Comment by davidmuzi** [comment]
As far as I recall, Cocoapods do not support module imports, so you should use the umbrella framework import:
`#import <Buy/Buy.h>`

Ive just tried creating a sample project, and it worked for me

**Comment by julianvogels** [comment]
Actually, they do. At least it works now with `@import Buy;`. The umbrella hadn't worked previously either.  
I resolved the problem by updating the Cocoapods ruby gem (but just a minor version step to 1.0.1 from 1.0.0), removing the local Cocoapods specs master repo, and running `pod setup` again. Something must've gone horribly wrong while running `pod update` to update the Mobile Buy SDK to 2.X.X.
