### ISSUE TITLE
Update Customer model fields

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#308]
The Customer model (and `BUYCustomer` class) include fields that are not provided by the underlying API, because they are meant to be merchant-facing.

These fields are writeable by clients:
- email: String
- acceptsMarketing: BOOL
- firstName: String
- lastName: String
- password: String
- addresses: Ordered Set

These additional fields are read-only:
- createdAt
- identifier
- defaultAddress
- lastOrderId
- lastOrderName
- multipassIdentifier
- ordersCount
- state
- taxExempt
- totalSpent
- updatedAt
- verifiedEmail

`password` is effectively write-only.

The following fields will be removed:
- note
- tags

These fields have never been provided by the API, so there is no consequence for removing them.

@davidmuzi @krisorr

**Comment by saurabhPV** [comment]
I wish if note would be available as read only field. We wanted admin to mark few customer as Elite customer( this can be done from dashboard ) and show this on app when customer logs in. If its not available could you please suggest any alternative ?
