### ISSUE TITLE
BUYModelManager.m:144 : -[NSBundle initWithURL:]: nil URL argument

### ISSUE THREAD

**Issue by hitendradeveloper** [Shopify/mobile-buy-sdk-ios#309]
Hi, Buy.bundle is available but app is crashing.

Ref1 : http://grab.by/SpHY

Ref2 : http://grab.by/SpIa

Ref3 : http://grab.by/SpIe

**Comment by bgulanowski** [comment]
You're going to have to set a breakpoint, and find out which method is returning `nil`. Is `Buy.bundle` in the right place? From the code in `NSBundle+BUYAdditions`, in `BUYModelManager.m`, you can see that `Buy.bundle` is supposed to be inside `Buy.framework`.

But it looks like you're not building a framework. The backtrace shows that the code has been statically linked into your app executable, `MoonCode`, which is not expected. Are you using the static framework?

A PR that falls back to looking in the main bundle would be appreciated.

**Comment by hitendradeveloper** [comment]
We are using pod as below, 
 pod 'Mobile-Buy-SDK','~> 2.0.0'

It is not showing any Buy.bundle in the pods>Mobile-Buy-SDK directory
So as the temporary patch we have added Buy.bundle in out test target.
We are try to run shopify code using the XCTests.

**Comment by hitendradeveloper** [comment]
Any update on this issue ?

**Comment by bgulanowski** [comment]
This is simple to fix, but we may not have a new build for a while, sorry.

See this code here:
https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/BUYModelManager.m#L143-L147

Remove lines 143-145 and line 146, leaving just `return [self frameworkBundle];`

Make this change locally for now.

This is an open source project. Please contribute. If you make a PR, please base it on the release/2.0.1 branch.

**Comment by bgulanowski** [comment]
Update: I don't think I understood your problem initially. I think your target is not set up correctly.

Why did you add the `Buy.bundle` to your test target?

`Buy.bundle` is a product build by CocoaPods. It's not a file input, it's an output. You should add the `Buy.bundle` product (from Xcode, as seen in your screen shot) as a dependency, and resource (copy resources build phase) of your app target. Then everything should work.
