### ISSUE TITLE
NSURLSessionDataTask is delayed or stuck forever when internet is connecting

### ISSUE THREAD

**Issue by thkeen** [Shopify/mobile-buy-sdk-ios#32]
To reproduce this, use any API call from BUYClient that returns NSURLSessionDataTask.

Example:
Step 1: turn off internet connection
Step 2: turn on internet connection and immediately fire the API call. Like:
```objective-C
[buyClient getCollections:^(NSArray *collections, NSError *error) {
  // observing completionBlock is delayed for several seconds or never fired at all
}];
```

Expected result: completionBlock should be called either with error or results.

**Comment by thkeen** [comment]
My guess for this NSURLSessionDataTask is handled by the system. It is not guaranteed to be executed when internet is back, hence causing a UX problem. In one of the apps I worked on, we had to aggressively force the task to run when there's Reachibility change.

**Comment by davidmuzi** [comment]
Tasks are automatically set to resume, which will immediately fail in an offline connection.  It is recommended to check for reachability before accessing any of the network APIs
