### ISSUE TITLE
Unable to get filtered products with getProductsPage method having withTags parameter

### ISSUE THREAD

**Issue by kmrashish** [Shopify/mobile-buy-sdk-ios#323]
Hi, I am currently using SDK 2.0. The storefront API method for BUYClient, "getProductsPage" which fetches products for a collection having particular tags supplied as withTags parameter is not working and I am getting all products (unfiltered) for the collection irrespective of the tags supplied. Is there some issue or am I missing something? Please reply asap.

**Comment by bgulanowski** [comment]
Confirmed. The problem appears to be server-side. The generated request appears correct. Investigating.

**Comment by bgulanowski** [comment]
Nope, not server-side. The URI is not correct. The parameter name should be "tag", not "tags". PR up in a moment. For now, you can make the change on your local copy here:

https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Data/BUYClient%2BStorefront.m#L190

by changing `param[@"tags"]` to `param[@"tag"]`.

**Comment by kmrashish** [comment]
Yes, it is working after the change. Thanks a lot.
