### ISSUE TITLE
issue with adding new lineItem

### ISSUE THREAD

**Issue by asudevil** [Shopify/mobile-buy-sdk-ios#325]
I'm having issues with adding a new line item to cart. I'm following the example given in the integration guide/checkout.

cart = client.modelManager.insertCartWithJSONDictionary(nil)
//Button to add item
addItemButtum.addTarget(self, action: #selector(self.addToCart(_:)), for controlEvents: . TouchUpInside)
// My function to add item to cart
func addToCart(button: UIButton) if let variant = product?.variants.firstObject as? BuyProductVariant { cart.addVariant(variant) } print("Number of items: \(cart.lineItems.count)")

The addToCart is overriding the previously added item instead of creating a new line. How do I create a new lineItem

**Comment by bgulanowski** [comment]
Please ignore my comment on the other issue.

If you create a new cart every time, yes, you will lose the contents of the previous cart.

And that's what your first line of code is doing:
`Swift
cart = client.modelManager.insertCartWithJSONDictionary(nil)
`
that creates a new cart with no line items. You have to keep a reference to the original cart you created.

**Comment by bgulanowski** [comment]
Please use https://ecommerce.shopify.com/c/shopify-apis-and-technology for questions. Only create issues on github if you can prove there is a bug, or you want to request a feature. Thanks.
