### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by manishnath** [Shopify/mobile-buy-sdk-ios#340]
Using pod file to integrate in my project,  I get a error saying Buy.h not found.
When I am trying to run the sample app , it gives me an error 
dyld: Library not loaded: @rpath/Buy.framework/Buy
  Referenced from: /var/containers/Bundle/Application/86EFB99C-3C55-4FD4-A2A5-CDD55D30F30A/Mobile Buy SDK Advanced Sample.app/Mobile Buy SDK Advanced Sample
  Reason: image not found

**Comment by invoodoo** [comment]
The solution is here - #297. You should integrate Shopify SDK without cocoapods.

**Comment by Maxim-Inv** [comment]
The solution is here - #297. You should integrate Shopify SDK without cocoapods, like in the Shopify Example

**Comment by manishnath** [comment]
I tried installing via Static framework but getting the same error . These are the steps I followed as writen in your doc:
Static Framework Installation

If you would like to not include the Mobile Buy SDK Project within your existing project, you can link directly to the Buy.framework.

Open the Mobile Buy SDK.xcodeproj and build the Static Universal Framework scheme
Drag the Buy.framework that was just created from Mobile Buy SDK Sample Apps into the Linked Frameworks and Libraries section for the target you want to add the framework to. Check Copy items if needed so the framework is copied to your project
In the Build Settings tab, add -all_load to Other Linker Flags
