### ISSUE TITLE
Unable to build (sdk 2.0) : Solution not building for some devices due to implicit conversion error

### ISSUE THREAD

**Issue by kmrashish** [Shopify/mobile-buy-sdk-ios#341]
I am getting the following error while building: 

/Users/xxxxx/Desktop/XXXXX/mobile-buy-sdk-ios-master/Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m:140:48: Implicit conversion loses integer precision: 'const NSUInteger' (aka 'const unsigned int') to 'BOOL' (aka 'signed char')

This error does not show up when I build the solution for some of the simulators like iPhone 6, iPhone 6s, iPhone 5s, iPad Air, iPad Air 2, iPad Pro, iPhone 6s Plus but I get it while building for iPad 2, iPad Retina, iPhone 4s, iPhone 5. 

In addition when I choose _Generic iOS Device_ it throws the same error.

![screen shot 2016-09-09 at 12 58 14 pm](https://cloud.githubusercontent.com/assets/5487522/18379178/a00d0b14-768e-11e6-83b0-8fb065bacacc.png)

I am using XCode 7.3.1

**Comment by bgulanowski** [comment]
There was a bug, already fixed, where the arguments were in the wrong order.

Fixed by: https://github.com/Shopify/mobile-buy-sdk-ios/pull/280

This should be 2.0.1. For now, you might want to try targeting develop, or fork and make the change yourself.
