### ISSUE TITLE
Xcode 8 nil returned by modelManager buy_objectWithEntityName

### ISSUE THREAD

**Issue by alexlavr** [Shopify/mobile-buy-sdk-ios#342]
Started having this problem with XCode 8. Now [newCartLineItemWithVariant](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/Persistent/BUYCart.m#L110) returns `nil` causing a crash. 

This is what I have:
```objective-c
BUYCart *cart = [[BUYCart alloc] init];
BUYProductVariant *variant = [self.product.variants firstObject];
[cart addVariant:variant];
```

Crash happens when  [adding nil to self.lineItemsSet](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/Persistent/BUYCart.m#L70).

Any idea why  [self.modelManager buy_objectWithEntityName:[BUYCartLineItem entityName] JSONDictionary:nil] returns nil?

I tested with `develop` branch and https://github.com/Shopify/mobile-buy-sdk-ios/pull/331 PR.

Trying to resolve this to submit iOS10 app to App Store. Thanks!

**Comment by bgulanowski** [comment]
Use the designated initializer: `-initWithModelManager:JSONDictionary:`. `-init` is not valid (should be `NS_UNAVAILABLE`.

**Comment by ravulamanjula** [comment]
I am also facing same issue , how you resolve issue , what to change in code, is recent framework resolved this issue, after updated also i am getting same crash, could help in this

**Comment by JaydeepPatel** [comment]
@alexlavr @bgulanowski @ravulamanjula 
Hello,

I want to add product in Cart. So, My Code is Like,

    NSLog(@"VARI==> %@",_product.variants);
    BUYCart *cart = [[BUYCart alloc] init];
    BUYProductVariant *variant = [self.product.variants firstObject];
    [cart addVariant:variant];

 *   **NSLog(@"VARI==> %@",_product.variants);=====> Response is Like,**

{
    "body_html" = "The bouquet contains Tulip flowers Dimensions Height- 75cm Width \U2030\U00db\U00d2 25cm";
    "created_at" = "2016-11-05T20:21:38+03:00";
    handle = fl017;
    id = 8999280067;
    image =     {
        "created_at" = "2016-11-08T09:33:55+03:00";
        id = 18634643971;
        position = 1;
        "product_id" = 8999280067;
        src = "https://cdn.shopify.com/s/files/1/1122/0976/products/FL017.jpg?v=1478586835";
        "updated_at" = "2016-11-08T09:33:55+03:00";
        "variant_ids" =         (
        );
    };
    images =     (
                {
            "created_at" = "2016-11-08T09:33:55+03:00";
            id = 18634643971;
            position = 1;
            "product_id" = 8999280067;
            src = "https://cdn.shopify.com/s/files/1/1122/0976/products/FL017.jpg?v=1478586835";
            "updated_at" = "2016-11-08T09:33:55+03:00";
            "variant_ids" =             (
            );
        }
    );
    options =     (
                {
            id = 10806517187;
            name = Title;
            position = 1;
            "product_id" = 8999280067;
            values =             (
                "Default Title"
            );
        }
    );
    "product_type" = Flowers;
    "published_at" = "<null>";
    "published_scope" = web;
    tags = "ANNIVERSARY, CONGRATULATIONS, GET WELL, NEW BABY, WEDDING";
    "template_suffix" = "<null>";
    title = FL017;
    "updated_at" = "2017-01-04T13:07:02+03:00";
    variants =     (
                {
            barcode = "";
            "compare_at_price" = "<null>";
            "created_at" = "2016-11-05T20:21:38+03:00";
            "fulfillment_service" = manual;
            grams = 0;
            id = 31099805571;
            "image_id" = "<null>";
            "inventory_management" = "<null>";
            "inventory_policy" = deny;
            "inventory_quantity" = "-21";
            "old_inventory_quantity" = "-21";
            option1 = "Default Title";
            option2 = "<null>";
            option3 = "<null>";
            position = 1;
            price = "37.00";
            "product_id" = 8999280067;
            "requires_shipping" = 1;
            sku = "";
            taxable = 1;
            title = "Default Title";
            "updated_at" = "2016-11-15T15:05:46+03:00";
            weight = 0;
            "weight_unit" = kg;
        }
    );
    vendor = Floward;
} 

And , In this way my application crash.
And **Crash Report is,=>**

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryI variants]: unrecognized selector sent to instance 0x7f8ef3715950'

So, What's the issue ? and How can i pass the variants in cart ?

Thank x in Advance...

**Comment by alexlavr** [comment]
@JaydeepPatel I fixed this by changing:

> BUYCart *cart = [[BUYCart alloc] init];

to 

> self.client = [[BUYClient alloc] initWithShopDomain:kShopifyDomain apiKey:kShopifyApiKey appId:@"8"];
> BUYCart *cart = [self.client.modelManager insertCartWithJSONDictionary:nil];

**Comment by JaydeepPatel** [comment]
@alexlavr 

Hello,
Thank x From Quick Reply...

But, I don't know How to insert the variants in cart ?

i put your code as per guide,
But How can i insert value in cart ?
Please share this code.

self.client = [[BUYClient alloc] initWithShopDomain:@"###"
                                                 apiKey: @"###"
                                                  appId:@"8"
                                        applicationName:@"###"];
  
    BUYCart *cart = [self.client.modelManager insertCartWithJSONDictionary:nil];
    NSLog(@"cart==> %@",cart);

**Comment by alexlavr** [comment]
This is what I have:
> BUYCart *cart = [self.client.modelManager insertCartWithJSONDictionary:nil];
> BUYProductVariant *variant = [self.product.variants firstObject];
> [cart addVariant:variant];

**Comment by JaydeepPatel** [comment]
@alexlavr 

I used that See my Code,

 self.client = [[BUYClient alloc] initWithShopDomain:@"###"
                                                 apiKey: @"###"
                                                  appId:@"8"
                                        applicationName:@"###"];
  BUYCart *cart = [self.client.modelManager insertCartWithJSONDictionary:nil];
  BUYProductVariant *variant = [self.product.variants firstObject]; //Crash From Here.....
  [cart addVariant:variant];


**Crash From this Line=>**BUYProductVariant *variant = [self.product.variants firstObject];
**CRASH:=>**
reason: '-[__NSDictionaryI variants]: unrecognized selector sent to instance 0x7fabf7d2e3b0'

So, How can solve it ?

**Comment by bgulanowski** [comment]
How are you instantiating your product? Your `product` is not an instance of `BUYProduct`, it is an `NSDictionary`. As it says right in your crash report, dictionaries don't respond to the `variants` message.

This isn't related to the cart (although the suggestions above are correct: you must instantiate models correctly).
