### ISSUE TITLE
Unable to compile Refer -  https://github.com/Shopify/mobile-buy-sdk-ios/issues/340

### ISSUE THREAD

**Issue by manishnath** [Shopify/mobile-buy-sdk-ios#343]
I tried installing via Static framework but getting the same error . These are the steps I followed as writen in your doc:
Static Framework Installation

If you would like to not include the Mobile Buy SDK Project within your existing project, you can link directly to the Buy.framework.

Open the Mobile Buy SDK.xcodeproj and build the Static Universal Framework scheme
Drag the Buy.framework that was just created from Mobile Buy SDK Sample Apps into the Linked Frameworks and Libraries section for the target you want to add the framework to. Check Copy items if needed so the framework is copied to your project
In the Build Settings tab, add -all_load to Other Linker Flags

**Comment by bgulanowski** [comment]
Same issue. Closing as duplicate.

As commented on #340 , the fix is already made, but you have to use the `release/2.0.1` branch, not 2.0.0.
