### ISSUE TITLE
Fetch best selling products from ALL collections

### ISSUE THREAD

**Issue by martinappberg** [Shopify/mobile-buy-sdk-ios#346]
Is there anyway to fetch the best selling products from all collections at once?
I know I can make a request to fetch products by page, but I'm not sure how to order them after best selling items.
Also is there anyway to query products from multiple collections at once?

Here is what I am doing right now but it is not working and returns error: 

`[client getProductsPage:1 inCollection:nil withTags:nil sortOrder:BUYCollectionSortBestSelling completion:^(NSArray<BUYProduct *> * _Nullable products, NSUInteger page, BOOL reachedEnd, NSError * _Nullable error) {`

**Comment by bgulanowski** [comment]
Sorting only works if you specify a collection.

No, there is currently no way to get products within multiple collections.

**Comment by davidmuzi** [comment]
We assert if a collection sort order is specified by no collection

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.

**Comment by konrain** [comment]
@dbart01 can I ask why this is no longer relevant in v3.0?
