### ISSUE TITLE
Apple Pay checkout Error

### ISSUE THREAD

**Issue by asoviche** [Shopify/mobile-buy-sdk-ios#349]
Hey guys,

We realised that when using Apple pay with the SDK, addresses from Europe were not working because they don't contain a province field, which is required by your SDK.

So we changed the SDK inside BUYAddress.m (commented the province line), see below.

Do you have any plan to change this?

Thanks a lot!! 👍 
- (BOOL)isValidAddressForShippingRates
  {
  BOOL valid = NO;
  
  if (self.city.length > 0 &&
      self.zip.length > 0 &&
  **//        self.province.length > 0 &&** 
      (self.country.length > 0 || self.countryCode.length == 2)) {
      valid = YES;
  }
  return valid;
  }

**Comment by bgulanowski** [comment]
In some locales, the province may be mandatory. So we would have to know what the requirements were for a specific locale, based on the country code. This is probably not trivial.

We don't have explicit plans to address this, yet, but thanks for bringing it to our attention.

**Comment by asoviche** [comment]
Thanks for the quick answer Brent, France for instance does not contain any province, but only a postal code. If you try to buy something with Apple Pay, and change the country to France you’ll see it.

For the moment, we manually fix this commenting the line (as previously said), but we need to do it after every pod update, which is pretty dangerous.

Can you please tell me what you could do for that? Let me know if you need any help, MoonCode would be happy to help you guys a bit! 👍

**Comment by asoviche** [comment]
Any news here :) ?

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.
