### ISSUE TITLE
No Such module 'Buy' Cocoapods

### ISSUE THREAD

**Issue by alaxicsmith** [Shopify/mobile-buy-sdk-ios#35]
I'm using the SDK via Cocoapods in a Swift project. In a controller I'm trying to import the framework by including import Buy, but I'm getting an error that says no such module 'Buy'. Any ideas?

**Comment by runmad** [comment]
Can you try the 1.2.1 pre-release https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/1.2.1, please?

**Comment by alaxicsmith** [comment]
How do I specify that in my podfile?

**Comment by runmad** [comment]
You can set it up so you're pointing to a pod spec locally. If you clone it locally and specify the `:path` in your Podfile.

**Comment by alaxicsmith** [comment]
Works perfectly. Awesome. Thanks!
