### ISSUE TITLE
`didDismissViewController:` conflicts with Apple private API

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-ios#352]
The `PaymentViewControllerDelegate` protocol defines a method: `-didDismissViewController:`:

https://github.com/Shopify/mobile-buy-sdk-ios/blob/f4be3b7b0385d71e10a01b17003ef868022374cc/Mobile%20Buy%20SDK%20Sample%20Apps/Advanced%20App%20-%20ObjC/Mobile%20Buy%20SDK%20Advanced%20Sample/Product%20View/View%20Controllers/PaymentViewController.h#L119

This conflicts with Apple private API on `UIViewController`. Reference:

https://github.com/Shopify/mobile-buy-sdk-ios/issues/350

This method may have been added in iOS 10.

Rename this method in the protocol, probably to `-didDismissPaymentViewController:`. And hope Apple doesn't create a payment view controller.

cc @davidmuzi @gabrieloc

**Comment by rmfleetTS** [comment]
Up voting this. I'm seeing the same thing.  Rejected app on updated submission.  Only changes were text content.  Passed previously.

**Comment by bgulanowski** [comment]
Read my reply. This code is *NOT* in the SDK. It is in the sample code. If you copied/pasted sample code from the SDK into your app, that is your responsibility. If you are using SDK < 2, you need to update to 2. We will eventually fix this, but it's not a priority.

**Comment by rmfleetTS** [comment]
@bgulanowski Thanks for the fast response.  It will be the SDK version in use for my case.
