### ISSUE TITLE
Crashes during BuyApplePayPaymentProvider.startCheckout

### ISSUE THREAD

**Issue by asudevil** [Shopify/mobile-buy-sdk-ios#356]
There seems to be bugs in the SDK.  It crashes when the sdk tries to present the payment sheet.
It also crashes when you are almost ready to pay and hit cancel, it crashes due to an NSXPCConnection unrecognized selector call.
Here is what I'm doing:
let applePayProvider = BUYApplePayPaymentProvider(client: self.client, merchantID: self.merchantId)
            applePayProvider.delegate = self
            print(checkout.token)
applePayProvider.startCheckout(checkout)

**Comment by davidmuzi** [comment]
Can you provide more details to the issue? What line is it crashing on? What is the unrecognized selector?

To better help us reproduce the issue, can you provide crash logs which would contain the call stack leading to the crash?  A sample app would also be of great help too.

**Comment by asudevil** [comment]
You can see my sample code at https://github.com/asudevil/ShopifyApplePayExample
The Apple Pay part is in the CartVC Class and starts with func applePayButton(button: UIButton)
I'm doing a applePayProvider.startCheckout(checkout).
Its hard to tell exactly whats causing the crash.  It doesn't provide any crash logs.

**Comment by davidmuzi** [comment]
Ive checked your sample project, and you are not holding on to a reference of your `BUYApplePayPaymentProvider`.  You need to hold a strong reference to it since its being called from the `PKPaymentAuthrorizationController`.

For issues like this, enable Zombie objects, which will give you this additional information:
```
*** -[BUYApplePayPaymentProvider respondsToSelector:]: message sent to deallocated instance 0x610000096260
```
