### ISSUE TITLE
[BUYViewController] failedToUpdateCheckout with error == nil

### ISSUE THREAD

**Issue by thkeen** [Shopify/mobile-buy-sdk-ios#36]
To reproduce: 
- On Shopify backend, try setting a shipping area to San Francisco.
- On device, choose the default shipping address to be New York
- Experiencing that the Apple Pay process will keep failing to update the checkout
- Only way to solve this is remove New York from the default shipping address and replace with San Francisco instead.

In short, once the shipping address is chosen wrongly, users have to cancel the Apple Pay sheet and start again. Otherwise it will keep failing without specific error given.

**Comment by runmad** [comment]
Hi @thkeen. We've looked into the above issue. There seems to be two:

1. There's an issue with shipping rates not being reset properly on the back-end when updating a checkout. We're looking into this.

2. Specifically with your shop, even though you have setup the shipping zones there seems to be an issue with the app, "Better Shipping" that you're using. Even when testing through the website I am unable to obtain shipping rates for New York, but it works fine for a San Francisco address. I discussed it with our Shipping team and I was told that that app specifically is known to have some issues, so I would recommend you bring it up with them. You can also test it out on your Online store for the same errors.

**Comment by thkeen** [comment]
Hi @runmad, 
1. Yeah. Saw the merge. Will test it very soon!
2. "Better Shipping" app we're using is to allow certain shipping areas. Thus what you're experiencing is expected, not bugs :)
Do we know when we'll have a new release soon?

**Comment by runmad** [comment]
@thkeen 1.2.1 is out.

Glad to hear it's working!
