### ISSUE TITLE
Available Quantity for Variant

### ISSUE THREAD

**Issue by samphomsopha** [Shopify/mobile-buy-sdk-ios#366]
Is there a property available on BUYProductVariant that will give me the total available quantity?  Looks like BUYProductVariant.available is 1 or 0 to indicate if the variant is available but does not contain the stock quantity.

If a user selects a quantity that is greater than the available quantity, I'm not able to create a BUYCheckOut Object.  How do you recommend dealing with this problem?

**Comment by davidmuzi** [comment]
The product will not give you access to the quantity of the variants available. If you create a checkout with a quantity exceeding stock level, you will get an error indicating so.

**Comment by EricNetsch** [comment]
@davidmuzi This needs to be added to the SDK asap. All this info in readily available in the API. Even the "Stockroom" app made by Shopify shows variant quantity. Please open this issue back up as this is an important addition.

**Comment by davidmuzi** [comment]
@EricNetsch this info is not available in the Product API.

If the quantity in the Checkout exceeds the inventory amount, you will get an error indicating such.

**Comment by EricNetsch** [comment]
@samphomsopha You can use the variant.available

From davidmuzi 

> "I understand the need for the inventory. Without going to far into the details, for legacy reasons the inventory is still available in the API themes use. This SDK uses a newer API which has measures to offer better protection for the merchant. For instance, the API key allows us to ensure the API is not abused by 3rd parties. As for inventory, it protects the merchant from bots which attempt to purchase all the inventory.
> 
> So yes, unfortunately there are no plans to disclose the inventory count in the product.
> 
> As for "Sold out", you can use the property on the variant http://cocoadocs.org/docsets/Mobile-Buy-SDK/2.2.0/Classes/_BUYProductVariant.html#//api/name/available"
