### ISSUE TITLE
Error running on Xcode 8, swift 3.

### ISSUE THREAD

**Issue by asudevil** [Shopify/mobile-buy-sdk-ios#368]
I'm getting an error when running the Sample App Customers on Xcode 8 swift 3.  

> Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11fdb3419) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11fbdf210). One of the two will be used. Which one is undefined.

**Comment by HmoIftikhar** [comment]
I have got the same error..  how to resolve it kindly help 
 Class PLBuildVersion is implemented in both /Applications/Xcode 7.16.52 PM.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x120203998) and /Applications/Xcode 7.16.52 PM.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x120025880). One of the two will be used. Which one is undefined.
