### ISSUE TITLE
Doesn't get ollections from shopify sdk in ios

### ISSUE THREAD

**Issue by maulikshah09** [Shopify/mobile-buy-sdk-ios#369]
Please checkout my question on stackoverflow. my app is crashed.I have successfully added buy framework

http://stackoverflow.com/questions/40067170/how-to-get-collection-from-shopify-sdk

Please help me I am new in shopify.

**Comment by davidmuzi** [comment]
Hi @maulikshah09, we'd like to keep questions about the SDK on our [forums](https://github.com/Shopify/mobile-buy-sdk-ios#help), and bug reports or feature requests on Github.

If you believe this is a bug, please provide detailed steps to reproduce, a symbolicated stack trace and/or sample code that demonstrates the issue.

Thanks

**Comment by pwr7549** [comment]
Hello, 
I have encountered with this getCollectionsPage issues. The most of properties as shown below are missing that I attempted to extract them from it. I only got data when I extracted it with htmlDescription property. I don't understand why these important properties  are now lacked from this instance Method. Could you please kindly add them to it like you had done with the previous version 1.2.6. 

  title - Missing
  collectionId -MIssing
  htmlDescription - Missing
  description - Existing
  imageURL - Existing but blanked URL 
  handle - Missing
  published - Missing
  createdAtDate - Missing 
  updatedAtDate - Missing
  publishedAtDate - Missing

Need to add these features:

productIds - Needed

**Comment by bgulanowski** [comment]
Those properties (excluding `productIds`) all still exist in version 2. If you think you have a bug, please provide steps to reproduce it.

To access products, you must use the product endpoint API via the `-getProduct(s)` methods.
