### ISSUE TITLE
Swift 3 client fetch returning nil

### ISSUE THREAD

**Issue by asudevil** [Shopify/mobile-buy-sdk-ios#370]
Having issues with client fetch functions after switching to SWIFT 3.  client.getCollectionsPage is requiring a return BUYDataCollectionsListBlock.  This crashes because BUYDataCollectionsListBlock is nil
`client.getCollectionsPage(pages, completion: {( collections:[BUYCollection]?, page: UInt, reachedEnd: Bool, error: NSError?) -> Void in
            
            if (collections != nil) && error == nil {
                completion (collections, error)
            }
            else {
                print("Error fetching collections: \(error!.userInfo)")
            }
        } as! BUYDataCollectionsListBlock)`

**Comment by davidmuzi** [comment]
You should be using `Error` instead of `NSError`, like this:

```
BUYClient.sharedClient.getCollectionsPage(pages, completion: {( collections:[BUYCollection]?, page: UInt, reachedEnd: Bool, error: Error?) -> Void in
        
      if (collections != nil) && error == nil {
           completion (collections, error)
      }
      else {
         print("Error fetching collections: \(error!.localizedDescription)")
      }
 })
```

Also, its much more succinct to use a trailing closure like so:

```
BUYClient.sharedClient.getCollectionsPage(1) { (collection, page, done, error) in
            
}
```
