### ISSUE TITLE
Discount not working

### ISSUE THREAD

**Issue by martinappberg** [Shopify/mobile-buy-sdk-ios#388]
I am trying to create a discount with the following code:
```
BUYDiscount * disc = [self.appDg.client.modelManager discountWithCode:@"XXXXX"];
self.appDg.disc = disc;
```
However when I use the code: 
```
if (appDg.disc != nil) {
                    appDg.checkout.discount=appDg.disc;
}
                
NSLog(@"What is the total price before discount: %@", [appDg formatPrice:appDg.checkout.totalPrice]);
```

Nothing changes for:
```
[appDg.client updateCheckout:appDg.checkout completion:^(BUYCheckout *checkout, NSError *error) {
                    if (error == nil) {
#warning Temp)
                        NSLog(@"What is the total price after discount: %@",  [appDg formatPrice:appDg.checkout.totalPrice]);
```

How can I know that the discount was applied? The code basically returns before=$5 and after=$5

Thanks in advance

**Comment by bgulanowski** [comment]
It's not clear from your sample code, but you appear to be using the wrong checkout object after the update. Existing checkout objects in memory are no longer valid. You must use the new checkout object received in the callback.

**Comment by martinappberg** [comment]
Yes you're right. Put the log before using the new checkout object! Thanks a lot.
