### ISSUE TITLE
Issue with REST API + Shopify login

### ISSUE THREAD

**Issue by asoviche** [Shopify/mobile-buy-sdk-ios#395]
Hi guys.

In our iOS App, to check if a user already exist in the store (hence decide if we have to do a signup or login), we first make a request on your REST API at this endpoint:
%@/admin/customers/search.json?query=email:%@

-> it is supposed to return a customer if an account is already created with the given email. 

—> The problem is that this endpoint is not returning any customer anymore, even if they exist. It was working until 30 minutes ago, can you check what happens please :) ?

Thanks  a lot!

**Comment by asoviche** [comment]
Just went back to normal, is that normal?

**Comment by davidmuzi** [comment]
Hey @asoviche , /admin endpoints are not exposed from the SDK since they are authenticated.  You may want to ask in the API forums: https://ecommerce.shopify.com/c/shopify-apis-and-technology
