### ISSUE TITLE
Validate discount by discount code

### ISSUE THREAD

**Issue by benvus** [Shopify/mobile-buy-sdk-ios#398]
Is there a way to validate a discount using the discount code instead of discount ID? 

This more applies to the API than the mobile buy SDK, but judging from the close similarity between the admin UI and the API in general, I would hope it would be somewhat straightforward to expose the "search discounts by code" functionality that already exists in the admin UI (/admin/discounts?query=DISCOUNT_CODE) but does not exist in the API (admin/discounts.json?query=DISCOUNT_CODE).

(Our Shopify Plus account rep Zack Lukosius asked me to open this issue here; sorry if it's the wrong place for it.)

**Comment by bgulanowski** [comment]
There is no overlap between the Shopify Admin API and the Mobile Buy SDK.

Please ask questions on the ecommerce forums.
