### ISSUE TITLE
List provinces by country

### ISSUE THREAD

**Issue by martinappberg** [Shopify/mobile-buy-sdk-ios#408]
Hi,

Is there any way to list all the available provinces per country for an API call?
Since the app requires them to be correct we want to minimize the chance of a customer mistyping something and becoming frustrated, but there is no way for us to know which countries use province and we would like to determine whether it is a necessary feature or not.

**Comment by bgulanowski** [comment]
No, not using this SDK or the underlying API.

The admin API has access to more information, but you shouldn't use that from a shopping app. That information changes very rarely. I recommend that you bundle that information into the app statically.

https://help.shopify.com/api/reference/country

If your shop is called "shop-name", then the following will work in a web browser if you are authenticated in the admin interface for the shop:

https://shop-name.myshopify.com/admin/countries.json

Just reformat that data as needed and include in your app bundle, update each time you release a new version of your app.
