### ISSUE TITLE
Login & using customer information

### ISSUE THREAD

**Issue by ollieatkinson** [Shopify/mobile-buy-sdk-ios#42]
Hi,

I am creating a mobile app with this SDK, I am looking to log the user using Shopify so I can show an order history as well as use reward points I have saved against the customers account.

I cannot see any API availability to do this, is it on your roadmap?

**Comment by runmad** [comment]
Hi @ollieatkinson,

Thanks for your ticket. There is currently no API available through the SDK that offers customer login and accounts.

You're not the first person to let us know about this, and I can tell you that it is on our internal roadmap. Unfortunately I cannot offer you any details to a specific timeline.

**Comment by ollieatkinson** [comment]
Thanks @runmad, 

Do you know how I would get the order history for a user in my app?

**Comment by runmad** [comment]
Have a look at https://docs.shopify.com/api/customer

However, I highly recommend that you **do not** add any API keys for your shop to your app. Anyone coming in possession of these credentials would have direct API access to your shop. If you are able to built something on your own hosted server, you could manage some of the logic surrounding customers through an self-hosted backend.

**Comment by ollieatkinson** [comment]
I agree with not adding the api keys embedded within the app as it poses __too much__ of a security risk. 

With direct access to the shop through a middleware I am still unsure that it is actually possible to get the order history without knowing how to identify the current user. Without any customer authentication it becomes too risky to verify that it was the user who requested to view their own order history

I have looked into multi-pass however that suffers from the same problem only identifying through email address.

**Comment by runmad** [comment]
I would definitely recommend holding off on adding such a feature to your app until there's official support for it through the SDK.

**Comment by ollieatkinson** [comment]
OK thanks for your prompt answers @runmad

**Comment by jkoutavas** [comment]
Any update available on the roadmap? User authentication from a mobile device will open up a large number of development opportunities.

**Comment by RJiryes** [comment]
I would also like to know if there are any new updates regarding this issue, thanks.. :)

**Comment by vijayakumarram** [comment]
Hi,
I am creating a mobile app with this SDK, I am looking to log the user using Shopify so I can show an order history as well as use reward points I have saved against the customers account.
I cannot see any API availability to do this, is it on your roadmap?

**Comment by dbart01** [comment]
@vijayakumarram The SDK supports custom login and order history. Please take a look at [the documentation](https://github.com/Shopify/mobile-buy-sdk-ios#customer-accounts-).
