### ISSUE TITLE
Other payment providers

### ISSUE THREAD

**Issue by martinappberg** [Shopify/mobile-buy-sdk-ios#424]
Is there any way to integrate other payment providers (listed on shopify)?
How can I present this as a web view likewise to what you get when you initialize the web checkout?

**Comment by bgulanowski** [comment]
Alternate payment providers will show up in the web checkout already, similar to checking out from the web store. We don't have any way to pre-select an alternate gateway before going to the web, however.

**Comment by martinappberg** [comment]
Thanks for your reply!
Also, can you use some sort of out-of-the-box solution as Stripe/Braintree SDK and get a token of the credit card and then pass it on to shopify during the native checkout?

**Comment by bgulanowski** [comment]
No, the checkout API does not support external gateways for Buy SDK clients.
