### ISSUE TITLE
Mobile buy SDK Web checkout not working.

### ISSUE THREAD

**Issue by pajju** [Shopify/mobile-buy-sdk-ios#43]
Hi,

We configured the mobile buy SDK with the below information

shopDomain = "jumkey.myshopify.com"
apiKey = "XXXXXXXXXXXXX"
channelId = “14070401"
productId = “1923353089”  —> This is the Product I am checking out.

Breakdown of Calls at Mobile Buy SDK
1. Get the Product Details based on Product ID
2. Checkout JSON is formed based on the configured info. JSON Looks as below
checkout =     {
        "channel_id" = 14070401;
        "line_items" =         (
                        {
                price = 350;
                quantity = 1;
                "requires_shipping" = 1;
                title = "Default Title";
                "variant_id" = 5982045505;
            }
        );
        "marketing_attribution" =         {
            medium = iOS;
            source = "Mobile Buy SDK Swift Sample";
        };
        "source_identifier" = 14070401;
        "source_name" = "mobile_app";
    };
}

3. With this the Mobile Buy SDK hits a Checkout POST METHOD - 
the URL isURL: https://jumkey.myshopify.com/anywhere/checkouts.json and POST Parameter is CHECKOUT JSON formed in step:2

4. This post request throws this error
{
    errors =     {
        checkout =         {
            "line_items" =             (
            );
            "payment_gateway" =             (
                                {
                    code = invalid;
                    message = "is invalid";
                    options =                     {
                    };
                }
            );
            "reservation_time" =             (
            );
            "source_name" =             (
            );
        };
    };
}

We are totally confused and not getting proper direction and help.

Our Payment gateway is PayU India(officially supported by Shopify Backend in India & Asia), 
We like to hit the web Checkout Page in Shopify, from there it's a breeze.

Are we missing anything here?
Kindly help & Give us proper direction.

Thanks in advance.

**Comment by davidmuzi** [comment]
PayU is not currently supported by the Mobile Buy SDK.  If you want to allow web checkout from a mobile application, you can use [Cart Permalinks](https://docs.shopify.com/manual/configuration/store-customization/page-specific/cart-page/cart-permalinks)

**Comment by pajju** [comment]
thanks for the update, will explore Cart Permalinks. That was very useful.

In Mobile Buy SDK, is there a way we can integrate PayU to this SDK & make it still work.
Can it be extended? 
Please give us some direction. 

PayU Gateway is supported by shopify backend, 
and is widely used in India & Asia.

Thanks in Advance.

**Comment by davidmuzi** [comment]
We continue to add support for additional gateways in the Mobile Buy SDK.  We will let you know when new ones are added.

**Comment by pajju** [comment]
Thanks! That's very positive.

Looking forward to the PayU integration.

**Comment by JaydeepPatel** [comment]
@pajju @davidmuzi  Please help me with this #560
