### ISSUE TITLE
In xcode 8 its crashing ,

### ISSUE THREAD

**Issue by ravulamanjula** [Shopify/mobile-buy-sdk-ios#442]
BUYProductVariant *variant = (BUYProductVariant *) [[product valueForKey:@"variants"] firstObject];
                NSLog(@"variant: %@", [variant class]);
                [cart addVariant:variant];
            }
while try to add variant its crashing ,this is error message
[NSDecimalNumber buy_decimalNumberFromJSON:]: unrecognized selector sent to class

**Comment by bgulanowski** [comment]
Please provide a stack trace.

Also,  you can get a variant using `product.variants[0]`; no need to use key-value coding.
