### ISSUE TITLE
Calling for image as imageview in cell

### ISSUE THREAD

**Issue by peersyichi** [Shopify/mobile-buy-sdk-ios#456]
Within my Product list page and Collections page, I've set it up the 'cell's as subtitle and collecting the title and description of each product without any problems using; 

cell.textLabel.text = product.title.uppercaseString;
cell.detailTextLabel.text = product.htmlDescription;

but I'm having huge issues calling for product image into the cell's imageview. I've tried many different approaches but they all end up basically like the following;

cell.imageView.image = product.image;

I know this isn't a technical problem and have seen that you recommend to go to the forums for this type of question but I've really had no luck. I have posts from a couple weeks back and have phoned up to ask for help from their experts, Had no response from the posts and sadly the experts emailed me last night that they are unable to help me. 

Any Help would be greatly appreciated.

**Comment by bgulanowski** [comment]
Unfortunately we are under-staffed on the SDK and don't always see posts on the forums. In future, please provide a link from GitHub to the forum so we can answer your questions there.

**Comment by bgulanowski** [comment]
I have answered your question on the forums.
