### ISSUE TITLE
Add Swift docs

### ISSUE THREAD

**Issue by EricNetsch** [Shopify/mobile-buy-sdk-ios#462]
There are no swift docs in the readme or the Shopify online docs. The example app was helpful but full documentation would be much appreciated. Happy to help with this. Thanks!

**Comment by unittesting0** [comment]
I'm also looking for swift documentation.
The swift example project doesn't run!

**Comment by davidmuzi** [comment]
@EricNetsch The SDK is written in Objective-C, and while we didn't write a readme or publish online docs in Swift, the in-line API documentation in Xcode works just fine.  We have no current plans to publish Swift docs at this time.

@unittesting0 
Whats preventing the `Customer App - Swift` from running? Please provide details in a new issue, thanks!
