### ISSUE TITLE
How to fetch metafields from mobile-buy-sdk?

### ISSUE THREAD

**Issue by thkeen** [Shopify/mobile-buy-sdk-ios#47]
Hey guys, been looking around and couldn't find elsewhere a way to fetch `metafields` *without* using private apps. In our mobile app, we have extra information about the shop and collections. We need these information in order to display them nicely in our app, which means it's fine to be public.

I dig into the `BUYClient.m` code, seeing lots of public endpoints that are not documented like: `collection_publications.json`, `meta.json` for shop, etc.

So question: will you guys expose metafields into the mobile-buy-sdk in the future? If not soon, is there  a way I can fetch it publicly?

**Comment by davidmuzi** [comment]
Hey Thkeen,

the methods consuming `collection_publications.json` and `meta.json` are documented in the `BUYClient.h` header.

As for the metafields, there is no current way to get them publicly.

**Comment by thkeen** [comment]
Thanks. I think it will be very helpful though believe this would take time. In the meantime any custom data we need to store somewhere else then.
