### ISSUE TITLE
Discount not working properly

### ISSUE THREAD

**Issue by martinappberg** [Shopify/mobile-buy-sdk-ios#472]
When I set a discount to the checkout and then return the checkout total price/discount amount it is incorrect to the one I have set in the admin panel ie. they don't match.

For instance if I have a discount with the amount $3.00 off and try to get checkout.totalPrice/checkout.discount.amount it returns another value

This happens after I have updated the checkout with the discount

**Comment by martinappberg** [comment]
Noticed that this was when creating a checkout with the value of for instance $0.99  this then returns the error because the discount is greater than the checkout however we have shipping for $3.51 as well and it would be great if the discount could take that in account when calculating total price

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.
