### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by ollieatkinson** [Shopify/mobile-buy-sdk-ios#48]
Do we support any caching in the mobile buy sdk?

e.g. 

1. fetch products A-Z
2. fetch products Z-A
3. fetch products A-Z <-- I would expect this to use the cached version

**Comment by runmad** [comment]
Caching is not supported on the API or in the SDK at this time.

You are free to add support for Core Data in your app if you require persistence.

**Comment by ollieatkinson** [comment]
Core Data isn't a cache, I was thinking a way to define what HTTP cache policy the requests would use.

**Comment by runmad** [comment]
Unfortunately our API does not support this, no.
