### ISSUE TITLE
Web-checkout not calling paymentProviderWantsControllerDismissed

### ISSUE THREAD

**Issue by MihaShoutem** [Shopify/mobile-buy-sdk-ios#480]
This issue is related to: #428 

I made a React Native bridge for Shopify SDK and initialized a web checkout like this:

```
BUYWebCheckoutPaymentProvider *webPaymentProvider = [[BUYWebCheckoutPaymentProvider alloc] initWithClient:self.client]; 
webPaymentProvider.delegate = self;
[webPaymentProvider startCheckout:checkout];
```
This method gets called:

```
- (void)paymentProvider:(id<BUYPaymentProvider>)provider wantsControllerPresented:(UIViewController *)controller
{
    self.rootViewController = [[ [UIApplication sharedApplication] keyWindow] rootViewController];
    [self.rootViewController presentViewController:controller animated:YES completion:nil];
}
```
I'm able to complete an order but when it is done, it just displays the order thank you page in the webview. Is the expected behaviour for it to redirect back to the app automatically or when I click "Done" ? After I click "Done" the webview closes but my app is not notified and I can't clear the cart. 

This method never gets called:

```
- (void)paymentProviderWantsControllerDismissed:(id <BUYPaymentProvider>)provider
{
    [self.rootViewController dismissViewControllerAnimated:YES completion:nil];
}
```

**Comment by bgulanowski** [comment]
Your app is responsible for posting the `BUYSafariCallbackURLNotification` when control returns from a web view. This notification will be observed by the payment provider. When it receives this notification, it will request that the controller be dismissed, and will also refresh the checkout status.

See `BUYWebCheckoutPaymentProvider.m` for details.

**Comment by MihaShoutem** [comment]
Hey,

Thank for the explanation! We decided to go with native checkout because of business requirements, but since we're also making a React Native bridge for the SDK, we'll look into it because it'll be useful for other people.

Thanks again!
