### ISSUE TITLE
Inconsistent data type with API in cart array

### ISSUE THREAD

**Issue by judopro** [Shopify/mobile-buy-sdk-ios#481]
I am trying to figure this one out for awhile, thought i would post it here. I am trying to access the BUYLineItem properties of a checkout (or cart) so that I can retrieve the fulfillment_service field for that specific line item. The BUYCartLineItem object doesn't have this property. So I am depending on shopify, and get the lineitems back after I added all items to cart and update the checkout. The API says BUYCheckout.lineItemsArray() should be [BUYCartLineItem] but when I am debugging the code, the returned is actually [BUYLineItem] which I can cast as individual BUYLineItem and access fulfillment_service but it definitely not matches what the API is saying. 

It gives me what I want for now since I can access the fullfilment_service but I know something is off here, so don't want to depend on something.... and then next version the content of the array changes to what the API says....

The other question is if BUYCheckout.lineItemsArray() is not the correct way to access fulfillment_service, what is ??
![screen shot 2016-12-28 at 9 58 10 pm](https://cloud.githubusercontent.com/assets/24821249/21537754/43cba6d6-cd4a-11e6-8c36-4109f1b44468.png)
![screen shot 2016-12-28 at 9 59 30 pm](https://cloud.githubusercontent.com/assets/24821249/21537756/472e37da-cd4a-11e6-915b-bef467259264.png)

**Comment by bgulanowski** [comment]
This a bug in the generic type declaration on the `lineItemsArray` derived property. Checkout objects always contain `BUYLineItem` objects in the `lineItems` property, from which `lineItemsArray` is derived as a convenience for Swift.

`BUYCartLineItem` objects are only used on `BUYCart.lineItems`. Both `BUYCart` and `BUYCartLineItem` objects are client-only.
