### ISSUE TITLE
Update SDK pod to Version 2.2.0

### ISSUE THREAD

**Issue by EishanVijay** [Shopify/mobile-buy-sdk-ios#482]
SDK Version 2.2.0 needs to be pushed to CocoaPods

#### * you will need to be set up with Trunk in order to update the SDK pod *

- `edit Mobile-Buy-SDK.podspec`
	-	set the new version to `VERSION_NUMBER`
	-	set the new tag to `VERSION_NUMBER`
-	run `pod lib lint` to to test the syntax of the .podspec file
-	`git add -A && git commit -m "Release VERSION_NUMBER."`
-	`pod trunk push Mobile-Buy-SDK.podspec`

**Comment by bgulanowski** [comment]
Done:

http://cocoadocs.org/docsets/Mobile-Buy-SDK/2.2.0/

**Comment by bgulanowski** [comment]
CocoaDocs seems to think the version in 2.0.1, although if you request 2.2.0 you get it. But it shows up as 2.2 on the cocoapods page:

http://cocoapods.org/pods/Mobile-Buy-SDK

**Comment by EishanVijay** [comment]
@bgulanowski CocoaDocs shows 2.2.0 now. Thanks 😄
