### ISSUE TITLE
how to set CORE_DATA_PERSISTENCE

### ISSUE THREAD

**Issue by pavangopal** [Shopify/mobile-buy-sdk-ios#485]
I need to implement caching in my application. I am using **cocoa pods** to install the SDK.
How should I enable CORE_DATA_PERSISTENCE flag to use coredata entities provided by the SDK.

**Comment by bgulanowski** [comment]
It's covered here under "Core Data":

https://help.shopify.com/api/sdks/mobile-buy-sdk/ios/integration-guide/caching

Let me know if you any further questions.

**Comment by pavangopal** [comment]
I downloaded the sample apps(Objective C) and tried to run it and did a check to see if that has core data enabled like this:
`#if defined CORE_DATA_PERSISTENCE
    NSLog(@"App has core data");
#endif
#if !CORE_DATA_PERSISTENCE
    NSLog(@"App doesn't have core data");
#endif`

But every time it logs   NSLog(@"App doesn't have core data");

I also have changed the build configuration for the "Buy" Target as shown the below snapshot

![image](https://cloud.githubusercontent.com/assets/13829145/22176930/8c2d0dae-e03a-11e6-8ca6-594ac6e5850a.png)

Can you please guide me to what  I am missing out on.

**Comment by bgulanowski** [comment]
When a framework is built *as a dependency* of an app target in Xcode, it *inherits* the build configuration specified in the app target. Selecting the configuration in the framework target only affects the target when it is built directly.

Xcode tries to find a framework build configuration with the same name as the app configuration. If it cannot, it will use "Release" (if it exists), or something else according to some rule of its own.

This is, admittedly, rather obscure Xcode knowledge.

The configuration of your *app target* must be named "Debug-core-data". If it is named, say, "Debug", or anything else, then Xcode will build the framework using "Release". And thus it will both be built wrong, and built in the wrong place.

**Comment by pavangopal** [comment]
Hi I enabled coredata into the project but I am getting a crash on getCollectionPage api.
`'[<BUYCollection 0x608000091490> valueForUndefinedKey:]: the entity (null) is not key value coding-compliant for the key "initWithModelManager:JSONDictionary:".'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010cfe1d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010ca4321e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010cfe1c99 -[NSException raise] + 9
	3   CoreData                            0x00000001151edf54 -[NSManagedObject valueForUndefinedKey:] + 308
	4   Buy                                 0x000000010c44a36c -[BUYManagedObject valueForPropertyKey:] + 92
	5   Buy                                 0x000000010c449f29 -[BUYManagedObject forwardInvocation:] + 681
	6   CoreFoundation                      0x000000010cf66e1e ___forwarding___ + 526
	7   CoreFoundation                      0x000000010cf66b88 _CF_forwarding_prep_0 + 120
	8   Buy                                 0x000000010c468624 __55-[BUYModelManager buy_objectsWithEntityName:JSONArray:]_block_invoke + 100
	9   Buy                                 0x000000010c44e809 __33-[NSArray(BUYAdditions) buy_map:]_block_invoke + 105
	10  CoreFoundation                      0x000000010cf7274d __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 77
	11  CoreFoundation                      0x000000010cf72606 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 166
	12  Buy                                 0x000000010c44e730 -[NSArray(BUYAdditions) buy_map:] + 288
	13  Buy                                 0x000000010c468549 -[BUYModelManager buy_objectsWithEntityName:JSONArray:] + 361
	14  Buy                                 0x000000010c46b9b3 __55-[BUYClient(Storefront) getCollectionsPage:completion:]_block_invoke + 291
	15  Buy                                 0x000000010c47ccd4 __65-[BUYClient requestForURL:method:object:start:completionHandler:]_block_invoke_2 + 52
	16  Foundation                          0x000000010c5459ad __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	17  Foundation                          0x000000010c54568f -[NSBlockOperation main] + 101
	18  Foundation                          0x000000010c543d8c -[__NSOperationInternal _start:] + 672
	19  Foundation                          0x000000010c53fccf __NSOQSchedule_f + 201
	20  libdispatch.dylib                   0x00000001139760cd _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x00000001139568a4 _dispatch_main_queue_callback_4CF + 406
	22  CoreFoundation                      0x000000010cfa5e49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	23  CoreFoundation                      0x000000010cf6b37d __CFRunLoopRun + 2205
	24  CoreFoundation                      0x000000010cf6a884 CFRunLoopRunSpecific + 420
	25  GraphicsServices                    0x0000000111e7ca6f GSEventRunModal + 161
	26  UIKit                               0x000000010dc46c68 UIApplicationMain + 159
	27  Mobile Buy SDK Advanced Sample      0x000000010c316cef main + 111
	28  libdyld.dylib                       0x00000001139c268d start + 1
	29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by bgulanowski** [comment]
You can't just enable Core Data. You have to write your own persistence. There is no built-in persistence manager.

You have to write a custom subclass of `BuyModelManager` (or a new class that conforms to the `BUYModelManager` protocol) that handles the Core Data work. We do not directly support offline caching.

**Comment by userDenis** [comment]
pavangopal, How you enable CORE_DATA_PERSISTENCE, please explain
