### ISSUE TITLE
Mobile Buy SDK Advanced Sample Error

### ISSUE THREAD

**Issue by skobyjay** [Shopify/mobile-buy-sdk-ios#488]
Hello, I have download the Mobile Buy SDK Advanced Sample app. when I run the application in Xcode, I get the output below and the example app looks odd. it displays products from my store but it doesn't look presentable. below is the error I have. any ideas?

objc[2463]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11a766998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11a588880). One of the two will be used. Which one is undefined.
2017-01-25 20:13:13.780 Mobile Buy SDK Advanced Sample[2463:30062] Error creating checkout: Error Domain=BUYShopifyErrorDomain Code=422 "(null)" UserInfo={errors={
    checkout =     {
    };
}}

**Comment by davidmuzi** [comment]
Can you provide more details?  If there are visual glitches, please provide screenshots.  If your interested in the checkout error, please provide steps to reproduce
