### ISSUE TITLE
There is no way to get products with Variant ID in SDK

### ISSUE THREAD

**Issue by MrGobert** [Shopify/mobile-buy-sdk-ios#489]
I've seen this issue asked a few different places but wanted to actually submit it as an issue. I'm creating an app for a Shopify store with a perpetual Shopping Cart that saves whatever is in the cart when the customer returns to the app. I'm converting my BUYCart into JSON, saving and grabbing the JSON whenever the app is opened. 

However the Product data is lost during that conversion so I lose the product image and title. In order to populate my Cart I have to make call to get the product again. However the product variant that's saved as JSON only contains the variant ID and there are no calls currently in the SDK to get the product or image, etc. It would be nice to just be able to add one if not multiple variant ID's into a BUYClient get-call and be able to get variant or product photo and Product title. 

If someone knows an alternative solution to restoring the images/product title for a shopping cart with only having the variant id please share with me.

**Comment by martinappberg** [comment]
It's been bugging me for a while as well. Would be great for the JSON to just contain the imgurl, shouldn't be that much of a trouble.

I have a solution for this that works, here is my cart restoration code:

```
-(void)loadCartWithJSON:(NSDictionary *)lastCart {
    NSArray * options = [[NSUserDefaults standardUserDefaults] objectForKey:@"lastCartOptions"];
    self.cart = [self.client.modelManager insertCartWithJSONDictionary:lastCart];
    NSArray * prodIds = [[NSUserDefaults standardUserDefaults] objectForKey:@"lastCartProdIds"];
    NSLog(@"Options: %lu  IDS: %lu   ITEMS: %lu",(unsigned long)options.count,(unsigned long)prodIds.count,(unsigned long)self.cart.lineItemsArray.count);
    if (((self.cart.lineItemsArray.count == options.count) && (self.cart.lineItemsArray.count == prodIds.count)) && options && prodIds) {
    [self.client getProductsByIds:prodIds completion:^(NSArray<BUYProduct *> * _Nullable products, NSError * _Nullable error) {
        NSLog(@"BEFORE: %lu, AFTER:%lu",(unsigned long)prodIds.count, products.count);
        NSMutableArray * newProds = [NSMutableArray new];
        for (NSNumber * prId in prodIds) {
            for (BUYProduct * pd in products) {
                if (prId == pd.identifier) {
                    [newProds addObject:pd];
                }
            }
        }
        
        NSMutableArray * newOptions = [NSMutableArray new];
        for (NSArray * optionsArr in options) {
            NSArray * loadedOption = [self.client.modelManager insertOptionValuesWithJSONArray:optionsArr];
            [newOptions addObject:loadedOption];
        }
        for (BUYCartLineItem * linItem in self.cart.lineItemsArray) {
            BUYProduct * prod = (BUYProduct*)[newProds objectAtIndex:[self.cart.lineItemsArray indexOfObject:linItem]];
            linItem.variant.product = prod;
            linItem.variant.options = [NSSet setWithArray:[newOptions objectAtIndex:[self.cart.lineItemsArray indexOfObject:linItem]]];
        }
        [self updateBadgeForCart];
        
    }];
    }else {
        self.cart = [self.client.modelManager insertCartWithJSONDictionary:nil];
    }
}
```


It sometimes has errors loading, if some data is lost along the way or if the product sells out, which is annoying. Have not seen it a lot but I've heard of one user having that issue so will try to optimize that code. This way you replace the options and the BUYCart should be completed, however it does not contain the image. So when I display the cart I check all of the products images and match it with the variantid to see which image is correct:

```
for (BUYCartLineItem * item in self.appDg.cart.lineItemsArray) {
        BUYProductVariant * variant = item.variant;
        BUYProduct * product = variant.product;
        BUYImageLink * firstImg = [product.images firstObject];
        BOOL addedImage = NO;
        for (BUYImageLink * image in product.images) {
            for (NSNumber * nom in image.variantIds) {
                if (variant.identifier == nom) {
                    if (!addedImage) {
                        [images addObject:image.sourceURL];
                        addedImage = YES;
                        break;
                    }
                }
            }
        }
        if (![images containsObject:firstImg.sourceURL] && addedImage == NO) {
            [images addObject:firstImg.sourceURL];
            addedImage = YES;
        }
```

It's not that pretty, but it works.
For title however I only use the product title but since I have the options stored in the cart I can show them under the product.

```
if (variant.options.count > 0) {
            for (BUYOptionValue * option in variant.options) {
                NSLog(@"%@",option.name);
                NSString * properties = [NSString stringWithFormat:@"%@: %@  ", option.name, option.value];
                [size appendString:properties];
                NSLog(@"PROP: %@   and ENDSTRING: %@", properties, size);
            }
            [notes addObject:size];
        }else{
            [notes addObject:[NSMutableString stringWithFormat:@""]];
        }
```

Hope this could help you out just a little bit.

**Comment by JaydeepPatel** [comment]
@martinappberg 
Hello, 

I want to add item in cart I try with this code but crash the application,

I used that See my Code,

self.client = [[BUYClient alloc] initWithShopDomain:@"###"
apiKey: @"###"
appId:@"8"
applicationName:@"###"];
BUYCart *cart = [self.client.modelManager insertCartWithJSONDictionary:nil];
BUYProductVariant *variant = [self.product.variants firstObject]; //Crash From Here.....
[cart addVariant:variant];

Crash From this Line=>BUYProductVariant *variant = [self.product.variants firstObject];
CRASH:=>
reason: '-[__NSDictionaryI variants]: unrecognized selector sent to instance 0x7fabf7d2e3b0'

So, How can solve it ? 

Varient Values like,

variants = (
{
barcode = "";
"compare_at_price" = "";
"created_at" = "2016-11-05T20:21:38+03:00";
"fulfillment_service" = manual;
grams = 0;
id = 31099805571;
"image_id" = "";
"inventory_management" = "";
"inventory_policy" = deny;
"inventory_quantity" = "-21";
"old_inventory_quantity" = "-21";
option1 = "Default Title";
option2 = "";
option3 = "";
position = 1;
price = "37.00";
"product_id" = 8999280067;
"requires_shipping" = 1;
sku = "";
taxable = 1;
title = "Default Title";
"updated_at" = "2016-11-15T15:05:46+03:00";
weight = 0;
"weight_unit" = kg;
}
);
vendor = Floward;
}

**Comment by bgulanowski** [comment]
@JaydeepPatel please don't cross-post or hijack issue threads.

As a reminder, GitHub is not a help forum. GitHub issues are to be used to describe bugs and request features, not for discussion of how to use the frameworks.

Do not post requests for help here. Post them in the Shopify Ecommerce forums here: https://ecommerce.shopify.com/ecommerce/

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.
