### ISSUE TITLE
pageSize errors

### ISSUE THREAD

**Issue by martinappberg** [Shopify/mobile-buy-sdk-ios#491]
So I noticed with the new release that .pageSize is deprecated but when I tried to use the other providers such as `productPageSize = 50` it returns the error `[BUYClient setProductPageSize:] Unrecognized selector sent to instance` 

What is the correct way to do this?

**Comment by davidmuzi** [comment]
its an instance variable, so you'll need to set like such:
```
BUYClient *client = [BUYClient alloc] init...]
[client.setProductPageSize: 42]
```
