### ISSUE TITLE
Set shipping prior to checkout

### ISSUE THREAD

**Issue by martinappberg** [Shopify/mobile-buy-sdk-ios#496]
My service only has one shipping option available. Is it possible for me to set this one prior to displaying the Web Checkout? I don't want user to be confused and not see the total price until after  he/she has entered their shipping address. I have tried to create a BUYShippingRate using JSONDictionary I copied from another Shipping Rate but this does not work once I set it to the checkout. Is it possible to do this?

**Comment by bgulanowski** [comment]
Did you use the provided API on `BUYClient`, `getShippingRatesForCheckoutWithToken:completion:`? I believe you should be able to set the shipping rate with that before beginning checkout.

https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Data/BUYClient%2BCheckout.h#L178

**Comment by martinappberg** [comment]
Yes sure that works, but only if I have specified the shipping address before. Since shipping is the same cost for everywhere with our service it would be great to assign the shipping rate prior to checkout to minimize steps needed to pay

**Comment by bgulanowski** [comment]
I'm sorry, but it's a requirement of Shopify checkout. It's not a limitation enforced by this SDK.

**Comment by martinappberg** [comment]
Ok thanks for clarifying
