### ISSUE TITLE
crash cart.setVariant

### ISSUE THREAD

**Issue by mariapush** [Shopify/mobile-buy-sdk-ios#505]
Get error when uses cart.setVariant(variant, withTotalQuantity: countItems)

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSMutableOrderedSet addObject:]: object cannot be nil'`

// create cart
`let cart = BUYCart();`

//get all products
```
self.client.getProductsByIds(productIds) { (products, error) -> Void in
            if (error) != nil {
                NSLog("Error retrieving products: \(error)");
            } else {
                for product in products! {                     
                        for aVariant in product.variants {
                            let variant = aVariant as! BUYProductVariant
                            let allKeys = Array(AppManager.shopping_cart.keys) // all selected variant ids
                            let currentKey = allKeys[0] as String
                            if(currentKey.caseInsensitiveCompare("\(variant.identifier as NSNumber)") == .orderedSame ){

                                let item = AppManager.shopping_cart[currentKey]! as Dictionary<String, AnyObject>
                                let countItems = item["countItems"] as! Int                          
                                cart.setVariant(variant, withTotalQuantity: countItems)
                            }
                        } 
                }
            }
        }
```

Please could you clarify - what kind of variant should be?
Variant is not empty when I add it to cart

**Comment by bgulanowski** [comment]
You have instantiated the `cart` incorrectly. You cannot use the default `init()` method. Every model requires a `modelManager` property to be set.

The `BUYClient` automatically creates a `modelManager`. Use `init(modelManager:JSONDictionary:)` method when creating model objects, passing in the model manager from the client. Or use the convenience `BUYModelManager.insertCart(with JSONDictionary: nil)`.

This is covered by the documentation here:
https://help.shopify.com/api/sdks/custom-storefront/mobile-buy-sdk/ios/integration-guide/checkout#building-a-cart
