### ISSUE TITLE
Version 1

### ISSUE THREAD

**Issue by mariapush** [Shopify/mobile-buy-sdk-ios#506]
Please could you clafiry few moments:
I use the first version to create a payment through the Apple pay and everything works fine. Please tell me how long first version will work? How urgent need to go to the second version?
Do you have an example when Swift with the addition of variant to Cart? I have not found such existing examples.

**Comment by bgulanowski** [comment]
SDK v1 is not supported. We have no specific plans for decommissioning it. It may stop working at any time. Please read the documentation, and ask questions on the forums. GitHub issues are meant to be for filing bugs and requesting features.
