### ISSUE TITLE
Error Handling for Sign In/Sign Up

### ISSUE THREAD

**Issue by ksingh65** [Shopify/mobile-buy-sdk-ios#509]
loginCustomer and createCustomer, if something wrong like user is trying to create an account while account exist we get an error. But when we try to show as localized description it always say BuySDK error domain 422. and if we check user-info it shows a inside a "errors". But this key is different like some time it will be "errors" or "error".

Can you please provide how to handle such scenario?

**Comment by davidmuzi** [comment]
Unfortunately, there will not be any changes to the current API to improve this.  The next version of the SDK will have much better error handling, but we have no timelines for its release

**Comment by EricNetsch** [comment]
Also, we experienced this quite a bit. Would be great to also be able to check whether the Shopify store "requires accounts" etc. to avoid potential sign in issues

**Comment by bgulanowski** [comment]
Shops don't require accounts.

This SDK only supports _customer_ login, not staff login. Shops are expected to know whether they support customer login before building an app that uses the SDK. If you are trying to build an app that _manages_ a shop, this is not the SDK for you.

**Comment by deekshibellare** [comment]
"Unfortunately, there will not be any changes to the current API to improve this. The next version of the SDK will have much better error handling, but we have no timelines for its release" what does this mean? Are you saying it's not going to be fixed? Is is not rude to close the issue without offering any solution ?
