### ISSUE TITLE
Variant available_quantity not included in SDK 

### ISSUE THREAD

**Issue by EricNetsch** [Shopify/mobile-buy-sdk-ios#510]
I know this topic has been dismissed in the past, but variant quantity is very basic to building a functional shopping app. 

In the API, there is a variant attribute "available_quantity" that displays the quantity of in-stock items available. This is used to show the items that are out-of-stock and to display the quantity currently in stock. Most Shopify web themes use this data. 

We need to add this attribute to the products/variants in the SDK. Let me know how I can help contribute to this issue and get this functionality working. 
Thanks in advance.

**Comment by davidmuzi** [comment]
Please don't intentionally open duplicate issues (#366), its bad etiquette.

This SDK exposes an API that does not have access to inventory counts for variants.  The API you are referring to is another API, which while it does have inventory counts, it does not honour channel publications.  The API used here honours channel publications, so you'll only see products and collections that the merchant published to the Mobile App Channel.

**Comment by EricNetsch** [comment]
@davidmuzi Got it, my bad. I will avoid this in the future. 

So by closing this issue your saying is there is absolutely no plans to include the inventory quantity using the SDK?

Excuses aside, it still doesn't make any sense to not include this in the SDK as all Shopify web themes have this functionality available. It's difficult to build quality apps on Shopify's mobile SDK because it is lacking the basic common sense features that we all need as partners and store owners.

**Comment by EricNetsch** [comment]
Also, even the Shopify "Stockroom" iOS app have "sold out" logic included. Curious on how they did this? Guessing they didn't even use the their own SDK. 

![photo mar 01 3 04 28 pm](https://cloud.githubusercontent.com/assets/5900690/23485632/21c0f51e-fe91-11e6-9979-9541d87facd2.png)

**Comment by davidmuzi** [comment]
I understand the need for the inventory.  Without going to far into the details, for legacy reasons the inventory is still available in the API themes use.  This SDK uses a newer API which has measures to offer better protection for the merchant.  For instance, the API key allows us to ensure the API is not abused by 3rd parties.  As for inventory, it protects the merchant from bots which attempt to purchase all the inventory.

So yes, unfortunately there are no plans to disclose the inventory count in the product.

As for "Sold out", you can use the property on the variant http://cocoadocs.org/docsets/Mobile-Buy-SDK/2.2.0/Classes/_BUYProductVariant.html#//api/name/available

**Comment by EricNetsch** [comment]
Got it! Thanks you man! We will use the "available" attribute. Not sure why it's and INT instead of a BOOL haha

I think removing available quantity from the API / SDK is a big mistake. Amazon has been showing quantity on their website/app for the last 10 years because it's shown to increase orders by 2x. There should be a toggle on the Shopify dashboard to turn this functionality off if the store is getting spammed. Or better yet...... add a captcha on checkout rather than removing core functionality from the API 😂

Anyways thanks for getting back to me so quickly!
