### ISSUE TITLE
Blank sample app

### ISSUE THREAD

**Issue by dbart01** [Shopify/mobile-buy-sdk-ios#512]

**Comment by JaydeepPatel** [comment]
@dbart01 
Hello Sir,

I am totally New In iPhone andShopify,
So, I already done with Login and SignUp API.
But Now I want to implement ForgotPassword API.
I know this is the URL For recoverPassword,

self.client = [[BUYClient alloc] initWithShopDomain:app.SHOP_DOMAIN
apiKey:app.API_KEY
appId:app.APP_ID];

    [self.client recoverPasswordForCustomer:txtEmail.text callback:^(BUYStatus status, NSError * _Nullable error) {
        if (!error){
            NSLog(@"NO ERROR");
        }else{
            NSLog(@"Failed to create customer: %@", error.userInfo);
        }
    }];
I am getting this error,
Error Domain=BUYShopifyErrorDomain Code=404 "(null)"

Failed to create customer: {
}

But, I don't Know how to use in Objective-C in iPhone Development code.

So, Please Help me.

Thank x in Advance
