### ISSUE TITLE
BUYApplePayPaymentProvider Incorrectly Calls paymentProviderWantsControllerDismissed

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#517]
`BUYApplePayPaymentProvider` appears to call `paymentProviderWantsControllerDismissed` on its delegate in `paymentAuthorizationDidFinish`. However, the `PKPaymentAuthorizationController` was already dismissed within the `paymentAuthorizationControllerDidFinish` delegate implementation.

https://github.com/Shopify/mobile-buy-sdk-ios/blob/2.2.0/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Payment%20Providers/BUYApplePayPaymentProvider.m#L267

https://github.com/Shopify/mobile-buy-sdk-ios/blob/2.2.0/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Payment%20Providers/BUYApplePayPaymentProvider.m#L324

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.
