### ISSUE TITLE
recoverPasswordForCustomer

### ISSUE THREAD

**Issue by JaydeepPatel** [Shopify/mobile-buy-sdk-ios#518]
Hello Sir,

I am totally New In iPhone andShopify,
So, I already done with Login and SignUp API.
But Now I want to implement ForgotPassword API.
I know this is the URL For recoverPassword,

self.client = [[BUYClient alloc] initWithShopDomain:app.SHOP_DOMAIN
                                                     apiKey:app.API_KEY
                                                      appId:app.APP_ID];
        
        [self.client recoverPasswordForCustomer:txtEmail.text callback:^(BUYStatus status, NSError * _Nullable error) {
            if (!error){
                NSLog(@"NO ERROR");
            }else{
                NSLog(@"Failed to create customer: %@", error.userInfo);
            }
        }];

I am getting this error,
**Error Domain=BUYShopifyErrorDomain Code=404 "(null)"**

**Failed to create customer: {
}**

But, I don't Know how to use in Objective-C in iPhone Development code.

So, Please Help me.

Thank x in Advance.

**Comment by dbart01** [comment]
What is the `shopDomain` that you're passing to `BUYClient`? It should be of this format: `your-shop-name.myshopify.com` where `your-shop-name` is the name of your shop.

**Comment by JaydeepPatel** [comment]
@dbart01  yes, I already pass that like ,

self.client = [[BUYClient alloc] initWithShopDomain:app.SHOP_DOMAIN
                                                     apiKey:app.API_KEY
                                                      appId:app.APP_ID];
