### ISSUE TITLE
didCompleteCheckout Called Twice During Apple Pay Checkout

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#519]
When performing an Apple Pay checkout using version 2.2 of the SDK, we're seeing duplicate calls to `paymentProvider:didCompleteCheckout:withStatus:` passing identical parameters in.

After placing a few breakpoints, the root of the issue appears to be that `paymentAuthorizationControllerDidFinish:` ([source link](https://github.com/Shopify/mobile-buy-sdk-ios/blob/2.2.0/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Payment%20Providers/BUYApplePayPaymentProvider.m#L322)) is being called twice. However `paymentAuthorizationController:didAuthorizePayment:completion:` is only called once.

Whether or not this is an iOS bug or not, I have yet to be able to determine.

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.
