### ISSUE TITLE
Web checkout for product using Recharge

### ISSUE THREAD

**Issue by tadadev** [Shopify/mobile-buy-sdk-ios#531]
We have a product that is set as free ($0.00), but if not returned within x days will incur a charge.  We're using the Recharge App to do this.  Normally when a customer buys this product online, the checkout goes through the Recharge portal.  When using the modile-buy-sdk, it does not, and therefore never asks the customer for credit card information.

Is this possible using the sdk?

**Comment by bgulanowski** [comment]
I suggest you talk to the developers of the app. We don't provide any explicit support for integrations with apps.
