### ISSUE TITLE
How to cache Shopify cart items?

### ISSUE THREAD

**Issue by JaydeepPatel** [Shopify/mobile-buy-sdk-ios#539]
Hi I'm using mobile buy sdk to integrate Shopify in my app. I add product to the cart by using [self.cart addVariant:self.productVariant]; 

And i get all item in lineitem object. 

But my problem is whenever I close and open the app means cart shows empty. 
How to overcome this problem?. 

Thanks in advance.

**Comment by davidmuzi** [comment]
For help, please post questions on our forum, in the Shopify APIs & Technology section: https://ecommerce.shopify.com/c/shopify-apis-and-technology

**Comment by JaydeepPatel** [comment]
@davidmuzi ,
Yes sir,
So check now please,
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/how-to-cache-shopify-cart-items-419876
