### ISSUE TITLE
Storing Credit cards to Shopify but how to retrieve those cards info

### ISSUE THREAD

**Issue by ksingh65** [Shopify/mobile-buy-sdk-ios#558]
Hi,

We are storing a card using, Store Card method:
- (NSOperation *)storeCreditCard:(BUYCreditCard *)creditCard checkout:(BUYCheckout *)checkout completion:(BUYDataCreditCardBlock)block

Is there a way to get Stored credit card info, just like stripe provides?

**Comment by bgulanowski** [comment]
Storing the card only applies to the checkout. You can then use the returned token to use the card as a payment method for the checkout, and complete the checkout.

You cannot store credit cards for later use on other checkouts.

**Comment by deekshibellare** [comment]
I have saved cards in stripe, I want to charge the customer using those cards and then update the checkout. Is there any way we can do it in the SDK?

**Comment by bgulanowski** [comment]
No, we don't provide access to Stripe features, we provide access to Shopify features. Perhaps Stripe has an SDK you can use.
