### ISSUE TITLE
ShippingRates not getting in Shopify SDK

### ISSUE THREAD

**Issue by JaydeepPatel** [Shopify/mobile-buy-sdk-ios#560]
I am working on shopify SDK in iOS app.
And i also check this #43 .
So, what the best solution i don't know.
I want to get shipping rates. when I call this method: 

- (NSOperation *)getShippingRatesForCheckoutWithToken:(NSString *)checkoutToken completion:(BUYDataShippingRatesBlock)block
{
    BUYAssertToken(checkoutToken);

    NSURL *url  = [self urlForCheckoutsShippingRatesWithToken:checkoutToken parameters:@{
                                                                                          @"checkout" : @"",
                                                                                          }];

    BUYRequestOperation *operation = (BUYRequestOperation *)[self getRequestForURL:url start:NO completionHandler:^(NSDictionary *json, NSHTTPURLResponse *response, NSError *error) {
        NSArray *shippingRates = nil;
        if (json && !error) {
            shippingRates = [self.modelManager insertShippingRatesWithJSONArray:json[@"shipping_rates"]];
        }

        block(shippingRates, [self statusForStatusCode:response.statusCode error:error], error);
    }];

    operation.pollingHandler = ^BOOL(NSDictionary *json, NSHTTPURLResponse *response, NSError *error) {
        return response.statusCode == BUYStatusProcessing;
    };

    [self startOperation:operation];
    return operation;
}

**Then, response is like**:
<NSHTTPURLResponse: 0x6000004266c0> 
{ URL: https://3abbas.myshopify.com/api/checkouts/4f9d202e6998631042d9a519c6b05cc3/shipping_rates.json?checkout=
 } 
{ 
status code: 412, headers
 }

**and:**
Error Domain=BUYShopifyErrorDomain Code=412 "(null)" UserInfo={errors={
    checkout =     {
        "shipping_address" =         (
                        {
                code = blank;
                message = "can't be blank";
                options =                 {
                };
            }
        );
    };
}}
How can I get the shipping rates? Can I pass static shipping rates in checkout?
I don't know hoe to get the shipping rates. Please Give me Proper Solutions.

Thank x In Advance.

**Comment by bgulanowski** [comment]
Shipping rates depend on the destination address. The error you got calls out that you didn't include the shipping address, so Shopify can't calculate the rates for you.

Make sure you set the `shippingAddress` property on the checkout to a valid address before requesting shipping rates.

**Comment by JaydeepPatel** [comment]
@bgulanowski  thank x for your good response. But,
i already set the address Like,
- (BUYAddress *)address
{
    BUYAddress *address = [self.client.modelManager insertAddressWithJSONDictionary:nil];
    address.address1 = @"150 Elgin Street";
    address.address2 = @"8th Floor";
    address.city = @"Ottawa";
    address.company = @"Shopify Inc.";
    address.firstName = @"Egon";
    address.lastName = @"Spengler";
    address.phone = @"1-555-555-5555";
    address.countryCode = @"CA";
    address.provinceCode = @"ON";
    address.zip = @"K1N5T5";
    return address;
}

**Comment by bgulanowski** [comment]
If you want to debug this properly, you should go lower in the stack. That code you just copied and pasted doesn't prove anything.

You should log and inspect the JSON body that you are submitting to Shopify as part of the request. That's where the problem is, so that's where you should start.

**Comment by JaydeepPatel** [comment]
@bgulanowski  sir, Please here we can't talk more here. So, Please Can u give me the email id ?

**Comment by bgulanowski** [comment]
No, I'm sorry.

But you're right. This isn't a forum. You should keep discussions to the ecommerce forums on Shopify.
