### ISSUE TITLE
Remove specific variant from the existing checkout

### ISSUE THREAD

**Issue by hitendradeveloper** [Shopify/mobile-buy-sdk-ios#563]
I want to remove reservation of the specific items.

1. let's say there are 5 product variants[v1,v2,v3,v4,v5] available in the cart -> created checkout[C1]. (we are saving the checkout token, not doing anything with cartToken)
2. The customer did not complete the checkout and deleted the variant v3,v4 from the mobile application cart. and tried to initiate checkout form the cartView
3. what we are doing as of now is, remove the reservation of the existing checkout using the checkoutToken, method: `removeProductReservationsFromCheckoutWithToken: completion:`

Requirement: we don't want to release all the product/variant from the last checkout, we only want to remove the variant v3,v4 which are deleted, and update the checkout with variant/products v1,v2.v5 to complete the checkout. 

What we have tried:
- We tried to update the existing checkout with the older token and new cart[v1,v2,v5].
- used the method `updateOrCreateCheckout: completion:`, but it does not release the older reserved product/variant[v3,v4].

How can we do that without creating the new checkout?

Any help or hint will be appreciated.
Thanks in advance.

**Comment by hitendradeveloper** [comment]
Here are the flow we have mentioned in the above comment so you can understand if not clear enough.

![screen shot 2017-04-07 at 2 30 56 pm](https://cloud.githubusercontent.com/assets/9197369/24793406/85ffaab8-1b9f-11e7-86eb-f01c13b7c795.png)

![screen shot 2017-04-07 at 2 31 08 pm](https://cloud.githubusercontent.com/assets/9197369/24793407/868a4862-1b9f-11e7-801d-7918554fcb05.png)

**Comment by hitendradeveloper** [comment]
@bgulanowski | Team Shopify
Is there any update on this?

**Comment by bgulanowski** [comment]
There will not be any changes to this functionality in this version of the SDK. I'm sorry, but I think you'll have to continue to use your workaround. Perhaps it will be revisited in version 3.

**Comment by hitendradeveloper** [comment]
@bgulanowski Thanks for the response. 
Looking forward to this improvement in version 3.
