### ISSUE TITLE
How to Get Shipping Rates at the time of checkout

### ISSUE THREAD

**Issue by rushabh0999** [Shopify/mobile-buy-sdk-ios#571]
Hello,
I want to insert shipping rates in billing price so I have pass address object in checkout object below code I am using it .

```
- (void)checkoutWithShopify
{
    self.checkout = [self checkoutWithVariant:self.selectedProductVariant];
  self.checkout.shippingAddress = [self address];
self startWebCheckout:self.checkout];
}

```

**Comment by JaydeepPatel** [comment]
@bgulanowski I have same issue...So, Help and guide in Proper Way...

**Comment by bgulanowski** [comment]
Did you try `-[BUYClient getShippingRatesForCheckoutWithToken:completion:`?

The completion will return you an array of `BUYShippingRate` objects.

**Comment by rushabh0999** [comment]
@bgulanowski Thanks for yr promt response but i tried using getShippingRatesforCheckoutwithToken method still i am not getting shipping rates can you plz help me !!!!

**Comment by bgulanowski** [comment]
You're going to have to provide a lot more detail.
