### ISSUE TITLE
Logout Crash

### ISSUE THREAD

**Issue by blackshrub** [Shopify/mobile-buy-sdk-ios#608]
The crash is in Buyclient+routing.

So when I logged in --> close app --> reopen the app (must update the accesstoken), but the accesstoken result is "nil". Although I have set to autologin, the logout result in 401 error.

Run build #1:
1. Login
2. Success, back to account page
3. Logout
4. Success

Run build #2:
1. Login
2. Success, back to account page
3. Kill app
4. Reopen the app, logged out --> crash

Run build #3:
1. Login
2. Success, back to account page
3. Kill app
4. Reopen the app
5. Auto login
6. Go to account page
7. Logout --> 401 response

The logout call:
![5a7b3c20-9bcf-4a83-ae3e-6802c69bee35](https://cloud.githubusercontent.com/assets/12421725/26433300/113ce3aa-412c-11e7-9a9a-1607808a6987.jpeg)

The crash:
![9991f88e-5a7c-4339-aeca-eec588a730b2](https://cloud.githubusercontent.com/assets/12421725/26433293/01b15b64-412c-11e7-819d-98c8a0cf4fe1.jpeg)

**Comment by dbart01** [comment]
No longer relevant in `v3.0`.
