### ISSUE TITLE
Swift Sample Application Fails to Build: No such file - GraphQL.swift

### ISSUE THREAD

**Issue by bdpluim** [Shopify/mobile-buy-sdk-ios#624]
Trying to get the Storefront sample application working, but it looks like the GraphQL.swift file is not included in the repo.  

I've downloaded the application, added the Mobile Sales Channel, and modified the Client.swift file, but xCode says I'm missing a file. 

```
<unknown>:0: error: no such file or directory: '/Users/bpluim/Code/Sandbox/mobile-buy-sdk-ios/Dependencies/Swift Gen/support/Sources/GraphQL.swift'

Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**Comment by bdpluim** [comment]
Looks like a simple dependency problem.  I fixed it by just recreating the project and pulling in the frameworks that were pre-built (using Carthage) but it was a bit annoying.

**Comment by dbart01** [comment]
The Buy SDK uses `graphql_swift_gen` submodule. Sounds like you needed to run `got submodule update` to fetch the missing dependency. The installation instructions should probably reflect that. Thanks for pointing that out!

**Comment by mars47** [comment]
> The Buy SDK uses `graphql_swift_gen` submodule. Sounds like you needed to run
> 
> ```
> git submodule update --init --recursive
> ```
> Doing so will clone and update the missing dependency. The installation instructions should probably reflect that. Thanks for pointing that out!

Hi, I am having the same problem. I've never used Carthage, only CocoaPods.

Running: ```git submodule update --init --recursive``` doesn't seem to do anything fo me

**Comment by dbart01** [comment]
@mars47 Your build is failing using CocoaPods? What are the errors you're seeing?

**Comment by mars47** [comment]
I have been following the installation guidelines and tried to build the Storefront sample app. When i build i get this: 

![screen shot 2019-02-20 at 16 20 14](https://user-images.githubusercontent.com/16666188/53106875-d9799300-352b-11e9-8c18-03a5d3b06f3e.png)
