### ISSUE TITLE
V 1.2.2 - Module 'Buy' STILL not found?

### ISSUE THREAD

**Issue by brittanyblair** [Shopify/mobile-buy-sdk-ios#63]
Hey all -

I've downloaded V1.2.2, and when I drag Mobile Buy SDK.xcodeproj into my existing project, add Buy to my target dependencies and embedded frameworks, I still get the "Module Buy not found" when I try importing it into my ViewController header? 

I've double checked the podspec file, and the module name is correct. 

Help :/

**Comment by runmad** [comment]
If you are embedding the project into your own Xcode project the podspec file isn't relevant. Are you using Cocoapods?

Ensure that you have added the `Buy` framework (not `Buy Static`) to your Target Dependencies in the target's Build Phases. Then, in Embedded Binaries, add the Buy.framework. Two will be listed, pick the second one, which is the dynamic framework.

You can also refer to the Advanced Sample App, which embeds the dynamic framework.

**Comment by brittanyblair** [comment]
@runmad Thanks for the quick response! I have the Buy framework (not static) added to my Target Dependencies. In Embedded Frameworks (I don't see an Embedded Binaries heading), I've added the Buy.framework (the second one). I then pop into my viewcontroller, and type: @import Buy; 

It then throws me the module not found error. I'm not using pods.

**Comment by runmad** [comment]
Here are the steps with a new Xcode project I just tested with 1.2.2:

1. Drag the Mobile Buy SDK Xcode project into yours:
<img width="261" alt="screen shot 2015-11-19 at 3 34 31 pm" src="https://cloud.githubusercontent.com/assets/708741/11283525/2f033112-8ed3-11e5-9f88-fff92bafdf16.png">

2. Add the **dynamic framework** to Target Dependencies in your target's Build Phases: 
<img width="1072" alt="screen shot 2015-11-19 at 3 34 51 pm" src="https://cloud.githubusercontent.com/assets/708741/11283533/37392e18-8ed3-11e5-94a4-4f4ec207cc0b.png">
<img width="1072" alt="screen shot 2015-11-19 at 3 35 01 pm" src="https://cloud.githubusercontent.com/assets/708741/11283541/3d69f1fa-8ed3-11e5-8fa4-64e6315999e3.png">

3. In General, Embedded Binaries, add the framework (pick the second one on the list):
<img width="1072" alt="screen shot 2015-11-19 at 3 35 15 pm" src="https://cloud.githubusercontent.com/assets/708741/11283543/433ef670-8ed3-11e5-8164-24093b98009c.png">

4. Build will include the SDK and succeed:
<img width="1072" alt="screen shot 2015-11-19 at 3 35 28 pm" src="https://cloud.githubusercontent.com/assets/708741/11283546/477300e2-8ed3-11e5-82a5-d2cc5a45d317.png">

**Comment by runmad** [comment]
Just to be clear, **Embedded Frameworks** in Build Phases will happen automatically. You need to add the framework to **Embedded Binaries** which can be found in the General tab of your target's settings.

**Comment by brittanyblair** [comment]
@runmad So strange - I do the above, build, and it's included. Now when I type @import Buy; it even autocompletes, but the error says "Could not Build module Buy".

**Comment by runmad** [comment]
Even if you do a Clean + Build?

**Comment by ollieatkinson** [comment]
@brittanyblair can you provide a sample project where it is not working for you?

**Comment by brittanyblair** [comment]
@runmad Yep, even then. When I build, it tells me Buy was built successfully along with the rest of my app. The minute I add that line in the header, i get "Could Not Build module Buy" highlighted in red.

**Comment by runmad** [comment]
Your product builds successfully, it's an Xcode bug that you're still seeing the error. If you restart Xcode and built the error will go away.

**Comment by brittanyblair** [comment]
@runmad Bloody XCode. Just restarted, issue is gone. THANK YOU. That was driving me absolutely mental. Cheers.

**Comment by runmad** [comment]
No worries, glad it worked out. I see this all the time. Xcode builds successfully, but 3rd party framework shows up with an error  :angry:  Restart always fixes it :tada:

**Comment by alvinwoon** [comment]
Just want to leave a note to those who are still having issues building Buy sdk.

Go to Build Settings and set "Allow Non-modular Includes in Framework Modules" to Yes.

**Comment by JaydeepPatel** [comment]
@runmad  thank you man... For your Steps...
