### ISSUE TITLE
Framework incorrectly requires iOS 10

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#636]
The framework builds fine on iOS 9.

**Comment by dbart01** [comment]
The `Pay` target requires `PKPaymentAuthorizationController`, which is only available on iOS 10. Granted, the `Buy` target is independent and can potentially be made available on iOS 9.0 and lower.

**Comment by calebd** [comment]
Ah you're right. I only changed the `Buy` target floor when I was testing. I think this might be the kick we need to drop 9. 👍
