### ISSUE TITLE
Graph QL interface for product.images returns image in incorrect order.

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#638]
The images we get back from `product.images` often do not match the sort order we see in Shopify admin. This is not true for every product, but it is for many. This is true regardless of how many images we fetch when requesting products.

**Comment by dbart01** [comment]
@xuorig seems similar to the issue we saw with product order in collections. Products don't have a `sortKey` parameter either. Seems like a GraphQL issue?

**Comment by calebd** [comment]
I don't necessarily need a shorting key on images. I always want them in the order our shop editors specify. If you do add that, maybe the default case is "sorted the way they are in the admin UI".

**Comment by dbart01** [comment]
This was an issue on the API side and has been fixed. The issue should now be resolved.
