### ISSUE TITLE
No price in BUYProduct class?

### ISSUE THREAD

**Issue by brittanyblair** [Shopify/mobile-buy-sdk-ios#64]
I'm loading my products to my Table View Controller, with product details in each cell (works great - e.g. title, htmlDescription, etc) - but is there no string to display the price in the Product List Controller? Eg.  cell.productDescrip.text = product.price ? I'm asking this ridiculous question because when I try running the Sample App in the simulator, it simply crashes, and there is no documentation stating what can/can't be referenced other than this: 

http://cocoadocs.org/docsets/Mobile-Buy-SDK/1.2.2/Classes/BUYProduct.html#overview 

And still no mention of price... O_O

**Comment by runmad** [comment]
Products do not have prices. Please refer to the variants on the product, which have prices:

https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/BUYProductVariant.h#L55

**Comment by brittanyblair** [comment]
Hey @runmad - thanks for letting me know! Though when I implement this, no matter what I do, my variant.price seems to be returned as null? Even double checked my Shopify account to make sure prices are in place. P.S. - thanks for putting up with my newb-ness :) Your help is so appreciated.

.h 
@property (nonatomic, strong) BUYProduct *detailedProduct;
@property (nonatomic, strong) BUYProductVariant *variant;

.m

BUYProductVariant *variant = self.detailedProduct.variants[indexPath.row];
cell.priceLabel.text = [NSString stringWithFormat:@"%@", variant.price];

NSLog(@"%@", variant.price);
