### ISSUE TITLE
Releasing Inventory Reservations w/ SDK 3.0

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#644]
In previous versions of the SDK, there was a way to extend or release the reservation on inventory held by a checkout. However, I do not see any way in the 3.0 (GraphQL) SDK to do this.

Is this an oversight, or are checkout reservations a thing of the past?

**Comment by dbart01** [comment]
It is not an oversight. The removal of "inventory release" is intentional and is no longer part of the storefront API.

**Comment by cocoahero** [comment]
So in our user flows, if a user cancels a checkout, there's no longer a way for us to pro-actively release the inventory? It's stuck for however long the reservation time is?

**Comment by dbart01** [comment]
The concept of reservation is removed entirely. The clients no longer have the burden of reservations or releasing them.

**Comment by cocoahero** [comment]
So imagine a limited inventory product (less than 10), that is highly sought after. A user of our app starts a checkout via Pay, but then cancels. That quantity of inventory is now caught up in limbo, reserved for an unknown, Shopify internally set amount of time, unable to be purchased by anyone.

The ability for us to pro-actively release that inventory is crucial given that a product might now appear to be sold out for say 5 minutes, even though it is not. Given enough aborted Pay checkouts, the entire inventory could be effectively caught in limbo, denying other customers everywhere the chance to purchase.

😕
