### ISSUE TITLE
Demo App Select Product Options

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#646]
The demo app currently only displays each product with its lowest price variant and ignores all other variants and selected options. We had written some fairly complex logic around the relationship between product, options, and variants to allow the user to select options. It would be nice to see an example of how Shopify thinks about those relationships with respect to the SDK and the way it structures data.

**Comment by chasemac** [comment]
I would also like to see how Shopify recommends adding variants to the app. I haven't written any code for this yet, but plan to soon, and I would like whatever help anyone is willing to contribute. Thanks!

**Comment by dbart01** [comment]
We currently have no plans to implement this in the sample app. Closing for now.
