### ISSUE TITLE
Inconsistent Field Optionality

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#648]
I've noticed a few fields that are marked as optional which is inconsistent with other parts of the SDK.

- `Storefront.Image.id` is a `GraphQL.ID?` while other entities have a `GraphQL.ID` instead.
- `Storefront.Order.email` is a `String?` but as far as we can tell it is not possible to create an order without a valid email address.
- `Storefront.ProductVariant.available` is a `Bool?` which makes it cumbersome to consume. (Additionally this could be named `isAvailable` to match Swift conventions, though I understand that it would no longer match the Graph QL field name. I could go either way on this one.)

**Comment by dbart01** [comment]
Thanks for surfacing these concerns. As these are GraphQL schema improvements, we'll have to investigate further on our end.

**Comment by rebeccajfriedman** [comment]
> Storefront.Image.id is a GraphQL.ID? while other entities have a GraphQL.ID instead.

You're right. This is, unfortunately, unlikely to change.

> `Storefront.Order.email` is a `String?` but as far as we can tell it is not possible to create an order without a valid email address.

Shopify supports creating an order with a phone number and no email address. While this is not currently supported in the Storefront API, we may want to in the future, and have left the email field as optional.

> Storefront.ProductVariant.available is a Bool? which makes it cumbersome to consume. (Additionally this could be named isAvailable to match Swift conventions, though I understand that it would no longer match the Graph QL field name. I could go either way on this one.)

This has since been updated to `availableForSale` which is not an optional value.
