### ISSUE TITLE
Where do you get the appId? 

### ISSUE THREAD

**Issue by Meeks91** [Shopify/mobile-buy-sdk-ios#649]
Where do you get the appId? 

I've seen  '8' being used as the appId but is that just being used for demonstrative purposes or should we actually use that id for all apps?

Thanks in advance.

**Comment by dbart01** [comment]
`appID` applies only to `v2.x` of the SDK and is a static value. We encourage you to upgrade to the latest version of the SDK where that value no longer applies.

**Comment by Meeks91** [comment]
Thanks for your response. I am using the latest version of the SDK using the 'Mobile-Buy-SDK' cocoa pod. it's still requiring me give an appId when creating an instance of the BuyClient.

How do I upgrade to the latest version? 

Also, where is the latest documentation? It still says on this page https://help.shopify.com/api/sdks/custom-storefront/mobile-buy-sdk/ios/integration-guide/setup that we have to use the appId?

Cheers

**Comment by dbart01** [comment]
This is the [latest release](https://github.com/Shopify/mobile-buy-sdk-ios/releases/latest).

CocoaPods support is coming in `v3.0.2` and isn't yet available. Alternatively, you can use the latest version via [Carthage](https://github.com/Shopify/mobile-buy-sdk-ios#carthage-) or [manual installation](https://github.com/Shopify/mobile-buy-sdk-ios#dynamic-framework-installation-).

The complete documentation is available on [repo's home page](https://github.com/Shopify/mobile-buy-sdk-ios).

**Comment by Meeks91** [comment]
Ok.

Thanks for your help.
