### ISSUE TITLE
Checkout won't update - UIButton unresponsive

### ISSUE THREAD

**Issue by brittanyblair** [Shopify/mobile-buy-sdk-ios#65]
I'm trying to update my CheckOut with shipping/address details, and when I tap my UIButton it's completely unresponsive. I've logged the cart, and my selected object is present. Is there a field I'm missing in terms of the saveAddress button? Tapping the button doesn't even throw me my logs (success or error). 

Follow up question: Does Shopify have a console of some sort that generates a backend report?

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view from its nib.
    
    self.cart = [BUYCart singleton];
     NSLog(@"%@", cart);
    
    BUYCheckout *checkout = [[BUYCheckout alloc]initWithCart:self.cart];
    BUYClient *client = [BUYClient singleton];
    
    [client createCheckout:checkout completion:^(BUYCheckout *checkout, NSError *error) {
        if (error == nil) {
            self.checkout = checkout;
        } else {
        //    [self controller:self failedToCreateCheckout:error];
        }

    }];

- (IBAction)saveAddress:(id)sender {
    
    BUYAddress *details = [[BUYAddress alloc] init];
    details.firstName = @"Brittany";
    details.lastName = @"Blair";
    details.address1 = @"1111 Beach Street";
    details.city = @"Vancouver";
    details.province = @"BC";
    details.zip = @"000000";
    details.countryCode = @"CA";
    
    self.checkout.shippingAddress = details;
    self.checkout.billingAddress = details;
    self.checkout.email = @"brittany@mail.ca";

    NSLog(@"%@", cart);
    
    [client updateCheckout:self.checkout completion:^(BUYCheckout *checkout, NSError *error) {
        if (error == nil) {
            self.checkout = checkout;
            NSLog(@"SUCCESS");
        } else {
          NSLog(@"FAIL");
        }
    }];

}

**Comment by ravulamanjula** [comment]
did you resolved this issue , same problem i am getting , its not enter into block of createCheckout:checkout
