### ISSUE TITLE
how can i integrate facebook login in shopify sdk?

### ISSUE THREAD

**Issue by maulikshah09** [Shopify/mobile-buy-sdk-ios#651]
I have implemented shopify in my app but now client need to login with facebook in my app? I have implement facebook sdk in my app?

now how to login in shopify ?

**Comment by dbart01** [comment]
The Buy SDK provides a `mutation` for obtaining a customer access tokens. It does not provide integration with Facebook. 

__Please keep in mind that GitHub issues are reserved for *problems* or *issues* with the SDK. General help questions should be posted on [our forum](https://ecommerce.shopify.com/c/shopify-apis-and-technology).__
