### ISSUE TITLE
Product returned as <BUYProductVariant: 0x161803390>, how can I make this readable?

### ISSUE THREAD

**Issue by brittanyblair** [Shopify/mobile-buy-sdk-ios#66]
I've retrieved my product from Shopify, and the console returns it to me as: 

BUYProductVariant: 0x161803390

I'm trying to display this product variant in my UILabel, how can I make it readable to my user (instead of that gibberish, lol)? Cheers.

**Comment by runmad** [comment]
Hi @brittanyblair, please have a look at our guidelines for opening tickets on our repo: https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/CONTRIBUTING.md

I know you closed the issue, but unfortunately we cannot provide help for questions like this as it's not an issue with the SDK. If you're having problems with the SDK I suggest you have a look at the Advanced Sample App or consult the documentation.

Thanks ☺️
