### ISSUE TITLE
Cocoapods Issues

### ISSUE THREAD

**Issue by carrotalan** [Shopify/mobile-buy-sdk-ios#660]
Attempting to install using the Cocoapods instructions on the readme, yields the following results:

- Only attempts to install v2, regardless of what version is specified. Pod repo updated on my machine and reinstalled several times. Only way to install v3 is to use git url **and** specify 3.0.2 release tag.
- After install, GraphQLSwiftGen is missing (all references to GraphQL come up as undefined in the Buy framework and there is no dependancies folder) therefore it cannot build.

**Comment by carrotalan** [comment]
Update - my temporary workaround for the GraphQL issue this is to manually download the [GraphQLSwiftGen](https://github.com/Shopify/graphql_swift_gen) repository and put it in a folder called "Dependancies" inside "Pods/Mobile-Buy-SDK"

**Comment by dbart01** [comment]
> Only way to install v3 is to use git url and specify 3.0.2 release tag

We are currently working on this.

> `GraphQLSwiftGen` is missing

You'll need to specify `:submodules = true` in your `.podfile` since the Buy SDK uses submodules for the GraphQL Swift generator.

**Comment by carrotalan** [comment]
Thanks for the update @dbart01.

It would be useful just to add that bit to the readme if possible?
