### ISSUE TITLE
Crypto Target Issues

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#661]
> Version of the SDK are you using?

3.0.2

The Crypto target has several issues.

1) It is a separate target despite only being consumed by the `Buy` target. This means any app that uses the Shopfiy SDK (with Apple Pay like we do) has to load not 1 but 3 dynamic libraries. There is a fixed, per-library amount of time added to app launch for every library load. It is silly to force all consumers to add that time for the Crypto framework when it is only consumed by `Buy`. `Crypto` should be implemented directly in `Buy` and there should be no separate `Crypto` target.

2) Crypto exports un-namespaced Objective-C categories and methods. These names can collide with any private functions on extended types, or with other libraries that implement those same functions. The extensions on `NSData` and `NSString` should be named `ShopifyHash` and the methods should be prefixed with `shopify_md5` (or something similar). Exposing a plain `md5` method on either of those types can (and probably will in this case given how common those names are) cause problems for a lot of people.

3) The functions in `Hash.m` have incorrect nullability annotations. `-[NSString dataUsingEncoding:]` is `nullable` which means if `nil` is ever returned to the code in `Digest.swift`, Swift will crash.

**Comment by dbart01** [comment]
1. We felt that a standalone `Crypto` target was more maintainable and was best abstracted as a separate module. Are you noticing a measurable difference between loading 1 vs 3 dynamic libraries?
2. `Crypto` was intended to only be used internally within the `Buy` target and only from Swift. As far as I understand, the naming collisions can only occur if used with Objective-C (since Swift will automatically namespace by module).
3. Nice catch, we'll fix it.

**Comment by calebd** [comment]
> Are you noticing a measurable difference between loading 1 vs 3 dynamic libraries?

The extra load time is well documented by other Swift on iOS developers. And it's not just one extra framework, now that Buy and Pay are different frameworks, it's _three_ extra on top of the 20 frameworks and Swift support libraries we already load on boot. Why burden apps with an entire extra framework load for a pair of small functions that can easily be included in the larger library?

> As far as I understand, the naming collisions can only occur if used with Objective-C

Those symbols are loaded into the Objective-C runtime regardless. The bad side effect will still happen. And even Swift can't disambiguate between two symbols added in an extension on a shared type. If `String.md5` were public and I also had a `String.md5` where both were reachable in the same file, there is no syntax by which I can say which should be called.

**Comment by calebd** [comment]
As for the nullability annotation, the data is going through a hexadecimal formatter which I guess always returns UTF-8 compatible data. I've always implemented that to return `nullable` data but this may be case where we know better than the compiler. In that case I'd say leave it. 🤷‍♂️
