### ISSUE TITLE
checkoutCreate failed?

### ISSUE THREAD

**Issue by carrotalan** [Shopify/mobile-buy-sdk-ios#663]
Hi There,

I know this isn't for developer support - but i've been racking my brain with this for over 6 hours now.

Trying a basic checkout workflow, based on the documentation here and the Storefront Sample App in SDK 3.

I am failing at the first hurdle. My attempts to create a checkout result in the following error:

```
invalidQuery([
    MobileBuySDK.Graph.QueryError.Reason(message: "Argument \'input\' on Field \'checkoutCreate\' has an invalid value. Expected type \'CheckoutCreateInput!\'.", line: nil, column: nil),
    MobileBuySDK.Graph.QueryError.Reason(message: "Argument \'lineItems\' on InputObject \'CheckoutCreateInput\' has an invalid value. Expected type \'[CheckoutLineItemInput!]\'.", line: nil, column: nil),
    MobileBuySDK.Graph.QueryError.Reason(message: "Argument \'variantId\' on InputObject \'CheckoutLineItemInput\' has an invalid value. Expected type \'ID!\'.", line: nil, column: nil)
])
```

Now as far as I can see, I am providing the correct types. See here:

```objective-c   
        let client = Graph.Client(
            shopDomain: "REDACTED",
            apiKey:     "REDACTED"
        )
let lineItems = [
            Storefront.CheckoutLineItemInput(variantId: GraphQL.ID(rawValue: "41621230094"), quantity: 5)
        ]
        
        let checkoutInput = Storefront.CheckoutCreateInput(lineItems: lineItems)
    
        var pluginResult = CDVPluginResult(
            status: CDVCommandStatus_ERROR
        )
    
        let mutation = Storefront.buildMutation { $0
            .checkoutCreate(input: checkoutInput) { $0
                .checkout { $0
                    .id()
                }
                .userErrors { $0
                    .field()
                    .message()
                }
            }
        }
        
        //Send Checkout Object
        let checkoutTask = client.mutateGraphWith(mutation) { result, error in
            guard error == nil else {
                print("Error creating checkout object")
                print(error!)
                return
            }
...
```

I have tried so many variations of this, all with the same error. Could somebody please put me out of my misery.

Thanks in advance!

**Comment by dbart01** [comment]
What is the output of `String(describing: mutation)` in the console?

**Comment by carrotalan** [comment]
Thanks for the reply.

Output is:

`mutation{checkoutCreate(input:{lineItems:[{variantId:"41621230094",quantity:5}]}){checkout{id},userErrors{field,message}}}`

**Comment by dbart01** [comment]
That query looks correct. Could this be an internal issue @xuorig ?

**Comment by xuorig** [comment]
variant id does not look like a global id to me @dbart01 this would cause an error I believe.

**Comment by carrotalan** [comment]
The variant ID for my attempt above is from this URL:

/admin/products/10608216334/variants/41621230094

**Comment by dbart01** [comment]
Ahh yes, nice catch. @carrotalan a global ID is obtained from a query for product variants. You cannot just insert a numeric value. It is an opaque global identifier provided by GraphQL. And looks something like: `variantId: "L3ZhcmlhbnQvODM0Mjkz="`

**Comment by carrotalan** [comment]
I wondered why my ID looked so different to the placeholders in the example... Thought you guys were just being creative!

So have I missed something in the documentation?

Im new to GraphQL (like many people) so I don't know if this is just assumed knowledge that you need to get this via a query first whenever an ID is required. Or if this could be better integrated into the readme.

I will make a query for the global ID now and try again.

Thank you for your help so far.
