### ISSUE TITLE
Pay Framework

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#666]
I don't really understand the point of the `Pay` framework. It appears to be only thin wrappers around existing `PassKit` types and functionality, and it requires consumers do a lot of work to translate between `Pay` and `Buy` types. Why should I spend the time on an extra framework load if it doesn't add any value? Could it be integrated into the `Buy` framework (like it was before) and have deeper integration with the `Storefront` API? At this point I might skip `Pay` and use `PassKit` directly.

**Comment by dbart01** [comment]
As you might've noticed, GraphQL let's you request partial model information. PassKit requires specific fields to work with when it comes to shipping rates, addresses, etc. While it might seem logical to simply pass a `Storefront.MailingAddress` model to PassKit, it's entirely plausible to run into a scenario where the mailing address model only contains an `id` and nothing else, resulting in a crash. Using the `Pay` models ensure that all the necessary information is present for PassKit to do it's job. Decoupling it from `Buy` also allows us to easily swap the code generation layer with something else, for example - Apollo. The best practice that we'd recommend is writing extensions on models to do that mapping for you:
```swift
import Pay

extension Storefront.MailingAddress {
    var payAddress: PayAddress {
        return PayAddress(...)
    }
}
```

**Comment by davidmuzi** [comment]
Also, keeping them separate keeps `Buy` more portable so it could be used on tvOS or macOS

**Comment by calebd** [comment]
> Also, keeping them separate keeps Buy more portable so it could be used on tvOS or macOS

That's one way to approach it. It's easy to not include those files in the tvOS or macOS targets in both CocoaPods and Carthage and you would never have to think about which you want.

Libraries should abstract all this work away from me. All the time I have to spend making the fundamentals work at all is time I can't spend focusing on what makes my shop great.

**Comment by dbart01** [comment]
> Libraries should abstract all this work away from me. All the time I have to spend making the fundamentals work at all is time I can't spend focusing on what makes my shop great.

I completely agree but I'm not sure I understand what you mean by "all this work". Perhaps we can introduce some abstractions that would simplify the usage of the Buy SDK and make it easier to use. Is a separate `Pay` target your only concern?

**Comment by calebd** [comment]
A separate `Pay` target is a concern but not the only one. The extra load time each additional dynamic library adds to iOS application launch time is well documented.

My main concern is, even if `Pay` is a separate framework, why doesn't it depend on `Buy` and add all the common conversions you would need to perform Apple Pay check out? As it is right now, all of the types and functions in `Pay` only mirror types already available in `PassKit`. I'm paying a launch time cost to load a library that doesn't add anything new. Every consumer has to write code to convert between all the Apple Pay types in the two frameworks.

That said, I would love to see these two frameworks flattened into one. Only add the `Pay` files to the correct platform targets and ship public helper functions and initializers that can translate between them where appropriate. These changes will make both loading consuming the library much easier for all consumers.

**Comment by dbart01** [comment]
> The extra load time each additional dynamic library adds to iOS application launch time is well documented.

You can measure the load times using this environment variable in your scheme:

![screen shot 2017-06-28 at 11 53 16 am](https://user-images.githubusercontent.com/5244861/27647077-6d8c316a-5bf8-11e7-878f-0d429a5738d1.png)

This is the output for the sample application. We didn't see a measurable difference between linking to just `Buy` vs both:
```
Total pre-main time: 420.75 milliseconds (100.0%)
         dylib loading time: 364.31 milliseconds (86.5%)
        rebase/binding time:  21.66 milliseconds (5.1%)
            ObjC setup time:  10.88 milliseconds (2.5%)
           initializer time:  23.79 milliseconds (5.6%)
           slowest intializers :
             libSystem.B.dylib :   6.48 milliseconds (1.5%)
```

> why doesn't it depend on Buy and add all the common conversions you would need to perform Apple Pay check out?

This is an excellent idea and we've considered this in the past. We can revisit this approach in future releases.

**Comment by calebd** [comment]
Apple recommends having no more than a handful (they said 6 last year) of dynamic libraries. Swift itself already adds 5+. People are resorting to all kinds of tricks to make this better (https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea). Sure, an app that links two frameworks on top of the Swift libraries instead of just one will not have a noticeable difference. But most people aren't adding just two. They're adding 15. Why contribute to that? The _only_ benefit of distributing these libraries separately is on the library author side. No consumer will ever see a benefit from these being separate libraries. Why make that tradeoff?

**Comment by dbart01** [comment]
Based on our measurements, the added framework has negligible startup overhead but allows us to modularize this functionality for internal purposes. If you're concerned about startup times, another alternative is to compile these frameworks statically since Xcode Beta 5 now supports static Swift frameworks.
