### ISSUE TITLE
Error updating checkout shipping address with a PayPostalAddress.

### ISSUE THREAD

**Issue by calebd** [Shopify/mobile-buy-sdk-ios#670]
SDK Version: 3.0.2

The `Pay` framework vends a `PayPostalAddress` when the user selects a new address in an Apple Pay sheet. This address only has fields for `city`, `country`, `province`, and `zip`. Attempting to update a checkout with only those fields provided to a `Storefront.MailingAddressInput` results in the following errors from the API:

```
userErrors =     (
            {
        field =             (
            shippingAddress,
            lastName
        );
        message = "Last name can't be blank";
    },
            {
        field =             (
            shippingAddress,
            address1
        );
        message = "Address1 can't be blank";
    }
);
```

How is this expected to work? The sample app sends placeholder values for all `Storefront.MailingAddressInput` fields and ignores the `PayPostalAddress` completely.

**Comment by dbart01** [comment]
That is definitely an issue with the sample app. In order for the checkout to support partial address, you'll have to pass a flag on checkout creation:

```swift
let checkoutInput = Storefront.CheckoutCreateInput(
    lineItems: lineItems,
    allowPartialAddresses: true // This will allow updating the checkout with a partial address
)

let mutation = Storefront.buildMutation { $0
    .checkoutCreate(input: checkoutInput) { $0
        .checkout { $0
            .fragmentForCheckout()
        }
    }
}
```
