### ISSUE TITLE
Query Timeout

### ISSUE THREAD

**Issue by eddiewouldgo** [Shopify/mobile-buy-sdk-ios#672]
When I replaced the shop URL and API key with mine, the app fails to load with the following error.

```
Graph.QueryError: invalidQuery([Buy.Graph.QueryError.Reason(message: "Timeout", line: nil, column: nil)])
Failed to load collections: Optional(Buy.Graph.QueryError.invalidQuery([Buy.Graph.QueryError.Reason(message: "Timeout", line: nil, column: nil)]))
```

**Comment by dbart01** [comment]
Could you please provide the query that yields this error?

**Comment by eddiewouldgo** [comment]
The queryForCollections is returning nil, timing out.
I made sure my shop url and api key is correct, but it's not working. Does my shop have to be v3 compatible? I tested the v2 of the test buy app, and it worked on my shop.

func fetchCollections(limit: Int = 25, after cursor: String? = nil, productLimit: Int = 25, productCursor: String? = nil, completion: @escaping (PageableArray<CollectionViewModel>?) -> Void) -> Task {
        
        let query = ClientQuery.queryForCollections(limit: limit, after: cursor, productLimit: productLimit, productCursor: productCursor)
        let task  = self.client.queryGraphWith(query) { (query, error) in
            error.debugPrint()
            
            print("Query = : \(String(describing: query))")
            
            if let query = query {
                let collections = PageableArray(
                    with:     query.shop.collections.edges,
                    pageInfo: query.shop.collections.pageInfo
                )
                completion(collections)
            } else {
                print("Failed to load collections: \(String(describing: error))")
                print("Query = : \(String(describing: query))")
                completion(nil)
            }
        }
        
        task.resume()
        return task
    }


static func queryForCollections(limit: Int, after cursor: String? = nil, productLimit: Int = 25, productCursor: String? = nil) -> Storefront.QueryRootQuery {
        return Storefront.buildQuery { $0
            .shop { $0
                .collections(first: Int32(limit), after: cursor) { $0
                    .pageInfo { $0
                        .hasNextPage()
                    }
                    .edges { $0
                        .cursor()
                        .node { $0
                            .id()
                            .title()
                            .descriptionHtml()
                            .image { $0
                                .src()
                            }
                            
                            .products(first: Int32(productLimit), after: productCursor) { $0
                                .fragmentForStandardProduct()
                            }
                        }
                    }
                }
            }
        }
    }

**Comment by dbart01** [comment]
@mtaher Any thoughts on this?

**Comment by dbart01** [comment]
@eddiewouldgo It sounds like your query is too complex or requesting too much data. Try reducing the `limit` parameter for all entities in your query and see if that helps resolve the problem.
