### ISSUE TITLE
checkoutCompleteWithCreditCard not working?

### ISSUE THREAD

**Issue by carrotalan** [Shopify/mobile-buy-sdk-ios#673]
I have been trying to use the `checkoutCompleteWithCreditCard` method in SDK 3 all day with no success whatsoever.

I receive a "payment gateway is invalid" message. This shows no matter what gateway is used; PayPal, Shopify Payments (Test mode and normal), Bogus Gateway - all UK based.

The documentation on Credit Card based checkout appears to be very light in comparison to Apple Pay. For example, it appears merchantID is required even though this is not an Apple Pay transaction. The example also has Syntax errors and references other functions not named anywhere else in the guide or codebase, e.g.:

```swift let payment = Storefront.CreditCardPaymentInput(
    amount:         payCheckout.paymentDue,
    idempotencyKey: paySession.identifier,
    billingAddress: self.mailingAddressInputFrom(payAuthorization.billingAddress,
    vaultId:        token
)
```

Using `checkoutCompleteWithTokenizedPayment` with type set "credit_card" makes an attempt to perform the transaction, but ends up as an abandoned checkout with `Failed. Response code = 500. Response message = Internal Server Error.`and no further information. This again, does not matter what type of gateway is used.

Setting test to true always throws a not supported message, regardless of gateway.

I have also changed this from a Development Store to Paid plan as the Shopify Website guides are a bit flaky on whether you can take payments (even in test mode) in a Development Store - but still no change.

Here is the code/responses when using checkoutCompleteWithCreditCard with Shopify Payments on and Test Mode:

**Checkout Mutation Response**

```
{Checkout: ["note": <null>, "shippingLine": {
    handle = "shopify-Standard%20Shipping-0.00";
    price = "0.00";
    title = "Standard Shipping";
}, "totalPrice": 6.15, "email": REDACTED, "lineItems": {
    edges =     (
                {
            cursor = "eyJsYXN0X2lkIjoiYzhkNzA5MDc1MDkzYWY3ZjI3N2M5NjA3NWRmODk4NDMifQ==";
            node =             {
                quantity = 5;
                title = "Carrot Cake Slice";
                variant =                 {
                    id = "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MTYyMTIzMDA5NA==";
                    price = "1.23";
                };
            };
        }
    );
}, "subtotalPrice": 6.15, "currencyCode": GBP, "requiresShipping": 1, "totalTax": 1.03, "shippingAddress": {
    address1 = "REDACTED";
    address2 = REDACTED;
    city = REDACTED;
    country = "United Kingdom";
    firstName = Alan;
    lastName = "Card Test";
    phone = "<null>";
    province = "<null>";
    provinceCode = "<null>";
    zip = "REDACTED";
}, "id": Z2lkOi8vc2hvcGlmeS9DaGVja291dC8xZjYwN2M5NjNmNDVmYTA3MTA5MGEzOWQ4Mzk3M2QxZT9rZXk9NTVmNjMxNGU4ZTc5MDg2YjE0ZTNjNmYxZmY5YWUzNzI=, "paymentDue": 6.15, "taxesIncluded": 1]}
```

**Payment Mutation**
```
{payment{id,errorMessage,amount,idempotencyKey,creditCard{brand,expiryMonth,expiryYear,firstDigits,firstName,lastName,maskedNumber},transaction{amount,kind,status,test},ready},checkout{id,ready},userErrors{field,message}}}
```

**Payment Mutation Response**
```
{checkoutCompleteWithCreditCard(checkoutId:"Z2lkOi8vc2hvcGlmeS9DaGVja291dC9hNWU2NTViOGE3NDFmZmJlMTNiNDhjYTA3OGQ3NWQ4OT9rZXk9ZGE5N2Y1YjdhMDllNzcxNjVkZmQ2N2FjYjhjMjk2ZjI=",payment:{amount:"6.15",idempotencyKey:"C9CCA2D0-019D-4A06-B1C0-D70F5FBC41C9",billingAddress:{address1:"REDACTED",address2:"REDACTED",city:"REDACTED",country:"United Kingdom",firstName:"Alan",lastName:"Card Test",province:"REDACTED",zip:"REDACTED"},vaultId:"east-c4b1b9915cbb8f29250eca1950f3053a"})
```

**Checkout Complete with Credit Card Response**
```
["checkoutCompleteWithCreditCard": {
    checkout =     {
        id = "Z2lkOi8vc2hvcGlmeS9DaGVja291dC9hNWU2NTViOGE3NDFmZmJlMTNiNDhjYTA3OGQ3NWQ4OT9rZXk9ZGE5N2Y1YjdhMDllNzcxNjVkZmQ2N2FjYjhjMjk2ZjI=";
        ready = 1;
    };
    payment = "<null>";
    userErrors =     (
                {
            field =             (
                payment
            );
            message = "Payment gateway is invalid";
        }
    );
}]```

**Comment by dbart01** [comment]
Investigation has revealed that `Card.CreditCard` is providing incorrect serialization for the payload being passed to the vault server. A fix for this will be coming in `3.0.3`.

**Comment by dbart01** [comment]
@carrotalan Please considering checking out the above branch to see if it fixes the problem you've been experiencing.

**Comment by carrotalan** [comment]
Cheers @dbart01, will give this a go in a few hours and let you know

**Comment by carrotalan** [comment]
You're the man, works as intended 👍

**Comment by BScharbau** [comment]
We had the same issue. Switching to develop also worked for us. Do you have any plans when you will merge these changes into master?

**Comment by dbart01** [comment]
@BScharbau The [3.0.3 release](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.0.3) is now live.

**Comment by BScharbau** [comment]
Thanks, that helps a lot

**Comment by AmaniOS** [comment]
Hi @dbart01 I am getting the same issue in the latest update(3.1.3).

- some : <Mutation: ["checkoutCompleteWithCreditCard": {
   checkout =     {
       id = "Z2lkOi8vc2hvcGlmeS9DaGVja291dC8xNjU3OWY1YTA0NGMzYjc2YjRjZTAzNTk3YmU1ZjEzND9rZXk9YTZlNTVmOTJkY2I2ZjA5YjNmYWU4YWY2OGQ1MzI2ZGE=";
       ready = 1;
   };
   payment = "<null>";
   userErrors =     (
               {
           field =             (
               payment,
               creditCard
           );
           message = "Credit card is invalid";
       }
   );
}]>

**Comment by XaviMorenoM** [comment]
We're having the same issue right now, is there any way we can sort it out?

**Comment by pmironov** [comment]
Hi, @XaviMorenoM, have you managed to find the solution for this issue? I have the same one.

@dbart01, could you please advise on what am I doing wrong? I am creating the reactjs app.  I set all the required fields, vault the card (receive what looks like a valid vaultD), but always get "Payment gateway is invalid" response. 
**But.** If I use Postman to vault the same credit card (perform POST request to the vault URL), I receive the token that looks the same. And I am able to complete the payment. 
My gateway is (for testing) Bogus Gateway and I'm setting the card number to "1".

**Comment by dbart01** [comment]
@AmaniOS Please create a separate issue. This is a valid use case that we don't have a good solution for, at the moment. A separate issue will allow us to track progress and report any updates.

**Comment by dbart01** [comment]
@XaviMorenoM If you're getting the results you're expecting from Postman, sounds like there's something going on in your application code. I would double check that all of your assumptions are correct.
