### ISSUE TITLE
invalidQuery when fetching a product node by its id

### ISSUE THREAD

**Issue by Chandlerdea** [Shopify/mobile-buy-sdk-ios#674]
I am cloned the submodule of the SDK into my repository, and checked out the 3.0.2 tag. I am using the example from the README to fetch a product, and I am receiving an error from the SDK. The error is: 

`invalidQuery([Buy.Graph.QueryError.Reason(message: "Argument \'id\' on Field \'node\' has an invalid value. Expected type \'ID!\'.", line: nil, column: nil)])`

Here is my code:
```
    func fetchFromShopify(for productID: Int) {
        guard let data: Data = String(describing: productID).data(using: .utf8) else {
            return
        }
        let str: String = data.base64EncodedString()
        let nodeID: GraphQL.ID = GraphQL.ID(rawValue: str)
        let query = Storefront.buildQuery { $0
            .node(id: nodeID) { $0
                .onProduct { $0
                    .id()
                    .title()
                    .description()
                    .images(first: 10) { $0
                        .edges { $0
                            .node { $0
                                .id()
                                .src()
                            }
                        }
                    }
                    .variants(first: 10) { $0
                        .edges { $0
                            .node { $0
                                .id()
                                .price()
                                .title()
                                .availableForSale()
                            }
                        }
                    }
                }
            }
        }
        let task: Task = Graph.sharedClient.queryGraphWith(query) { (query: Storefront.QueryRoot?, error: Graph.QueryError?) in
            if let product: Storefront.Product = query?.node as? Storefront.Product, error == nil {
                print(product)
            } else if let unwrappedError: Graph.QueryError = error {
                print(unwrappedError)
            }
        }
        task.resume()
}
```
It seems that the API is expecting the node to pass the argument `ID` instead of `id`. Anyone seen this before?

**Comment by carrotalan** [comment]
I received this error when using an incorrect ID (e.g. the Shopify numeric ID) rather than a GraphQL id.

Can you show me the value of productID?

**Comment by dbart01** [comment]
@carrotalan is right. It looks like you're passing an incorrect value for `id`. The string should be an opaque GraphQL ID that looks like a base64 encoded string.

**Comment by Chandlerdea** [comment]
@carrotalan The value of `productID` is`9612464520`, which is an `Int`

**Comment by carrotalan** [comment]
You'll need to use another GraphQL query to get a GraphQL ID. The normal Shopify numeric ID is not what it requires.

For me, I used `productByHandle` and then `variantBySelectedOptions` to get a GraphQL ID for what I needed. See below:

`    
        let variantQuery = Storefront.buildQuery { $0
            .shop { $0
                .productByHandle(handle: "oreo-ice-cream-cake", { $0
                    .variantBySelectedOptions(selectedOptions: [
                        Storefront.SelectedOptionInput(name: "Pouring Cream", value: "Pouring Cream"),
                        Storefront.SelectedOptionInput(name: "Ice Cream", value: "Ice Cream")
                        ], { $0
                           .id()
                           .title()
                        }
                    )
                })
            }
        }`

**Comment by Chandlerdea** [comment]
The problem with that solution is that I only have the productID to go on. I don't have the title or name of the product to search with. The read me says that you can fetch a product by its id, and I am using their example code.

**Comment by carrotalan** [comment]
I agree @Chandlerdea, the readme just states ID - and anybody used to existing Shopify services and not used to GraphQL would assume it's the normal ID used everywhere else.

@dbart01 do you think it would be possible to just drop a line or two in the readme regarding the use of GraphQL IDs?

As far as I can see, `productByHandle` is the only way you can query a product as the SDK is suppose to be a way of presenting the products in the first place (via collections) so you would have the GraphQL ID naturally (correct me if im wrong there!).

Maybe Search might allow you to query by the "normal" Shopify ID?
https://github.com/Shopify/mobile-buy-sdk-ios#search-

**Comment by dbart01** [comment]
You're right @carrotalan , the README is a little sparse when it comes to documenting where the GraphQL IDs come from. We'll try to improve that in future releases. Closing this issue.

**Comment by Chandlerdea** [comment]
@dbart01 I'm still not clear on how to fix my issue. Are you saying that cannot create the GraphQL ID from a string?

**Comment by dbart01** [comment]
That's correct. GraphQL IDs are opaque strings. The values for any parameters that accept `ID` types should be initially provided by GraphQL. You cannot use a plain object ID such as `123456789` for this purpose.
