### ISSUE TITLE
Version 2.x support

### ISSUE THREAD

**Issue by ucerxxx** [Shopify/mobile-buy-sdk-ios#676]
Is objective-c version of SDK is still supported? 

As I see Swift version was merged in master and last Objective-C version was not moved in separate branch. We use Objective-C version of the SDK (we created the app right before Swift version was released) and there are an issue in it that should be fixed. To be clear the issue is posted as #665. I know the reason and can fix it. I want to make pull request with the fix, but the problem is that there are no custom branch for Objective-C version and it is senseless to make it to master.

May be you can create new branch for 2.x version? Even if you are not going to do something in it, it will be possible to add some fixes in it if someone want.

**Comment by dbart01** [comment]
We welcome contributions to support SDK 2.0! The legacy version of the SDK is already available on the following branches:
- `sdk-2.1/develop`
- `sdk-2.1/master`

Please ensure that your PR contributions are submitted to `sdk-2.1/develop`.
