### ISSUE TITLE
Cocoapods still shows 2.2.0 as the latest release

### ISSUE THREAD

**Issue by calebl** [Shopify/mobile-buy-sdk-ios#678]
https://cocoapods.org/pods/Mobile-Buy-SDK

The readme instructions to do not work for installing using cocoapods because the 3.0.* releases are not available through cocoapods yet.

**Comment by carrotalan** [comment]
This is currently amended in the develop branch:

https://github.com/Shopify/mobile-buy-sdk-ios/pull/664

If you manually target the Git url in your podfile, it will install the latest version

**Comment by dbart01** [comment]
CocoaPods has been updated to the latest version.
