### ISSUE TITLE
Checkout vaultUrl property from Card Vaulting example not in SDK

### ISSUE THREAD

**Issue by Chandlerdea** [Shopify/mobile-buy-sdk-ios#680]
I have the SDK as a git submodule, using version 3.0.2. I was reading through the READ ME Card Vaulting section, and the function `cardClient.vault(to:)` function expects a URL. The documentation says to use the `vaultUrl` property of the `Storefront.Checkout` object. But the `Storefront.Checkout` class doesn't have that property. Where am I supposed to get that URL from?

**Comment by dbart01** [comment]
This is actually an error on the documentation's part. The `vaultUrl` used to exist as a property on `Storefront.Checkout` but it has since moved to `cardVaultUrl` on `Storefront.Shop`.
