### ISSUE TITLE
Sales Channel Apple Pay Configuration Broken

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#684]
I've created a forum post for this incase this isn't the place to mention it, but I figured it would be good to shed light on it here. (https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/mobile-app-sales-channel-apple-pay-configuration-disabled-broken-452175)

Essentially, the Apple Pay configuration page in the Shopify admin for our store shows it as disabled, with no working way to re-enable it or to update the associated certificate.

After clicking the "Enable" button and doing a page refresh (because the button does nothing), it looks like this:

![screen shot 2017-07-10 at 11 23 11 am](https://user-images.githubusercontent.com/318265/28026166-42632b78-6563-11e7-986c-877eeaff78bc.png)

Not sure if this is localized to just our shop, or is for all stores after the SDK 3.0 / Storefront SDK switchover.

**Comment by mtaher** [comment]
Hey @cocoahero, can you try going through the workflow one more time?

**Comment by cocoahero** [comment]
@mtaher it now shows the proper merchant ID, which is great. Is there a way to update the associated certificate?

**Comment by mtaher** [comment]
Currently there's no way to update the existing certificate, the old one would have to revoked and a new one would have to be generated.

However, this is something we are taking a look at right now. We'll definitely provide an update once we have a fix.

**Comment by cocoahero** [comment]
@mtaher an update when you have one would be appreciated. We received an email from Apple letting us know that our current certificate expires in 30 days, so we will need something before then.

**Comment by mtaher** [comment]
hey @cocoahero, we updated the channel to allow the configuration of a second Apple Pay certificate. If you run into any issues, just let us know.
