### ISSUE TITLE
Documentation not clear on how to pay with a credit card

### ISSUE THREAD

**Issue by Chandlerdea** [Shopify/mobile-buy-sdk-ios#686]
I am using v3.0.2 as a submodule in my project. I am going through the documentation to see how I can complete a checkout with a credit card. After following the instructions to vault the credit card, the docs have this code example: 
```
// let paySession: PaySession
// let payCheckout: PayCheckout
// let payAuthorization: PayAuthorization

let payment = Storefront.CreditCardPaymentInput(
    amount:         payCheckout.paymentDue,
    idempotencyKey: paySession.identifier,
    billingAddress: self.mailingAddressInputFrom(payAuthorization.billingAddress,
    vaultId:        token
)
```
From what I understand, the idempotencyKey is the unique identifier of the `PaySession`, to keep from duplicating transactions. But your docs say that the `PaySession` object is used to complete transactions with Apple Pay. After looking through the SDK, it seems that I need to use a `PaySession` regardless of the payment option I am using. Is there a way I can get that `idempotencyKey` without the `PaySession`?

**Comment by dbart01** [comment]
Every instance of a `PaySession` has a unique identifier that can be used for the  `idempotencyKey` parameter. However, it isn't a requirement. If you're not using Apple Pay or you don't have an instance of `PaySession` handy, you can create a UUID yourself:
```swift
let uuid = UUID().uuidString
```
As long as you use the same UUID to process a payment within the same session, the transaction will be idempotent.

**Comment by Chandlerdea** [comment]
Awesome thank you.
