### ISSUE TITLE
Using checkoutCompleteFree

### ISSUE THREAD

**Issue by carrotalan** [Shopify/mobile-buy-sdk-ios#688]
How does one use the `checkoutCompleteFree` which I assume should let you process a checkout using an "alternative" payment method like cash on collection.

Calling it the same as `checkoutCompleteWithCreditCard`, minus the payment object returns an error:
`Optional(MobileBuySDK.Graph.QueryError.invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "Checkout requires payment.", line: nil, column: nil)]))`

The interface for `checkoutCompleteFree` seems to suggest that is all that is required, but there is no documentation anywhere else for this.

**checkoutCompleteFree Mutation**
```swift
let freeMutation = Storefront.buildMutation { $0
    .checkoutCompleteFree(checkoutId: checkout.id) { $0
        .checkout { $0
            .id()
            .ready()
        }
        .userErrors { $0
            .field()
            .message()
        }
    }
}
```
**checkoutCompleteFree Query**
```swift
        let freeTask = client.mutateGraphWith(freeMutation) { result, error in
            guard error == nil else {
                print("There was a system error");
                print(error as Any)
//This is where the above error appears
```

**Comment by dbart01** [comment]
What line items does the checkout contain? What's the checkout's subtotal?

**Comment by carrotalan** [comment]
I cant figure out how to print the contents of the line item, but it essentially contains a variant that costs £1.23 and quantity 1 and subtotal is £1.23

Reading the error again, am I right in thinking the error is telling me because there is a subtotal, it cannot process it as "free"?

If so, my follow up question would be - how do you process a alternative payment (Called Manual Payments in Shopify Admin) like cash on collection.

**Comment by dbart01** [comment]
@carrotalan The `. checkoutCompleteFree` mutation is used only for completing a checkout that doesn't cost anything - it must be *free*. The GraphQL API and the SDK currently don't support manual payments that are available in Admin.

**Comment by patelgaurav4u** [comment]
@dbart01 any other ways to archive manual payment option with mobile app?
