### ISSUE TITLE
User error finishing checkout: Shipping rate & Shipping line item can't be blank

### ISSUE THREAD

**Issue by Chandlerdea** [Shopify/mobile-buy-sdk-ios#692]
I am using version 3.0.2 as a submodule in my project. I am trying to finish a checkout, and the checkouts become abandoned. The errors coming back are "Shipping rate can't be blank" and "Shipping line can't be blank". I am not showing the user shipping rates, and I don't see anything in the documentation that says shipping rates are required to be sent when finishing a checkout. Are they required?

Here is the query: 
```graphql
mutation {
  checkoutCompleteWithCreditCard(
    checkoutId: "Z2lkOi8vc2hvcGlmeS9DaGVja291dC83YzFkNjJlMjFjYTJiYzhhMjY0OTgyMDE4ODlkNWNhND9rZXk9MGU2N2Y5MGIwNjdhMzViZWE3ZWI5NDBjM2JjNTU3MGY=", 
    payment: {
      amount: "1", 
      idempotencyKey: "FAADFFE4-FB29-4D4B-BC8B-8396E6861BB4", 
      billingAddress: {
        address1: "6447 E Crocus Dr", 
        address2: "Scottsdale, AZ  85254", 
        city: "Phoenix", 
        country: "United States", 
        firstName: "Chan", 
        lastName: "Man", 
        province: "AZ", 
        zip: "85254"
      }, 
      vaultId: "west-c6a88b9d3a25b872528289f615c0ba3c", 
      test: true
    }
  ) {
    payment {
      id
      ready
    }
    checkout {
      id
      ready
      order {
        id
      }
    }
    userErrors {
      field
      message
    }
  }
}
```

**Comment by dbart01** [comment]
Try removing the `test: true` parameter.

**Comment by dbart01** [comment]
If your checkout contains line items that require shipping, your checkout **must** have a shipping line associated with it. There are mutations for updating the shipping address and the shipping line on a checkout, if that information isn't available to you at checkout-creation time.

**Comment by networld301ios** [comment]
can you give reference link of code . these  are updating  shipping line and  shipping rate in checkoutid. ?
i also got email is invalid error. what is the reason behind it.i added the my valid gmail.

**Comment by dbart01** [comment]
Have a look at the [sample app](https://github.com/Shopify/mobile-buy-sdk-ios/tree/master/Sample%20Apps/Storefront) for reference.
