### ISSUE TITLE
Crash During Apple Pay Checkout When Shipping Isn't Needed

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#696]
When attempting to complete an Apple Pay checkout where none of the line items require shipping, the app will crash when attempting to initialize a `PayAddress` with a `PKContact` where the `postalAddress` is nil.

It appears that when the `PKPaymentRequest` is made, if the checkout does not require shipping, a postal address is not requested. https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Pay/PaySession.swift#L152

However, it is later assumed that there will always be a `postalAddress` on the `PKContact` passed in to `PayAddress`. https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Pay/PayAddress.swift#L142

Here is a screenshot of the stack trace where the crash happens:
<img width="802" alt="screen shot 2017-07-17 at 4 40 11 pm" src="https://user-images.githubusercontent.com/318265/28289023-3200f0ce-6b0f-11e7-83f4-ccb79da45218.png">

**Comment by dbart01** [comment]
@cocoahero A fix has been merged to `develop` and will soon be making it's way to a release on `master`.
