### ISSUE TITLE
The client seems to be asking for the wrong kind of authentication key

### ISSUE THREAD

**Issue by Meeks91** [Shopify/mobile-buy-sdk-ios#697]
The constructor for the Graph.Client is: `Graph.Client(shopDomain: String, apiKey: String)`. But, setting it up using the apiKey didn't work and resulted in me getting a 403 error. I fixed this by using the private app's **access token** instead so the Graph.Client's constructor signature should be:  Graph.Client(shopDomain: String, **accessToken**: String).

Cheers

**Comment by dbart01** [comment]
Where are you getting the API key?

**Comment by Meeks91** [comment]
I'm getting it from the Custom Storefront section of the private app details page that you get to when you click on a private app on the manage private apps page.

**Comment by dbart01** [comment]
The SDK is expecting an API key that is found under the `Mobile App` channel, in your shop's Admin.

![screen shot 2017-07-18 at 8 40 15 am](https://user-images.githubusercontent.com/5244861/28317438-dbc8636e-6b94-11e7-84ba-658aadf4bd5d.png)

**Comment by Meeks91** [comment]
You're right, using a mobile app API key does work.

I was originally using a private app's API key which must be why it wasn't working. However, the private app's access token did work.

Thanks for your help.
