### ISSUE TITLE
Expose Supported Pay Payment Networks / Capabilities

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#701]
It would be nice if this framework exposed a public property that dictated the supported `PKPaymentNetwork` and `PKMerchantCapability`. As this is really dictated by the Shopify Payments gateway, it makes sense that Shopify has the responsibility in keeping these values up to date through SDK releases.

It appears that they are currently hardcoded here: https://github.com/Shopify/mobile-buy-sdk-ios/blob/a63dca5a7a5206f5066d2fa91fdffefdcdd0f67c/Pay/PaySession.swift#L165

This information would be useful in deciding whether or not to show an Pay checkout button in our apps. For example:

```swift
if PKPaymentAuthorizationViewController.canMakePayments() {
  if PKPaymentAuthorizationViewController.canMakePayments(usingNetworks: [.visa, .masterCard, .amex], capabilities: [.capability3DS]) {
    return PKPaymentButton(type: .buy, style: .black)
  }
  else {
    return PKPaymentButton(type: .setUp, style: .black)
  }
}
```

**Comment by dbart01** [comment]
Completely agree. This is, in fact, a known problem and we are working on making it better.

**Comment by dbart01** [comment]
This problem has been solved in 3.0.6 with `acceptedCardBrands` field on `PaymentSettings` in `Shop`.

**Comment by davidmuzi** [comment]
Im not sure the exposed paymentSetting for `supportedDigitalWallets` is sufficient.  Even though your shop has a payment gateway that supports Apple Pay, that does not mean it has been _enabled_.

For instance, my dev shop returns APPLE_PAY as a supported digital wallet, but its not enabled in the Mobile Channel.

**Comment by cocoahero** [comment]
I'm also a little disappointed that yet again, a new type was introduced (`CardBrand`) that has no built-in interoperability with iOS APIs, in this case `PKPaymentNetwork`.

**Comment by cocoahero** [comment]
Also, it looks like [3.0.6](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.0.6) still hard codes the payment networks on the request? So, what was the point of that change?

**Comment by dbart01** [comment]
It allows us to ship the schema updates faster. The changes to the sample application are coming in future releases. 

As for `CardBrand`, there are many platforms other than iOS relying on the GraphQL schema to be platform-agnostic. Having said that, we can definitely explore making changes to the SDK code generation to provide more specific iOS compatibility to help reduce the manual mapping required to convert between these types.

**Comment by dbart01** [comment]
Sorry, I misread the initial issue. The changes to `PaySession` will be coming in the next release.

**Comment by dbart01** [comment]
> For instance, my dev shop returns APPLE_PAY as a supported digital wallet, but its not enabled in the Mobile Channel.

Just something to note regarding the `supportedDigitalWallets` field. It **only returns supported digital wallets on the web**. The Mobile App channel has separate setup for Apple Pay and Android Pay which isn't taken into account for `supportedDigitalWallets`.
