### ISSUE TITLE
Unable to compile sample app

### ISSUE THREAD

**Issue by nogginme** [Shopify/mobile-buy-sdk-ios#702]
<unknown>:0: error: no such file or directory: '/Users/abc/mobile-buy-sdk-ios-3.0.5/Dependencies/Swift Gen/support/Sources/GraphQL.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

(XCode 8.3.3) -- Do I have to add GraphQL.swift manually? From where? Thx

**Comment by magickaito** [comment]
Same error. Any chance you have figured out?

**Comment by nogginme** [comment]
No, sorry!

**Comment by nogginme** [comment]
Try this,
git clone https://github.com/Shopify/mobile-buy-sdk-ios.git
git submodule init
git submodule update
open ~/mobile-buy-sdk-ios/Sample\ Apps/Storefront/Storefront.xcodeproj
Build and Run

**Comment by magickaito** [comment]
Yes. That works! Thanks
