### ISSUE TITLE
Nil Payment Returned From checkoutCompleteWithTokenizedPayment

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#705]
When attempting to complete an Pay checkout, we are seeing `payment` objects being returned as `nil` from `checkoutCompleteWithTokenizedPayment`. The checkout then appears to be marked as abandoned and listed in our `Abandoned Checkouts` list in Shopify.

Here is the returned response from the mutation query:

```
(lldb) po response
<Mutation: ["checkoutCompleteWithTokenizedPayment": {
    checkout =     {
        completedAt = "<null>";
        email = "jonathan@jonathanbaker.me";
        id = "a-redacted-checkout-id";
        orderStatusUrl = "<null>";
    };
    payment = "<null>";
    userErrors =     (
    );
}]>
```

**Comment by cocoahero** [comment]
Should note that the sample app (Storefront) appears to have the same issue.

**Comment by davidmuzi** [comment]
The bug is in the sample app, there needs to be a call to `mutationForUpdateCheckout:updatingShippingAddress` to add a shipping address before completing the checkout

**Comment by cocoahero** [comment]
@davidmuzi wouldn't that have already been done via the `paySession(_ paySession: PaySession, didUpdateShippingAddress:` callback from the `PaySessionDelegate`?

**Comment by davidmuzi** [comment]
Unfortunately, Apple only provides a partial address suitable only to fetch shipping rates on that call.  Only once the user authorizes the payment does Apple provide the full shipping address in `didAuthorizePayment`

**Comment by calebd** [comment]
The API should return an error in that case. If it knows the checkout isn't _really_ complete, why do we get a successful response?

**Comment by davidmuzi** [comment]
Agree 💯 %. We are going to fix that.

**Comment by calebd** [comment]
Thanks! We were beating our heads against this for a while haha.
