### ISSUE TITLE
Missing ProductVariant.compareAtPrice in SDK 3.0

### ISSUE THREAD

**Issue by glyuck** [Shopify/mobile-buy-sdk-ios#706]
I'm migrating my app from SDK 2.0 to SDK 3.0 and I can't find a `ProductVariant.compareAtPrice` property. Do you plan to add this property?
Or I should use some other property / approach to display discounted prices for products?

**Comment by tolkachovs** [comment]
I'm also missing `.tags()` property for `Order`

**Comment by davidmuzi** [comment]
`compareAtPrice` on Product has been added to our backlog.

`tags` on Order is a merchant facing property, not intended to be visible by customers.  This did not exist in SDK 2.0, and will not be added to 3.0

**Comment by tolkachovs** [comment]
@davidmuzi thanks for an answer. I want to pass delivery information with `Order` object. I was thinking of creating tags, i.e. _shipped_ and _delivered_ so I could display current delivery status to the customer. Can you advice any other way of passing information like this, since tags are out?

**Comment by darylteo** [comment]
Just noting that the ProductVariant.compareAtPrice is now available via the GraphQL Explorer, so this should simply be a matter of regenerating the SDK from the GraphQL Schema?

Hoping this will be pushed soon if that's the case.

**Comment by dbart01** [comment]
That's correct; `compareAtPrice` is not available via GraphQL and will be coming to the SDK shortly.

**Comment by dbart01** [comment]
The `compareAtPrice` and `sku` fields are now available in [3.0.6](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.0.6).

**Comment by MVakas** [comment]
> I'm migrating my app from SDK 2.0 to SDK 3.0 and I can't find a `ProductVariant.compareAtPrice` property. Do you plan to add this property?
> Or I should use some other property / approach to display discounted prices for products?

Hi I'm having trouble displaying discounted prices in my iOS app. How have you implemented this?
