### ISSUE TITLE
Return-to-App Button after web checkout missing

### ISSUE THREAD

**Issue by dwnld-mitch** [Shopify/mobile-buy-sdk-ios#71]
I'm creating a BUYCheckout object with the webReturnToURL and webReturnToLabel properties set (BUYClient also has URLScheme set), and I am then sending the app to Safari to complete checkout using the webCheckoutURL property on my BUYCheckout object.  Once the checkout is complete, I am expecting there to be a back-to-app button, based on the documentation, but the button is never there.  This also appears to be an issue in the advanced demo app.

**Comment by runmad** [comment]
You only need to set the `urlScheme` on your `BUYClient`.

I just checked the Advanced Sample App, using the default `advancedsample://` as the `urlScheme` and the button appears at the bottom of the order confirmation:

<img width="366" alt="screen shot 2015-12-08 at 12 36 13 pm" src="https://cloud.githubusercontent.com/assets/708741/11663108/541eaa24-9da8-11e5-9833-38d99be909da.png">

When I tap the button, the delegate method `application:openURL:sourceApplication:annotation:` is called and the notification is posted in the app.

**Comment by dwnld-mitch** [comment]
This is what my web confirmation screen looks like (in the Advanced Sample App):

![confirmation-2](https://cloud.githubusercontent.com/assets/7774979/11668230/09180982-9dc4-11e5-9edf-7c3622249d08.png)
![confirmation-1](https://cloud.githubusercontent.com/assets/7774979/11668231/092015aa-9dc4-11e5-9c9e-4be27a3f4ca7.png)

This is with the client's urlScheme set to the default "advancedsample://".  I tested through the BUYProductViewController and the native->web checkout flow.  I must be misunderstanding the intended usage.  Should the return-to-app appear in the SFSafariViewController after a successful checkout?

**Comment by runmad** [comment]
Yes, it appears in the bottom of the order confirmation page on a successful checkout.

Can you set a breakpoint here: https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Data/BUYClient.m#L272

And check what the output for `checkoutJSON` is? The JSON should include the following:

```
"web_return_to_label" = "Return to Mobile Buy SDK Advanced Sample";
"web_return_to_url" = "advancedsample://";
```

**Comment by dwnld-mitch** [comment]
Here's the JSON at that breakpoint:

```
(lldb) po checkoutJSON
{
    checkout =     {
        "channel_id" = 13946177;
        "line_items" =         (
                        {
                price = 3300;
                quantity = 1;
                "requires_shipping" = 1;
                title = Black;
                "variant_id" = 7467297985;
            }
        );
        "marketing_attribution" =         {
            medium = iOS;
            source = "Mobile Buy SDK Advanced Sample";
        };
        "source_identifier" = 13946177;
        "source_name" = "mobile_app";
        "web_return_to_label" = "Return to Mobile Buy SDK Advanced Sample";
        "web_return_to_url" = "advancedsample://";
    };
}
```

I am using the 4242 4242 4242 4242 test credit card with a shop that is on the trial plan, if that is useful.

**Comment by runmad** [comment]
Thanks for confirming. I have edited your response to exclude the `channel_id`.

I'm looking into the issue further. I was able to replicate it on my end. I will respond with any updates.

**Comment by dwnld-mitch** [comment]
Thanks. Let me know if I can help out in any way.

**Comment by runmad** [comment]
Looks like because it's a test account the shop was still on and older version of Shopify checkout. I've upgraded it and the button now appears.

**Comment by dwnld-mitch** [comment]
Gotcha. Thanks for finding the cause+fix.
