### ISSUE TITLE
Checkout.discount in SDK 3.0

### ISSUE THREAD

**Issue by glyuck** [Shopify/mobile-buy-sdk-ios#710]
Is there a way to apply a discount code to `Checkout` in SDK 3.0?
In the previous version of the SDK, there was a `BUYCheckout.discount` property of type `BUYDiscount`. Now I can't see anything similar in SDK 3.0

**Comment by dbart01** [comment]
Discounts are not yet available in SDK 3.0. Unfortunately, I don't have a timeline to share for discounts availability but will keep this ticket open to report any progress.

**Comment by H3ndrx** [comment]
That would be awesome to have apply discount functionality in SDK 3.0 we are now moving huge project from 2.0 to 3.0 and this is blocker :(

**Comment by darylteo** [comment]
@dbart01 regarding this, am I correct by saying that PayDiscount only applies to the payment section, not the checkout, so it is currently impossible to display "final quote" to the user with discount codes and we'll have to implement this functionality ourselves? But PayDiscount should still be applied to PayCheckout if we use it?

**Comment by darylteo** [comment]
Actually, we're now finding that adding PayDiscount has no impact on the final order. 

Disappointing.

**Comment by dbart01** [comment]
@darylteo Unfortunately, yes, the storefront GraphQL API doesn't support discounts, yet. As a result, this functionality isn't available in the SDK either.

**Comment by dbart01** [comment]
Latest release of the SDK now supports applying a discount. However, the discount object is not yet available on the `Checkout`.

**Comment by DmIvanov** [comment]
@dbart01 Hi, I'm new to the SDK, just implemented the main functionality (based on your example storefront) and now am trying to add discounts to ApplePay. Do you have any documentation about the API on this matter? I could only find discount property of PayCheckout, which we pass to PaySession (CartViewController in your example). If I create PayDiscount object and pass it there I can see "Discount" line in ApplePay native controller, which opens after pressing ApplePay button, but the discount (which is valid and works for Web Checkout) isn't applied to the total price. I assume the discount should be somehow applied before all these, when we interact with the Shopify backend via GraphQL.

**Comment by dbart01** [comment]
@DmIvanov Correct, the discount should be applied using the `checkoutDiscountCodeApply` mutation. The sample app includes an example of it's implemented. Please note that `PayDiscount` is not currently used as we have no way of retrieving the applied discounts on `Storefront.Checkout`. That is to say, you can **apply** a discount, but you can't **view** applied discounts, yet. You also won't be able to reflect that a discount has been applied in the Apple Pay dialog. This is the current limitation of the API and we are working on addressing the problem.

**Comment by DmIvanov** [comment]
@dbart01 Thanks for clarification.

**Comment by DmIvanov** [comment]
@dbart01 Hello there! Any changes on applying discounts? Because it still seems kinda useless if you can apply but you cannot reflect it in the UI (neither our custom UI, not the ApplePay controller), which would be definitely confusing for the users. You previous reply 9 months ago ended on `we are working on addressing the problem`.
