### ISSUE TITLE
I'm getting an error when i run sample app 

### ISSUE THREAD

**Issue by kamalsinghDigimantra** [Shopify/mobile-buy-sdk-ios#717]
Xcode version 8.1

![screen shot 2017-08-17 at 6 10 18 pm](https://user-images.githubusercontent.com/24381829/29412675-5fc995bc-8377-11e7-87c1-832d41602f17.png)
![screen shot 2017-08-17 at 1 18 03 pm](https://user-images.githubusercontent.com/24381829/29412754-9e283b6a-8377-11e7-879e-1c5cc7062288.png)

**Comment by dbart01** [comment]
Please update to the latest version of Xcode 8.3.3. It looks like a potential issue with Swift language version.

**Comment by kamalsinghDigimantra** [comment]
Thanks @dbart01 , now its working
