### ISSUE TITLE
Note field on Checkout Object is not updated

### ISSUE THREAD

**Issue by tolkachovs** [Shopify/mobile-buy-sdk-ios#720]
As a title says, I'm getting `Checkout` object with initial value of `.note()`. Note can be updated through the web page, but still I'll receive an object with initial value of `.note()`. I've tried to  download `Checkout` object in Postman and it returns **_updated_** value.

**Comment by dbart01** [comment]
It sounds like you're probably hitting the cache and it's returning the old value. You can disable caching on a per-request basis:
```swift
let task = client.queryGraphWith(query, cachePolicy: .networkOnly) { query, error in
    // ...
}
```
or you can set a preferred cache policy on the client. Have a look at the [documentation](https://github.com/Shopify/mobile-buy-sdk-ios#caching-) for a more detail guide on caching.

**Comment by tolkachovs** [comment]
My cache policy was:
`client.cachePolicy = .networkFirst(expireIn: 3600)`

I've tried your suggestion but it haven't worked. :(

**Comment by dbart01** [comment]
Can you ensure that you're getting the fresh network data? You should have logs in the console detailing what cache policy the client is using. Can you provide that here?

**Comment by tolkachovs** [comment]
Hm, it's strange, because I don't have any logs in console. :) Is there any way to enable them?
I'm checking response using `Charles`, in this way I can see that the `.note()` is not updated.

**Comment by dbart01** [comment]
The `Graph.Client` automatically logs message in `Debug` builds. Can you provide a code snippet of how you're calling the `Graph.Client`?

**Comment by tolkachovs** [comment]
It's getting stranger and stranger. :) I'm building on `Debug` configuration.

`
client = Graph.Client(shopDomain: shopDomain, apiKey: apiKey)
client.cachePolicy = .networkFirst(expireIn: 3600)
`
and then I have this code:
`
    private func getOrderForCheckoutID(_ checkoutID: String) -> Observable<Order> {
        return Observable.create({ (observer) in
            let query = ShopifyServiceQuery.queryForCheckout(identifier: checkoutID)
            let task = self.client.queryGraphWith(query, cachePolicy: .networkOnly, completionHandler: { (response, error) in
                if let checkout = response?.node as? Storefront.Checkout {
                    observer.onNext(Order(model: checkout))
                    observer.onCompleted()
                } else if let error = error {
                    observer.onError(error)
                } else {
                    observer.onError(ServiceError.custom("Error downloading orders."))
                }
            })
            task?.resume()
            return Disposables.create()
        })
    }
`

**Comment by dbart01** [comment]
That looks correct to me. There's no output in the console at all? Is it possible the response is being cached at the RxSwift layer?

**Comment by tolkachovs** [comment]
I have other requests performed with Shopify SDK 3.x in my app and all of them are composed in the same way, and all of them are working fine (as far as I know :), so I can say - it's rather not possible to have anything with RxSwift.

**Comment by dbart01** [comment]
Okay, you mentioned that you're able to get the updated value in Postman. What is the query you're using in Postman?

**Comment by tolkachovs** [comment]
I forgot to mention that in Postman I'm using web api, so the query looks like this:
`https://shop.myshopify.com/admin/orders/43773427738.json`

**Comment by dbart01** [comment]
Your endpoint above the querying `orders`, not checkouts. Are you comparing `order.note()` to `checkout.note()`?

**Comment by tolkachovs** [comment]
Yeah, I got it, when you said it. :)
So the checkout note always stays the same? It's make sense. But there is no `.note()` property on `Checkout` object.

**Comment by dbart01** [comment]
Ohh I see what's happening here. You're accessing orders and checkout from two different points of view: admin and storefront. The SDK uses the Storefront API, not Admin API. The REST endpoint you referenced above is using the Admin API, hence `/admin/orders/123`. The problem here is that the web Admin allows you to modify the `Order` note while the Storefront API let's you *create* a `Checkout` with a *different* note. Changing the note value on `Order`, naturally, will not affect this value on `Checkout` as they are two completely different entities with a property that coincidentally shares the same name - `note`.

**TIP:** Don't use the Admin REST API to validate values provided by the SDK. They have different access scopes and will not share the same properties, values, entities, etc.

**Comment by tolkachovs** [comment]
OK, appreciate your help and guess the issues is solved.
Can you share if the adding of `.note()` for `Order` is planned?

**Comment by dbart01** [comment]
There's is currently no timeline for adding a `note` field to orders. 

You can use our public [GraphiQL interface](https://help.shopify.com/api/storefront-api/graphql-explorer/graphiql) for exploring the Storefront GraphQL API and models instead of Postman.
