### ISSUE TITLE
Running the sample project

### ISSUE THREAD

**Issue by developerwr1** [Shopify/mobile-buy-sdk-ios#723]
When I run the sample project I get an error: 
<unknown>:0: error: no such file or directory: '/Users/danielnomura/Downloads/mobile-buy-sdk-ios-3.0.7 2/Dependencies/Swift Gen/support/Sources/GraphQL.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

There is no GraphQL.swift file to be found.

**Comment by dbart01** [comment]
Please refer to the second point in [Dynamic Framework Installation](https://github.com/Shopify/mobile-buy-sdk-ios#dynamic-framework-installation-). You need to update git submodules.
