### ISSUE TITLE
too many incompatibilities between GraphQL and this "swift" lib

### ISSUE THREAD

**Issue by jsfunfun** [Shopify/mobile-buy-sdk-ios#724]
mobile-buy-sdk-ios-3.0.7/Buy/Client/Graph.Task.swift:46:20: 
Type 'InternalTask' cannot be nested in extension of generic type 'Graph'

plus hundreds of other "internal" vs. "open" vs. "override" vs. non "override" issues between the generated GraphQL schema and this lib version... 

a total waste, sorry but who thought basing this on a demo/never-ready-for-prime-time-swift would result in a usable production API/SDK/LIB.

sorry - too bad for this, it was promising until we hit upon swift.
<img width="255" alt="nested-inheritance-issues" src="https://user-images.githubusercontent.com/3376550/29948526-54aa0da4-8e7d-11e7-8456-59cd6b1bed15.png">

**Comment by dbart01** [comment]
`Graph` isn't a generic type. The errors seem to be a byproduct of a different issue. Do you mind offering some more insight into your problem?
- what Xcode version are you using?
- what Swift version are you using?
- how are you installing the SDK?
