### ISSUE TITLE
Search products with price range in SDK 3.0

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#725]
Hi :)
Is there any way I can make search products with price range(priceMax/priceMin)?

**Comment by dbart01** [comment]
Am I understanding correctly that your wish to *query* for products within a specific price range? If so, there's currently no way to *filter* products within a price range.

**Comment by EricNetsch** [comment]
I upvote this

**Comment by dbart01** [comment]
This is now possible using the `variants.price` parameter in `Shop.products` query.
