### ISSUE TITLE
How to determine the type of collection? (Smart or Custom) SDK 3.0

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#727]
Is there any way to detect type of collection? (Smart or Custom)

**Comment by dbart01** [comment]
The SDK doesn't currently expose this information. We're looking into it.

**Comment by dbart01** [comment]
Do you mind describing the use case for which you need to know the type of `Collection`? Perhaps I can offer a workaround.

**Comment by aShaforostov** [comment]
In the Admin API, the collections are divided into two types (Smart / Custom). Mobile Buy SDK, sends all collections without type. I need to get a list of collections through the Mobile Buy SDK and send it to the Admin API, but I do not know how to filter the collection by type, because for Smart Collections one request, for the Custom another

**Comment by dbart01** [comment]
Storefront API doesn't distinguish between different collection types. Could you use the Admin API instead?

**Comment by aShaforostov** [comment]
Yes, I get collections by MobileBuySDK on mobile client and send to server where use Admin API
