### ISSUE TITLE
Where the product parameter inventory_quantity, inventory_managment?

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#732]
Does the SDK 3.0 receive inventory_quantity and inventory_managment parameters?

**Comment by dbart01** [comment]
No, those parameters aren't available. You can reference the [GraphiQL](https://help.shopify.com/api/storefront-api/graphql-explorer/graphiql) documentation for any additional inquiries regarding available parameters and APIs.
