### ISSUE TITLE
Querying all tags of a shop

### ISSUE THREAD

**Issue by adanmayer** [Shopify/mobile-buy-sdk-ios#735]
It seems that currently there is no way to directly query all tags defined on products in a shop. 

We could make a workaround and query the tags of all products, but we will have a lot of products that's why we want to query the tags directly and filter / navigate our products based on these tags.

**Comment by dbart01** [comment]
This is a reasonable request. We'll look into adding a `tags` field on `Shop`. I'll keep this issue open to track any progress.

**Comment by adanmayer** [comment]
Hi there, 
any update when this will be integrated? 
We have the described workaround in place, but would love to replace it with something solid. 
Best, 
Alex.

**Comment by morganmccunn** [comment]
Hi @adanmayer this has now been shipped. You can manage this for private apps under the settings for the app. https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started#authentication
