### ISSUE TITLE
How test checkout with Credit Card?

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#737]
I'm set a Bogus Gateway in Shop Settings -> Payment
But is not working, when i send a credit card number "1" To Simulate an Approved Transaction, query was failed with no error

**Comment by dbart01** [comment]
Please see [documentation](https://help.shopify.com/manual/payments/shopify-payments/testing-shopify-payments) for more information about using `Test Mode` and simulating payments.
