### ISSUE TITLE
How fetching multiple products by array of ids?

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#739]
I need to update the products data in the favorite list, I have a list of ids and handles. How to fetch them with one GraphQL request?

**Comment by dbart01** [comment]
You can achieve this using aliases. You'll need to query for `Storefront.Product` nodes and products by handle using an alias for each:

```swift
let query = Storefront.buildQuery { $0
    .node(alias: "product-node-1", id: GraphQL.ID(rawValue: "opaque-product-id-1")) { $0
        .onProduct { $0
            .id()
            .title()
        }
    }
    .node(alias: "product-node-2", id: GraphQL.ID(rawValue: "opaque-product-id-2")) { $0
        .onProduct { $0
            .id()
            .title()
        }
    }
    .shop { $0
        .productByHandle(alias: "product-1", handle: "product-handle-1") { $0
            .id()
            .title()
        }
        .productByHandle(alias: "product-2", handle: "product-handle-2") { $0
            .id()
            .title()
        }
    }
}
```
After executing the query, you can access the products in a similar fashion:

```swift
client.queryGraphWith(query) { response, error in
    if let response = response {
        let productNode1   = response.aliasedNode(alias: "product-node-1") as! Storefront.Product
        let productNode2   = response.aliasedNode(alias: "product-node-2") as! Storefront.Product
        let productHandle1 = response.shop.aliasedProductByHandle(alias: "product-1")!
        let productHandle2 = response.shop.aliasedProductByHandle(alias: "product-2")!
    }
}
```

**Comment by aShaforostov** [comment]
And what if I do not know the number of products. Do not set a separate query for each size of the array? Can not somehow dynamically create this query?

**Comment by dbart01** [comment]
This is a literal version of the query. You can just as easily create a loop and sequentially add `node` or handle fields as necessary.

**Comment by dbart01** [comment]
It's also worth mentioning that the next release of the SDK will add support for fetching nodes by ids, which will simplify everything to:
```swift
let ids = [GraphQL.ID]()
let query = Storefront.buildQuery { $0
    .nodes(ids: ids) { $0
        .onProduct { $0
            .id()
            .title()
        }
    }
}
```

**Comment by dbart01** [comment]
Support for `nodes` now available in the [3.1 release](https://github.com/Shopify/mobile-buy-sdk-ios/tree/3.1).

**Comment by natecraft1** [comment]
> This is a literal version of the query. You can just as easily create a loop and sequentially add `node` or handle fields as necessary.

@dbart01 Can you show an example of this please?

**Comment by dbart01** [comment]
You no longer need that workaround @natecraft1. The `nodes` interface is now available directly.

**Comment by natecraft1** [comment]
so how do you add a node to an existing query @dbart01 ?

**Comment by dbart01** [comment]
I'm not sure I understand what you're trying to do here. If you have multiple ids to entities you'd like to fetch, you can create a query to fetch them as described in [the comment above](https://github.com/Shopify/mobile-buy-sdk-ios/issues/739#issuecomment-329139750).

**Comment by deanWombourne** [comment]
Hi, I have a similar problem, but the nodes(...) doesn't quite cover my use case - when a nodes query is made with an invalid id (i.e. maybe a product has been removed, or hidden from my app?) then the whole query fails - is it possible to fetch a selection of products and only return existing ones in the response?
