### ISSUE TITLE
The address from the checkout becomes the default address for the customer 

### ISSUE THREAD

**Issue by tolkachovs** [Shopify/mobile-buy-sdk-ios#744]
Hi :)
As the title says, the case is when customer is completing checkout from iOS app, the address he provides during checkout becomes his default address. 
The flow is as follows:
```
checkoutCreate
checkoutLineItemsUpdate
checkoutCompleteFree
```
Is this intended behaviour? Maybe it can be changed somewhere in Shopify store settings?

**Comment by dbart01** [comment]
Yes, this the intended behaviour. Am I correct in assuming that you don't want _any_ address to be associated with a customer?

**Comment by tolkachovs** [comment]
I want a customer to be able to set his default address separately and don't take into account his last shipment address.

**Comment by dbart01** [comment]
We're looking into it.

**Comment by dbart01** [comment]
The latest release of the SDK supports explicitly settings customers' default address via a mutation.
