### ISSUE TITLE
Is the BuyTV included to this version 3.0 SDK? 

### ISSUE THREAD

**Issue by pwr7549** [Shopify/mobile-buy-sdk-ios#748]
I tried to switch from iOS to tvOS Simulation or Device, I noticed it is not included to this source. Since the Mobile Buy 2.2 SDK is deprecated starting Sept 20017, because the API Key and others are migrated into Private App. That leave me out cold for trying to complete the tvOS app. Any advise?

**Comment by dbart01** [comment]
The tvOS target is not currently included in the latest release but will be coming shortly.

**Comment by dbart01** [comment]
Now available in the [3.1 release](https://github.com/Shopify/mobile-buy-sdk-ios/tree/3.1).
