### ISSUE TITLE
Checkout appearing to succeed but not appearing in orders.

### ISSUE THREAD

**Issue by JoshBoluga** [Shopify/mobile-buy-sdk-ios#753]
I'm developing a mobile app only using only Apple Pay to pay for an order. I've followed the documentation and, using the app, am able to complete the checkout but the order is not appearing in the myshopify web orders list.

I'm not getting any errors in the userErrors.

I'm a bit confused by the example's checkoutCompleteWithTokenizedPayment, specifically the lines:

    let checkoutReady = result?.checkoutCompleteWithTokenizedPayment?.checkout.ready ?? false
    let paymentReady  = result?.checkoutCompleteWithTokenizedPayment?.payment?.ready ?? false
            
    // checkoutReady == false
    // paymentReady == false

Are the comments suggesting that these bools should both be false? When I break here, checkoutReady is always true and paymentReady is always false.

I'm using version Buy 3.0.7 and Pay (version that came with 3.0.7)
Expected behaviour: Order placed
Actual behaviour: Appearing to checkout but silently not doing anything.

If there's any any more information needed, please let me know. Many thanks in advance.

**Comment by JoshBoluga** [comment]
**Update:** I've been using Apple Pay Sandbox test cards. I've just tried my a real card now and although the behaviour is the same in the app, I get a notification from my banking app that my payment was declined.

**Comment by JoshBoluga** [comment]
**Further update**: The orders are going into abandoned checkouts and the history section says "Unable to process a payment for $29.99 USD on the card ending in ••• via Apple Pay." Is the mobile SDK considering the checkout to be valid yet Shopify only finds out later that the payment is failed. Is there any way to present this information to the user within the app? Perhaps at the point where we're polling the checkout?

**Comment by dbart01** [comment]
> When I break here, `checkoutReady` is always true and `paymentReady` is always false

This is the correct behaviour. You'll need to [poll the checkout](https://github.com/Shopify/mobile-buy-sdk-ios#polling-for-checkout-completion-) until `paymentReady` returns `true`.

> I get a notification from my banking app that my payment was declined

But Shopify's checkout returns an `Order` and `Payment` object with no errors or `userErrors`?

> The orders are going into abandoned checkouts

Are you updating your checkouts with a "complete" address after PassKit authorizes payment? Before payment is authorized, the shipping contact will only have partial address information (restricted by Apple for security reasons). While is sufficient for obtaining shipping rates from Shopify, you'll need to send a `mutation` to update the shipping address with the complete `postalCode`, `addressLine1`, etc.

**Comment by JoshBoluga** [comment]
**Final update:** It turns out that our Shopify payments were set to use a payment provider that didn't support Apple Pay. Many, many apologies on my behalf for wasting your time.

Thanks for confirming the behaviour of the two Bools. I was also polling for a checkout as you mentioned. It's all working at I'd hoped now.

Would there be any way to query which payments are supported by Shopify is a future API? It could be interesting to be able to code for all different payments types and be able to remotely switch them on and off on the fly. V4 maybe?

Again many apologies.

**Comment by dbart01** [comment]
Glad everything is working as expected 👍 

As for payment providers, the best we can do right now is query available card brands and supported digital wallets:
```graphql
{
  shop {
    paymentSettings {
      supportedDigitalWallets
      acceptedCardBrands
    }
  }
}
```
If you believe the SDK can benefit from additional functionality, please open a separate issue and we can file it as a feature request for future consideration :)
