### ISSUE TITLE
AccessDenied using Access Token from Private App

### ISSUE THREAD

**Issue by darylteo** [Shopify/mobile-buy-sdk-ios#755]
Hi Shopify, 

 we're trying to port our existing setup from a Mobile App Sales Channel to a Private App as we're about to launch and can't wait for migration (i.e. for UAT, we don't want to have to do another round of tests). https://www.shopify.com/partners/blog/updates-to-shopifys-custom-storefronts-api says it should be easy. However, when using the StoreFront Access Token, we are getting a 403 Access Denied when trying to checkout (products etc. all works, which indicates that the api key is working...)

Everything works with the Mobile App Sales Channel API Key. 

Is there any extra permissions we need set up on the Admin API? I assumed the process should be seamless. We're using the latest SDK release. Has this work not been completed yet? Are there some payment settings we need to provide as well? 

Kind Regards,
Daryl

----

Some "Postman" Calls, but I can't actually paste the whole process because I need to vault the card.

`https://appetiser-1288.myshopify.com/api/graphql` with X-Shopify-Access-Token of `9f16123694bfb11313d68d262f2110ce` (just a test account). Mobile App Key is `d098a197b928e2ba91a410a66b70f448`.

#### Query 

```graphql
mutation {
  checkoutCreate(input: {
    lineItems: [{ variantId: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80NjU5NTg4OTM2Mw==", quantity: 1 }]
  }) {
    checkout {
       id
       webUrl
       lineItems(first: 5) {
         edges {
           node {
             title
             quantity
           }
         }
       }
    }
  }
}
````

#### Response

```json
{
    "data": {
        "checkoutCreate": {
            "checkout": {
                "id": "Z2lkOi8vc2hvcGlmeS9DaGVja291dC8wNzQ3Mzc5MjY0NjVmMzNkZDcwZGRmZWViNGM4NDFjZj9rZXk9NjZmZmRlNDJhNmJkZGUwNjliZDNjMjczODA5OTcxMDA=",
                "webUrl": "https://checkout.shopify.com/21928791/checkouts/074737926465f33dd70ddfeeb4c841cf?key=66ffde42a6bdde069bd3c27380997100",
                "lineItems": {
                    "edges": [
                        {
                            "node": {
                                "title": "Beef Lasagne",
                                "quantity": 1
                            }
                        }
                    ]
                }
            }
        }
    }
}
````

----

#### query
```graphql
mutation {
  checkoutCompleteWithCreditCard(
	checkoutId: "Z2lkOi8vc2hvcGlmeS9DaGVja291dC9kYjk0ZDI4ZGYzNGRmNGY3MjYwMjIyNzhlMmU4OGM2Zj9rZXk9YzQ5MWFkODQxYjhkYTRmZmJkNzJlY2Q3YzRlODIxMDQ=",
	payment: {
		amount: 100,
		idempotencyKey: "",
		billingAddress: {
			firstName: "Daryl",
			lastName: "Teo",
		    address1: "123 Test Street",
		    province: "QC",
		    country: "Canada",
		    zip: "H3K0X2",
		    city: "Montreal"
		},
		vaultId: "abc123"
	}
  ) {
    userErrors {
      field
      message
    }
    payment {
      id
    }
  }
}
````

#### Response

```json
{
    "data": {
        "checkoutCompleteWithCreditCard": null
    },
    "errors": [
        {
            "message": "CheckoutCompleteWithCreditCard access denied",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "checkoutCompleteWithCreditCard"
            ]
        }
    ]
}
````

#### Alternative Response with Mobile App Key
```json
{
    "errors": [
        {
            "message": "Internal error"
        }
    ]
}
````

Obviously, it doesn't work because I skipped a lot of steps. But with the Private App key, it doesn't even get to that validation stage.

**Comment by mtaher** [comment]
Hi @darylteo, currently your private app is missing a scope that prevents it from performing that mutation. However, a UI change is coming shortly that will give you the option to enable it.

**Comment by darylteo** [comment]
@mtaher that's what I needed to know! I can inform the client. Thanks!
