### ISSUE TITLE
Get Checkout/Cart

### ISSUE THREAD

**Issue by nlogioco** [Shopify/mobile-buy-sdk-ios#756]
v3.0.8

Is there a way to start a checkout on one device and finish it on another?
I understand how to create/start a checkout, but I don't understand how to 'get the users current cart/checkout progress'.

Thanks

**Comment by dbart01** [comment]
Unfortunately, no API current exists for obtaining customer's "current" or "active" checkouts for security reasons. Having said that, this is something we are exploring. I'll keep this ticket open to track progress.

**Comment by nlogioco** [comment]
Sounds good, thanks.

**Comment by morganmccunn** [comment]
Hi @nlogioco, we've added an `incompleteCheckouts` field to customers which returns an array of one: the most recently updated, incomplete checkout between the customer and that shop.
