### ISSUE TITLE
Pay tvOS

### ISSUE THREAD

**Issue by pwr7549** [Shopify/mobile-buy-sdk-ios#758]
I realized that there is a problem with Pay framework  that lack in tvOS? Could  you please create a new framework of Pay for tvOS?

**Comment by dbart01** [comment]
`tvOS` doesn't support Apple Pay and `PassKit`. That's why there's no tvOS `Pay` target.

**Comment by pwr7549** [comment]
Okay I realized that you are right after reviewing it. The question is that do you have any support major credit card and other merchant API readily for tvOS?

**Comment by dbart01** [comment]
Apple Pay support is scoped only to the platforms it's available on. I'm sorry, I cannot provide support for your Stripe account.
