### ISSUE TITLE
Polling Checkout <null> Apple Pay

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#759]
I'm trying to make a payment with Apple Pay, but when i do pollingCheckout I get an response.

Checkout ready, but no errors. How to find out what is missing to complete checkout?

```
Optional(<QueryRoot: ["node": {
    "__typename" = Checkout;
    order = "<null>";
    orderStatusUrl = "<null>";
    ready = 1;
}]>)
```

```
let retry = Graph.RetryHandler<Storefront.QueryRoot>(endurance: .finite(30)) { (response, error) -> Bool in
            return (response?.node as? Storefront.Checkout)?.order == nil
        }
        
        let query = Storefront.buildQuery { $0
            .node(id: GraphQL.ID(rawValue: checkoutID.id)) { $0
                .onCheckout { $0
                    .ready()
                    .orderStatusUrl()
                    .order { $0
                        .id()
                        .orderNumber()
                        .totalPrice()
                    }
                }
            }
        }
        
        let task  = client.queryGraphWith(query, retryHandler: retry) { response, error in
            let checkout = (response?.node as? Storefront.Checkout)
            let orderID  = checkout?.order?.id
            
            
            
//            print("SWIFT POLLING = \(response.debugDescription) ANDERROR = \(error.debugDescription) ANDORDER = \(checkout?.orderStatusUrl?.absoluteString) ANDCHECKOUTREADY = \(checkout?.ready.description)")
            
            if (orderID != nil){
                completionHandler(orderID.debugDescription)
            }
            else{
                completionHandler(error.debugDescription)
            }
        }
        task.resume()
```

**Comment by dbart01** [comment]
Sorry, but I'm not sure I understand what the problem is here. Could you please elaborate on what you're expecting to happen vs. what is actually happening?

**Comment by aShaforostov** [comment]
I want to get order and complete checkout. But response 
`order = "<null>";`
and no errors

**Comment by dbart01** [comment]
Your query above just send obtains a checkout by ID. Are you calling `checkoutComplete...`? Please take a look at [completing a checkout](https://github.com/Shopify/mobile-buy-sdk-ios#apple-pay-checkout-) in our case study for how to correctly complete a checkout with Apple Pay. Alternatively, checkout the sample app, it'll show you how to implement `checkoutCompleteWithTokenizedPayment` correctly.

**Comment by GhostCoder7** [comment]
I've got the same problem. I'm calling checkoutCompleteWithTokenizedPaymentV3 and then after that triggering polling using the same polling code in the README, but I never get an order (its always null) eventually resulting in a failure. No error messages returned. Just an empty order. Using Apple Pay test credit cards.
