### ISSUE TITLE
Get product photo from Checkout

### ISSUE THREAD

**Issue by nlogioco** [Shopify/mobile-buy-sdk-ios#760]
v3.0.8

When I create a checkout and want to show the product image to users, is there a way to retrieve the image? I see i can get a variants image, but I was hoping to get a lineItems image from the node perspective (how you get the images when you query the the shop.)

Thanks

**Comment by dbart01** [comment]
Am I understanding correctly that you want to obtain the variant image associated with the line item? If so, your query would look something like this if you fetch the `Storefront.Checkout` using the `Node` interface by `id`:
```graphql
{
  node(id: "opaque-checkout-id") {
    ... on Checkout {
      lineItems(first: 10) {
        edges {
          node {
            variant {
              image {
                src
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by nlogioco** [comment]
@dbart01 Thanks for the quick response. I apologize for the confusion.

So the query I'm using looks like yours, the issue is image is always null. 

I'm assuming I'm not setting the image correctly in the UI which is why image is null?

Is there something special that I need to do when adding an image to a product?

**Comment by dbart01** [comment]
Are you adding images to the product or the product's _variants_? Those are different.
