### ISSUE TITLE
Invalid credit card when completing checkout

### ISSUE THREAD

**Issue by ivanvranjic** [Shopify/mobile-buy-sdk-ios#762]
I get 
```
<UserError: ["message": Credit card is invalid, "field": <__NSArrayI 0x60400083fec0>(
payment,
creditCard
)
]>
``` 
when attempting to complete checkout using Discover, Diner's club and JCB cards listed here: https://help.shopify.com/manual/payments/shopify-payments/testing-shopify-payments#simulate-successful-transactions. Test mode was on during the attempt. First three cards (Visa, Mastercard and American Express) work wihout problems.
Does this indicate a problem in SDK or somewhere else?

**Comment by dbart01** [comment]
This isn't an SDK issue. It sounds like those cards are not supported by your payment gateway.

**Comment by ivanvranjic** [comment]
You are correct. Thanks. Closing this.
