### ISSUE TITLE
How do you use a non-variantID to create a CheckoutLineItemInput?

### ISSUE THREAD

**Issue by Meeks91** [Shopify/mobile-buy-sdk-ios#766]
I am trying to create a CheckoutLineItemInput but I seem to only be able to  create them with variant IDs. How do you create one with a normal product ID?

Thanks in advance.

**Comment by dbart01** [comment]
A product cannot be a line item. Customers can only purchase a `ProductVariant`, even if there's only one variant of a product. Every product will have a variant. As long as you query for the product variant id, you can use it to create a line item input.

**Comment by Meeks91** [comment]
Ok, that makes sense.

Thanks for your help.
