### ISSUE TITLE
Clearing cache manually

### ISSUE THREAD

**Issue by ivanvranjic** [Shopify/mobile-buy-sdk-ios#767]
I am using .cacheFirst policy with one hour expiration throughout the app. I would like to implement pull to refresh feature, but due to cache policy I use, I need to clear cache, so that latest data from server gets pulled. I don't see such methods publicly exposed. Does it make sense to make Graph.Cache public or there is another way to achieve what I want?

**Comment by dbart01** [comment]
It sounds to me like that functionality you're looking for is _ignoring_ cached data, rather than clearing it. Caching is supported a query-by-query basis and you can specify a `.networkOnly` cache policy only when pulling to refresh. For example:

```swift
// let query = ...

let cachePolicy: Graph.CachePolicy?
if pullToRefresh {
    cachePolicy = .networkOnly
} else {
    cachePolicy = nil
}

let task = client.queryGraphWith(query, cachePolicy: cachePolicy) { result, error in
    // handle response
}

task.resume()
```

**Comment by ivanvranjic** [comment]
That helped. Thanks.
