### ISSUE TITLE
BUYWebCheckoutPaymentProvider shows 2 bars

### ISSUE THREAD

**Issue by mihaibulic** [Shopify/mobile-buy-sdk-ios#768]
(on iphone 6s running ios 11)

When I launch BUYWebCheckoutPaymentProvider from our app, I see the native iOS bar allowing the user to leave checkout and return to our cart, which has always been there.  But now, following the update to iOS 11, I see a second bar below by default, which shows a "Done" button, the url (checkout.shopify.com), and a refresh symbol.

Apple [suggests](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller#//apple_ref/occ/instm/SFSafariViewController/initWithURL:) using WKWebView instead of SFSafariViewController if a more customized interface is needed (such as one that doesn't show this url), so maybe it'd be better if BUYWebCheckoutPaymentProvider uses WKWebView instead of SFSafariViewController?

![img_2423](https://user-images.githubusercontent.com/1116672/31313781-134a139e-aba2-11e7-95ac-be5c1ea85af0.PNG)

**Comment by dbart01** [comment]
We encourage you to upgrade to `v3.x` since prior versions are no longer supported. However, the problem in this case is trivial. In iOS 11.0, `SFSafariViewController` needs to be presented instead of pushed. Non-intuitively, it will be "pushed" on the navigation stack if you call:

```swift
navigationController.present(safariController, animated: true, completion: nil)
```

**Comment by mihaibulic** [comment]
Thank you for the quick reply/fix Dima!

I see from the release notes that there was a long stretch between v2.1 and v3, and that v3 is totally different.

I'm trying to gauge how important migrating to v3 should be for us.  I have two quick questions:
1. How extensively has the api changed externally from v2.x to v3.x?
2. Will v2 stop functioning at some point?

Thanks

**Comment by dbart01** [comment]
1. The API is completely different with 0% backwards-compatibility. This is because `v3.x` is based on GraphQL and introduces a completely new programming paradigm. The initial migration might be somewhat involved but brings with it many awesome features, like search (among many others).

2. We currently don't have a roadmap for shutting down the REST APIs backing `v2.x`.
