### ISSUE TITLE
Variants not visible 

### ISSUE THREAD

**Issue by mickymills** [Shopify/mobile-buy-sdk-ios#769]
I have been unable to successfully call and display product details in the demo SDK. 
I know this isn't a build related question, but I could use the communities insight to know for certain if this feature is supported.
I can see in Node.swift that ProductVariant function and ProductVariantQuery are marked discardableResult .
Is there a plan to implement product variants into the Mobile Buy SDK ?

Thanks in advance

**Comment by dbart01** [comment]
I'm not sure I understand your question. Product variants have been supported from day one, as without them, the SDK would not be able to create or complete a checkout.

Take a look at [how to build a query for product variants](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Sample%20Apps/Storefront/Storefront/Fragment%2BProductConnectionQuery.swift#L43) in our Sample App. Our [documentation](https://github.com/Shopify/mobile-buy-sdk-ios#fetch-product-details-) also includes an example of how to query for product variants.

**Comment by mickymills** [comment]
Great Dima. This is what I needed. Thanks very much for the reply. :)

--
Michael Herlihy

michael.liam.herlihy@gmail.com
http://au.linkedin.com/in/mlherlihy

See who we know in common                             Want a signature like this?


This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.
