### ISSUE TITLE
Ability to persist BUYCart between app launches

### ISSUE THREAD

**Issue by jimspeth** [Shopify/mobile-buy-sdk-ios#77]
Is there a way to persist the cart object between app launches?  If there's not already, could you add a way to serialize/deserialize the cart to JSON?

`BUYCart` implements `BUYSerializable` to get a JSON dictionary, but there is no corresponding `initWithDictionary:` method.

Thanks!

**Comment by jimspeth** [comment]
@bgulanowski Any update on the local data caching solution for this that you mentioned in the PR?  Thanks!

**Comment by zebarahman** [comment]
Hi, will the Ability to persist BUYCart between app launches be there in version 2.0? Thanks.

**Comment by bgulanowski** [comment]
No. There will be hooks to enable you to provide your own persistence solution, if you want to. The SDK will not provide built-in persistence support.

**Comment by nabeelahmed87** [comment]
What are these hooks ?

**Comment by bgulanowski** [comment]
For help with the SDK, please post questions on https://ecommerce.shopify.com/forums

In this case, the hooks are for storefront objects (shop, collections, products, variants, etc.), and are part of the `BUYModelManager` interface.

The model classes are instantiated via model manager methods like `-insertShopWithJSONDictionary:`, which in turn uses `-buy_objectWithEntityName:JSONDictionary:` (or, for arrays, `-buy_objectsWithEntityName:JSONArray:`). So if you implement those methods, you will always get notified when objects have been fetched from Shopify.

Then you can use your custom caching system to fetch and update, or create and cache, new objects, and retrieve them. You can also implement `-buy_refreshCacheForObject:` and `-buy_purgeObject:error:` to update and delete the objects in the cache, or use your own methods as you wish.
