### ISSUE TITLE
Address Type

### ISSUE THREAD

**Issue by nlogioco** [Shopify/mobile-buy-sdk-ios#772]
Why are there so many different address types and is there a way to convert one to another?

Thanks

**Comment by dbart01** [comment]
Which mailing address types are you referring to, specifically? There's only two:
- `MailingAddressInput`
- `PayAddress`

The former is used throughout the Storefront API, while the latter is only used for Apple Pay.

**Comment by nlogioco** [comment]
Those two, as well as:
`MailingAddress` which is used when you're retrieving a users address.

I thought you had to create a PaySession in order to get a idempotencyKey?

**Comment by dbart01** [comment]
`MailingAddress` and `MailingAddressInput` go hand-in-hand and serve two different purposes. 

> I thought you had to create a PaySession in order to get a idempotencyKey?

A `PaySession` creates a unique identifier that can server as an idempotencyKey but it isn't _required_ in any way. An `idempotencyKey` is just a unique string that represents an intent to complete a checkout.

**Comment by nlogioco** [comment]
Gotcha, could we use `UUID().uuidString` for a unique string? Or is there something else you guys recommend?

**Comment by dbart01** [comment]
That's exactly what `PaySession` uses.

**Comment by nlogioco** [comment]
<img width="639" alt="screen shot 2017-10-12 at 1 35 52 pm" src="https://user-images.githubusercontent.com/6886305/31510301-49cdde10-af52-11e7-8d71-cb18de2965f7.png">

This is the issue i'm facing with the different address types.

**Comment by dbart01** [comment]
That's pretty expected. They are two completely different types.

**Comment by nlogioco** [comment]
Is there a way to do this without taking each value out and placing it in the other? Such as exporting the dict of one and importing it to another?

**Comment by dbart01** [comment]
You can write an extension on `Storefront.MailingAddress` that gives you an input "copy". And call it like:
```swift
let input = address.copyAsInput()
input.addressLine1 = "Lakeshore West"
// etc...
```
