### ISSUE TITLE
Is it possible to sign in/sign up customer through OAuth via SDK?

### ISSUE THREAD

**Issue by dron247** [Shopify/mobile-buy-sdk-ios#776]
Hi, currently I'm building a client application and i'm trying to figure out a possibility to add a Facebook login for example. It's clear what to do with password/email but thirdparty login and possibility to use that without own backend is not.

**Comment by dbart01** [comment]
Unfortunately, the Storefront API doesn't support OAuth for customer authentication at this time.

**Comment by dron247** [comment]
@dbart01 is there any possibility, example or just thoughts about how to implement my own members only shop on my own backend? Looks like i have to implement my own customer database and basically create a proxy for cart, checkout etc, correct?

**Comment by dbart01** [comment]
> how to implement my own members only shop on my own backend

I'm not sure what you mean here. You want to enforce that customers authenticated with email / password can _only_ purchase products from one particular Shopify store?

**Comment by dron247** [comment]
No, i want to give my customers an ability to log in with OAuth at the first place, and i want only registered users to be able to purchase

**Comment by dbart01** [comment]
Well, OAuth isn't supported, but you can certainly create accounts and authenticate users using the Storefront API. Then, it's up to your application to enforce the login-before-purchase requirement client-side. For more detail on the customers API, you can take a look at [how to work with customers](https://github.com/Shopify/mobile-buy-sdk-ios#customer-accounts-) in our docs.

**Comment by dron247** [comment]
thanks
