### ISSUE TITLE
No error if checkout store is disabled

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-ios#778]
I try make payment by credit card, all ok, but when i make checkoutCompleteWithCreditCard

```
<Mutation: ["checkoutCompleteWithCreditCard": {
    checkout =     {
        id = "Z2lkOi8vc2hvcGlmeS9DaGVja291dC8yOTQ3ZWQ0YzM1MTY2YmQ2ZTM0OWE2YWM5ZTQwYzVhND9rZXk9YjUyMzNmNjhhMWRiNTQyMDNkN2UxMzRlZjUxNGNmNjA=";
        ready = 1;
    };
    payment =     {
        errorMessage = "<null>";
        id = "Z2lkOi8vc2hvcGlmeS9QYXltZW50Lzc4MjkzODUwMz9jaGVja291dD0yOTQ3ZWQ0YzM1MTY2YmQ2ZTM0OWE2YWM5ZTQwYzVhNCZrZXk9YjUyMzNmNjhhMWRiNTQyMDNkN2UxMzRlZjUxNGNmNjA=";
        ready = 0;
    };
    userErrors =     (
    );
}]>
```

Is no errorMessage and userErrors. I think this is due to the fact that checkout system are disabled on store. But why there is no error message about this?

**Comment by dbart01** [comment]
> make payment by credit card, all ok, but when i make checkoutCompleteWithCreditCard

I'm sorry, I don't understand the problem here. `checkoutCompleteWithCreditCard` _is_ making a payment with a credit card, isn't it?

The response you posted looks normal. The `Payment` is not ready - `ready = 0;` so you'll need to poll for completion. Is this the response you're getting _after_ polling for payment completion?

**Comment by aShaforostov** [comment]
Thanks for the answer) I thought that there should be a message why payment is not ready

**Comment by dbart01** [comment]
When you submit a mutation for completing a checkout (regardless) of a method, it starts an async task on the server to complete the checkout, create a payment, etc. This takes time. When you get the response, just like any other async call, there's no guarantee that the task is finished. You'll need to poll until it is. This isn't an error state, though. It's a normal part of the payment lifecycle. Hence, there's no error provided.

**Comment by dbart01** [comment]
The process of polling is documented [here](https://github.com/Shopify/mobile-buy-sdk-ios#polling-for-checkout-completion-).

**Comment by aShaforostov** [comment]
Thanks) The question is solved. I changed the logic in the application
