### ISSUE TITLE
#import <Buy/MD5.h> in mixed Swift/Objective-C project

### ISSUE THREAD

**Issue by Hans92** [Shopify/mobile-buy-sdk-ios#782]
While linking your SDK via Cocoa Pods I have encountered a problem while building the app. There is a file `Buy.h` and it tries to `#import <Buy/MD5.h>`. Only changing this line to `#import "MD5.h"` helps. Is there any other way to make your SDK running without modifying files in your Pod?

**Comment by dbart01** [comment]
I can't seem to reproduce the problem. What version of SDK are you using? Also, please verify that Cocoapods is setting the preprocessor macros correctly. You should see `COCOAPODS=1` in your build settings:

| Build Settings |
| - |
| ![screen shot 2017-11-09 at 8 27 27 am](https://user-images.githubusercontent.com/5244861/32607901-667b8f12-c528-11e7-8b75-f7e90aa38524.png) |

**Comment by Hans92** [comment]
It started to work after I've added this macro. Thanks
