### ISSUE TITLE
Help to open product description directly

### ISSUE THREAD

**Issue by Marcus0993** [Shopify/mobile-buy-sdk-ios#786]
Hello,

I was wondering if someone could give me some tips :) I am working from the sample app in the SDK as I don't have an app yet (don't know if this is the best way or not) anyway I need the app to open directly into the product description and show this and the cart only, as we only have one product. 

Can someone please advise on the best way to do this? any help would be greatly appreciated :) 

Thanks

Marcus

**Comment by sav007** [comment]
What you are looking for is https://developer.android.com/training/app-links/deep-linking.html

**Comment by Marcus0993** [comment]
Thanks for your reply :) its for iOS tho is it the same thing?

**Comment by sav007** [comment]
sorry my bad, I thought this issue for Android.

https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html
