### ISSUE TITLE
'invalid id' in checkoutCreate

### ISSUE THREAD

**Issue by RayoRavi** [Shopify/mobile-buy-sdk-ios#788]
I'm using this code to create a checkout object.

    func buyAction(_ sender:UIButton) {
        let product = products[sender.tag]
        
        let input = Storefront.CheckoutCreateInput.create(
            lineItems: .value([
                Storefront.CheckoutLineItemInput.create(quantity: 1, variantId: product.id)
                ])
        )
        
        let mutation = Storefront.buildMutation { $0
            .checkoutCreate(input: input) { $0
                .checkout { $0
                    .id()
                    .webUrl()
                }
                .userErrors { $0
                    .field()
                    .message()
                }
            }
        }
        
        SVProgressHUD.show()
        let task = client.mutateGraphWith(mutation) { result, error in
            SVProgressHUD.dismiss()
            guard error == nil else {
                print(error!)
                return
            }
            
            guard let userError = result?.checkoutCreate?.userErrors else {
                // handle any user error
                print(result!.checkoutCreate!.userErrors)
                return
            }
            
            if let checkout = result?.checkoutCreate?.checkout {
                self.openSafariFor(checkout)
            }
        }
        task.resume()
    }

I'm getting this error

    invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "invalid id", line: nil, column: nil)])

mutation object 

     mutation{checkoutCreate(input:{lineItems:[{quantity:1,variantId:"Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM5NDExMjU2NTI4Nw=="}]}){checkout{id,webUrl},userErrors{field,message}}}

Any idea what's wrong here?

**Comment by dbart01** [comment]
You're passing in a product ID instead of a product _variant_ iD.
