### ISSUE TITLE
Use of unresolved identifier 'MD5'

### ISSUE THREAD

**Issue by qwill** [Shopify/mobile-buy-sdk-ios#793]
Dunno what to do.

**Comment by dbart01** [comment]
Are you using Cocoapods?

**Comment by qwill** [comment]
Carthage

**Comment by qwill** [comment]
Also I get this error..

> 
> Build Failed
> 	Task failed with exit code 70:
> 	/usr/bin/xcrun xcodebuild -project /Users/houseofpawn/Downloads/mobile-buy-sdk-ios-master/Carthage/Checkouts/mobile-buy-sdk-ios/Buy.xcodeproj -scheme Buy\ watchOS -configuration Release -derivedDataPath /Users/houseofpawn/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/mobile-buy-sdk-ios/3.1.3 -sdk watchsimulator -destination platform=watchOS\ Simulator,id=A7058861-71F6-43BA-A9E4-7F3E8902F8B3 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/houseofpawn/Downloads/mobile-buy-sdk-ios-master/Carthage/Checkouts/mobile-buy-sdk-ios)
> 
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/sr/7ppk49jj3wd_ks1z69lf2jzc0000gn/T/carthage-xcodebuild.WJTYDY.log

**Comment by qwill** [comment]
If I try running pod install I get this error
[!] The dependency `Mobile-Buy-SDK` is not used in any concrete target.

**Comment by qwill** [comment]
I'm trying to get the sample app working..

**Comment by qwill** [comment]
nm fixed
