### ISSUE TITLE
Mobile-buy-sdk forbidden issue

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#794]
Hello experts,

I am new to shopify. Downloaded mobile-buy-sdk and integrate in my project by following the steps given in doc. I use sample app provided with this sdk to test if my store is working or not.

Now in sample app I just replace my `apiKey` in `Client.swift` but I am always getting the following error:
```
Exercising cache policy: CACHE_FIRST(3600)
Exercising cache policy: NETWORK_ONLY
Graph.QueryError: http(403)
Failed to load collections: Optional(Buy.Graph.QueryError.http(403))
```
Can anyone else tell me what else I need to set up to get details of my store's data in this sample app. 

Also do I need to set Storefront Access token in my app?

Can any one help me to resolve this issue.

Thanks in advance

**Comment by dbart01** [comment]
Are you updating the shop domain to your own domain? The error you're seeing is typical of mismatched shop domain and API key.

**Comment by thousandzerokanika** [comment]
@dbart01 Thanks sir for replying.

 No I use the same apiKey provided by shopify and use the same domain as my shopify account is showing its like myshopname.shopify.com

**Comment by thousandzerokanika** [comment]
Thanks @dbart01 for your suggestion, I have resolved the issue. the wrong apiKey which I used was not related to my shop's sales channels.

**Comment by bornbrie** [comment]
Can I ask which API Key you were using and which one fixed your issue? I'm running in circles with this issue!

**Comment by DebasisDipu** [comment]
Hello experts,

I am new to shopify. Downloaded mobile-buy-sdk and integrate in my project by following the steps given in doc. I use sample app provided with this sdk to test if my store is working or not.

Now in sample app I just replace my apiKey in Client.swift but I am always getting the following error:
Exercising cache policy: NETWORK_ONLY
Graph.QueryError: http(statusCode: 403)
Failed to login customer: []
Please help me, so that i can move forward.

**Comment by dbart01** [comment]
@DebasisDipu Have you also replaced the `shopDomain` with _your_ shop domain?

**Comment by DebasisDipu** [comment]
Hi @dbart01 ,Yes i replaced the shopDomain with my shop domain.
I am not subscribing any plan as I am totally new to Shopify. Once i did my R&D, I will subscribe and build my store.

**Comment by dbart01** [comment]
@DebasisDipu Is the error you're seeing only related to customer login?

**Comment by DebasisDipu** [comment]
@dbart01 I am using the mobile buy SDK inside my application. from the first step I need the access token to go to the product/order list. for that only I need to log in with my store based on the login user of my app.
Even I tried with admin credentials, still, I am getting the same error. 
Do not know where I am doing the mistake

**Comment by DebasisDipu** [comment]
@dbart01 
I created a private app and enable storefront API and mobile buy SDK and grant all the API permission.
I am able to see the list of products through postman but not able to generate an access token to move forward.
Thanks

**Comment by DebasisDipu** [comment]
@dbart01  getting this error after using the storefront access tomen.
Exercising cache policy: NETWORK_ONLY
Failed to login customer: [<CustomerUserError: ["field": <null>, "code": UNIDENTIFIED_CUSTOMER, "message": Unidentified customer]>]

**Comment by dbart01** [comment]
Is the error you're seeing only related to customer login?

**Comment by DebasisDipu** [comment]
@dbart01 I did not try anything apart from this as I was totally stuck in this

**Comment by dbart01** [comment]
Are your product and collections loading?

**Comment by AnmolMalpani** [comment]
> In Admin, inside your private app configuration, locate the `Storefront API` section (generally the bottom section). At the bottom, you'll find `Storefront Access Token` with the following description:
> 
> > Storefront API access tokens are not secret. You can place them in a JavaScript file or any public HTML document.
> 
> Use this token with your shop domain in the SDK.

Hello @dbart01,

Actually i am also implementing this SDK and getting firstly i was getting a error which says StatusCode - 403 and now m getting StatusCode- 404. So can you please tell me that how to use token with shop domain?

**Comment by MVakas** [comment]
> In Admin, inside your private app configuration, locate the `Storefront API` section (generally the bottom section). At the bottom, you'll find `Storefront Access Token` with the following description:
> 
> > Storefront API access tokens are not secret. You can place them in a JavaScript file or any public HTML document.
> 
> Use this token with your shop domain in the SDK.

This worked for me guys.

**Comment by PayalDinc** [comment]
> Storefront Access Token

Can you tell me where to use  Storefront Access Token?

**Comment by PayalDinc** [comment]
I am also facing same issue. Please help 
**Graph.QueryError: http(statusCode: 403)
Failed to load collections: Optional(Buy.Graph.QueryError.http(statusCode: 403))**

I have used my domain and API key. I am trying with sample of Mobile Buy SDK.

**Comment by PayalDinc** [comment]
@dbart01  Mobile Buy SDK works with API or Storefront Access token?

**Comment by MVakas** [comment]
@dbart01 API is a different thing and Storefront Access token is another. You need Storefront Access token to get access to the the Storefront APIs.

**Comment by MVakas** [comment]
@dbart01 Follow all the steps to configure the app, you may be missing something.

**Comment by PayalDinc** [comment]
> @dbart01 API is a different thing and Storefront Access token is another. You need Storefront Access token to get access to the the Storefront APIs.

Can you tell me when to use API key and when to use Storefront Access token ?

**Comment by MVakas** [comment]
> > @dbart01 API is a different thing and Storefront Access token is another. You need Storefront Access token to get access to the the Storefront APIs.
> 
> Can you tell me when to use API key and when to use Storefront Access token ?

Have you enable iOS app on admin portal as well?

**Comment by MVakas** [comment]
<img width="931" alt="Screenshot 2019-02-21 at 2 22 02 PM" src="https://user-images.githubusercontent.com/7447077/57221413-9736fc80-7018-11e9-9294-8f6233bd4ac9.png">

**Comment by MVakas** [comment]
![WhatsApp Image 2019-02-21 at 3 07 25 PM](https://user-images.githubusercontent.com/7447077/57221559-22b08d80-7019-11e9-8d7a-d62418305886.jpeg)

**Comment by PayalDinc** [comment]
@MVakas I have enabled iOS app on admin portal.
I found that Storefront Access token is not authorised so I am confused that to use Storefront Access token is the correct solution or not?
Caution
The Storefront API is an unauthenticated public API.
[https://help.shopify.com/en/api/custom-storefronts/storefront-api]()
