### ISSUE TITLE
Mobile Buy SDK for iOS objective C version

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#795]
Hello everyone,

Can anyone here tell me that If I want mobile buy sdk for iOS in objective c. I follow the steps available here and installed the buy sdk successfully but this sdk is written in swift language and I need its objective c version. Please help if any one can.

Thanks in advance.

**Comment by dbart01** [comment]
The Mobile Buy SDK isn't supported directly in Objective-C. You can still use it, however, you'll need to write your own bridging layer for the `Graph.Client` and models in order to expose them to Objective-C.

**Comment by LadyRanger1992** [comment]
@dbart01 how to create bridging layer for the Graph.Client and models in order to expose them to Objective-C? 
<img width="372" alt="screen shot 2018-08-01 at 5 44 16 pm" src="https://user-images.githubusercontent.com/6637801/43517344-95f5a8a8-95b2-11e8-971f-a298d5569165.png">

**Comment by LadyRanger1992** [comment]
@thousandzerokanika Do you passed this problem?

**Comment by thousandzerokanika** [comment]
@LadyRanger1992  I didn't use bridge-header class as I switched my project from objective c to swift language & when you use swift for mobile buy sdk you didn't need to create any bridge-header. But still if you want to continue with what you are doing right now you can do this as:

you can create bridge-header file by creating a new .h file with name "YourProjectName-Bridging-Header.h" i.e after your project name add  -Bridging-Header.h and import buy sdk pr graph client class in this.

**Comment by LadyRanger1992** [comment]
I tried to add bridge-header file. 
So my project can not see the Graph client class. how to import this into .h file?
