### ISSUE TITLE
Add Product Variant Inventory / Transfer Related Fields

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#796]
We're currently working on supporting product backordering in our shop, **but only if the product has known incoming inventory**. To do this, we would be using several liquid tags available on product variants:

- `variant.inventory_policy`
- `variant.inventory_quantity`
- `variant.incoming`
- `variant.next_incoming_date`

However, none of these fields are currently made available via the Storefront SDK. Because of this, we're blocked on enabling this functionality on our web shop because it would create a scenario where a customer could purchase a product that is out of stock in our app when we don't want them to. For example, since the Storefront SDK only exposes `availableForSale`, and for products who's `inventory_policy` is set to `continue` this value would always be true. We would only want to allow them to purchase the product if `variant.incoming` is also true.

**Comment by dbart01** [comment]
Unfortunately, the Storefront API doesn't expose inventory information beyond `availableForSale`. This is an intentional limitation for enhancing security and preventing bots from leveraging inventory data.

**Comment by cocoahero** [comment]
The Storefront API is authenticated and scoped to a sales channel correct? What threat from bots is there? Any bot would in theory be intentionally created by the shop owner, or at least intentionally given the API access token?

**Comment by EricNetsch** [comment]
@cocoahero Dealt with this issue last year. I guess once a "bot" obtains the public API key they can use the storefront API to get information about the certain products. 

Seems silly and would be a great option for merchants to toggle from their admin dashboard ex "Display Inventory quantity "

**Comment by dbart01** [comment]
Closing. You should use `availableForSale`, now available in the [3.1.6](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.1.6) release.
