### ISSUE TITLE
Manually add a CollectionViewModel in  PageableArray

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#797]
Hi,

I want to classified or divide in different arrays all the product of shopify collection to display them in some specific sections. For this I want to make multiple array of **PageableArray<CollectionViewModel>**. For this I fetch the collectionViewModel one by one from **PageableArray<CollectionViewModel>** collection but now I am unable to add this to a new **PageableArray<CollectionViewModel>**.

Here I am sharing my code too so that you can understand it better. Please find below code:
```swift
if collections.items.count != nil
{
	var i_count = 0
	while (i_count < collections.items.count) {
		if (collections.items[i_count].title.contains("XYZ"))
		{
			**self.selectedCollectionViewModel** = collections.items[i_count]
		}
		i_count += 1
	}
 }
```
Can you tell me how to add **self.selectedCollectionViewModel** (this is declared as **var selectedCollectionViewModel: CollectionViewModel!**) object back to a newly declared **PageableArray<CollectionViewModel>** in iOS swift. 

Thanks in advance

**Comment by dbart01** [comment]
Conceptually, it doesn't make sense to paginate sections separately using the mechanism implemented in the sample app. From a UX perspective, scrolling to the bottom of the table view would indicate that the _last_ section wants to load more items but what does that mean for the other section in the table view?

I would recommend rethinking the UX for this problem. I don't think an array of `PageableArray`s is the correct approach. Also, please keep in mind that the included sample application is a _sample_ implementation provided as-is and is _not_ designed to be a universal fit for every storefront use case. It's purpose is to showcase the functionality of the SDK.
