### ISSUE TITLE
Express Checkout with PayPal button

### ISSUE THREAD

**Issue by H3ndrx** [Shopify/mobile-buy-sdk-ios#799]
Hi, is there a way to add button to iOS app with link to PayPal express? Because right now when I get webUrl to checkout it points to checkout site and there is PayPal button which points to PayPal.
I would like to skip checkout site part and show PayPal login site.
Is this possible?

**Comment by dbart01** [comment]
The SDK is not designed to support direct access to PayPal checkout. What you've described is not currently possible.
