### ISSUE TITLE
Get list of supported shipping countries

### ISSUE THREAD

**Issue by Hans92** [Shopify/mobile-buy-sdk-ios#800]
Is it possible to query for the list of supported shipping countries of my shop?

**Comment by dbart01** [comment]
No, the GraphQL API does not currently expose fields for querying supported shipping countries. I'll leave this open as a feature request.

**Comment by dbart01** [comment]
As of [3.1.6](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.1.6) `Shop` exposes a field `shipsToCountries`, which is an array of ISO country codes that products can be shipped to.
