### ISSUE TITLE
Check Backorder/Preorder in mobile-buy-sdk iOS

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#804]
Hello,

Can you please tell me how can I check the preorder/backorder status of product in mobile-buy-sdk for iOS app.

**Comment by dbart01** [comment]
There's a field on `ProductVariant` that will indicate whether a variant is in stock - `availableForSale`. Unfortunately, the Storefront API doesn't offer more granular control over product inventory.

**Comment by thousandzerokanika** [comment]
Thank you its done
