### ISSUE TITLE
Product Variant images crashing in mobile-buy-sdk for iOS

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#805]
Hello,

I want to fetch product's Variant images in my app. I am using mobile-buy-sdk in my custom iOS app. I fetched the url for variants but the issue is if in case no variant images are available than it returns nil which causing crash in my iOS app. Can you please tell me how to resolve this crashing issue. I tried to set some value when it is nil but I am not able to get this.
Waiting for your response
Thanks

**Comment by dbart01** [comment]
This is an issue outside the scope of the SDK. You'll have to conditionally handle `nil` values appropriately to avoid unwrapping `nil` optionals.
