### ISSUE TITLE
Variant Price

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#806]
Hello,

I am trying to fetch variant data using mobile-buy-sdk for iOS but its not returns any value for Price. Beside price I am fetching titile, name, sky & availableForSale all these are values are available.
Can you please tell me why I am not able to fetch value for key Price.

Thanks

**Comment by dbart01** [comment]
I'm not sure I understand your question. A `ProductVariant` does, indeed, have a `price` field that you can query along with `title`, `name` and `sku`.

**Comment by thousandzerokanika** [comment]
Yes price field is there in ProductVariant. But it does not return any value for iOS. I am getting values for title, sku etc but it is not returning any value for price.

**Comment by dbart01** [comment]
Do you have prices configured for your product's variants?

**Comment by thousandzerokanika** [comment]
Yes variant's price is configured on my shopify account. It is showing in android. the issues is only occurring on iOS end

**Comment by dbart01** [comment]
Can you please paste the raw GraphQL response that indicates a `nil` value for `price`?

**Comment by thousandzerokanika** [comment]
Yes Please check.. the below screenshot..

![121](https://user-images.githubusercontent.com/33921828/35082410-ab64057a-fc3f-11e7-9e57-fffc1dcdd96a.jpg)

**Comment by dbart01** [comment]
Price is a `Decimal`, it's not `nil`. What do you see when you print out the value of `price`?

**Comment by thousandzerokanika** [comment]
Okay sir Got the issue will make it work. Thanks for your quick response.
