### ISSUE TITLE
Option's value in Variants in iOS

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#810]
Hello, I am fetching data for variants in my app. I want to get option value for the variants available on my store. Can you tell me how can I get the option value. Like I have fetched id, title, price, image, sku, availableForSale but I need option value too. Can you please tell me the key for this.

Thanks

**Comment by dbart01** [comment]
Options are found in `Product` not `ProductVariant`.
```graphql
{
  shop {
    products(first: 10) {
      edges {
        node {
          title
          options(first: 10) {
            id
            name
            values
          }
        }
      }
    }
  }
}
```
