### ISSUE TITLE
Product Options

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#812]
Can you please tell me how to fetch Product option in ProductViewModel class. I have wrote code as you told earlier in graphql but I am not able to find the return value of options in ProductViewModel class.

Thanks

**Comment by dbart01** [comment]
You will have to add and map the appropriate values in `ProductViewModel`.

`ProductViewModel` is provided as an example implementation in the sample app. We do not provide support for the sample application.
