### ISSUE TITLE
Ability to Authenticate Order.customerUrl

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#813]
Due to the fact that the storefront API does not expose any attributes on `Order`s regarding fulfillment or shipping status, we are planning on opening the `customerUrl` within a web view of some sort within our app. The problem is that the URL requires the customer to enter their email address to view the details, which doesn't make sense from a UX standpoint if the customer is already signed in to our app.

Is there a way to use the `customerAccessToken` that we already have to pre-authenticate the `URL(Request)`?

**Comment by EricNetsch** [comment]
@cocoahero we recently added the `orderStatusUrl` to the order object if that helps. This was a much better option for us instead of the customerURL option.

**Comment by cocoahero** [comment]
@EricNetsch Correct me if I'm wrong but `orderStatusUrl` is not available in the Storefront SDK GraphQL schema. I still only see `customerUrl`.

**Comment by dbart01** [comment]
As of [3.1.6](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.1.6), `statusUrl` is now available on `Order`.

**Comment by networld301ios** [comment]
these give me like these
![screen shot 2018-08-07 at 11 20 52 am](https://user-images.githubusercontent.com/39612162/43756907-86fb50c4-9a34-11e8-8695-df4418be64bc.png)
