### ISSUE TITLE
Customer Endpoint Returning Null

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#814]
Sometime yesterday, the Storefront API started returning `null` for the `customer` field when requesting it using a `customerAccessToken`.

*Query*:
```
{
  customer(customerAccessToken: "myAccessToken") {
    displayName
  }
}
```
*Response*:
```
{
  "data": {
    "customer": null
  }
}
```

Normally in my experience if the `customerAccessToken` is invalid, I get a `userError` along the lines of `unidentified customer`. Attempts to sign in as a customer using `customerAccessTokenCreate` always succeeds and returns the same access token. Attempts to delete the access token using the `customerAccessTokenDelete` mutation results in an "access denied" error.

```
{
  "data": {
    "customerAccessTokenDelete": null
  },
  "errors": [
    {
      "message": "CustomerAccessTokenDelete access denied",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "customerAccessTokenDelete"
      ]
    }
  ]
}
```

**Comment by dbart01** [comment]
Seems to be a server issue. We're looking into it.

**Comment by dbart01** [comment]
We've address the problem but you'll need to create new customer access tokens to see the effect (login again). Please let me know if the problem persists.

**Comment by mattclough1** [comment]
I'm actually seeing this same error with customerAccessTokenDelete at the moment.

**Comment by dbart01** [comment]
This problem has been address on our backend.
