### ISSUE TITLE
Fuzzy Matching by Field Type

### ISSUE THREAD

**Issue by SkylerNova** [Shopify/mobile-buy-sdk-ios#816]
It seems that when searching for products you can only get options where the word is contained anywhere in the product description, title or any other field. And field matching seems to be an exact match for a specific field. Is there a way to fuzzy match by title only or fuzzy match by handle only or something like that?

**Comment by dbart01** [comment]
Have a look at the [field matching documentation](https://github.com/Shopify/mobile-buy-sdk-ios#field-matching-). Is that sufficient for your use case?

**Comment by SkylerNova** [comment]
Not exactly, I've got the matching working but I want to sort the results after the field match, I looked through the code and there are enum's like ProductSortKeys which has multiple sort values. https://help.shopify.com/api/storefront-api/reference/enum/productsortkeys I just dont know the correct syntax to actually sort the results.

**Comment by dbart01** [comment]
The sorting is not part of your search query. It's a parameter in the GraphQL query. For example:
```graphql
{
  shop {
    products(first: 10, query: "field:query", sortKey: PUBLISHED_AT) {
      edges {
        node {
          ...
        }
      }
    }
  }
}
```

**Comment by SkylerNova** [comment]
Thank You, this is exactly what I was looking for.
