### ISSUE TITLE
Login via custom app

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#820]
Hi, 

I am creating an app using mobile buy sdk of shoplift. I want to integrate user's login/sign up option & want to manage from my app as it is working at website end. I am not a shopify gold user. Is it possible or Do we have api's login from custom app and maintain user's session and record?

My second question is do we have any api for checkout via my custom app ?

Thanks.

**Comment by thousandzerokanika** [comment]
Can anyone help me for this.

**Comment by dbart01** [comment]
Please take a look at the documentation for [customer account](https://github.com/Shopify/mobile-buy-sdk-ios#customer-accounts-) and [checkout](https://github.com/Shopify/mobile-buy-sdk-ios#checkout-).
