### ISSUE TITLE
How to check if product is out of stock or on discount via mobile buy sdk

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#822]
Hello,

I wants to check the products which are out of stock or for sale using mobile-buy-sdk.

My website showing some product out of stock & available with some discount but I am not able to fetch this information in my custom app. Can you please help me out to find its solution.

Thanks.

**Comment by dbart01** [comment]
You can use the `availableForSale` on `ProductVariant`.
