### ISSUE TITLE
Customer accounts

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#824]
I asked you earlier for this but still I have confusions. I want to use user login and signup in my custom iOS app. I checked following shopify link: 

https://help.shopify.com/api/sdks/custom-storefront/mobile-buy-sdk/ios/integration-guide/customers#customer-activation v

but I am not able to get customer sample app. from this link.

Can you please help me out for this issue.

**Comment by thousandzerokanika** [comment]
Can any one help please.

**Comment by aShaforostov** [comment]
Why do you need customer sample app?
By this link, an example of the old SDK v2, which is no longer supported.

Use v3 SDK for your task
https://github.com/Shopify/mobile-buy-sdk-ios#customer-login-

**Comment by aShaforostov** [comment]
This is customer app on v2 SDK
https://github.com/Shopify/mobile-buy-sdk-ios/tree/sdk-2.1/master/Mobile%20Buy%20SDK%20Sample%20Apps/Customers%20App%20-%20Swift

But I do not know if it's working

**Comment by thousandzerokanika** [comment]
@aShaforostov  I have fetched data using this https://github.com/Shopify/mobile-buy-sdk-ios#customer-login-      
link it returns data as require but this response is in raw graphql format & I am not able to get accesstoken as string from this response. 
& thats why I needed that example.

**Comment by dbart01** [comment]
The documentation is an excellent resource. Take a look at [Mutations](https://github.com/Shopify/mobile-buy-sdk-ios#mutations-) for a complete guide on how to work with response objects.
