### ISSUE TITLE
424 Error & “Payment not completed” with Apple Pay in shopify SDK

### ISSUE THREAD

**Issue by surbhihanda06** [Shopify/mobile-buy-sdk-ios#826]
Hello Team,

I always got the error "Payment not completed" with Apple Pay  with the real card.

Here is the payment setting:

When I debuged the code , I have got the payment code from apple pay, and then failed to pay with the error from Shopify SDK API.

Here is the error infomation from the sdk API : (- (NSOperation *)updateCheckout:(BUYCheckout *)checkout completion:(BUYDataCheckoutBlock)block) .

Error Domain=BUYShopifyErrorDomain Code=424 "(null)" UserInfo={errors={

    checkout =     {

        "payment_gateway" =         (

                        {

                code = "processing_error";

                message = "Your payment could not be processed at this time, please try again in a few minutes";

                options =                 {

                    "raw_gateway_error" = "There was an error processing your payment. Please try again.";

                };

            }

        );

    };

}}

So what  should I do to solve the problem.

**Comment by surbhihanda06** [comment]
Can anyone pls help

**Comment by aShaforostov** [comment]
What is gateway your using?

**Comment by surbhihanda06** [comment]
Shopify only

**Comment by aShaforostov** [comment]
You configure payment gateway in "Payment providers"? 

![screen shot 2018-03-23 at 12 11 09](https://user-images.githubusercontent.com/26708110/37823819-50aaaf36-2e93-11e8-9c79-53eb35f77e90.png)

**Comment by surbhihanda06** [comment]
Yes.I have done this.
Any other reason for this error ?

**Comment by CYXie0402** [comment]
@surbhihanda06   I got a error when i create checkout ：
Error creating checkout: Error Domain=BUYShopifyErrorDomain Code=412 "(null)" UserInfo={errors={
    "version_date" =     (
                {
            code = blank;
            message = "can't be blank";
            options =             {
            };
        }
    );
}}

Have you ever seen the same mistake？
