### ISSUE TITLE
Apple Pay- Polling Checkout issue

### ISSUE THREAD

**Issue by surbhihanda06** [Shopify/mobile-buy-sdk-ios#827]
I am trying to make a payment with Apple Pay, but when i do pollingCheckout I get an response.

Checkout is ready . I am getting error this :-

Optional(<QueryRoot: ["node": {
    "__typename" = Checkout;
    order = "<null>";
    orderStatusUrl = "<null>";
    ready = 1;
}]>)

Can you please suggest

**Comment by vinay035** [comment]
@dbart01 can you please help.

**Comment by vinay035** [comment]
Can anyone help?

**Comment by aShaforostov** [comment]
Payment is async operation.

Therefore, I polling payment, not checkout

When you do checkoutCompleteWithTokenizedPayment, you are getting Payment object whose identifier should be polling

```
let paymentQuery = Storefront.buildQuery{ $0
            .node(id: GraphQL.ID(rawValue: paymentID), { $0
                .onPayment(subfields: { $0
                    .ready()
                    .errorMessage()
                    .checkout{ $0
                        .orderStatusUrl()
                        .order{ $0
                            .orderNumber()
                        }
                    }
                })
            })
        }
```

**Comment by dbart01** [comment]
☝️ That's correct, you should be polling the payment since your `Checkout` is returning `ready = 1` already.
