### ISSUE TITLE
Build fail with 160 issues.

### ISSUE THREAD

**Issue by LadyRanger1992** [Shopify/mobile-buy-sdk-ios#829]
I try to install over CocoaPod with build 3.1.3,
XCode 9.3
Deloyment target = 11.0
But it build fail.

**Comment by LadyRanger1992** [comment]
<img width="690" alt="screen shot 2018-04-03 at 10 42 06 am" src="https://user-images.githubusercontent.com/6637801/38228199-607cc40c-372c-11e8-88ed-3678b4f273ef.png">

**Comment by LadyRanger1992** [comment]
<img width="937" alt="screen shot 2018-04-03 at 10 42 50 am" src="https://user-images.githubusercontent.com/6637801/38228206-6b80d6c2-372c-11e8-9a3a-9af34f78af46.png">

**Comment by LadyRanger1992** [comment]
<img width="895" alt="screen shot 2018-04-03 at 10 44 10 am" src="https://user-images.githubusercontent.com/6637801/38228214-75aef00c-372c-11e8-865d-704cadb89d82.png">

**Comment by LadyRanger1992** [comment]
<img width="887" alt="screen shot 2018-04-03 at 10 44 16 am" src="https://user-images.githubusercontent.com/6637801/38228219-8285e876-372c-11e8-9bea-1cbb496f8fd7.png">

**Comment by LadyRanger1992** [comment]
I try to this follow instrcution in CocoaDoc.
My problem is I can not add your git as sub git. Because i using private sever in my company.

What I can do?

Best regard,
Lucas Luu.

**Comment by dbart01** [comment]
Are you attempting to add the SDK as a submodule or are you using CocoaPods? These are mutually exclusive integration alternatives.

**Comment by LadyRanger1992** [comment]
It still crash.
<img width="1280" alt="screen shot 2018-04-17 at 8 42 32 pm" src="https://user-images.githubusercontent.com/6637801/38873414-ec5e59be-427f-11e8-96a0-0e550ba42d1c.png">

**Comment by dbart01** [comment]
Are you linking to `Buy.framework` explicitly? If you've tried both CocoaPods and submodules, that error might a result of some left over submodule configuration.

**Comment by dbart01** [comment]
Try `pod update`

**Comment by LadyRanger1992** [comment]
Yes, I do that. My pod is 3.1.5.
But it crash when running.
<img width="1280" alt="screen shot 2018-04-17 at 11 10 58 pm" src="https://user-images.githubusercontent.com/6637801/38882554-9a48e544-4294-11e8-91e7-93f8d6ed7d2c.png">

**Comment by dbart01** [comment]
I'm sorry, I can't help with that.

**Comment by LadyRanger1992** [comment]
Okie, Thank you.
Please help me what build is most stable. And what it need (Swift compiler version, deloyment target, git version, cocoapods version, etc).
And what time to release new build? I will follow this up.
I don't know why but this time I can not search anything in cocoapods.org and cocoadoc.org. May be it down.

Best Regard.

**Comment by dbart01** [comment]
Every released version is stable. Your issue doesn't seem to be related to the SDK.
