### ISSUE TITLE
OrderLineItem.id Unavailable

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#831]
It appears that the Storefront API / GraphQL schema does not include the IDs for an Order's line items. This is a disparity from the Admin JSON API.

**Comment by rebeccajfriedman** [comment]
@cocoahero Is there a use case where you need this information exposed?

**Comment by cocoahero** [comment]
@rebeccajfriedman we have information attached to the Order object within metafields that are keyed by the line item IDs.

**Comment by phdemontigny** [comment]
@cocoahero Following up on this ticket, ids for [order line items](https://help.shopify.com/en/api/reference/orders/order#line-items-property) are available through the admin API along with [metafield data](https://help.shopify.com/en/api/reference/metafield). Is there a use case for you where it would be preferable to have the ids available through the storefront API?

**Comment by cocoahero** [comment]
It is already unreasonable to ask us to make two network requests to fetch the Order from the Storefront SDK, and one to fetch the metafields via a proxy API service that we had to build to prevent embedding admin API tokens in the app. You're now asking us to make a third?

**Comment by cocoahero** [comment]
> I'm curious what you're trying to accomplish with this app?

A native app version of our web storefront. That's what this SDK was originally designed for, correct? The fact that this SDK has transitioned to utilizing the same storefront APIs designed for simple product marketplace services like Pinterest and Facebook has become its biggest weakness. Many desirable features (such as [metafield access](https://github.com/Shopify/mobile-buy-sdk-ios/issues/97), [checkout scripts](https://github.com/Shopify/mobile-buy-sdk-ios/issues/231), and [product inventory levels](https://github.com/Shopify/mobile-buy-sdk-ios/issues/796)) have become intentionally out of scope.

Due to various limitations or lack of features in the Shopify platform, we've had to resort to building custom private embedded apps that read and write metafields to attach information to things like products, collections, and orders. We use those metafields to then implement features on our online store. It is obviously desired to have those same features available within our native app. Thus our need to access metafield information via a proxy service.

An example of said features include product collection filter UIs, structured product descriptions beyond a singular block of HTML, displaying product videos, etc.

> I'm wondering if there's a better solution here that would simplify the whole flow?

To be frank, our internal discussions of a better solution and our frequent frustrations with the direction of the Shopify platform (in particular its disregard to native mobile apps) has led us to think about migrating off of Shopify for something better. It is unfortunate that we're having to hold back powerful user facing features on our web storefront simply because limitations in this SDK prevent native app parity.

**Comment by eapache** [comment]
> Many desirable features (such as metafield access, checkout scripts, and product inventory levels) have become intentionally out of scope.

Inventory levels are intentionally out of scope as discussed in the ticket you linked since the Storefront API is unauthenticated. Metafield access is potentially in scope, but requires a great deal of internal work first in order to deal with the permissions and security issues described [here](https://github.com/Shopify/js-buy-sdk/issues/168#issuecomment-309049840). Checkout scripts are definitely in scope, they just haven't been implemented yet.

> It is obviously desired to have those same features available within our native app. Thus our need to access metafield information via a proxy service.

Right, this makes total sense and I'll see if I can bump up the priority of fixing metafields properly internally.

**Comment by DrTeePot** [comment]
@cocoahero I believe this information is now available in the SDK 🎉 (Order id's and [product metafields](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.5.1)), so I'm going to close this. Let us know if you need anything else!
