### ISSUE TITLE
 ‘BUYShopifyErrorDomain' error 403 for Fetch Product info call using Buy SDK

### ISSUE THREAD

**Issue by LonappanLinto** [Shopify/mobile-buy-sdk-ios#833]
Please find below store details:

Store name: orig3nsample1
API Key: 180c2xxxxxxxxxxxxxxxxxxxxxxxxxxx
Shop Domain: orig3nsample1.myshopify.com  
App Id: 8

I have also set up a mobile sales channel associated to the store and created an iOS app. I am using BuySDK(version:2.0.1) for integrating the Shopify to the app. It was working fine earlier.

Recently shopify team moved the Mobile app to the Private app section.Right now, I am unable to fetch the product details from the store using the above details.  The api call throws ‘BUYShopifyErrorDomain' error 403.

I created BUYClient object with the above details and uses 'getProductById:(NSNumber *)productId' method to fetch the product details which throws me ‘BUYShopifyErrorDomain' error 403. 
I have also given Read/Write permission for the mobile app to fetch the product information,Shipping info and pricing info.

Please  let me know whether I am missing something on the settings.

Thanks in advance.

**Comment by dbart01** [comment]
It looks like you have another private app called `Mobile App`. Try using its API key that starts with `b684...`, instead. 

**For future reference, please don't disclose your _private_ API keys in the open.**

**Comment by LonappanLinto** [comment]
In my admin screen I can see only one Mobile app in the private app list. Its api key starts with 180c...
<img width="1440" alt="screen shot 2018-04-10 at 7 08 05 pm" src="https://user-images.githubusercontent.com/36474891/38560321-0317e59a-3cf3-11e8-8609-7108a81b6dbd.png">

**Comment by lshapton** [comment]
@LonappanLinto you should still be using the same `storefront_access_token` = `b684...`

**Comment by lshapton** [comment]
The BUYClient object requires a `storefront_access_token` (which was moved from the Mobile App to the private app and is still the same)

**Comment by LonappanLinto** [comment]
@lshapton  @dbart01 It worked once I changed the param value of apiKey to storefront_access_token. 

I have one more store which is works fine without this change of value.The only difference between the stores is one of them is in test mode.

So can you please tell me why it is working for one store with api key and not working for the other?The latter one requires storefront_access_token.
