### ISSUE TITLE
Combine duplicate Model types (Storefront.ProductEdge + Storefront.Product)

### ISSUE THREAD

**Issue by EricNetsch** [Shopify/mobile-buy-sdk-ios#836]
The SDK has duplicate model types for every object (products, variants, collections etc). Each should be taken care of at the SDK level and combined into one single model type. Having 2 model types for each object is causing inconsistency and confusion while building out the business logic in our production apps.

Examples: 
- Storefront.ProductEdge and  Storefront.Product have all the same data and usage.
- Storefront.ProductVariantEdge and Storefront.ProductVariant have all the same data and usage.
- Storefront.ProductCollectionEdge and Storefront.Collection have all the same data and usage.
Etc....

These models should all be combined to make the SDK well architected and easy to use.
This is a side effect of GraphQL that needs to be addressed at the SDK level not dealt with in the app logic.

Happy to help in any way.

@bgulanowski @dbart01 @fananta @andrew-evershed

**Comment by dbart01** [comment]
I agree with you that in theory, it might be easier to work with an SDK that didn't expose connections and edges. However, the SDK was designed as a thin convenience wrapper around existing models.

The Mobile Buy SDK is built on top of GraphQL and a schema defined by Shopify in the Storefront API. These models are part of a schema that describes the relationships between entities and facilitates pagination in GraphQL. These are not arbitrary models that were introduced by the SDK. Instead, they are a requirement.

You can read more about [Connections specification in GraphQL](https://facebook.github.io/relay/graphql/connections.htm).

**Comment by dbart01** [comment]
I'm not sure what you mean here. Why do you want to "combine both models"? In what use case is that a requirement?

**Comment by EricNetsch** [comment]
@dbart01 Look at the sample project. The model ProductViewModel only accepts Storefront.ProductEdge and not Storefront.Product. 

What is the recommended approach for the ProductViewModel to accept both  Storefront.Product and Storefront.ProductEdge?

**Comment by dbart01** [comment]
`ProductViewModel` isn't an SDK concept. It's a sample app model that is designed to work for sample app use cases.

There is no recommended approach for consuming `ProductViewModel` with both models because they serve two completely different purposes. A `ProductEdge` describes the product _location_ in the connection using the `cursor`, where as the `Product` describes the properties of a storefront product itself. How can you create a single representation from 2 different models that have no overlapping properties? 

I encourage you to have a look at the GraphQL spec, it describes the concept of connections and edges far better than I can convey here.

**Comment by EricNetsch** [comment]
@dbart01  I'm aware that ProductViewModel isn't part of the SDK but we are trying to figure out a workaround to create a model that accepts both types Storefront.ProductEdge and Storefront.Product. 

This has proven to be quite complex so any help would be greatly appreciated. 

Again, I think ideally developers shouldn't have to deal with advanced iOS modeling issues when using the SDK without a proper sample for this case. Fetching collections and products by ID is certainly not an edge-case.

Can you give me some hints on how to accept both SDK models types into the same view model?
Thanks,

**Comment by ArchieGoodwin** [comment]
@EricNetsch if this still interesting then I've made so to convert from Product to ProductEdge: 

                let node = ["node": product.fields, "cursor": "111"] as [String : Any]
                let model = try! Storefront.ProductEdge(fields: node)
