### ISSUE TITLE
Checkout issue

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#840]
I am not able to call "completeCreateCheckout" to make checkout via webcheckout in iOS. Can you please tell me what is the solution for this..

**Comment by dbart01** [comment]
GitHub issues is not a place for how-to questions. It is reserved for **issues**, **bugs** or **feature requests** in the SDK. If you require help using or implementing the SDK, please make use of our [developer forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology/). 

If you do find that SDK output doesn't match your expectations, it is possible you've discovered an issue. In that case, use the issue template to provide a **detailed breakdown** of your specific problem. The information you've provided is not sufficient for us to help you.
