### ISSUE TITLE
Apple Pay - The certificate used to sign your request is invalid

### ISSUE THREAD

**Issue by CookieKaze** [Shopify/mobile-buy-sdk-ios#843]
Hi, I am trying to integrate Apple Pay but have run into an issue with the order ending up in "Abandoned checkouts" rather than under Orders. The error given is 

> The certificate used to sign your request is invalid. For help troubleshooting, please visit https://stripe.com/docs/apple-pay/apps#troubleshooting.

This appears to be related to the following issues but neither solutions are working:
https://github.com/Shopify/mobile-buy-sdk-ios/issues/808
https://github.com/Shopify/mobile-buy-sdk-ios/issues/753

I have generated the certificate using the CSR file provided from admin > apps > Manage private apps > Storefront API > Mobile Buy SDK (iOS). The app builds and runs without any issues. Deleting the merchant ID and regenerating the certificate did not work.

**Additional Information:**
- Payment provider is Shopify Payments (powered by Stripe)
- SDK version is 3.1.5
- Payment authorization is on manual (tested with automatic and didn't work)
- Doing a query for supportedDigitalWallets in the shop shows support for ApplePay

I feel like I am missing an additional step but currently at a lost right now. Any help is much appreciated. Thanks.

![screen shot 2018-04-25 at 2 17 38 pm](https://user-images.githubusercontent.com/22121937/39265088-5d01068e-4894-11e8-9db9-c79809f022a8.png)

**Comment by CookieKaze** [comment]
Hi Dima, thanks for the fast reply. 

I can confirm that I see the full name, address, city, province, zip, country and phone number under the shipping address section of the order. The billing address is also populated but with no phone number. Clicking on the "View map" link brings up the correct latitude and longitude.

Is there another way to confirm?

**Comment by dbart01** [comment]
Sorry, I wasn't very clear. Before `checkoutCompleteWithTokenizedPayment` is called, are you updating the checkout object with appropriate mutations as shown in the sample app? Because of how Apple Pay vends information about the customer, not all of it is available at once. The checkout needs to be updated incrementally and on completion in order to contain all the required fields. Before you call `checkoutCompleteWithTokenizedPayment` just ensure all fields are being updated as shown in the sample app.

**Comment by CookieKaze** [comment]
Hi Dima, 

I am updating the full shipping address and email during `didAuthorizePayment` similar to the sample app before calling `checkoutCompleteWithTokenizedPayment`. Ran another test and the order still ended up in abandoned cart even though `if let payment = payment, checkout.paymentDue == payment.amount` is causing a `completeTransaction(.success)`

**CartViewController:**
```
func paySession(_ paySession: PaySession, didAuthorizePayment authorization: PayAuthorization, checkout: PayCheckout, completeTransaction: @escaping (PaySession.TransactionStatus) -> Void) {
    
    guard let email = authorization.shippingAddress.email else {
      print("Unable to update checkout email. Aborting transaction.")
      completeTransaction(.failure)
      return
    }
    
    print("Updating checkout shipping address...")
    ShopifyClient.shared.updateCheckout(checkout.id, updatingCompleteShippingAddress: authorization.shippingAddress) { updatedCheckout in
      guard let _ = updatedCheckout else {
        completeTransaction(.failure)
        return
      }
      
      print("Updating checkout email...")
      ShopifyClient.shared.updateCheckout(checkout.id, updatingEmail: email) { updatedCheckout in
        guard let _ = updatedCheckout else {
          completeTransaction(.failure)
          return
        }
        
        print("Checkout email updated: \(email)")
        print("Completing checkout...")
        ShopifyClient.shared.completeCheckout(checkout, billingAddress: authorization.billingAddress, applePayToken: authorization.token, idempotencyToken: paySession.identifier) { payment, errors in
          if let payment = payment, checkout.paymentDue == payment.amount {
            print("Checkout completed successfully.")
            completeTransaction(.success)
          } else {
            completeTransaction(.failure)
          }
        }
      }
    }
  }
```

**Client:**
```
@discardableResult
  func updateCheckout(_ id: String, updatingCompleteShippingAddress address: PayAddress, completion: @escaping (CheckoutViewModel?) -> Void) -> Task {
    let mutation = ShopifyClientQuery.mutationForUpdateCheckout(id, updatingCompleteShippingAddress: address)
    let task     = self.client.mutateGraphWith(mutation) { response, error in
      error.debugPrint()
      
      if let checkout = response?.checkoutShippingAddressUpdate?.checkout,
        let _ = checkout.shippingAddress {
        completion(checkout.viewModel)
      } else {
        completion(nil)
      }
    }
    
    task.resume()
    return task
  }
``` 

```
@discardableResult
  func updateCheckout(_ id: String, updatingEmail email: String, completion: @escaping (CheckoutViewModel?) -> Void) -> Task {
    let mutation = ShopifyClientQuery.mutationForUpdateCheckout(id, updatingEmail: email)
    let task     = self.client.mutateGraphWith(mutation) { response, error in
      error.debugPrint()
      
      if let checkout = response?.checkoutEmailUpdate?.checkout,
        let _ = checkout.email {
        completion(checkout.viewModel)
      } else {
        completion(nil)
      }
    }
    
    task.resume()
    return task
  }
```

```
func completeCheckout(_ checkout: PayCheckout, billingAddress: PayAddress, applePayToken token: String, idempotencyToken: String, completion: @escaping (PaymentViewModel?, [Storefront.UserError]?) -> Void) {
    let mutation = ShopifyClientQuery.mutationForCompleteCheckoutUsingApplePay(checkout, billingAddress: billingAddress, token: token, idempotencyToken: idempotencyToken)
    
    let task = self.client.mutateGraphWith(mutation) { response, error in
      error.debugPrint()
      
      if let payment = response?.checkoutCompleteWithTokenizedPayment?.payment {
        print("Payment created, fetching status...")
        self.fetchCompletedPayment(payment.id.rawValue) { paymentViewModel in
          completion(paymentViewModel?.viewModel, response?.checkoutCompleteWithTokenizedPayment?.userErrors)
        }
      } else {
        completion(nil, response?.checkoutCompleteWithTokenizedPayment?.userErrors)
      }
    }
    
    task.resume()
  }
```

**Queries:**
```
static func mutationForUpdateCheckout(_ id: String, updatingCompleteShippingAddress address: PayAddress) -> Storefront.MutationQuery {
    
    let checkoutID   = GraphQL.ID(rawValue: id)
    let addressInput = Storefront.MailingAddressInput.create(
      address1:  address.addressLine1.orNull,
      address2:  address.addressLine2.orNull,
      city:      address.city.orNull,
      country:   address.country.orNull,
      firstName: address.firstName.orNull,
      lastName:  address.lastName.orNull,
      phone:     address.phone.orNull,
      province:  address.province.orNull,
      zip:       address.zip.orNull
    )
    
    return Storefront.buildMutation { $0
      .checkoutShippingAddressUpdate(shippingAddress: addressInput, checkoutId: checkoutID) { $0
        .userErrors { $0
          .field()
          .message()
        }
        .checkout { $0
          .fragmentForCheckout()
        }
      }
    }
  }
``` 

```
static func mutationForUpdateCheckout(_ id: String, updatingEmail email: String) -> Storefront.MutationQuery {
    return Storefront.buildMutation { $0
      .checkoutEmailUpdate(checkoutId: GraphQL.ID(rawValue: id), email: email) { $0
        .userErrors { $0
          .field()
          .message()
        }
        .checkout { $0
          .fragmentForCheckout()
        }
      }
    }
  }
```

```
static func mutationForCompleteCheckoutUsingApplePay(_ checkout: PayCheckout, billingAddress: PayAddress, token: String, idempotencyToken: String) -> Storefront.MutationQuery {
    
    let mailingAddress = Storefront.MailingAddressInput.create(
      address1:  billingAddress.addressLine1.orNull,
      address2:  billingAddress.addressLine2.orNull,
      city:      billingAddress.city.orNull,
      country:   billingAddress.country.orNull,
      firstName: billingAddress.firstName.orNull,
      lastName:  billingAddress.lastName.orNull,
      province:  billingAddress.province.orNull,
      zip:       billingAddress.zip.orNull
    )
    
    let paymentInput = Storefront.TokenizedPaymentInput.create(
      amount:         checkout.paymentDue,
      idempotencyKey: idempotencyToken,
      billingAddress: mailingAddress,
      type:           CheckoutViewModel.PaymentType.applePay.rawValue,
      paymentData:    token
    )
    
    return Storefront.buildMutation { $0
      .checkoutCompleteWithTokenizedPayment(checkoutId: GraphQL.ID(rawValue: checkout.id), payment: paymentInput) { $0
        .userErrors { $0
          .field()
          .message()
        }
        .payment { $0
          .fragmentForPayment()
          .errorMessage()
        }
      }
    }
  }
```

**Comment by CookieKaze** [comment]
I tried to generate a new certificate using a new CSR from the Shopify Admin panel. Upon uploading the certificate from Apple the admin page refreshes and never loaded properly. It also generated a new CSR file and will do so again after a manual page refresh. I had to go through Apps > Manage private apps in order to get the page to load properly again. 

Could the generation of a new CSR cause the invalid certificate error to be thrown?

**Comment by dbart01** [comment]
@CookieKaze It possible, I supposed. Have you tried redoing the entire Apple Pay setup flow from beginning to end? Perhaps the "turn it off, turn it on again" approach might resolve this issue. Your code above looks okay, which leads me to believe it may be a misconfiguration of some kind. Either way, unrelated to the SDK itself. We are still looking into this internally, at the moment.

**Comment by CookieKaze** [comment]
Hey Dima, 

I actually found the issue. We were using the wrong merchant ID when generating the PaySession. I've updated the ID and the order when though (although flagged and cancelled by Riskified as a fraudulent order). All it good. Thanks for all your help.

**Comment by dbart01** [comment]
Perfect. Glad to hear 👍
