### ISSUE TITLE
Apply and remove Discount codes

### ISSUE THREAD

**Issue by lucamegh** [Shopify/mobile-buy-sdk-ios#844]
I know it’s possibile to apply a discount code using checkoutDiscountCodeApply mutation but it would be useful for the Checkout object to provide a discountCode node as well (so we don’t have to manually track whether a discount code has been applied or not). As for the removal, as far as I can see, it is not covered at all. I guess the only way to remove a discount code from a checkout is to create a new checkout.

I believe these features would be much appreciated by the developer community.

**Comment by dbart01** [comment]
Thanks for point this out. We are currently exploring how discount management can be improved in the Storefront API / SDK. Will keep this open to track progress.

**Comment by dbart01** [comment]
Discount code removal is now available in the [latest release](https://github.com/Shopify/mobile-buy-sdk-ios/releases/latest). Please feel free to create a separate issue for exposing the applied discount code node, the work on that is in progress.
