### ISSUE TITLE
How to change currency in the test app??

### ISSUE THREAD

**Issue by nok91** [Shopify/mobile-buy-sdk-ios#845]
**Please complete the checklist before filing an issue:**

- [x] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).
- [ ] Is this something you can **debug and fix**? Create a pull request and contribute! Bug fixes and documentation fixes are welcome. You can read our [contribution](https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/CONTRIBUTING.md) guidelines for more details.

None of the above? Create an issue. Be sure to include all the necessary information for us to understand and reproduce the problem:

- Screenshot (if applicable)
- Stack trace, if the problem is related to a crash in the SDK
- Version of the SDK are you using
- What is the expected behaviour?
- What is happening instead?

If there's not enough information to address the problem, we'll tag your issue with `information required` and close it until futher information is provided.

**Comment by nok91** [comment]
How can I change currency in the Sample app??

**Comment by dbart01** [comment]
The currency isn't determined by the sample app. It's defined by the shop. You'll have to change the currency in your shop.

**Comment by nok91** [comment]
Thank you for the quick Answer!
Where about in the Shop? It's already in GBP the online store, but the app it's still in USD!

**Comment by nok91** [comment]
Sorted by adding
**formatter.currencyCode = "GBP"**

Thanks you so much!!
