### ISSUE TITLE
Storefront.CheckoutQuery doesn't let you specify the billing address.

### ISSUE THREAD

**Issue by lucamegh** [Shopify/mobile-buy-sdk-ios#846]
`Storefront.CheckoutQuery` doesn't let you specify the billing address, only the shipping address. Same thing for the `Storefront.Checkout` and `Storefront.Order` objects: they only expose the shipping address.

I understand that most times people set the same address to both shipping and billing but that might not always happen.

**Comment by dbart01** [comment]
Thanks for point this out. We'll look into it.

**Comment by lucamegh** [comment]
I found out you can actually specify the billing address in the [Payment object](https://help.shopify.com/api/storefront-api/reference/object/payment).
