### ISSUE TITLE
Login Page Creation , Registration Page 

### ISSUE THREAD

**Issue by nagarajanpn** [Shopify/mobile-buy-sdk-ios#849]
How to create login page ? Pl share any link ?

**Comment by dbart01** [comment]
Do you have a specific issue with the SDK?

**Comment by nagarajanpn** [comment]
Am beginner. Am try to add below code am getting errors 
Cannot convert value of type 'Input<_>.Type' to expected argument type 'Storefront.CustomerAccessTokenCreateInput'

Please share any sample project link.

**Comment by dbart01** [comment]
Using this SDK requires a basic knowledge of Swift and existing Apple frameworks. We cannot offer that here.

For SDK integration, a good place to start would be [our comprehensive documentation](https://github.com/Shopify/mobile-buy-sdk-ios#getting-started-). It'll provide all the background you'll need to start build your custom storefront. The SDK also ships with a [sample app](https://github.com/Shopify/mobile-buy-sdk-ios/tree/master/Sample%20Apps/Storefront) that will help you get started.

**Comment by nagarajanpn** [comment]
Ok Thank you! Use this SDK i gave registration details and user name and password but it is not reflected in website. Whatever we created in mobile or shopify website it should reflect. Example like amazon..
