### ISSUE TITLE
Support for iDEAL checkouts?

### ISSUE THREAD

**Issue by isaachinman** [Shopify/mobile-buy-sdk-ios#851]
After scouring through all of the Shopify documentation I could find, I still have not found a official suggestion as to how to support iDEAL payments in a mobile app when using Shopify.

I would think the easiest way would be to open a webview to an iDEAL payment process, and then deep link back into the app when the process is complete. In that case, I would need a way to manually process the `checkoutComplete` event.

Is there a way to mark a checkout as complete, wherein payment has taken place outside of the three main methods (Apple Pay, Web, Credit Card)?

**Comment by dbart01** [comment]
There is currently no way mark a checkout as complete outside the 3 primary methods. Unfortunately, this isn't something we'll be considering in the near future.

**Comment by isaachinman** [comment]
Care to explain why?

**Comment by dbart01** [comment]
This isn't something determined by the SDK, but rather our Storefront API that powers it. Since the API doesn't support 3rd party gateway checkout completion, there isn't much we can do on the SDK level at this time.
