### ISSUE TITLE
checkoutLineItemsUpdate inventory issue

### ISSUE THREAD

**Issue by patelgaurav4u** [Shopify/mobile-buy-sdk-ios#852]
We have update lineitem quantity greater than available count and not getting any error.

this scenario work with `checkoutCreate` but not work with `checkoutLineItemsUpdate`

**Comment by patelgaurav4u** [comment]
@dbart01 any update?

**Comment by dbart01** [comment]
Can you please clarify the expected and actual outcome for each of those mutations?

**Comment by patelgaurav4u** [comment]
Item1: Stock in Inventory = 3
Item2: Stock in Inventory = 1

First we have create checkout with line items.

item1: Quantity 1
item2: Quantity 1

then after we have other screen for edit quantity.

item1: Quantity 5
item2: Quantity 1

 for this we are use "checkoutLineItemsUpdate" using checkout id reference.

in this case "no error came" . but actually api needs to give error for quantity is not available

**Comment by dbart01** [comment]
Do you get an error if you create a checkout with the items below?

item1: Quantity 100
item2: Quantity 100

**Comment by patelgaurav4u** [comment]
yes we got error on create checkout

**Comment by patelgaurav4u** [comment]
@dbart01 any update ?

**Comment by dbart01** [comment]
We're looking into this. I'll update the issue when I have more information to share.

**Comment by networld301ios** [comment]
can you provide code for checkoutLineItemsUpdate ?

**Comment by osamie** [comment]
Hello @networld301ios, here is our API documentation for `checkoutLineItemsReplace` mutation. 
https://shopify.dev/docs/storefront-api/reference/mutation/checkoutlineitemsreplace?api[version]=2020-01

**Comment by osamie** [comment]
@patelgaurav4u Please note that checkout create no longer does inventory validation as described in this GH issue. 
Also note we've added the ability to track inventory and it [will be available in the Storefront API as of April 2020](https://shopify.dev/changelog/inventory-quantity-available-on-storefront-graphql-api) as `ProductVariant.quantityAvailable`! 

Check out the [Storefront API ProductVariant API reference for `2020-04`](https://shopify.dev/docs/storefront-api/reference/object/productvariant?api[version]=2020-04). 

Note that this field will require the new `unauthenticated_read_product_inventory` scope as per the settings in the private app. 

This SDK will be updated shortly after the full release in early April. I'll leave this issue open until it's shipped to the SDK, but please let us know if you don't think this will help address your flash sale issue.
