### ISSUE TITLE
CheckoutCompleteWithCreditCard access denied

### ISSUE THREAD

**Issue by patelgaurav4u** [Shopify/mobile-buy-sdk-ios#853]
Hello,
we are create private app and working fine with all mutation .
create check out and all thing working fine.
in our admin we have set payment gateway as Shopify Payments,
we have check with test mode and live mode for CheckoutCompleteWithCreditCard mutation.

please suggest where is issue

**Comment by aShaforostov** [comment]
Hello) It's a bug of Shopify

Write in the topic your store and name of private app


 https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/bug-access-denied-calling-checkoutcompletewithcreditcard-from-ios-app-478115

**Comment by patelgaurav4u** [comment]
any other way to contact shopify ?

**Comment by patelgaurav4u** [comment]
@aShaforostov i have post on that forum but after 5 days goes and not getting any response

**Comment by patelgaurav4u** [comment]
@dbart01 can you please help for clear my issue?

**Comment by networld301ios** [comment]
I have also posted 3 days ago but didn't get reply still waiting.

I have also created new issue 2 days ago but still no reply.
check issue: https://github.com/Shopify/mobile-buy-sdk-ios/issues?utf8=%E2%9C%93&q=CheckoutCompleteWithCreditCard

**Comment by Abhishek05media** [comment]
hello ,
facing a same issue. @dbart01 could you fix it ?
Private App: "tasangs" & Domain:"https://tasanga-group.myshopify.com"
