### ISSUE TITLE
Can't get specific Node using it's ID

### ISSUE THREAD

**Issue by shemchavez** [Shopify/mobile-buy-sdk-ios#856]
- Screenshot (if applicable)
![screen shot 2018-05-22 at 4 17 23 pm](https://user-images.githubusercontent.com/19364885/40350389-3bcb3590-5ddc-11e8-97ec-29abf93828b0.png)

- Version of the SDK are you using
3.1.3

- What is the expected behaviour?
Get the Product with ID 1308443410490
- What is happening instead?
MobileBuySDK.Graph.QueryError.invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "Argument \'id\' on Field \'node\' has an invalid value. Expected type \'ID!\'.", line: nil, column: nil)]

What's wrong with my query? Newbie here

**Comment by aShaforostov** [comment]
You must send ID in GraphQL format (gid://shopify/Product/"+targetID) converted to Base64 string
Example: Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzEyMzQ1Ng==
