### ISSUE TITLE
Shopify web checkout not working

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#858]
I am trying to make web checkout in ios swift but it always showing "Failed to create checkout". I also tried storefront sample app too but that app too showing the same error can you please help me to resolve this issue.

**Comment by dbart01** [comment]
What are the steps to reproduce your problem?

**Comment by thousandzerokanika** [comment]
I just follow the checkout method 

let cartItems = CartController.shared.items
        Client.shared.createCheckout(with: cartItems) { checkout in
            print("check",checkout?.webURL)
            guard checkout != nil else {
                print("Failed to create checkout.")
                return
            }
            
            let completeCreateCheckout: (CheckoutViewModel) -> Void = { checkout in
                self.openSafariFor(checkout)
            }

and it will always returns checkout nil

**Comment by thousandzerokanika** [comment]
Can you please help me ?

**Comment by thousandzerokanika** [comment]
Sorry.. I found the mistake.. its working

 but now I am facing another issue.. When I add more them one item in my cart it not returns me checkout url. i.e. I have 5 items in my cart and I have added my cart's data to CartController but it again returns nil or checkout url and working fine when I have only one item in my cart.

Can you please tell me how to send multiple items for check out.

**Comment by dbart01** [comment]
Sounds like something is wrong with your implementation, not the checkout. Please open a separate issue if this is a problem with the SDK.
