### ISSUE TITLE
Can't update checokut using PayPostalAddress from delegate in Apple Pay

### ISSUE THREAD

**Issue by shemchavez** [Shopify/mobile-buy-sdk-ios#860]
I'm having a problem updating the checkout using the `PayPostalAddress` from the delegate:

```swift
func paySession(_ paySession: PaySession, didRequestShippingRatesFor address: PayPostalAddress, checkout: PayCheckout, provide: @escaping (PayCheckout?, [PayShippingRate]) -> Void)
```

I've copied the sample code still it requires `lastName` and `address1` of the shipping address. What did I miss?

My code:

![1](https://user-images.githubusercontent.com/19364885/40975365-4b10d7d6-68fd-11e8-8ef1-96f5ae8e242d.png)

Sample code:

![2](https://user-images.githubusercontent.com/19364885/40975371-4d41da96-68fd-11e8-83d4-0d4cf081f38d.png)

**Comment by dbart01** [comment]
The problem is likely in the order of operations. Your snippet of the sample app shows only a fraction of the work that goes into creating and updating a `Checkout`. The `lastName` and `address1` fields aren't blank in the sample app. You're correct that they aren't being set with _this_ mutation, but they are being set somewhere _before_ this mutation.

The error you're receiving is valid. Those two fields are required.

**Comment by shemchavez** [comment]
In my implementation of Apple Pay, the order of operations happens is:

1. Creation of checkout (No shipping rate, No shipping address, No email)
2. Execute this:

![3](https://user-images.githubusercontent.com/19364885/40976209-f0e5e9e2-68ff-11e8-94c1-42ccab689086.png)

3. (If there's an existing shipping address in Apple Pay the last one set will be selected by default right?)
4. We will update the checkout using the **PayPostalAddress** from the delegate
5. Get the shipping rates from the updated checkout

**Comment by dbart01** [comment]
It seems that somewhere in you're flow, you're not setting the `firstName` or `address1`.

**Comment by shemchavez** [comment]
So it's **required** in Apple Pay implementation? I thought that you can get the last name & address 1 from what you input in Shipping. No need to set before opening the Apple Pay Modal

![4](https://user-images.githubusercontent.com/19364885/40977722-5a68b274-6904-11e8-9571-a8d882d172ba.png)

**Comment by dbart01** [comment]
No, it's a Shopify requirement. Not Apple Pay. The error you're getting is from the mutation, not the Apple Pay dialog.

**Comment by shemchavez** [comment]
Then my question is now answered. Thanks, @dbart01 for fast response. Will star this one 👍
