### ISSUE TITLE
Apple Pay - How is cart total value calculated?

### ISSUE THREAD

**Issue by CookieKaze** [Shopify/mobile-buy-sdk-ios#861]
When checking out with Apple Pay, the "Cart Total" is incorrect when the quantity of an item is greater than 1. The correct total shows up initially but after Apple Pay finish processing and prompts for fingerprint confirmation the cart total is calculated incorrectly. 

For example:
Item A: $5.00 * 2 (quantity) = $10 
Item B: $2.00 * 4 (quantity) = $8

Correct Total: $18
Cart Total shows: $18 to start but then changes to $52 ($10 * 2 + $8 * 4)

All other values are correct (subtotal, shipping, grand total)

**Additional Information:**
- SDK version is 3.1.5
- Passing no payItems will still result in the same incorrect value
- Totals are showing up correctly when going through web checkout

```
let lineItems   = checkout.lineItems
    var payItems = [PayLineItem]()
    
    for item in lineItems.edges {
      let quantity = Int(item.node.quantity)
      let individualPrice = item.node.variant!.price
      payItems.append(PayLineItem(price: individualPrice, quantity: quantity))
    }
    
    let payCheckout = PayCheckout(
      id:              checkout.id.rawValue,
      lineItems:       payItems,
      discount:        nil,
      shippingAddress: nil,
      shippingRate:    nil,
      subtotalPrice:   checkout.subtotalPrice,
      needsShipping:   checkout.requiresShipping,
      totalTax:        checkout.totalTax,
      paymentDue:      checkout.paymentDue
    )
    
    let paySession      = PaySession(shopName: shopName, checkout: payCheckout, currency: payCurrency, merchantID: ShopifyClient.shared.merchantID)
    paySession.delegate = self
    self.paySession     = paySession
    paySession.authorize()
```

![image uploaded from ios 18](https://user-images.githubusercontent.com/22121937/41045889-5445c472-6977-11e8-86f3-d5ab51ee20b8.png)

**Comment by dbart01** [comment]
Are you able to reproduce this in the sample app?

**Comment by CookieKaze** [comment]
Yes. I was able to repro on the sample app.
<img width="476" alt="screen shot 2018-06-06 at 11 44 03 am" src="https://user-images.githubusercontent.com/22121937/41049455-f7f71984-697e-11e8-9c85-3ec6d18329e8.png">

**Comment by dbart01** [comment]
I've confirmed the issue, fix is coming shortly.

**Comment by CookieKaze** [comment]
Could we get more information on what is causing the issue or where to look?

**Comment by dbart01** [comment]
@CookieKaze Have a look [here](https://github.com/Shopify/mobile-buy-sdk-ios/pull/862/files).

**Comment by CookieKaze** [comment]
@dbart01  Unfortunately this only fixes the issue if the user does not update their shipping address. Once a shipping address is added the cart total reverts back to the incorrect value.

**Comment by dbart01** [comment]
@CookieKaze I'm not able to reproduce the issue. Please make sure you're running a clean build.

**Comment by CookieKaze** [comment]
Okay, so I tried a clean, a build clean, erasing all content from my simulator, as well as cloning the repo again.

`PayLineItem(price: item.individualPrice, quantity: item.quantity)`

Still the same issue. Here is a screen recording of the checkout process with the incorrect cart total. This happens when a shipping address is selected. Passing in an empty array of PayLineItem will not have any effect on the cart total after it finishes processing the shipping address. 

[(https://www.dropbox.com/s/wxm57xf7o7fxbba/ApplePay861.mov?dl=0)](url)

**Comment by dbart01** [comment]
I'm going through exactly the same steps using the same products, shop, etc to no avail. Can you try injecting a few breakpoints to see where this value is coming from?

**Comment by CookieKaze** [comment]
The sample app is using the total price when generating the PayLineItems under the CheckoutViewModel.

```
let payItems = self.lineItems.map { item in
    PayLineItem(price: item.totalPrice, quantity: item.quantity) 
}
```

**Comment by dbart01** [comment]
It already included [that fix](https://github.com/Shopify/mobile-buy-sdk-ios/pull/862/files#diff-c4ce163591010df70bd8092ea1c3f7a4R34).
