### ISSUE TITLE
Internal Error in `completeCheckoutUsingCreditCard`

### ISSUE THREAD

**Issue by dbart01** [Shopify/mobile-buy-sdk-ios#866]
I'm using BuySDK for iOS.

While I try to call Client.shared.completeCheckout using credit card, I receive the following error

```
Graph.QueryError: invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "Internal error. Looks like something went wrong on our end.
Request ID: 8ab875d6-0000-4c40-8f78-0f82b9d453a9 (include this in support requests).", line: nil, column: nil)])
```

The request ID is `8ab875d6-0000-4c40-8f78-0f82b9d453a`

VaultID: `west-961ebf7a6fa3d07f85201ca8476bf8c4` (the payment token)

**Comment by rebeccajfriedman** [comment]
Unfortunately, the request ID has expired, so we cannot investigate. Please create a new issue if you are still experiencing this problem.
