### ISSUE TITLE
payment using Credit card option

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-ios#870]
hi..
i am using current latest sdk . i want to payment integration using credit card option. can you provide code for generating credit card tokens. 

i am getting code from 
https://github.com/Shopify/mobile-buy-sdk-ios#card-client-

but i can't understand how to initialized  below variable

 let settings: Storefront.PaymentSettings
 let cardClient: Card.Client

**Comment by dbart01** [comment]
You have to [create a client](https://github.com/Shopify/mobile-buy-sdk-ios#graphclient-) and query for payment settings. The equivalent GraphQL query looks like this:

```graphql
{
  shop {
    paymentSettings {
      // fields you care about
    }
  }
}
```
