### ISSUE TITLE
enable to find default  Address from multiple Addresses.

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-ios#875]
hi
i am try to getting default address from multiple addresses. using below query 

```swift
 let query = Storefront.buildQuery { $0
            .customer(customerAccessToken: accesstoken)
            { $0
                .addresses(first: 10) { $0
                    .edges { $0
                        .node { $0
                            .id()
                            .address1()
                            .address2()
                            .city()
                            .province()
                            .provinceCode()
                            .country()
                            .zip()
                        }
                    }
                }
            }
        }
```

can you give a field for as a default address.

**Comment by aShaforostov** [comment]
let query = Storefront.buildQuery { $0
            .customer(customerAccessToken: "")
            { $0
                .defaultAddress{ $0
                    .address1()
                    .address2()
                }
                .addresses(first: 10) { $0
                    .edges { $0
                        .node { $0
                            .id()
                            .address1()
                            .address2()
                            .city()
                            .province()
                            .provinceCode()
                            .country()
                            .zip()
                        }
                    }
                }
            }
        }

**Comment by networld301ios** [comment]
thanks...
it's work but i want also change default address. can you help for these

**Comment by aShaforostov** [comment]
You can get default address with previous query change address object and then update 

```
let mutation_UpdateAddress = Storefront.buildMutation{ $0
            .customerAddressUpdate(customerAccessToken: "token", id: GraphQL.ID(rawValue: "ID"), address: mailingAddressInputFrom, { $0
                .customerAddress{ $0
                    .id()
                }
                .userErrors{ $0
                    .field()
                    .message()
                }
            })
            
        }
```

Address object like this

`let mailingAddressInputFrom = Storefront.MailingAddressInput.create(address1: .value("address1"), address2: .value("address2"), city: .value("city"), company: .value("company"), country: .value("country"), firstName: .value("first"), lastName: .value("last"), phone: .value("phone"), province: .value("province"), zip: .value("zip"))`

**Comment by networld301ios** [comment]
thanks for answer
i have a multiple addresses. and one address is default. then i want make second address as a default   not changing other field value.

**Comment by networld301ios** [comment]
previous query only update address not set as default . can you have another solution?

**Comment by aShaforostov** [comment]
```
let mutationUpdateDefaultAddress = Storefront.buildMutation{ $0
            .customerDefaultAddressUpdate(customerAccessToken: "token", addressId: GraphQL.ID(rawValue: "id"), { $0
                .customer{ $0
                    .defaultAddress{ $0
                        .id()
                    }
                }
                .userErrors{ $0
                    .field()
                    .message()
                }
            })
        }
```

**Comment by dbart01** [comment]
To change the default address for a customer, use the `customerDefaultAddressUpdate` mutation.

**Comment by networld301ios** [comment]
yes that's work

**Comment by networld301ios** [comment]
i am getting default address and addresses using these query. but i can't identified default address from addresses list. because default address id and same address id in address-list not be equal

let query = Storefront.buildQuery { $0
            .customer(customerAccessToken: "")
            { $0
                .defaultAddress{ $0
                    .address1()
                    .address2()
                }
                .addresses(first: 10) { $0
                    .edges { $0
                        .node { $0
                            .id()
                            .address1()
                            .address2()
                            .city()
                            .province()
                            .provinceCode()
                            .country()
                            .zip()
                        }
                    }
                }
            }
        }

**Comment by dbart01** [comment]
You're not querying for `id` under `.defaultAddress`.

**Comment by networld301ios** [comment]
querying for id under .defaultAddress not give same id in addresses list and default address
 query is 
Storefront.buildQuery { $0
            .customer(customerAccessToken: Acesstoken)
            { $0
                .defaultAddress
                { $0
                    .id()
                    .firstName()
                    .lastName()
                    .company()
                    .address1()
                    .address2()
                    .city()
                    .province()
                    .provinceCode()
                    .country()
                    .zip()
                    .phone()
                    .countryCode()
                }
                .addresses(first: Int32(limit), after: cursor)
                {
                    $0
                        .pageInfo { $0
                            .hasNextPage()
                        }
                        .edges { $0
                            .cursor()
                            .node { $0
                                .id()
                                .firstName()
                                .lastName()
                                .address1()
                                .address2()
                                .city()
                                .province()
                                .provinceCode()
                                .country()
                                .zip()
                                .phone()
                                .countryCode()
                            }
                    }
                }
            }
        }

**Comment by dbart01** [comment]
You're saying that the address returned as `defaultAddress` doesn't match _any_ addresses returned in `.addresses` edges and nodes?

**Comment by networld301ios** [comment]
only address id not match other than id is match

**Comment by dbart01** [comment]
This has been fixed on our backend.

**Comment by ankityadav2604** [comment]
Storefront.buildQuery { $0
      .customer(customerAccessToken: accessToken)
      { $0
        .defaultAddress{ $0
          .id()
          .firstName()
          .lastName()
          .address1()
          .address2()
          .city()
          .province()
          .country()
          .zip()
      }
      .addresses(first: 10) { $0
      .edges { $0
      .node { $0
      .id()
      .firstName()
      .lastName()
      .address1()
      .address2()
      .city()
      .province()
      .country()
      .zip()
        }}}}}

Not return default address

**Comment by aganglada** [comment]
@dbart01 We are experiencing the same problem using storefront api, none of the ids returned for addresses match `defaultAddress.id`
