### ISSUE TITLE
StorefrontCollectionView - Cached search results initially not visible

### ISSUE THREAD

**Issue by ritteraf** [Shopify/mobile-buy-sdk-ios#876]
As the title says, I've set my cachePolicy to .cacheFirst(expireIn: 3600). For any search performed that is cached, the products in the collection are initially not visible on screen. If I so much as lightly tap in the collectionView area immediately the products are shown. They are not reloaded or anything, just they become visible.

This behavior never happens when my cache policy is set to .networkOnly, so I can only assume there is some sort of issue in the SDK regarding the loading of this cached data into the collectionView. I have no idea where/how caching happens inside the SDK, so looking for a little help! Thanks.

**Comment by dbart01** [comment]
That sounds like a UI-layer problem, from what you're describing. Have you looked at the sample app to see what the differences in implementation are? The sample app also makes extensive use of caching.

**Comment by ritteraf** [comment]
@dbart01 Thanks for the tip Dima. I am working on a modified version of the SDK, with the core functionality of the SDK in tact. I added the following code after the collectionView data is loaded:
self.collectionView.layoutSubviews()
self.collectionViewLayout.invalidateLayout()

The cells are now partially showing on load(product title doesn't load?). This information is good, as I know now for sure the issue resides somewhere inside the subviews of the collectionView.

However, pagination is now not working on cached results. I'm hoping this last bit of information can help narrow down the root of the issue. If pagination is not triggering, then there is something definitely wrong with how the collectionView subviews are being loaded.

**Comment by dbart01** [comment]
Pagination relies on an accurate cursor. Sounds to me like your controller is doing something funky with both your collection view and cursor. I would recommend stepping through your application and to verify that your assumptions (of the data) are correct.
