### ISSUE TITLE
Can't complete credit card payment with test credit card and Stripe.

### ISSUE THREAD

**Issue by lorenzOliveto** [Shopify/mobile-buy-sdk-ios#877]
I'm using Stripe as payment provider but I can't make it work with the test credit card.

From the Stripe dashboard we can see the payments but they are all rejected with this error: 
> live_mode_test_card
> This charge request was in live mode, but used a Stripe test card number. (See https://stripe.com/docs/testing for the complete list.)
> 

From the Shopify we have the same error but I can't find a way to toggle the test mode of Stripe.

Setting the test value to true when creating the CreditCardPaymentInput give me the error "Test is not supported".

Am I missing some steps needed to setup the test environment?

Data of the test card:
Card number: 5555555555554444
Expiry month: 08
Expiry year: 18
Ccv: 424

SDK version: 3.1.7

Error displayed in error page:
![schermata 2018-06-22 alle 16 48 22](https://user-images.githubusercontent.com/3470464/41783010-1a32f4ae-763c-11e8-9928-1dce88c91e7c.png)

**Comment by aShaforostov** [comment]
Just set "Shopify Payments" as your payment gateway, not a Stripe and test your payments
We also spent a lot of time to test the purchases inside the application

**Comment by lorenzOliveto** [comment]
So it's not possible to test payments with the Stripe gateway and this SDK?

**Comment by aShaforostov** [comment]
@lorenzOliveto I'm test Stripe with real payments, set prices on products to 0.5$ and pay.

**Comment by dbart01** [comment]
You can enable "Test Mode" in:

| Admin > Settings > Payment Providers > Test Mode |
| - |
| <img width="994" alt="screen shot 2018-07-09 at 3 39 00 pm" src="https://user-images.githubusercontent.com/5244861/42472287-c3ba819a-838e-11e8-893f-526eda1035b0.png"> |

**Comment by lorenzOliveto** [comment]
Using Stripe as the payment provider I can't see that checkbox. Is there a way to enable it?
I see this:
![schermata 2018-07-17 alle 12 32 22](https://user-images.githubusercontent.com/3470464/42812315-91706a62-89bd-11e8-8c74-4d4ef7b9cdc7.png)

**Comment by dbart01** [comment]
What Stripe defines as "Test Mode" is specific to Stripe. From my understanding you have to use test card numbers provided by Stripe instead explicitly defining "test mode".

**Comment by lorenzOliveto** [comment]
Using Stripe alone you have to specify if you're in test/production mode changing the key used.
I'm already using a test card but Stripe thinks that I'm making the payment in live mode.
