### ISSUE TITLE
Errors in Sample App

### ISSUE THREAD

**Issue by JaydenIrwin** [Shopify/mobile-buy-sdk-ios#878]
I'm brand new to this SDK.
I downloaded the Sample App.
Run in Xcode 9.4, and I get the "GraphQL not found at x path"
I downloaded GraphQL.swift from the internet, and added it into folder x.
I try running, and a whole bunch of errors show up.

![screen shot 2018-06-19 at 10 10 25](https://user-images.githubusercontent.com/13500479/41785300-282415ba-7610-11e8-9492-5fd31bb97915.png)

**Comment by dbart01** [comment]
Please take a look at the [installation instructions](https://github.com/Shopify/mobile-buy-sdk-ios#installation-). You are missing the GraphQL submodule, which can be resolved by cloning the repo and running:
```
git submodule update --init --recursive
```
Please keep in mind that simply "downloading" the sample app or the SDK will not work.

**Comment by MVakas** [comment]
Well following all the instruction for the Sample App, still not able to run the app without errors.
