### ISSUE TITLE
Checkout Complete using CreditCard option  access denied

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-ios#880]
i am using credit card option for payment.  i got below error in test credit card with test mode

MobileBuySDK.Graph.QueryError.invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "CheckoutCompleteWithCreditCard access denied", line: nil, column: nil)])

taken a code from  reference link
 https://github.com/Shopify/mobile-buy-sdk-ios#credit-card-checkout-

**Comment by networld301ios** [comment]
is these problem  of "shopifyPaymentsAccountId = "<null>" getting in payment setting . while creating a token?

**Comment by networld301ios** [comment]
Hello,

Any updates ?
It's an urgent can you please reply.

**Comment by dbart01** [comment]
Can you provide your store domain and private app name that you're using?

**Comment by networld301ios** [comment]
Store: proj-buttonedup.myshopify.com
Private App: Buttonedup

**Comment by dbart01** [comment]
Are you still seeing the problem?

**Comment by networld301ios** [comment]
no. that's work fine.

**Comment by blackneck** [comment]
@dbart01 @networld301ios hey guys, what was the problem? could you share?

**Comment by ArchieGoodwin** [comment]
Have the same issue. @dbart01 could you please fix? 

Private app "Purity Mobile App Ready Only" for 100-pure.myshopify.com

**Comment by dbart01** [comment]
@ArchieGoodwin done.

**Comment by qutub-bharmal** [comment]
hello ,
facing a same issue. @dbart01  could you fix it ?
Private App: "Buttoned Up" & Domain:"buttoned-up-tx.myshopify.com"

**Comment by qutub-bharmal** [comment]
have you fix it?

**Comment by dbart01** [comment]
@qutub-bharmal Yes, permissions have been updated.

**Comment by Networld301** [comment]
hello ,
facing a same issue. @dbart01 could you fix it ?
Private App: "jules&james" & Domain:"jules-james.myshopify.com"

**Comment by Networld301** [comment]
Hello,

Any updates ?
It's an urgent can you please reply.

**Comment by morganmccunn** [comment]
Hi @Networld301 - we will take a look this week. If that is not soon enough, please elaborate on the urgency. Thanks!

**Comment by kierobinson1** [comment]
Hi, it seems that the ability to checkout using Apple Pay & credit cards is now unsupported by the Mobile Buy SDK. This feature is restricted to sales channel marketplaces. Is this true? If so could the documentation please be updated to reflect this as it's quite misleading at the moment. I'm also having the above error and after searching around came across this forum post: 

https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/bug-access-denied-calling-checkoutcompletewithcreditcard-from-ios-app-478115

that ends with a message saying to only use the checkout link inside a webview in my iOS app.

**Comment by aadilHaffez** [comment]
**URGENT** @dbart01 Can you please confirm what @kierobinson1  is saying, i am also facing the same issue checked all the permissions on shopify admin settings all are granted,

**Comment by Abhishek05media** [comment]
hello ,
facing a same issue. @dbart01 could you fix it ?
Private App: "tasangs" & Domain:"https://tasanga-group.myshopify.com"
