### ISSUE TITLE
while checkout got error " Shipping rate & Shipping line can't be blank "

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-ios#881]
while checkoutCompleteWithCreditCard getting error like these
```
 userErrors =     (
                {
            field = "<null>";
            message = "Shipping rate can't be blank";
        },
                {
            field = "<null>";
            message = "Shipping line can't be blank";
        }
    );
```

my code is like these
```
mutation =
 {
	checkoutCompleteWithCreditCard(
		checkoutId: "Z2lkOi8vc2hvcGlmeS9DaGVja291dC9mYTk5MDAzZWI3OGFhOWYwZDIxYTNkNjNkZTYwZDE5Yj9rZXk9ZTkwNjI2MDM5ZmZjNGM5ZTUxM2JlYzBlYzRkYzE1Y2Y=",
		payment: {
			amount: "30",
			idempotencyKey: "9D78AC87-C555-45F1-BF00-4C38731728A8",
			billingAddress: {
				address1: "3645 Las Vegas aaaaa",
				address2: "monorail",
				city: "Las Vegas 222",
				country: "United States",
				firstName: "test1",
				lastName: "test1",
				phone: "+18129159015",
				province: "Nevada",
				zip: "89109"
			},
			vaultId: "west-9243ff6f950f56fd0b2c672057752d32"
		}
	) {
		payment {
			id,
			ready
		},
		checkout {
			id,
			ready
		}, userErrors {
			field,
			message
		}
	}
}
```

**Comment by dbart01** [comment]
These are not errors but rather `userErrors`, which means the payload your app is providing is not sufficient for the mutation to succeed. They are valid. You need to provide a shipping line and shipping rate. For details on how to implement checkout mutation for updating these fields you can take a look at the [sample app](https://github.com/Shopify/mobile-buy-sdk-ios/tree/master/Sample%20Apps/Storefront). You'll need to [poll for shipping rates](https://github.com/Shopify/mobile-buy-sdk-ios#polling-for-shipping-rates-) and execute the  `checkoutShippingLineUpdate` mutation.
