### ISSUE TITLE
Main Banner image slider

### ISSUE THREAD

**Issue by rehannali** [Shopify/mobile-buy-sdk-ios#884]
Hello,
I'm trying to find out, how i can get all slider images which are present at home page. I tried at different places but didn't found anything.
Where i can find it or from which node? 
Waiting from your response. Any help would be appreciated.
Thanks

**Comment by dbart01** [comment]
Please take a look at the [sample app](https://github.com/Shopify/mobile-buy-sdk-ios/tree/master/Sample%20Apps/Storefront).
