### ISSUE TITLE
Fetch customer tags

### ISSUE THREAD

**Issue by chirilavasiletiberiu** [Shopify/mobile-buy-sdk-ios#885]
Hello, 

There is a possibility to fetch a customer's tags with iOS Mobile Buy SDK? These are essential for the app I work on because the customer should see only the products/shipping rates has access to, based on it's tags. 

Thank you.

**Comment by dbart01** [comment]
Unfortunately, customer tags are Admin-facing and don't belong in the Storefront API. Alternatively, you can take a look at the [Admin GraphQL API beta](https://help.shopify.com/en/api/graphql-admin-api) to see if it fits your needs.
