### ISSUE TITLE
Build fail in Simulator on XCode 9.4.1

### ISSUE THREAD

**Issue by LadyRanger1992** [Shopify/mobile-buy-sdk-ios#888]
I using CocoaPods with 

` use_frameworks!`
 ` pod 'Mobile-Buy-SDK', '2.2.0'`

My project build fail with error:
Can not found header file in .pch file

`#import <Buy/Buy.h>`

Note: build okie in real device. My partner build in XCode 9.2 has successful. May be issue by new Swift compiler

**Comment by dbart01** [comment]
Please migrate to the [latest release](https://github.com/Shopify/mobile-buy-sdk-ios/releases/latest) of the SDK. The version you're using, v2.x, is no longer supported.
