### ISSUE TITLE
BUYObject#dirtyProperties Purpose

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#89]
In digging into the SDK, I found a fairly nasty looking runtime hack that appears to amount to the simple ability to magically track "dirty properties" on a model. It looks like this is only used when sending partial checkout representations to the API.

Is this an API requirement that only diffs be sent? If not, what's the decision behind this? Just curious...

**Comment by runmad** [comment]
As you figured, it's done to send partial checkout requests when PATCHing the checkout objects.

We're working on an update of the SDK that removes the need for this code.
