### ISSUE TITLE
Prepopulating billing address and shipping address to apple pay dialog

### ISSUE THREAD

**Issue by andytrill** [Shopify/mobile-buy-sdk-ios#892]
Hi
Is there any way to prepopulate billing address and shipping address to apple pay dialog?

**Comment by dbart01** [comment]
I'm afraid this isn't SDK related. As far as I'm aware, Apple Pay billing and shipping address can only be provided through user-initiated actions or default settings. You can take a look at the [sample app](https://github.com/Shopify/mobile-buy-sdk-ios/tree/master/Sample%20Apps/Storefront) to see how we leverage Apple Pay using the SDK.
