### ISSUE TITLE
Could not Load shopname.JSON

### ISSUE THREAD

**Issue by havocko** [Shopify/mobile-buy-sdk-ios#897]
First of all want to thank DBart for speedy response.

I have it set up with my api key and correct shopify URL but am receiving this error on the sample app.

Any suggestions please?

failed to load cart from disk: Error Domain=NSCocoaErrorDomain Code=260 "The file “MYSHOPNAMEHERE.myshopify.com.json” couldn’t be opened because there is no such file."

**Comment by havocko** [comment]
Cart URL: file:///Users/LD/Library/Developer/CoreSimulator/Devices/B6E9E574-C040-46AD-8FA3-159829F21123/data/Containers/Data/Application/FB566CF5-1AA2-4E51-A38E-993006950863/Documents/SHOPNAMEHERE.json
Failed to load cart from disk: Error Domain=NSCocoaErrorDomain Code=260 "The file “orientaldrift.com.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/LD/Library/Developer/CoreSimulator/Devices/B6E9E574-C040-46AD-8FA3-159829F21123/data/Containers/Data/Application/FB566CF5-1AA2-4E51-A38E-993006950863/Documents/SHOPNAMEHERE.com.json, NSUnderlyingError=0x6000039a9170 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Exercising cache policy: CACHE_FIRST(3600)
Exercising cache policy: NETWORK_ONLY
Graph.QueryError: http(statusCode: 403)
Failed to load collections: Optional(Buy.Graph.QueryError.http(statusCode: 403))

**Comment by dbart01** [comment]
Replace `MYSHOPNAMEHERE` with your shop name.

**Comment by havocko** [comment]
Yes I have done that I just removed it on this public post - I put **myshopname**.myshopify.com and the API Key from creating a private app on shopify

**Comment by dbart01** [comment]
Looks like you're getting a `403` when fetching collections. That generally indicates a mismatch between your API key and shop domain. Double-check that all your credentials are correct. Is everything working as expected using the default `graphql` shop domain?

**Comment by havocko** [comment]
I tested out the default graphql shopdomain and it looks like same kind of error any thoughts?

2018-08-15 14:13:43.219910+0100 Storefront[6367:80852] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
Cart URL: file:///Users/LD/Library/Developer/CoreSimulator/Devices/B61D7BA4-4CB8-444A-8945-5D92E2DE02A5/data/Containers/Data/Application/7DEB9A9D-15C5-4542-8096-584288CD592F/Documents/graphql.myshopify.com.json
Failed to load cart from disk: Error Domain=NSCocoaErrorDomain Code=260 "The file “graphql.myshopify.com.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/LD/Library/Developer/CoreSimulator/Devices/B61D7BA4-4CB8-444A-8945-5D92E2DE02A5/data/Containers/Data/Application/7DEB9A9D-15C5-4542-8096-584288CD592F/Documents/graphql.myshopify.com.json, NSUnderlyingError=0x6000024bd200 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Exercising cache policy: CACHE_FIRST(3600)
Exercising cache policy: NETWORK_ONLY


Thanks Dbart, Appreciated

**Comment by dbart01** [comment]
The `Failed to load cart from disk` isn't an error. It's just a notice saying that a local cart doesn't exist, yet.

**Comment by havocko** [comment]
Ok thanks alot got it to work with your help looks like I was not using the storefront access token
