### ISSUE TITLE
Unable to find Discount Type While Applying Discount code

### ISSUE THREAD

**Issue by qutub-bharmal** [Shopify/mobile-buy-sdk-ios#905]
hello,
Using MobileBuySDK a applied Discount to CheckoutID. My Discount Type is "Free Shipping". while Applying  Discount i could not find anything about is these applied or not. and also getting shipping Rate. 

is there any way , when applied discount code  For (Free shipping ) to checkoutID then Shipping Rate should be  empty.

Please Help.

**Comment by dbart01** [comment]
Discounts are not yet exposes in the `Storefront.Checkout` object. We are currently working on it with changes coming in the next release. Stay tuned.

**Comment by dbart01** [comment]
The [latest release](https://github.com/Shopify/mobile-buy-sdk-ios/releases/latest) now features support for discounts.

**Comment by mahmutpinarbasi** [comment]
Hi, with v3.2 `discountAllocations` works as expected for `ChecoutLineItems` but not `shippingDiscountAllocations`.

Whenever I apply discount code for shipping, `shippingDiscountAllocations` always returns an empty array. But total `paymentDue` is correct. Any idea why?
