### ISSUE TITLE
Apple Pay not charging customers credit cards

### ISSUE THREAD

**Issue by VasApps** [Shopify/mobile-buy-sdk-ios#906]
@#I have successfully implemented the Apple Pay process. I have tracked all parts of the checkout properly. I got nothing but success callbacks. However, my credit card is NOT being charged. Upon reading more I found that Apple Pay needs to be enabled for private apps using the storefront api. 

My use case is different. My app is a public sales channel app. How can I enable apply pay for the public sales channel app I currently have? 

I am looking to have this option in my admin but I can't find it/seem to have it? 

<img width="624" alt="screen shot 2018-08-27 at 2 16 38 am" src="https://user-images.githubusercontent.com/10765940/44634873-64276e00-a99f-11e8-9f56-157cdcfd7d76.png">

Please help me! @dbart01

**Comment by rebeccajfriedman** [comment]
@VasApps Is Apple Pay activated via the Settings? https://help.shopify.com/en/manual/payments/apple-pay#activate-apple-pay

**Comment by VasApps** [comment]
Yes it 100% is for all our stores that are using our app.

**Comment by rebeccajfriedman** [comment]
Are you still experiencing this issue?

**Comment by rebeccajfriedman** [comment]
Closing as stale. Please reopen this issue if the problem persists.
