### ISSUE TITLE
shopify_payments_account_id ALWAYS returning NULL value

### ISSUE THREAD

**Issue by VasApps** [Shopify/mobile-buy-sdk-ios#907]
Hello there. I have gone through several live chat supports and have read through several threads that are similar, if no the same, as the issue I am posting about. There have been no answers posted anywhere or help provided. I am a shopify partner and my application is a sales channel app, which has access to use the checkout API. Our application has 100% been approved for payment processing. It is noted in the admin for our partner app.

I am trying to integrate payments with stripe. The problem is the key "shopify_payments_account_id" ALWAYS returns null value, and I cannot move forward with that value being NULL. I am following the below insturctions to create a checkout.

https://help.shopify.com/en/api/guides/sales-channel-sdk/completing-a-payment#integrate-stripe-with-your-sales-channel-app

It says clearly in the docs that upon creating the checkout, shopify will return the stores "shopify_payments_account_id" but it always comes back NULL no matter what. All stores that I have tested this with do have shopify payments as the payment provider in the admin payment settings, I have all the permissions properly set, and the app is 100% a sales channel app that DOES have access to use the checkout API.

What could be the issue here? I believe there has to be some configuration that is missing for our application. Any help would be greatly appreciated! This is the last step before our app is published to the shopify app store and we cannot move on without this issue being resolved.

Thanks!

**Comment by rebeccajfriedman** [comment]
@VasApps Do you meet the Setup Criteria specified in that doc? ie. do the app consumers have Shopify Payments enabled?

**Comment by VasApps** [comment]
Yes ALL stores and even TEST STORES have shopify payments enabled and we are an approved payment processing sales channel.

**Comment by rebeccajfriedman** [comment]
Can you share the name of your application and a test store?

**Comment by VasApps** [comment]
Yes, no problem. The name of our app is "Drobile - Native iOS And Android App Maker" and the name of a test store is "tech-outlett.myshopify.com" or you can even try with "zbcarter3.myshopify.com" same result.

**Comment by vtrusevich** [comment]
@VasApps have you seccedded fixing issue?
I am having the same

Always null in responce for shopify_payments_account_id

**Comment by rebeccajfriedman** [comment]
@VasApps I reached out directly to the contact email on file for "Drobile - Native iOS And Android App Maker"
@vtrusevich If you provide your app name, I can reach out to the contact email on file as well to help you troubleshoot.

**Comment by vtrusevich** [comment]
@rebeccajfriedman , 

public app name

**Comment by vtrusevich** [comment]
@rebeccajfriedman my email v.trusevich@itransition.com

**Comment by vtrusevich** [comment]
@rebeccajfriedman Was something new investigated according to the problem?
I still can not retrieve shopify_payments_account_id

**Comment by fedebalderas** [comment]
@rebeccajfriedman any update? same problem here

**Comment by rebeccajfriedman** [comment]
@fedebalderas If your app is a public app, you will need to go through the formal approval process noted here to get Stripe access: https://help.shopify.com/en/api/guides/sales-channel-sdk/getting-started#request-payment-processing
