### ISSUE TITLE
Fetch data from navigation of shopify panel in ios mobile buy sdk

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#909]
I want to fetch data from navigation (used in my shopify panel to sequence the collections) of shopify panel in ios mobile buy sdk. Is it possible to get same sequence of data as I set in navigation on shopify panel.

**Comment by dbart01** [comment]
The SDK is built on Storefront API, which is a fundamentally different permission model than Admin-level features. What you're looking for is not supported.
