### ISSUE TITLE
how to fetch multiple variant images

### ISSUE THREAD

**Issue by thousandzero** [Shopify/mobile-buy-sdk-ios#910]
Hey, I want to show multiple image for a single variant or you can say that I want to group images for a variant.
I was added multiple images for a variant according this tutorial  : http://docs.minionmade.com/shopify/grouping-images-with-variants-on-shopify

Now I want to fetch these images in ios private app.

Thanks

**Comment by dbart01** [comment]
Product variants only have 1 image. I think what you're looking for is the paginated `images` field of a `Storefront.Product`.

**Comment by thousandzerokanika** [comment]
@dbart01  Yes I have fetched the product images from storefront.Product. But I need to add multiple variant images. But Thanks for reply.

**Comment by dbart01** [comment]
Variants can only have one image.
