### ISSUE TITLE
Polling Checkout Apple

### ISSUE THREAD

**Issue by rehannali** [Shopify/mobile-buy-sdk-ios#911]
After complete checkout through apple i'm polling for checkout and it gives me nothing. I see sample app and compare with it and i'm doing everything which is implemented in sample app and still didn't know what happened.
I didn't got an error but i got checkout.order attribute is nil.

![screen shot 2018-09-17 at 6 21 07 pm](https://user-images.githubusercontent.com/22426977/45625555-92800100-baa6-11e8-8ef7-fe10e6725e5e.png)
![screen shot 2018-09-17 at 6 21 22 pm](https://user-images.githubusercontent.com/22426977/45625557-94e25b00-baa6-11e8-91f7-10bbe1ab84de.png)
![screen shot 2018-09-17 at 6 21 36 pm](https://user-images.githubusercontent.com/22426977/45625560-97dd4b80-baa6-11e8-857a-d124b73ce85d.png)

- Version of the SDK are you using
   Latest
- What is the expected behaviour?
   Create order and return order details
- What is happening instead?
   I only got order null when i polling Checkout

**Comment by rehannali** [comment]
I got nothing in userErrors.

**Comment by dbart01** [comment]
This doesn't appear to be an issue with the SDK. I encourage you to look over your application logic and ensure your operations are executed in the correct order. You can use the documentation and sample app as a guide. I'm afraid I can't be of more help with the information provided.

**Comment by rehannali** [comment]
@dbart01 I looked into application logic and all operations are executed in correct order. I use sample app as guide and payment flow similar to guide and still i've same problem.

**Comment by dbart01** [comment]
Can you paste your raw response from `checkoutCompleteWithTokenizedPayment` mutation?

**Comment by rehannali** [comment]
**Raw response for checkoutCompleteWithTokenizePayment**
`Optional<Mutation>
  - some : <Mutation: ["checkoutCompleteWithTokenizedPayment": {
    payment =     {
        amount = "31.00";
        checkout =         {
            appliedGiftCards =             (
            );
            currencyCode = USD;
            email = "rehannali.devclan@gmail.com";
            id = "Z2lkOi8vc2hvcGlmeS9DaGVja291dC9jOWI3NmNkNjkwZWVkMzM1Yzc0ZjEwOTFlNDY3MWNmNz9rZXk9OGFiMmYyOWQ2MzIxNDgxZjU2ZTQ3YzA3YzU0MjIzNjc=";
            lineItems =             {
                edges =                 (
                                        {
                        cursor = "eyJsYXN0X2lkIjoiNjhmZDdhZWM1ZGFiNDc3MTIxZWUxYmIxOTk2OThjOTciLCJsYXN0X3ZhbHVlIjoiNjhmZDdhZWM1ZGFiNDc3MTIxZWUxYmIxOTk2OThjOTcifQ==";
                        node =                         {
                            quantity = 1;
                            title = "Rose Gold Contour Brushes- 10Pc";
                            variant =                             {
                                id = "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MjYwMjI0MTc0NA==";
                                price = "20.00";
                            };
                        };
                    },
                                        {
                        cursor = "eyJsYXN0X2lkIjoiZjJhN2RlYzMxMDg0ZDMyODE0YWZiNDM3MTlhNWIxMzUiLCJsYXN0X3ZhbHVlIjoiZjJhN2RlYzMxMDg0ZDMyODE0YWZiNDM3MTlhNWIxMzUifQ==";
                        node =                         {
                            quantity = 1;
                            title = "Glam Gal Selfie Ring Light";
                            variant =                             {
                                id = Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80ODUyNjI5NjAyMzQx;
                                price = "8.00";
                            };
                        };
                    }
                );
            };
            note = "<null>";
            paymentDue = "31.00";
            ready = 1;
            requiresShipping = 1;
            shippingAddress =             {
                address1 = "10-5th";
                address2 = "<null>";
                city = Astoria;
                country = "United States";
                countryCodeV2 = US;
                firstName = Rehan;
                lastName = Ali;
                phone = 3474454480;
                province = "New York";
                provinceCode = NY;
                zip = 11105;
            };
            shippingLine =             {
                handle = "Better Shipping App-BetterShippingProductBasedOnly-3.00";
                price = "3.00";
                title = Shipping;
            };
            subtotalPrice = "28.00";
            taxesIncluded = 0;
            totalPrice = "31.00";
            totalTax = "0.00";
            webUrl = "https://shinepop.myshopify.com/16461469/checkouts/c9b76cd690eed335c74f1091e4671cf7?key=8ab2f29d6321481f56e47c07c5422367";
        };
        creditCard = "<null>";
        errorMessage = "<null>";
        id = "Z2lkOi8vc2hvcGlmeS9QYXltZW50LzUwNTk4OTAwNTM2ND9jaGVja291dD1jOWI3NmNkNjkwZWVkMzM1Yzc0ZjEwOTFlNDY3MWNmNyZrZXk9OGFiMmYyOWQ2MzIxNDgxZjU2ZTQ3YzA3YzU0MjIzNjc=";
        ready = 0;
        test = 0;
    };
    userErrors =     (
    );
}]>`

**Comment by dbart01** [comment]
Your payment is not ready. Note the line 6 from the bottom:
```
ready = 0;
```
This indicates that your polling logic condition isn't requiring a complete payment _or_ it's timing out. You can try rewriting the logic or increasing the timeout / number of polling retries and see if it solves your problem.

**Comment by rehannali** [comment]
@dbart01 I increased time out and follow again through sample app and i saw ready 1 but still payment is not ready. Can you please look into it and tell me whats wrong or anything you want to identify the problem.
P.S I'm using simulator and dummy card details for payment through Apple pay.

https://pastebin.com/x0ytvNPW

**Comment by dbart01** [comment]
What do you mean by "payment is not ready"? It looks like your payment flow completed but you're getting an error:
```
There was an error processing your payment. Please try again.
```
This can be a result of incorrect payment information, gateway, etc. If you're using a dummy card with Apple Pay, this can also be the culprit.

**Comment by rehannali** [comment]
@dbart01 The reason i'm using it to test whether it works as i expected or not. How can i test these cases before go live?

**Comment by dbart01** [comment]
Ensure that your gateway is setup to handle test payments with dummy cards. This can be done in Shopify admin for your shop. I would also encourage you to do a live end-to-end test with a real card before pushing to production.

**Comment by rehannali** [comment]
@dbart01 Thanks for help and suggestion.
