### ISSUE TITLE
Add note-attribute to BUYCheckout

### ISSUE THREAD

**Issue by mariapush** [Shopify/mobile-buy-sdk-ios#92]
Is it possible?

**Comment by runmad** [comment]
Yes: https://github.com/Shopify/mobile-buy-sdk-ios/blob/master/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK/Models/BUYCheckout.h#L244

**Comment by mariapush** [comment]
This is for note, and i mean note_attribute

**Comment by mariapush** [comment]
Note_attribute is array with non-default settings

**Comment by runmad** [comment]
Ah, sorry I misunderstood!

Right now, unfortunately it's not possible, but I'll re-open the ticket to keep track.

**Comment by mariapush** [comment]
Thank you. Could you tell me how long does it take?
It is an urgent task for me - if it is a long time for you then I'll look for other ways to solve for me

**Comment by runmad** [comment]
@mariapush I have a PR up, it's possible to do it with it, but I would recommend you wait until it's in a release.

Unfortunately I cannot say when this will be.

**Comment by mariapush** [comment]
@runmad Thanks, but one more question - Please could you add this attribute for Android mobile SDK too?

**Comment by runmad** [comment]
It's been merged into `develop`, look out for this in our next release.

And yes, we will be adding this on the Android Mobile Buy SDK as well. cc @krisorr

**Comment by krisorr** [comment]
This update has been added to the Android develop branch.
https://github.com/Shopify/mobile-buy-sdk-android/issues/22

**Comment by mariapush** [comment]
Hi all, I have problem with SDK version 2:
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/checkout-attribute-in-new-sdk-422999
Say to create threads on the forum but I practically do not get any answers there
