### ISSUE TITLE
Product Query

### ISSUE THREAD

**Issue by AlexanderBaranowski** [Shopify/mobile-buy-sdk-ios#920]
Can't find a possibility to get "**product_id**" field by product's handle. How to do it without Admin API?
just to clarify I need numeric **product_id** not a global unique id  "**id**"

**Comment by dbart01** [comment]
`product_id` isn't exposed in the Storefront API and will likely remain that way in the near future. Having said that, if you _really_ need access to the `product_id`, base64 decoding the GraphQL id will yield the value you're looking for. Please keep in mind that we don't recommend coupling your app to the implementation detail of GraphQL identifiers as it may change in the future.
