### ISSUE TITLE
How to access files uploaded on Shopify?

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#921]
Hi.. I want to access files which are uploaded on my shopify panel's file section in settings tab. 
In my website end I am able to access these file but now I want to use these file in iOS application.

Is there any way by which I can fetch these images or files in iOS app using mobile buy sdk

**Comment by dbart01** [comment]
Unfortunately no, this is outside the scope pf Mobile Buy SDK.
