### ISSUE TITLE
Checkout Error when shipping isn't required.

### ISSUE THREAD

**Issue by natecraft1** [Shopify/mobile-buy-sdk-ios#930]
For digital products that don't require shipping I'm receiving an ambiguous 400 error for invalid query.
`"The operation couldn’t be completed. (MobileBuySDK.Graph.QueryError error 4.)"
`

This is the mutation:

```
<Mutation: ["checkoutShippingAddressUpdate": {
    checkout =     {
        appliedGiftCards =         (
        );
        availableShippingRates = "<null>";
        currencyCode = USD;
        email = "<null>";
        id = "Z2lkOi8vc2hvcGlmeS9DaGVja291dC81NTlkYjdhNjZjZDRmY2E3ZGZjMTQzNzM5NGQwZGExZT9rZXk9MTJlOWI2M2RmMTRiMGE3MjczODUxZDVjNGY3ZDk3Zjk=";
        lineItems =         {
            edges =             (
                                {
                    cursor = "eyJsYXN0X2lkIjoiNTI0OWRiYjY2OTA4NGM5ZTFiMDY1OGMxMjI2ODc0ODgiLCJsYXN0X3ZhbHVlIjoiNTI0OWRiYjY2OTA4NGM5ZTFiMDY1OGMxMjI2ODc0ODgifQ==";
                    node =                     {
                        quantity = 3;
                        title = "Strawberry Slam";
                        variant =                         {
                            id = Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC84MjIyMTQzMTUyMjE2;
                            price = "6.75";
                        };
                    };
                }
            );
        };
        note = "<null>";
        paymentDue = "20.25";
        ready = 1;
        requiresShipping = 0;
        shippingAddress =         {
            address1 = "208 Bicknell Ave";
            address2 = "";
            city = "Santa Monica";
            country = "United States";
            countryCode = US;
            firstName = nat;
            lastName = G;
            phone = "<null>";
            province = California;
            provinceCode = CA;
            zip = 90405;
        };
        shippingLine = "<null>";
        subtotalPrice = "20.25";
        taxesIncluded = 0;
        totalPrice = "20.25";
        totalTax = "0.00";
        webUrl = "https://achieve-fitness.myshopify.com/10888820/checkouts/559db7a66cd4fca7dfc1437394d0da1e?key=12e9b63df14b0a7273851d5c4f7d97f9";
    };
    userErrors =     (
    );
}]>
```

**Comment by dbart01** [comment]
The snippet you posted is a response, not the query. What does your mutation look like? Also, `Graph.QueryError` is an `enum`. What is the value of that enum?

**Comment by natecraft1** [comment]
@dbart01 Thanks for getting back. The message is "You don't have any items that require shipping"

We are sending a shippingAddress, is that not allowed when requiresShipping is false? Thanks!

**Comment by dbart01** [comment]
What is the query that results in the above error?

**Comment by natecraft1** [comment]
Not sure if I'm providing the right info here.
`  static func mutationForCompleteCheckoutUsingCreditCard(checkout: CheckoutViewModel.ModelType, payment: Storefront.CreditCardPaymentInput) -> Storefront.MutationQuery {
        return Storefront.buildMutation { $0
            .checkoutCompleteWithCreditCard(checkoutId: checkout.id, payment: payment) { $0
                .payment { $0
                    .fragmentForPayment()
                }
                .checkout { $0
                    .fragmentForCheckout()
                }
                .userErrors { $0
                    .field()
                    .message()
                }
            }
        }
    }`

This is the Checkout param...

`<Checkout: ["lineItems": {
    edges =     (
                {
            cursor = "eyJsYXN0X2lkIjoiYjRjNjhmNjY5NjI2MjhiN2MyYTkzMTliZGVkZTgxMjYiLCJsYXN0X3ZhbHVlIjoiYjRjNjhmNjY5NjI2MjhiN2MyYTkzMTliZGVkZTgxMjYifQ==";
            node =             {
                quantity = 1;
                title = "short sleeve cheese its";
                variant =                 {
                    id = "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8xMjQ4MzU1MDI0ODk4Mw==";
                    price = "1.00";
                };
            };
        }
    );
}, "webUrl": https://tapcart-marine.myshopify.com/24040455/checkouts/cbe7ebc7cb5df881a2a86ff4be0ca347?key=a19bb190682126f13b4b5daab59ab7a7, "id": Z2lkOi8vc2hvcGlmeS9DaGVja291dC9jYmU3ZWJjN2NiNWRmODgxYTJhODZmZjRiZTBjYTM0Nz9rZXk9YTE5YmIxOTA2ODIxMjZmMTNiNGI1ZGFhYjU5YWI3YTc=, "email": <null>, "subtotalPrice": 1.00, "note": <null>, "availableShippingRates": <null>, "taxesIncluded": 0, "shippingLine": <null>, "currencyCode": USD, "requiresShipping": 0, "ready": 1, "totalPrice": 1.00, "paymentDue": 1.00, "shippingAddress": <null>, "totalTax": 0.00, "appliedGiftCards": <__NSArray0 0x2806e0080>(

)
]>`

Also, fragmentForCheckout contains fields like shippingAddress, maybe that needs to be removed...

**Comment by dbart01** [comment]
Not exactly. That's a mutation, in Swift, to complete a checkout. Can you please provide the raw GraphQL query that you're sending with a `400` result error code. You'll need to set a breakpoint in the `Graph.Client` and print out the request payload.

**Comment by natecraft1** [comment]
```        

public func mutateGraphWith(_ mutation: Storefront.MutationQuery, retryHandler: RetryHandler<Storefront.Mutation>? = nil, completionHandler: @escaping MutationCompletion) -> Task {
            return self.graphRequestTask(
                query:             mutation,
                cachePolicy:       .networkOnly,
                retryHandler:      retryHandler,
                completionHandler: completionHandler
            )
        }

I printed the mutation in that method in the Graph.Client...

mutation{
checkoutCompleteWithCreditCard(checkoutId:"Z2lkOi8vc2hvcGlmeS9DaGVja291dC9iNmFjNDI5MDM0NGRhNjg3MTA2N2E1YTdlZmFlYzVkZT9rZXk9OWQ0OTFlOWFkMzQ4ZGQwYWNhMTA0OGU3ZmFkMjNjZjY=",payment:{amount:"1",idempotencyKey:"A10F172B-40BD-49AD-8C5E-7B5AADF39C1D",billingAddress:{address1:null,address2:null,city:null,country:null,firstName:null,lastName:null,phone:null,province:null,zip:null},vaultId:"east-045829756dbedec6fdb8abaed77ce429"}){payment{id,ready,test,amount,checkout{id,ready,requiresShipping,taxesIncluded,email,appliedGiftCards{amountUsed,balance,lastCharacters},shippingAddress{firstName,lastName,phone,address1,address2,city,country,countryCode,province,provinceCode,zip},shippingLine{handle,title,price},availableShippingRates{ready,shippingRates{handle,price,title}},note,lineItems(first:250){edges{cursor,node{variant{id,price},title,quantity}}},webUrl,currencyCode,subtotalPrice,totalTax,totalPrice,paymentDue},creditCard{firstDigits,lastDigits,maskedNumber,brand,firstName,lastName,expiryMonth,expiryYear},errorMessage},checkout{id,ready,requiresShipping,taxesIncluded,email,appliedGiftCards{amountUsed,balance,lastCharacters},shippingAddress{firstName,lastName,phone,address1,address2,city,country,countryCode,province,provinceCode,zip},shippingLine{handle,title,price},availableShippingRates{ready,shippingRates{handle,price,title}},note,lineItems(first:250){edges{cursor,node{variant{id,price},title,quantity}}},webUrl,currencyCode,subtotalPrice,totalTax,totalPrice,paymentDue},userErrors{field,message}}}

**Comment by natecraft1** [comment]
@dbart01 Can you confirm whether that is the payload you're looking for? If not, can you please point to the specific line in Graph.Client that you would like me to print?

**Comment by natecraft1** [comment]
Now the checkout is succeeding but I am still receiving an error

```Optional<QueryError>
  ▿ some : QueryError
    ▿ invalidQuery : 1 element
      ▿ reasons : 2 elements
        ▿ 0 : Reason
          - message : "You don\'t have any items that require shipping"
          - line : nil
          - column : nil
        ▿ 1 : Reason
          - message : "You don\'t have any items that require shipping"
          - line : nil
          - column : nil

**Comment by Sayandhkp** [comment]
https://github.com/Shopify/mobile-buy-sdk-ios/issues/930

**Comment by Sayandhkp** [comment]
Hei I am facing this same issue with Shopify version 1.6.7

**Comment by Sayandhkp** [comment]
In Shopify flutter inspire UI
