### ISSUE TITLE
Getting duplicate products for different product cursers while fetching products using collection id.

### ISSUE THREAD

**Issue by rohitkowadkar** [Shopify/mobile-buy-sdk-ios#937]
**I am getting following issues when we try fetch products for specific collection**

- I am getting duplicate product even if we send right cursor to fetch next products
- I am getting less products even if I send "first:10".
- If I apply sorting with TITLE then we are getting only 2 products in first page and then we are getting duplicate products.

- Issue is reproduce when fetching the products using the mobile buy sdk and also through **graph ql** api on REST API also client.
- we are using the Sales Channel App to fetch data.
**We are sending followingQuery**
```
{
    node(id: Base64EncodedCollectionId )
       {__ typename,... on Collection{
             id,
             products(first: 10,sortKey:TITLE,reverse:true) 
             {
               pageInfo
                { 
                  hasNextPage
                },
                edges{ 
                   cursor,
                   node
                   {
                     id,
                     title,
                     handle, 
                     onlineStoreUrl,
                     updatedAt
                   }
                }
             }, 
             handle,
             title,
             updatedAt
         }
       }
}
```

**Comment by rebeccajfriedman** [comment]
@rohitkowadkar We are tracking this issue internally and we are working on a fix. I'll update this ticket when the fix goes live.

**Comment by rohitkowadkar** [comment]
@rebeccajfriedman @dbart01 Is there any update on this?

**Comment by rebeccajfriedman** [comment]
No update. We are still working on a fix.

**Comment by rebeccajfriedman** [comment]
@rohitkowadkar we have fixed an underlying pagination issue on our side. Please reopen this ticket if any of your above issues are not fixed.

**Comment by rohitkowadkar** [comment]
ya sure @rebeccajfriedman Thank you for your timely information & support.
