### ISSUE TITLE
Application crash in ProxyView hitTest override method in ParallaxViewController

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [Shopify/mobile-buy-sdk-ios#938]
if let scrollView = self.scrollView,
            let headerView = self.headerView {
            
            /* ---------------------------------
             ** Test if the point is contained
             ** by the scroll view first.
             */
            let scrollViewPoint = scrollView.convert(point, from: self)
            if scrollView.point(inside: scrollViewPoint, with: event) {
        }

Error:- Trying to put the stack in unreadable memory at 0x16eed7d90.

How we check scrollview in memory or not?

**Comment by dbart01** [comment]
Thanks for pointing that out. A fix is coming in the next release.

**Comment by dbart01** [comment]
Fixed in the [latest release](https://github.com/Shopify/mobile-buy-sdk-ios/releases/latest).

**Comment by NALAWALAMURTUZA** [comment]
Thank you Quick update.

**Comment by AnmolMalpani** [comment]
Hey dear,

I am doing sign up using this code,

let input = Storefront.CustomerCreateInput.create(
            email:            emailTF.text ?? "",
            password:         passwordTF.text ?? "",
            firstName:        .value(firstNameTF.text ?? ""),
            lastName:         .value(lastNameTF.text ?? "")
        )
        let mutation = Storefront.buildMutation { $0
            .customerCreate(input: input) { $0
                .customer { $0
                    .id()
                    .email()
                    .firstName()
                    .lastName()
                }
                .userErrors { $0
                    .field()
                    .message()
                }
            }
        }

But i am not getting any response and output from this. So can you please help me to take the response from that and to created a user. Thanks in advance.

**Comment by rebeccajfriedman** [comment]
@AnmolMalpani If you are still experiencing this issue, can you please create a new Github issue for it, and include details about the response that you are getting / the SDK version that you are using.
