### ISSUE TITLE
MobileBuySDK Timeout Error

### ISSUE THREAD

**Issue by HermanKayy** [Shopify/mobile-buy-sdk-ios#940]
[MobileBuySDK.Graph.QueryError.Reason(message: "Timeout", line: nil, column: nil)])

I get this error message when I tried to add image to my graphQL variant query call. 

```   func fragmentForStandardVariant() -> Storefront.ProductVariantConnectionQuery { return self
        .pageInfo { $0
            .hasNextPage()
        }
        .edges { $0
            .cursor()
            .node { $0
                .id()
                .title()
                .price()
                .availableForSale()
                .compareAtPrice()
                .selectedOptions() { $0
                    .name()
                    .value()
                }
                .image() { $0
                    .id()
                    .src()
                    .altText()
                }
            }
        }
    }

**Comment by rebeccajfriedman** [comment]
@HermanKayy Can you provide your app name or shopify domain so that we can investigate this on our side?

**Comment by HermanKayy** [comment]
This happens on all the shopify stores we're working on whenever we have a query for variants that include images

**Comment by rohitkowadkar** [comment]
@HermanKayy  @rebeccajfriedman  I also faced this timeout error and it got resolved when I set the limit to variants and their image in the query (e.g. first:20) and received the products. but when I increased limit was getting the timeout error.

**Comment by rebeccajfriedman** [comment]
Thanks for elaborating @rohitkowadkar. It sounds like your queries are too complex. I suggest limiting the number of collections / products / variants that you are trying to pull in each query.
