### ISSUE TITLE
Not Able to create customer using ios sdk. every time receive Creating Customer Limit exceeded. Please try again later. 

### ISSUE THREAD

**Issue by NALAWALAMURTUZA** [Shopify/mobile-buy-sdk-ios#943]
let input = Storefront.CustomerCreateInput.create(email:email,
                                                          password: password,
                                                          firstName:firstName,
                                                          lastName:lastName,
                                                          phone:phone/*,
                                                          acceptsMarketing: acceptsMarketing*/)
        return Storefront.buildMutation { $0
            .customerCreate(input: input) { $0
                .customer { $0
                    .id()
                    .email()
                    .firstName()
                    .lastName()
                    /*.phone()
                    .displayName()
                    .createdAt()
                    .updatedAt()*/
                }
                .userErrors { $0
                    .field()
                    .message()
                }
            }
        }
    

when I create customer through android it's working perfect.but while creating a customer I receive this userErrors every time we have only 3 customers in my store.

**Comment by rebeccajfriedman** [comment]
Are you reusing existing email addresses? You can only reuse an existing email address 3 times in a 5 minute window.

**Comment by rebeccajfriedman** [comment]
How are you formatting the phone number? A phone number formatted like "+15551112222" should work - provided that you are sending a valid phone number (with a valid area code and a valid dialing code).

**Comment by NALAWALAMURTUZA** [comment]
if API returns user error with **please adds a mobile number with country code**. so the user gets an idea about a wrong mobile number.instand of Creating Customer Limit exceeded. Please try again later.

**Comment by rebeccajfriedman** [comment]
The create customer throttle of 3 times in 5 minutes is still being applied, even though you are unsuccessfully creating a customer. If you wait 5 minutes, and then send the request, you should see a "Phone is invalid" user error.
