### ISSUE TITLE
Payment and cart synced through server

### ISSUE THREAD

**Issue by rehannali** [Shopify/mobile-buy-sdk-ios#945]
Hi, I didn't find any information about my query. Is there any implementation where we can save and retrieve cart items to shopify server and for payment vise versa.
I also didn't see any information about these in your standard api.

I'm using latest Shopify SDK.

**Comment by dbart01** [comment]
There's no concept of "shared cart" in Storefront API, however, we do support fetching last incomplete checkout for logged in customers. Take a look at `Customer.lastIncompleteCheckout` field for more info.
