### ISSUE TITLE
Constant error when trying to search products 

### ISSUE THREAD

**Issue by ArchieGoodwin** [Shopify/mobile-buy-sdk-ios#947]
I am getting constant error from Shopify when trying to search for products. This one: 

      "message": "Internal error. Looks like something went wrong on our end.\nRequest ID: bf7ad6b3-79b1-42fc-9d64-3178878a39bf (include this in support requests)."

This feature was working well, but few days ago broke (regardless from iOS side or from GraphQL client). Search is very simple like: 

```
shop {
    products(first: 10, query: "Shampoo") {
      edges {
        node {
          title
          variants(first: 1) {
            edges {
              node {
                price
              }
            }
          }
        }
      }
    }
  }

```
For app: 100-pure.myshopify.com

P.S. Search with fields in query working (products(first: 10, query: "title:Mattifying Primer"))

**Comment by rebeccajfriedman** [comment]
I have resolved the issue on our side. Please don't hesitate to reach out if this pops up again in the future.
