### ISSUE TITLE
Apple Pay doesn't change ShippingAddress

### ISSUE THREAD

**Issue by VizenkoRoman** [Shopify/mobile-buy-sdk-ios#948]
version SDK 3.2
Hello I have issues:
1. When Apple Pay starts and ShippingAddress is not correct. Apple Pay say about it. 
2. Select correct ShippingAddress. Apple Pay hides warning. It is ok.
3. Select again not correct ShippingAddress after Apple Pay doesn't warning about incorrect ShippingAddress.

Request always reponse valid 'checkout' after 1 request with correct ShippingAddress.
Client.shared.updateCheckout(checkout.id, updatingPartialShippingAddress: address)

**Comment by dbart01** [comment]
The behaviour of Apple Pay modal (beyond the basic provider methods in the `Pay` framework) are outside the scope of this SDK. If you have an issue with the SDK, please explain the expected behaviour of the SDK.
