### ISSUE TITLE
No way to clear credit card from BUYCheckout

### ISSUE THREAD

**Issue by dwnld-mitch** [Shopify/mobile-buy-sdk-ios#95]
If a user adds an invalid credit card and tries (fails) to checkout, all future updates to the BUYCheckout object (excluding updating the credit card) get a "payment session id invalid" error. This could happen if a user decides to update their shipping address before changing their credit card after an unsuccessful attempt to complete a purchase. 

If, however, the credit card is removed from the BUYCheckout object after an unsuccessful checkout attempt, the 'payment session id invalid' error can be avoided. Unfortunately, there doesn't appear to be a built-in way to do this, so I've had to resort to completely destroying and rebuilding the entire BUYCheckout object.  Would be great to have a non-hacky way to remove the credit card.

**Comment by runmad** [comment]
Are you getting an error back in `storeCreditCard:checkout:completion:` before you attempt to complete the checkout?

**Comment by dwnld-mitch** [comment]
```storeCreditCard:checkout:completion:``` returns with a paymentSessionId and no error.  I get the error when I call ```completeCheckout:completion``` right after calling ```storeCreditCard:completion:```

**Comment by runmad** [comment]
This happens all the time for you? Can you temporarily post a checkout token so I can look into it on our end and I will remove the token once I have grabbed it.

**Comment by dwnld-mitch** [comment]
```82b4607aef1fbbd0268fa8091a323687``` is the token from the checkout object returned in the ```storeCreditCard:checkout:completion:``` with an invalid credit card number.

**Comment by runmad** [comment]
Thanks!

**Comment by davidmuzi** [comment]
This is the expected behaviour.  You can recreate the payment session and perform another `completeCheckout`call

**Comment by dwnld-mitch** [comment]
@davidmuzi How does one recreate the payment session? By calling ```-storeCreditCard:checkout:completion:```?  This doesn't work if a user decides to change some other part of the checkout object before updating the card.  

Is there some other way to prevent an invalid credit card from being associated with a BUYCheckout object?  My current hack of destroying and recreating the entire BUYCheckout object to clear the card is pretty bad (has to re-add all discounts, gift-cards, addresses, etc), and it'd be nice to avoid this.  Please let me know if I'm missing something.

**Comment by davidmuzi** [comment]
"This doesn't work if a user decides to change some other part of the checkout object before updating the card."

`completeCheckout:completion` should be the last call made. If the checkout is modified, `updateCheckout` must be called before `completeCheckout` is called again.

**Comment by dwnld-mitch** [comment]
Right, but calling ```updateCheckout:completion:``` after calling ```completeCheckout:completion:``` with an invalid credit card results in the following error:
```
{
    errors =     {
        checkout =         {
            "payment_session_id" =             (
                                {
                    code = invalid;
                    message = "is invalid";
                    options =                     {
                    };
                }
            );
        };
    };
}
```

Clearing the invalid credit card from the BUYCheckout object should fix this, but there is no way to remove a credit card.

**Comment by davidmuzi** [comment]
Correct.  The last steps to modifying a checkout should be setting of the payment, and calling completion.  

You should be preventing other modifications of the checkout, as they could influence taxes, shipping, etc.

Since this is expected behaviour, if you would like to continue to discuss usage of the SDK, please create a post on our forums, https://ecommerce.shopify.com/c/shopify-apis-and-technology

**Comment by mihai-moldovan** [comment]
Our application collects in the same screen both the credit card data and the billing address, exactly as the website does.
Actually on the website there is also the possibility to modify the billing address after trying a wrong credit card number.

Another use case is that the user, after trying to process the payment gets an error for insufficient funds. Then she can go back and change the shipping method to a cheaper one, and try again. It is not possible because of this issue

**Comment by davidmuzi** [comment]
Correct, this is not possible.

In the case described, you would need to re-create the checkout (you can keep the `BUYCart` object to recreate it).

Adding the payment should be the very last step in the checkout process
