### ISSUE TITLE
automatic discount is not working

### ISSUE THREAD

**Issue by networld301ios** [Shopify/mobile-buy-sdk-ios#951]
i set automatic 50% discount for specific products. while creating checkout these discount not applied. these working in website. how these implement in app using these sdk

**Comment by dbart01** [comment]
Automatic discounts are not yet supported in the Storefront API. We are looking into this.

**Comment by itarato** [comment]
Just tipping in - a week ago we've shipped an adjustment on automatic discount application - before only online store API was calculating (applying) automatic discounts - now all APIs are included (with the exception of POS api client). This includes the application of the discount and price calculation - however not including the presentation of automatic discount details in checkout REST API payloads. GraphQL presence is not a plan atm, but if there is a higher demand for it we can add it.

**Comment by dianapetrova** [comment]
According to the release notes in v3.3 the sdk supports Automatic discounts.  But when I create an automatic discount, the application starts to crash. 
How can I apply some automatic discount without app to crash?

**Comment by dbart01** [comment]
Can you please post the crash log / report / stack trace or any other relevant info that pertains to the crash?

**Comment by dianapetrova** [comment]
Is this OK? It's from Crashlytics. - 
DiscountApplication.swift – line 44 
DiscountApplication.resolvedViewModel.getter

Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x22c03aba0 specialized _assertionFailure(_:_:file:line:flags:) + 360
1  libswiftCore.dylib             0x22be5e2bc _assertionFailure(_:_:file:line:flags:) + 32
2  				0x1008bce7c DiscountApplication.resolvedViewModel.getter (DiscountApplication.swift:44)
3                                         0x10091d8c8 specialized Array<A>.viewModels.getter (DiscountAllocationViewModel.swift:48)
4                                         0x10097dc00 specialized LineItemViewModel.init(from:) (LineItemViewModel.swift:56)
5                                         0x10091e45c specialized Array<A>.viewModels.getter (<compiler-generated>)
6                                         0x100971268 specialized CheckoutViewModel.init(from:) (CheckoutViewModel.swift:85)
7                                         0x1009591f4 closure #1 in Client.updateCheckout(_:cartItems:completion:) (CheckoutViewModel.swift)
8  MobileBuySDK                   0x1013ea580 partial apply for closure #4 in Graph.InternalTask.resume(using:) (Graph.Task.swift:138)
9  MobileBuySDK                   0x1013e8c18 closure #1 in closure #1 in Graph.InternalTask.graphTaskWith(_:retryHandler:completion:) (Graph.Task.swift:237)
10 MobileBuySDK                   0x1013ea424 partial apply for closure #1 in closure #1 in Graph.InternalTask.graphTaskWith(_:retryHandler:completion:) (<compiler-generated>)
11 MobileBuySDK                   0x1013e8d94 thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>)
12 libdispatch.dylib              0x1fdf34a38 _dispatch_call_block_and_release + 24
13 libdispatch.dylib              0x1fdf357d4 _dispatch_client_callout + 16
14 libdispatch.dylib              0x1fdf159e4 _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 1008
15 CoreFoundation                 0x1fe485ec0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
16 CoreFoundation                 0x1fe480df8 __CFRunLoopRun + 1924
17 CoreFoundation                 0x1fe480354 CFRunLoopRunSpecific + 436
18 GraphicsServices               0x20068079c GSEventRunModal + 104
19 UIKitCore                      0x22a929b68 UIApplicationMain + 212
20                                        0x100873ef8 main (LoginViewController.swift:20)
21 libdyld.dylib                  0x1fdf468e0 start + 4

**Comment by dbart01** [comment]
It's crashing in your app, not the SDK. You'll have to debug your application logic to figure what it's doing wrong.

**Comment by rebeccajfriedman** [comment]
Closing this as stale. Please open a new github issue if the problem persists.
