### ISSUE TITLE
Can't Update Customer Information

### ISSUE THREAD

**Issue by SakoHovaguimian** [Shopify/mobile-buy-sdk-ios#957]
**Please complete the checklist before filing an issue:**

- [ X ] Is this a "how to" question? For questions on how to use the SDK, implement features or other related questions, [please use our forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).

Hello, 

I've been having trouble updating a customers information. Attached you will see how I've been attempting to do it. When it comes to the shipping information, passwords, & almost every other aspect it's been working just fine. This is the response I receive : 

""" <Mutation: ["customerUpdate": {
    customer = "<null>";
    customerAccessToken = "<null>";
}]> """ 

The error returns nil, which to me is a good sign. 

Any assistance is appreciated. Thank you

-Sako Hov
![screen shot 2018-12-26 at 10 26 47 am](https://user-images.githubusercontent.com/37895330/50453973-640d8f80-08f9-11e9-987e-3a2e05c53aaa.png)

**Comment by rebeccajfriedman** [comment]
> When it comes to the shipping information, passwords, & almost every other aspect it's been working just fine.

You mean when you try to update some fields for a customer it works, and for some others, it doesn't?

**Comment by rebeccajfriedman** [comment]
Closing as stale. Please reopen a new issue if the problem persists.
