### ISSUE TITLE
Status Code: - 404

### ISSUE THREAD

**Issue by AnmolMalpani** [Shopify/mobile-buy-sdk-ios#958]
1 - When i am doing login with the credentials, what i got when i created through the shop website, then i am getting a error which says **Graph.QueryError: http(statusCode: 404)**.

2- When i am creating a user then getting this mutation object

**mutation{customerCreate(input:{firstName:" Test2",lastName:"Test1",email:"aa@aa.com",password:"123456789",acceptsMarketing:true}){customer{id,email,firstName,lastName},userErrors{field,message}}}**

But when i am passing this mutation for creating the customer access token then still i found status code: - 404.

Please help to solve out this problem because i have tried all possible ways.

I am using this dict in header.

▿ 0 : 2 elements
    - key : "Password"
    - value : "c106b16175d482c898f57d1e52003d2a"
  ▿ 1 : 2 elements
    - key : "X-SDK-Variant"
    - value : "ios"
  ▿ 2 : 2 elements
    - key : "X-SDK-Version"
    - value : "1"
  ▿ 3 : 2 elements
    - key : "User-Agent"
    - value : "Mobile Buy SDK iOS/1/app.aromeo.com"
  ▿ 4 : 2 elements
    - key : "X-Shopify-Storefront-Access-Token"
    - value : "d55f1ddda20ea361067054b4be4f1874"

Thanks in advance.

**Comment by DrTeePot** [comment]
`customerCreate` will create a customer but not log them in. If `customerCreate` is successful you must pass the username (email) and password to `customerAccessTokenCreate` to log the customer in. 

You shouldn't need to pass a `password` in the header.

I'm a little unclear on where you're seeing a 404, if that doesn't help feel free to re-open this issue.

**Comment by DrTeePot** [comment]
See [Creating a customer](https://github.com/Shopify/mobile-buy-sdk-ios#creating-a-customer-) for more information.
