### ISSUE TITLE
Unable to checkout with Apple Pay if gift card is applied (follow up from #927)

### ISSUE THREAD

**Issue by jenchuah** [Shopify/mobile-buy-sdk-ios#959]
This is a follow up from #927 

The `paymentDue` is reduced by gift card applications, see Mobile Buy SDK's `Checkout` class:

```
/// The amount left to be paid. This is equal to the cost of the line items, 
        /// taxes and shipping minus discounts and gift cards. 
        open var paymentDue: Decimal { get }
```
So when you add `paymentDue` to `[PKPaymentSummaryItem]` you will get the following error because as you said the API is expecting the total since the gift card isn't charged until checkout completion.

```
Optional(<Mutation: ["checkoutCompleteWithTokenizedPayment": {
    payment = "<null>";
    userErrors =     (
                {
            field =             (
                payment,
                amount
            );
            message = "Amount The amount of the payment must match the total of 52.00.";
        }
    );
}]>)
```

**Comment by dbart01** [comment]
@rebeccajfriedman Is this the intended behaviour for `paymentDue`?

**Comment by jamiemtdwyer** [comment]
Since `paymentDue` is reduced by gift card applications, and the API is expecting the full balance of the checkout, I think the solution then is to pass the `totalPrice` to the payment mutation.

**Comment by chirilavasiletiberiu** [comment]
I don't really understand the process of a transaction.
Why we should pass the `totalPrice` to the payment mutation if the `paymentDue` reflects the total value that customer should pay? After all, how `gift cards` are working? :)

**Comment by rebeccajfriedman** [comment]
The gift card is not charged until the `checkoutCompleteWithTokenizedPayment` mutation is called, which is why it needs to accept the full amount. It will deplete the gift card before charging the remaining (`paymentDue`) balance.

**Comment by mihai-moldovan** [comment]
Hey, we've recently hit the same problem. I've checked the latest sample app and the latest sdk version and the problem still presist. How did you fix it?
