### ISSUE TITLE
CheckoutViewModel lineItemDiscountName concatenated 5 times

### ISSUE THREAD

**Issue by natecraft1** [Shopify/mobile-buy-sdk-ios#961]
@dbart01 When I submit a discount, for example "helloworld", the CheckoutViewModel comes back with it's lineItemDiscountName property as "helloworld, helloworld, helloworld, helloworld, helloworld"

**Comment by dbart01** [comment]
Is this something that happens in the vanilla sample app?

**Comment by natecraft1** [comment]
I don't know if it happens in the sample app, but it's happening in our app.
