### ISSUE TITLE
How to pass customAttributes in CheckoutLineItemInput?

### ISSUE THREAD

**Issue by ksatasiya** [Shopify/mobile-buy-sdk-ios#962]
Hello There,
I have many tried to pass customAttributes in CheckoutLineItemInput but I didn't find way to pass **Input<[AttributeInput]>** so please give me suggestion how to pass customAttributes in CheckoutLineItemInput?

Thank you :)

**Comment by dbart01** [comment]
I'm not sure I understand the problem here. `CheckoutLineItemInput` has a `customAttributes` property that you can use to pass a value. For example:
```swift
let attributeInputs = [
    Storefront.AttributeInput(key: "key-1", value: "value"),
    Storefront.AttributeInput(key: "key-2", value: "value"),
]

let lineItemInput = Storefront.CheckoutLineItemInput.create(
    quantity: 1,
    variantId: id,
    customAttributes: .value(attributeInputs)
)
```

**Comment by ksatasiya** [comment]
Thank you :)
