### ISSUE TITLE
Checkout requires payment when checkout paymentDue amount is 0.0

### ISSUE THREAD

**Issue by ohthatsjhall** [Shopify/mobile-buy-sdk-ios#963]
I'm running into an issue where the amount giftcard or discount that is applied to a checkout is greater than the subtotal, resulting in a `paymentDue` amount of $0. When trying to complete the checkout, I receive the following error:

`(MobileBuySDK.Graph.QueryError.invalidQuery([MobileBuySDK.Graph.QueryError.Reason(message: "Checkout requires payment.", line: nil, column: nil)])`

From a user experience perspective,  I'd like to avoid having the user input a Credit Card for a $0 purchase if possible. Is there away around this?

**Comment by rebeccajfriedman** [comment]
Thanks for flagging this issue. We are tracking this issue on our side, and we'll update you here once we've corrected this.

**Comment by ohthatsjhall** [comment]
thanks @rebeccajfriedman, I'll check back.

**Comment by jamiemtdwyer** [comment]
Hey @ohthatsjhall, you can now use the `CheckoutCompleteFree` mutation to complete a checkout that has no outstanding balance after gift card applications 👌
