### ISSUE TITLE
No call back url after webcheckout

### ISSUE THREAD

**Issue by thousandzerokanika** [Shopify/mobile-buy-sdk-ios#966]
I am using Web checkout for making checkout process in my app. But there is an issue I am facing in case when we add product to checkout process and in this case if user cancel the web checkout process the product remain in the cart of checkout when user add a new product to is cart and when the checkout called it will show earlier product too which user has cancelled i.e. the browser is not clearing the cache after the process is aborted... this issue occur in web site's end too.. as both web and app using the same url for checkout.

Here the issue is the web checkout process didn't provide any call back url and we are not able to trace if the checkout process is completed successfully or it is aborted by the user. Can you please tell me how to check the status of the web checkout process.

**Comment by dbart01** [comment]
The SDK has no support for monitoring the web checkout flow. One suggestion I can provide is to re-fetch the checkout status when the user comes back to your app from either in-app web view or Safari.

**Comment by walteryaron** [comment]
i created polling every 3 seconds for "checkoutCompleteFree" 
And got this results (while entering credit card details and pay)

1.
code = "MISSING_PAYMENT_INPUT";
     field = "<null>";
     message = "Checkout requires payment.";

2.
invalidQuery(reasons: [Buy.Graph.QueryError.Reason(message: "Checkout is processing.", line: nil, column: nil)])

3.
invalidQuery(reasons: [Buy.Graph.QueryError.Reason(message: "Checkout is already completed.", line: nil, column: nil)])

i want to listen on application side when user finish the checkout and not by checking errors
