### ISSUE TITLE
Sample app build failure!

### ISSUE THREAD

**Issue by MKGitHub** [Shopify/mobile-buy-sdk-ios#969]
I downloaded mobile-buy-sdk-ios-master, open the Storefront.xcodeproj and run…build failures!

Xcode Version 10.1 (10B61)

![screen shot 2019-02-04 at 14 46 03](https://user-images.githubusercontent.com/535550/52212108-053e1d00-288c-11e9-88fe-a2dba7146c7a.png)

Where to go from here?

**Comment by dbart01** [comment]
Please follow the [installation instructions](https://github.com/Shopify/mobile-buy-sdk-ios#installation-). The SDK requires a recursive submodule update:
```
git submodule update --init --recursive
```
