### ISSUE TITLE
Ability to View Resource Metafields

### ISSUE THREAD

**Issue by cocoahero** [Shopify/mobile-buy-sdk-ios#97]
A powerful feature of Shopify is the ability to add metafields to products, collections, etc. These fields are available via liquid to be used within our web shops, but they are currently not available via the mobile SDK.

Are there any plans to add them?

**Comment by davidmuzi** [comment]
Its being considered.  Ill keep this issue open to track any progress.

**Comment by junketjim** [comment]
I'd definitely appreciate the meta-field support too.  So, until GitHub gives us a :+1: here's a :+1:

**Comment by biddster** [comment]
Is there any news on this, I'd really like to see this too?

**Comment by strappe** [comment]
One more vote for this -- it would make Shopify the ideal backend for all the other information we need to keep about our products, some of which shouldn't be exposed to the user.

**Comment by horsejockey** [comment]
Here is another vote for this!

**Comment by saurabhPV** [comment]
looks like it is not yet  implemented.

**Comment by rmfleetTS** [comment]
I'd just like to weigh in here and vote on this as well.  I'm currently exploring alternative options for retrieving this information.

**Comment by biddster** [comment]
Voting for read/write access to the customer meta.

**Comment by bgulanowski** [comment]
Write access will never happen with this API. If you want write access, you must use the admin API.

**Comment by vineetsaini** [comment]
Any update on getting Metafield information for products on a per product basis?

**Comment by cocoahero** [comment]
@dbart01 @davidmuzi any chance this can get bumped up and added to the GraphQL API? Would help on mobile tremendously.

**Comment by cocoahero** [comment]
Case studies where this would be incredibly useful:
- Driving tag based filter UIs driven by metafields on collections
- Driving home screen shop layouts using metafields on the shop object itself.
- Associating a video with a particular product for presentation natively (not via hard to utilize HTML description)

Frankly, not having metafields available to native mobile storefronts via this SDK completely strangles innovation and possibilities. We must resort to hard coding or building 3rd party servers to host configuration APIs, neither of which is reasonable when such a feature as metafields exists to serve this purpose.

**Comment by darylteo** [comment]
Where can we go to air our grievances regarding the lack of this functionality in Storefront API? It makes no sense to pressure @dbart01 if you have no control over the development of the API itself.

**Comment by darylteo** [comment]
Anyone who still thinks that metafields is happening is encouraged to [not kid themselves](https://github.com/Shopify/js-buy-sdk/issues/168). 

Hope future tech leads will make the better decisions given this information - I certainly wish I had this information 2 months ago. 

Avoid metafields, or write your own APIs and expose the metafields you need.

**Comment by darylteo** [comment]
I will attempt to be as conciliatory as possible so I have deleted my previous comment.

For those of you treading down the same path as I did, you'll probably want to track [this](https://github.com/Shopify/js-buy-sdk/issues/168) issue instead.

**Comment by rebeccajfriedman** [comment]
Metafields are now available on Products and Collections! I suggest using the [guide](https://help.shopify.com/en/api/custom-storefronts/storefront-api/guides/metafields) for more information on how to retrieve them!
