### ISSUE TITLE
fetch product id from shopify online store

### ISSUE THREAD

**Issue by RishabhTayal** [Shopify/mobile-buy-sdk-ios#977]
I am aware of the `id` property of Product object. However, this `id` is a GraphQL id which is not the same as the numeric id from the online store. 

How can we get the numeric id?

**Comment by RishabhTayal** [comment]
If it's technically possible, I could create a PR with the implementation.

**Comment by dbart01** [comment]
The contents of the GraphQL identifier is opaque and considered an implementation detail. If you have a transform that you wish to apply to the `id`, it should live in your application layer, not the SDK.

**Comment by RishabhTayal** [comment]
@dbart01 I understand the GraphQL identifier is opaque and considered an implementation detail. However, I am just trying to find out a way to get the numeric identifier from the Shopify admin. Do you have any proposed solution on how to find it (Other than calling the REST API)?

> If you have a transform that you wish to apply to the id, it should live in your application layer, not the SDK.

What kind of transform are you talking about here?

**Comment by dbart01** [comment]
While we don't recommend doing this, you _can_ base64 decode the GraphQL ID and extract the numeric identifier. This is one possible transformation that should live in your application layer.

**Comment by RishabhTayal** [comment]
Got it. Thanks for the info.
