### ISSUE TITLE
Filter out "Out Of Stock" products.

### ISSUE THREAD

**Issue by MVakas** [Shopify/mobile-buy-sdk-ios#988]
Is there any possibility that I can query and only get the available products. I don't want the 'Out of stock' products?

**Comment by morganmccunn** [comment]
Hi @MVakas - On the `Product` object there is an `availableForSale` field  that you can use. See [help docs](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/object/product) for details. If a product is out of stock, then it is not available for sale. Hope that helps!

**Comment by MVakas** [comment]
I am aware of avaialableForSale, with this field I have to filter out after I have fetched all the products including the one not available for sale. I want to fetch only the available products.

**Comment by MVakas** [comment]
The problem is that I’m getting too many products which are of stock.

**Comment by rebeccajfriedman** [comment]
As per the [API documentation](https://help.shopify.com/en/api/custom-storefronts/storefront-api/reference/queryroot#products), you can filter your products by `availableForSale` using the `query` filter parameter.

**Comment by MVakas** [comment]
Thanks I'm able to filter out the products using `available_for_sale`

**Comment by Komal2905** [comment]
@MVakas  Can you specify how you able to filter out products which are out of stock
?

**Comment by MVakas** [comment]
`available_for_sale`
Use this tag.

**Comment by Komal2905** [comment]
@MVakas but I am not sure how to use that tag. should I create custom collection which this condition ?
if you could provide sample query for it , then that will be so useful
