### ISSUE TITLE
totalTax is incorrect, preventing checkout with this error:

### ISSUE THREAD

**Issue by natecraft1** [Shopify/mobile-buy-sdk-ios#993]
"The amount of the payment must match the total of 26.72."

The totalPrice, and amountDue properties both show 26.23, however, if I go to the webUrl provided on the checkout, the total is correct. The only difference is the tax - it is not being calculated correctly.

**Comment by rebeccajfriedman** [comment]
Resolved this issue offline!

**Comment by zackshapiro** [comment]
@natecraft1 @rebeccajfriedman How were you able to resolve this? I'm dealing with this issue currently. Thanks!

**Comment by rebeccajfriedman** [comment]
Poll the checkout until the `ready` field is true. That should fix the issue.

**Comment by zackshapiro** [comment]
Interesting. Any idea why that fixes this issue?

**Comment by dbart01** [comment]
Before a checkout is `ready` it needs to run async computation on various parameters. Attempting to complete a checkout in this state will result in mismatch between expected and provided values, in this case - `paymentDue`.

**Comment by zackshapiro** [comment]
Thanks! Will try that this morning

**Comment by zackshapiro** [comment]
This worked perfectly. @dbart01 maybe worth adding to the readme as this wasn't clear from the doc or the sample app. 

Thanks @rebeccajfriedman
