### ISSUE TITLE
Recommended Products 

### ISSUE THREAD

**Issue by MVakas** [Shopify/mobile-buy-sdk-ios#995]
**Product Recommendations**

Hi 
Is there any way to fetch product recommendations for mobile apps? I know it's possible for the web 
https://help.shopify.com/en/themes/development/recommended-products

**Comment by dbart01** [comment]
Product recommendations are now available in [3.5.2](https://github.com/Shopify/mobile-buy-sdk-ios/releases/tag/3.5.2).
